### ISSUE TITLE
Trigger new flux-sched builds on flux-core PRs

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#1093]
As we discussed yesterday, it would be useful to have successful builds of flux-core trigger a new build of flux-sched.  The idea is not to use it as a blocker for flux-core PRs, but as a notification when changes to flux-core break the master of flux-sched (to avoid situations like https://github.com/flux-framework/flux-sched/pull/246)

Apparently travis-ci doesn't support these dependent builds [(and don't plan to)](https://github.com/travis-ci/travis-ci/issues/249), but there is [a workaround hosted on github](https://github.com/stephanmg/travis-dependent-builds) that uses the travis-ci API to trigger downstream project builds.  It would require some tweaks to avoid a trigger of flux-sched from each matrix build of flux-core.  It is also unclear where the feedback from the flux-sched build would appear (would we manually have to visit travis-ci's website, or would it appear somewhere on github?). Alternatively, maybe we could leverage bamboo to build flux-sched on every new commit to flux-core master?

Just a thought...

**Comment by grondo** [comment]
Thanks @SteVwonder, I was just looking this. I was considering using a script to trigger the dependent build (as in the script you linked above), then monitor the build for success/failure using the API or the travis CLI tool, and finally post a status to the PR using the GitHub API with success or failure as a warning. The actual build could be run in the matrix with `allow_failures` so it doesn't explicitly block a merge as you suggest.

I was surprised there was nothing that does all this together, but there may be pieces out there already. [This](https://github.com/cesium-ml/dependent_build_server/blob/master/dependent_build_server.py) project does all the steps but is built to run as a server (I think). Does it look like it could be easily modified to run as a singleshot script? (written in python so it would take me a little bit to figure it out)

**Comment by grondo** [comment]
I looked into this a bit more, and I'm not sure it is possible to trigger build of a dependent project *from a PR*. The problem is that we need Travis (and probably also GitHub) API tokens to get this to work properly, and these tokens can't safely be stored in such as way to be safe for PRs (secure environment variables are disabled for PRs from forks)

Otherwise this seems doable via the following process:
 * trigger build of flux-sched/master using Travis API v3 [builds](https://docs.travis-ci.com/api?http#builds) entity. Set environment variables for the flux-sched build so it can build from the correct PR branch:
```json
{
  "request": {
  "branch": "master",
  "message": "$MESSAGE",
  "config": {
    "env": {
      "global": [
         "FLUX_TRIGGERED_FROM_REPO=flux-core",
         "FLUX_TRIGGERED_FROM_BRANCH=$TRAVIS_PULL_REQUEST_BRANCH",
         "FLUX_TRIGGERED_FROM_SHA=$TRAVIS_PULL_REQUEST_SHA",
       ]
     }
   }
 }
}
```
  * Grab Travis build.id from response
  * Update PR status using GitHub [status api](https://developer.github.com/v3/repos/statuses/), e.g.:
```json
{
  "state": "pending",
  "target_url": "https://travis-ci.org/flux-framework/flux-core/builds/$BUILDID",
  "context": "dependencies/flux-sched",
}
```
  * Poll build status until build complete with success/failure 
  * Update PR commit status with pass/fail

This could be done either as another build in the matrix, or only after all flux-core builds succeed using [build stages](https://blog.travis-ci.com/2017-05-11-introducing-build-stages)
