### ISSUE TITLE
Suggestion: Replace prompt when calling flux start

### ISSUE THREAD

**Issue by sampollard** [flux-framework/flux-core#1146]
If I call flux start there is no easy way of knowing if I'm in my base shell or in a flux instance. Perhaps appending something to the end of PS1 would be useful?

**Comment by grondo** [comment]
Good suggestion, however commands rewriting PS1 is probably not good practice (especially since PS1 won't work for csh style shells). Better practice would be to do what the git package does and add a file to `/etc/bash_completion.d` (which would only work for bash), and extend the default PS1.
(not sure what is done for lonely csh users)

For now, I append something like this to my PS1
```bash
${FLUX_URI+(}${FLUX_URI##*/}${FLUX_URI+)}
```

Which results in 
```bash
grondo:~/flux-core.git (master) $ src/cmd/flux start
grondo:~/flux-core.git (master)(flux-DUYzdX) $ 
```

I set this PS1 in my `~.bashrc`

**Comment by sampollard** [comment]
Thank you for the `.bashrc` trick, that should suit my purposes for now.
