### ISSUE TITLE
[minor cleanup] KVS cache entries shouldn't use 'hp' variable name

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#1222]
in the KVS, the variable name 'hp' is used universally for cache entries.  This is legacy holdover from before the KVS cache existed as an api and 'hp' stood for "hash pointer".  Could update this.

**Comment by garlick** [comment]
Also let's move the `href_t` type to blobref.h and call it `blobref_t`.  We can then change `blobref_hash()`, `blobref_hashtostr()`, and `blobref_strtohash()` to accept a `blobref_t` parameter instead of `char *s, int len`.   Even though the compiler would allow the user to substitute any char pointer for the blobref_t, I think this is less error prone that repeating `sizeof (href_t)` at all the call sites.
