### ISSUE TITLE
test: ensure public headers have C++ linkage directive

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1224]
I just noticed that `kvs.h` has some function definitions that are not enclosed in an "extern C" directive after the merge of #1223.  Is there a test we can add to catch this and any future slip-ups?

Maybe something that runs through the public symbols defined in libflux-core.so et al and generates C++ code that includes the flux headers and references the symbols, then attempt to link that program to ensure the C++ compiler did not mangle the C symbols?   That may be an impractical proposition but thought I'd throw it out there in case others have some good ideas of how to do it.

**Comment by morrone** [comment]
I can't think of anything more practical.  It probably isn't a big deal though, because fixing it doesn't change the compilation of the libraries.  And a user can always work around by adding their own extern "C" wrapper.  The bigger issue is finding things that won't actually compiler under C++, and we would only find _those_ issues by actually compiling everything under C++.  And like you said, that might not be that practical.

**Comment by garlick** [comment]
This is probably not worth holding open as an issue on.
