### ISSUE TITLE
flux-submit always sets nnodes in job request

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#1368]
Problem: flux-submit currently always sets a default `nnodes` in a job "request", even if the user did not specify `-N, --nodes` on the cmdline. This means that sched can not reliably determine when the user wished to force a number of nodes, vs the wreck code picking an arbitrary default.

There are multiple ways to approach this (in the short term obviously for the wreck implementation). @trws and I already talked and discussed leaving `nnodes <= 0` for `flux-submit` when it is not set by the user. Unfortunately this may turn out to be difficult because some of the other code assumes that nnodes is set to a nonzero positive integer (may be able to fix that though). At the very least, if sched can update `nnodes` when it assigns resources this can work for now.

@trws if you want to try out the code, the change is in a branch in my repo  [here](https://github.com/grondo/flux-core/commit/8d8c255cddc14be7bb558548905c4b6e9b589e04).

Another approach could be a flag set in the kvs when "exclusive" nodes are being requested. `flux-submit` could continue to operate as it does now (setting a default nnodes), but if `-N, --nodes` wasn't used on the cmdline something like `exclusive-nodes = false` could be set in the entry for the job.

I think this has taught me an important lesson in separating the request from the job data (hopefully solved as we transition to using jobspec!)

**Comment by trws** [comment]
That would work for me, just add a field into the Jason object at the same level and I’ll read it out in sched. Flipping the switch so that node exclusivity is possible solved several of the issues I was having with seemingly random over subscription.


---
Sent from VMware Boxer

On March 16, 2018 at 9:37:28 PM PDT, Mark Grondona <notifications@github.com> wrote:

Problem: flux-submit currently always sets a default nnodes in a job "request", even if the user did not specify -N, --nodes on the cmdline. This means that sched can not reliably determine when the user wished to force a number of nodes, vs the wreck code picking an arbitrary default.

There are multiple ways to approach this (in the short term obviously for the wreck implementation). @trws<https://github.com/trws> and I already talked and discussed leaving nnodes <= 0 for flux-submit when it is not set by the user. Unfortunately this may turn out to be difficult because some of the other code assumes that nnodes is set to a nonzero positive integer (may be able to fix that though). At the very least, if sched can update nnodes when it assigns resources this can work for now.

@trws<https://github.com/trws> if you want to try out the code, the change is in a branch in my repo here<https://github.com/grondo/flux-core/commit/8d8c255cddc14be7bb558548905c4b6e9b589e04>.

Another approach could be a flag set in the kvs when "exclusive" nodes are being requested. flux-submit could continue to operate as it does now (setting a default nnodes), but if -N, --nodes wasn't used on the cmdline something like exclusive-nodes = false could be set in the entry for the job.

I think this has taught me an important lesson in separating the request from the job data (hopefully solved as we transition to using jobspec!)

**Comment by grondo** [comment]
@trws, thanks. Not sure if you've been able to get back to this yet, but for now I've taken a simple approach by saving the exact values the user supplied on the cmdline to the job KVS directory under an `opts.` subdir. If an option wasn't used, its key won't appear in the directory. The scheduler, if necessary, can check any of these options to "see what the user meant".

e.g.

```
grondo@peep:/tmp/flux-core.git$ flux wreckrun -n1 hostname
peep.chaos
grondo@peep:/tmp/flux-core.git$ flux kvs dir lwj.0.0.$(flux wreck last-jobid).opts
lwj.0.0.5.opts.ntasks = 1
grondo@peep:/tmp/flux-core.git$ flux wreckrun -n1 -N1 hostname
peep.chaos
grondo@peep:/tmp/flux-core.git$ flux kvs dir lwj.0.0.$(flux wreck last-jobid).opts
lwj.0.0.6.opts.nnnodes = 1
lwj.0.0.6.opts.ntasks = 1
grondo@peep:/tmp/flux-core.git$ flux wreckrun -N2 hostname
peep.chaos
peep.chaos
grondo@peep:/tmp/flux-core.git$ flux kvs dir lwj.0.0.$(flux wreck last-jobid).opts
lwj.0.0.7.opts.nnnodes = 2
lwj.0.0.7.opts.ntasks = 2
```

(Note there is still a case where if ntasks not set ntasks gets set to nnodes, but I can fix that. For now it seems like all you want is to be able to check if opts.nnodes exists in the kvs, so maybe we don't want to fix the wreck code too much!)

**Comment by grondo** [comment]
If you need to get at the code, the changes are on my [wreck-experimental](https://github.com/grondo/flux-core/tree/wreck-experimental) branch. We can perhaps iterate on the solution here and then when you are OK with the result I'll propose a PR.

**Comment by grondo** [comment]
Ok, on my branch I went ahead and fixed the issue with setting ntasks to nnodes:
```
grondo@peep:/tmp/flux-core.git$ flux wreckrun -N2 hostname
peep.chaos
peep.chaos
grondo@peep:/tmp/flux-core.git$ flux kvs dir lwj.0.0.$(flux wreck last-jobid).opts
lwj.0.0.9.opts.nnnodes = 2

```

**Comment by garlick** [comment]
Is that a typo in the nnodes key name (three n's)?

**Comment by grondo** [comment]
Oh yes it is. Thanks!
Fixed in my branch.
