### ISSUE TITLE
jobs killed with wreck kill give status complete rather than failed or cancelled

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#1380]

**Comment by grondo** [comment]
This is intended behavior at this time. Check exitcodes in KVS to determine if any job tasks exited with non-zero status.

**Comment by trws** [comment]
While I understand that, since we have a cancelled status I personally would have expected that to be the result since the job wasn't allowed to complete of its own accord.  A kill *in* the job, certainly I'd want to see completed with an exit code, but kill with flux itself seems different somehow.

**Comment by grondo** [comment]
It would be nice to keep the canceled-while-pending state separate from ran-but-one-or-more-tasks-exited-with-non-zero-status. In the first case there will be no data available from the running tasks (no IO, no exit status) and job informational tools can key off the state to know that.

That being said, I'm open to other ideas. The single "complete" state for a job that actually runs is nice, because consumers watching the job only have to watch for one state to know that the job considers itself complete (whether tasks exited normal or died from a signal) and a single event to watch for, however we could set the state to "failed" after "complete" if any task exited with non-zero status. "canceled" is doable, but a little kludgy, because you have to save some state off to the side that a signal was sent to the job, then *after* the job completes set the state to "canceled" instead of "complete" or "failed".

Another alternative is that we are not limited to one "state" key in the KVS for jobs, Could we just have another key that would denote a more fine-grained "final-state"? (can't think of a better term for it right now)

**Comment by grondo** [comment]
@trws, if it is helpful we could change the output of `flux wreck ls` to detect if tasks of a job exited due to a signal and report the state `killed` (I'm not sure of your need here, if you are reading the KVS state directly then this is not helpful)

Also, might be useful to know that `flux wreck status ID` itself exits with the highest recorded task exit status of the job (e.g. a job killed with SIGKILL will cause `flux wreck status` to exit with 137). `flux wreck status` also reports task exit codes in output:

```
$ flux wreck status 50
Job 50 status: complete
task[0-3]: exited with signal 9
$ echo $?
137
$ flux wreck status 49
Job 49 status: complete
task[0-3]: exited with exit code 0
$ echo $?
0
```

**Comment by grondo** [comment]
@trws, how about this experimental change to `flux wreck ls`: Optionally (or by default if you want) the status of completed jobs with non-zero exit status is reported as either "killed" if the job was terminated by a signal, or "failed" if the job exited with non-zero exit code?

```
$ flux wreck ls
    ID NTASKS STATE                    START      RUNTIME    RANKS COMMAND
     1      2 complete   2018-03-23T15:46:01       0.037s    [0-1] hostname
     2      2 complete   2018-03-23T15:46:07       0.035s    [0-1] false
     3      2 complete   2018-03-23T15:46:14       1.667m    [0-1] sleep
     4      2 complete   2018-03-23T15:50:26      15.020s    [0-1] sleep
$ flux wreck ls -x
    ID NTASKS STATE                    START      RUNTIME    RANKS COMMAND
     1      2 exited     2018-03-23T15:46:01       0.037s    [0-1] hostname
     2      2 failed     2018-03-23T15:46:07       0.035s    [0-1] false
     3      2 exited     2018-03-23T15:46:14       1.667m    [0-1] sleep
     4      2 killed     2018-03-23T15:50:26      15.020s    [0-1] sleep
```

```diff
diff --git a/src/cmd/flux-wreck b/src/cmd/flux-wreck
index 9e051d8..1b83753 100755
--- a/src/cmd/flux-wreck
+++ b/src/cmd/flux-wreck
@@ -221,6 +221,20 @@ function LWJ:timediff (tstart, tend, talt)
     return s > 0 and s or 0
 end
 
+function LWJ:exit_string ()
+    local flux = require 'flux'
+    local state = self.lwj.state
+    local max = self.lwj.exit_status.max
+    if max then
+        local s, code, core = flux.exitstatus (max)
+        state = s
+        if s == "exited" and code > 0 then
+            state = "failed"
+        end
+    end
+    return state
+end
+
 LWJ.__index = function (self, key)
     if key == "state" then
         return self.lwj.state
@@ -291,7 +305,10 @@ prog:SubCommand {
  options = {
   { name = "max", char = 'n', arg="COUNT",
     usage = "Display at most COUNT jobs",
-  }
+  },
+  { name = "exit-status", char = 'x',
+    usage = "Display exit status instead of job state for completed jobs"
+  },
  },
  description = "List jobs in kvs",
  handler = function (self, arg)
@@ -305,7 +322,11 @@ prog:SubCommand {
         if tonumber (id) then
             local j, err = LWJ.open (f, id, dir)
             if not j then self:die ("job%d: %s", id, err) end
-            printf (fmt, id, j.ntasks, j.state, j.start,
+            local state = j.state
+            if state == "complete" and self.opt.x then
+                state = j:exit_string ()
+            end
+            printf (fmt, id, j.ntasks, state, j.start,
                     seconds_to_string (j.runtime),
                     tostring (j.ranks),
                     j.command:match ("([^/]+)$"))
```

**Comment by grondo** [comment]
I think this is done with new `flux-wreck ls` (modulo fixing the bug introduced by those changes). Feel free to reopen if there is more to do here.
