### ISSUE TITLE
unknown connector-local error

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#1386]
I'm getting an error every so often, on the order of hours, in a long running flux session.  Nothing is obviously going wrong, but given that it's an error rather than a warning, it seems like this might be a smell worth tracking down.

```
scogland at sierra4367 in /usr/gapps/kras/flux-long-test   !255!
$ ~/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.9.3/mpich-3.2-d2ooviunycxekch72hwkxg2aunt4bpvk/bin/mpiexec.hydra -launcher rsh -ppn 1 flux broker ~/projects/flux/butte/make_fenv_and_sit.sh
ENV READY
2018-03-24T01:19:51.997830Z connector-local.err[0]: send hb event to client BEA79: Broken pipe
2018-03-24T03:52:27.992887Z connector-local.err[1]: send hb event to client 21D24: Broken pipe
2018-03-24T12:16:35.992892Z connector-local.err[1]: send hb event to client 096B7: Broken pipe
```

This instance has so far run 64,123 jobs.  Its memory usage has grown over time, but it's still only at about 700 MB (it was at ~400 after the first 1,000 jobs).  The content store is up to 8.2 gigabytes, with a cron job purging the lwj directory with a target of 5000 remaining jobs once every thousand completions or 10 minutes.  I'm not sure how to figure out what those were trying to connect to, but if there's something I can dig out of it, it's still running, and barring a system failure will be until late Monday if someone wants to poke at it.

**Comment by grondo** [comment]
@garlick will likely have more information next week, but in case it is helpful I think those errors are from the connector-local module itself getting an EPIPE writing to an API client that has disconnected without properly shutting down the connection (e.g. exiting due to error or signal, etc) I think there may be certain error exit paths in wrexecd for example that could cause this error. If there aren't other failures from the jobs or tools, I don't think this is a critical problem.

**Comment by garlick** [comment]
Sounds like this might be similar to #542

**Comment by garlick** [comment]
Not sure this is a current issue?  Reopen if so.
