### ISSUE TITLE
wreck purge leaves directories?

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#1387]
This may be intentional, or useful for a reason I'm unaware of and if so feel free to just close this, but wreck purge leaves the parent directories behind when clearing out jobs.  This is probably not a big deal, but it does amount to thousands of directories after a while.

**Comment by grondo** [comment]
This is not intentional or useful, sorry, just not implemented. Possibly a hold-over from when lwj entires were kept in one place, instead of moved to a separate hierarchy for completed jobs.

If its a problem, maybe wreck purge could traverse lwj.x.y hierarchy looking for empty directories and prune them after a purge is complete. Or we could just write a script to do this on some interval.

**Comment by trws** [comment]
Thanks @grondo, that works.  I just noticed something else though, which is that purge takes the first jobs as sorted by a string rather than numeric sort, so jobs in the 8000 and 9000 range stick around essentially forever while jobs in the 100,000 and 200,000 range get removed.  I wouldn't worry about either of these right now, but for the longer term we probably want oldest to go first.

**Comment by grondo** [comment]
Oh, yeah, `purge` is just iterating keys in  whatever order the kvs iterator returns them (and you're right, the default sort is strcmp(), D'oh!) Not too smart sorry!

This should be an easy fix for now so that at least the `lwj-complete.[hb]` dirs are iterated oldest-first.
(Silly error sorry)

**Comment by grondo** [comment]
BTW, I'll also just add a `-C, --clear-empty` flag for `flux wreck purge` to run the script above after any purge is done (since I already had the code). This will go on the [wreck-experimental](https://github.com/grondo/flux-core/tree/wreck-experimental) branch
