### ISSUE TITLE
consider using a hierarchical memory allocator

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#139]
@trws:

> I was curious if anyone would be interested in using a hierarchical allocator for
> memory management? It's certainly not a need, but it tends to cut
> down on memory leak mistakes substantially (at least for me...), and
> frequently on allocation cost as well when pooling is used.  We
> already have talloc on all of our systems, it being a required
> dependency for samba and thus nearly ubiquitous, but not the headers
> at present.

**Comment by trws** [comment]
The main reason I would want to at least consider it is to be able to tie the lifetime of subfields to the structs or other things that they belong to. Something like this:

```c
struct stuff{
    char * name;
    char * type;
    struct other_struct_full_of_pointers * complex;
};

struct stuff * stuff_new(const char * name, const char * type){
    struct stuff * ret = malloc(sizeof(struct stuff));
    *ret = {
        .name = strdup(name),
        .type = strdup(type),
        .complex = malloc(sizeof(other_struct_full_of_pointers))
    };
    complex_init(ret->complex);
    return ret;
}

void stuff_destroy(struct stuff * in){
    free(in->name);
    free(in->type);
    complex_destroy(in->complex);
    free(in);
}
```

I'm guessing you all saw see the memory leak there right away, but if you get enough lines in a destroy or a copy I find it really easy to miss things. Now with something like talloc, the to-free logic goes with the allocation logic, so you aren't replicating it across 2-3 functions every time a pointer gets added.

```c
//might want to take a context in here, but not strictly required
struct stuff * stuff_new(const char * name, const char * type){
    struct stuff * ret = talloc(NULL, sizeof(struct stuff));
    *ret = {
        .name = talloc_strdup(ret, name),
        .type = talloc_strdup(ret, type),
        .complex = talloc(ret, sizeof(other_struct_full_of_pointers))
    };
    complex_init(ret->complex);
    talloc_destructor(ret->complex, complex_destroy);
    return ret;
}

void stuff_destroy(struct stuff * in){
    talloc_free(in);
    //destroy complex called, then frees for the strings, then free for the top-level
}
```

They can also be chained together, and have their parents re-assigned, so it's a relatively flexible mechanism. One downside would be that things like zlist_t use their own allocator, so those would still have to be strung off of a parent with a destructor or some similar, unless czmq allows the user to allocate then pass to an init.

As to downsides, it's an extra dependency and we don't have talloc-dev on our machines right now, though the library is there.  It would also be some overhead adopting it now, but it can always be done in stages rather than trying to re-work the whole thing in one go.

**Comment by trws** [comment]
Given where things are in the project, I think we are past where this would be practical.  We probably were when it first came up honestly, but it's bluesky at this point.
