### ISSUE TITLE
run interactive job with scheduling

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#1392]
We can either submit a batch job or run an interactive job at the moment.  As a note, if you once flux wreckrun something it seems to make sched no longer schedule jobs thereafter.  Since that's the case, it would be very helpful to be able to submit an interactive job, basically get wreckrun behavior on the client side but waiting for the job to be scheduled in the script.

**Comment by dongahn** [comment]
> As a note, if you once flux wreckrun something it seems to make sched no longer schedule jobs thereafter. 

I need to test this more. But I believe this should no longer be the case with the latest PRs that @grondo and I worked on.

**Comment by trws** [comment]
If they’re from the last ~day that is entirely possible.

**Comment by dongahn** [comment]
Yap. Those PRs have not even gone into the master yet. Will let you know when they are ready. Should be soonish.

**Comment by grondo** [comment]
We'll just need to re-enable to code in `wreckrun` to call the submit event instead of issuing a request to run immediately (right now the `--immediate` behavior is run in an `if true` block). I wonder if the best way to enable this automatically is to have the `job.create` respond with a `hey-there-is-a-scheduler` flag. When the scheduler is active you most definitely don't want to stomp over other jobs with wreckrun.

**Comment by grondo** [comment]
@trws, as a workaround you can somewhat simulate interactive job by using `flux wreck attach ID` immediately after submit. (I don't think attach will forward SIGINT though...)

**Comment by trws** [comment]
That sounds reasonable, and thanks for the reminder about attach, that's a good point.
