### ISSUE TITLE
killing, or ending, a job doesn't reliably kill all children

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#1412]
This seems to be specific to detached daemons, I'm seeing things like a redis cluster launched under a sub-instance survive a job being reaped.

**Comment by grondo** [comment]
Yeah, unfortunately this might be a gaping hole in process management right
now

**Comment by grondo** [comment]
Coming back around to this I'm not sure what we can do here with the current single-user non-IMP launched jobs. The way current launch works is we create a new process group to track launched processes, which is easily thwarted by processes that daemonize or leave the process group. In fact, when the processes fork and exit, the job will probably be considered complete at that point since wrexecd is only watching for its direct children to exit... (only maybe open stdout/err could keep the job running, but typically daemonize closes those fds as well).

I'll try to look into a stopgap process tracking mechanism we might be able to use to track all processes that are descendants of a job. Not sure that we have access to pid cgroup or similar as a normal user, so it could be rather hacky until we have IMP support...

**Comment by grondo** [comment]
Ben Woodard gave me the idea of trying the Dyninst ProcControl API to track process creation as non-root user. @dongahn, do you have experience with this interface? Would it be simple to create a tool/module that keeps a list of processes associated with a job by following clone/fork of all job tasks and their children, and so on, etc. so that we don't lose track of any processes created as part of the job?

**Comment by trws** [comment]
This is where I really, really wish we could just use `unshare -pf 
—kill-child — wreck…` to launch the actual job on the node.  I 
realize it wouldn’t always take care of the problem, but it would make 
the job of finding all children a whole lot easier.

**Comment by dongahn** [comment]
> Ben Woodard gave me the idea of trying the Dyninst ProcControl API to track process creation as non-root user. @dongahn, do you have experience with this interface? Would it be simple to create a tool/module that keeps a list of processes associated with a job by following clone/fork of all job tasks and their children, and so on, etc. so that we don't lose track of any processes created as part of the job?

I think it uses ptrace to track those events. Probably not a good fit as wrexecd using this will cause debugging tools not to be able to act on them.

**Comment by grondo** [comment]
> This is where I really, really wish we could just use `unshare -pf —kill-child — wreck…` to launch the actual job on the node.  I realize it wouldn’t always take care of the problem, but it would make the job of finding all children a whole lot easier.

I agree, and once we have the IMP we can do something like this, but since unshare(2) requires privileges we have to look for something ad hoc in the interim ...

>  I think it uses ptrace to track those events. Probably not a good fit as wrexecd using this will cause debugging tools not to be able to act on them.

Thanks for input @dongahn!

**Comment by trws** [comment]
Random thought, but would creating a process session for the job then walking that and child sessions help?

**Comment by trws** [comment]
Bah, we're already doing that, I should have guessed as much, sorry for the extraneous comment.

**Comment by grondo** [comment]
I don't think systemd user sessions are setup on our systems so that might be a dead end.

Another dumb idea is, assuming that the daemons we want to track don't completely reset their environment, search all `/proc/PID/environ` files for the current user looking for `FLUX_JOB_ID=%d` -- I wonder if this would work as a silly  stopgap?

**Comment by grondo** [comment]
@trws, when you have a minute, and if it isn't too much trouble, could you paste the redis cluster use case in this issue so I can reproduce the problem and try some solutions? 

Actually it will be easy to create a test case myself if the redis example is involved, but it will be handy if I just have something ready to run.

**Comment by trws** [comment]
Unfortunately it is a bit involved, and uses a non-public version of redis that may only run on ppc64le.  I think it just boils down to redis daemonizing itself though.

**Comment by grondo** [comment]
Here's a thought -- is there an option for redis to run in the foreground? That is probably a better long term solution. Even if we add a w/a to track and kill all processes spawned by a "job" when that job is completing, if a process daemonizes then wreck will think it is complete (since the original task has exited) and will then proceed to kill all  your daemons...

**Comment by trws** [comment]
I think we managed to get the specific use-case taken care of, and you're probably right.  It seems we handle this in the other resource managers with admin set prologue and epilog scripts, which we support in wreck anyway right?

**Comment by grondo** [comment]
Yeah, in the eventual exec replacement we'll be using the IMP to set inescapble cgroups for processes, and then be able to signal/stop/terminate those processes as a whole via the cgroup interfaces (or leave it to the job epilog as you say) 

For now we're running as unprivileged user so we don't have access to that functionality, so there isn't a convenient way to do it.

**Comment by trws** [comment]
Makes sense.  I'll close this in favor of the larger effort on that front then.
