### ISSUE TITLE
lua iowatcher doesn't check kz_get errors

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1427]
The iowatcher kz_ready_f callback should check for `kz_get() == -1` and do something to let the user know there was an error on the stream.  Right now it ignores errors and doesn't call the user's callback.

Since there isn't a way to pass an error to the iowatcher callback (at least not that I'm aware of), it seems like the only thing to do is to stop the reactor?

Just wanted to check if this is the best way to handle an error here.

**Comment by grondo** [comment]
I'll have to look back at the iowatcher implementation. Feel free to change
the callback to include an err message as warranted. Should be handled in
the callback, imo. (nicer to have a separate err handler, but that's for
the future)

**Comment by garlick** [comment]
Just tacked on a commit to #1424 that adds an `err` paramter to the iowatcher callback and another that updates the lua/t1003-iowatcher.t test.

Maybe if you have a spare moment this evening, could you give that a thumbs up or down?

Next is to figure out how to propagate errors back to wrexecd from the "ioplex" stuff I think.

**Comment by grondo** [comment]
I'll take a look.

Would it be easier at this point to just wire output handling directly in
wrexecd.c with the C API?

For the ioplex Lua stuff, the challenge might be passing some state down to
the handler to log an error to stderr or the job "event log". I think you
can just set keys directly on the watcher object, but can't remember for
certain right now.

You probably don't want to make kz read error fatal to jobs... Not sure I
have enough context for what errors were getting reading I/O to make a
judgement though.

On Apr 4, 2018 4:13 PM, "Jim Garlick" <notifications@github.com> wrote:

Just tacked on a commit to #1424
<https://github.com/flux-framework/flux-core/pull/1424> that adds an err
paramter to the iowatcher callback and another that updates the
lua/t1003-iowatcher.t test.

Maybe if you have a spare moment this evening, could you give that a thumbs
up or down?

Next is to figure out how to propagate errors back to wrexecd from the
"ioplex" stuff I think.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/flux-framework/flux-core/issues/1427#issuecomment-378773781>,
or mute the thread

**Comment by garlick** [comment]
The change to iowatcher was committed to master, but I think changes will be needed to ioplex in order for errors to be properly handled in wrexecd rank 0 /  flux-wreckrun.

I'm not sure at this point whether fixing ioplex is worth the effort or we should pursue some other simple mechanism for transporting I/O (preferably one that works with the new exec system).

**Comment by grondo** [comment]
I'm not even sure what the correct action is for an error from `kz_next` when reading output stream from a job to send to a file. Probably just log the error and stop watching that stream? Seems silly to kill the job or exit the reactor with an error.

**Comment by garlick** [comment]
I agree, close the stream and log the error.
