### ISSUE TITLE
test driver # OUT-OF-ORDER failures on ubuntu 14.04.1

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#143]
On my ubuntu 14.04.1 VM, subprocess unit tests all pass, but the automake test driver is apparently picky about the test numbering, which is reset to 1 at the `subprocess_fork` test on line 168.  This causes all subsequent tests to fail with `# OUT-OF-ORDER`.

**Comment by grondo** [comment]
Sorry, just submitted a PR that fixes this issue (before I noticed there was a new issue open on it).

The problem is that, when run under a test driver, IO is fully buffered, and the "exec failure" part of the test was flushing the child's buffers at `exit(2)`, which caused duplicate output from the test.

**Comment by garlick** [comment]
That fixed it, thanks.
