### ISSUE TITLE
idea: move creation of kvs.commit "name" into local kvs module

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#1446]
It is confusing why the client has to create the name for a kvs commit. In fact, the name (a UUID) is created  dynamically the `flux_kvs_commit` function, and never returned to the caller, apparently unused by the API client.

Because there can be unknown many clients doing commits, a UUID makes sense in this situation, but at least with zuuid, this is a heavyweight operation and the zuuid implementation appears to be bad (broken?).

It would be nice if we moved the dynamic creation of these names for individual commits into the kvs module. The module is in a much better position to create unique names for commits without resorting to UUIDs, and so unique names could be much shorter, and the "name" field could become optional for single commit requests. (though it would be forwarded via the relaycommit request).

The kvs module could create unique names for commits by including the current rank, a timestamp, and a sequence number, which would be guaranteed unique per Flux instance in maybe 64bits instead of 128.

Just an idea to throw out there!

**Comment by garlick** [comment]
This makes sense now that commit and fence are two different rpcs.

I think commits are routed directly to rank 0 kvs module so a simple
counter could work here?

**Comment by grondo** [comment]
> I think commits are routed directly to rank 0 kvs module so a simple
> counter could work here?



I didn't realize that. Do commits need a name then?

**Comment by chu11** [comment]
I like the idea of having some algorithm to calculate the fixed name.  Since it'll be way less heavyweight than creating a uuid.

The commits aren't directly relayed to the rank 0, but given all the recent changes, that seems like something that could work now.

At the moment, the name is used for infrastructure purposes.  When a commit completes, the "name" attached to that commit can be mapped back to the original RPC request so a response can be returned.

**Comment by grondo** [comment]
For now you could make "name" parameter optional in `commit_request_cb()`, and if it is missing (or maybe empty) create a name on the local kvs module for the commit that is something simple like `"kvs.<rank>.seq"`, passing that down to rank 0 via `kvs.relaycommit`.

It is very minor but I think removes a couple failure points in the kvs_commit client path, namely the memory allocation and opening of `/dev/urandom` by the zuuid implementation.

**Comment by chu11** [comment]
I think it's better to remove the "name" parameter completely, since it makes no sense with commits.  I actually did this in a prior refactoring, but the belief was that uuid generation was too heavyweight and we wouldn't want to put that stress on the local module.  But with this approach, it shouldn't be a problem.
