### ISSUE TITLE
broker.err lost events without clues as to where they went

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#1451]
The long-running instance running createsim jobs for splash (which is still running at least one live job) printed these early this morning:

```
2018-04-12T00:55:43.599808Z broker.err[289]: lost events 271723-275519
2018-04-12T00:56:01.860919Z broker.err[293]: lost events 271675-276364
2018-04-12T00:56:01.860825Z broker.err[292]: lost events 271713-276364
2018-04-12T00:56:01.860884Z broker.err[291]: lost events 271667-276364
2018-04-12T00:56:01.867319Z broker.err[287]: lost events 271710-276365
2018-04-12T02:08:49.864204Z broker.err[288]: lost events 271740-280718
2018-04-12T02:08:55.305509Z broker.err[310]: lost events 271890-280744
```

The broker on the first node is still running when I ssh to the node, but is not responding to an exec request.  There have definitely been recent nfs-related hangs on this system, but the broker itself and the hydra_pmi_proxy managing it have not been hung by this (at least not for more than 120 seconds at a time).  It may also be useful to know that no log message in the log file has referred to broker 289 since 6pm on the 10th, so it's been a while since anything came out of there.

@garlick, if you can think of anything diagnostic, let me know, I'll be happy to dig out some information while this instance remains up.

**Comment by garlick** [comment]
Event messages are globally sequenced.  This error is triggered when an event is received with an unexpected sequence number.  It means messages were lost on our supposed reliable transport.  Given that events are by default distributed over the TBON which is wired with TCP, this indicates that messages were probably lost somewhere in a broker or zeromq.

This is one of the big resiliency problems we have to solve for the system instance and little band aids are not going to cut it, but it would still be useful to find out how this error manifested itself, if it did at all.  Could you maybe run
```
flux dmesg | grep broker.err
```
on rank 0 and see if there are any other messages before these that might indicate why we dropped those messages?  In theory, zeromq shouldn't drop them since we have configured all TBON endpoints to have unlimited queue sizes, and it should retain messages in its queue until it handshakes with the receiving endpoint.  There could be a lzeromq bug, or we could be looking for some other broker error.

**Comment by garlick** [comment]
Eh, probably we won't find anything since the return value of this function is ignored in `broker.c::handle_event()`
```c
(void)overlay_mcast_child (ctx->overlay, msg);
```
This needs to be fixed.

**Comment by garlick** [comment]
Since lost messages in the TBON is clearly possible and recovery from them is a known longer term issue, I changed the name of this issue to reflect the need to log any errors (something we can solve in the short term).

**Comment by trws** [comment]
Works for me, thanks @garlick.

Also, you gave me an amusing double-take wondering if you were referencing a C++ method there for a bit. 😄
