### ISSUE TITLE
kz.KZStream in python binding cannot be instantiated

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#1536]
@trws: I am trying to test the KZStream class in kz Python binding, but I am getting a trace back when I am instantiating a class object. Any thought? 

```
quartz770{dahn}25: python
Python 2.7.14 (default, Jan 17 2018, 10:04:29)
[GCC 4.9.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import flux
>>> from flux import kz
>>> kzobj = kz.KZStream (fh, "lwj.0.0.1")
>>> fh = flux.Flux ()
>>> kzobj = kz.KZStream (fh, "lwj.0.0.1")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nfs/tmp2/dahn/flux-dev/lib/python2.7/site-packages/flux/kz.py", line 126, in __init__
    flux_handle, name, flags, handle, prefix)
  File "/nfs/tmp2/dahn/flux-dev/lib/python2.7/site-packages/flux/kz.py", line 84, in __init__
    self.handle = None
  File "/nfs/tmp2/dahn/flux-dev/lib/python2.7/site-packages/flux/wrapper.py", line 299, in handle
    if self._handle is not None:
  File "/nfs/tmp2/dahn/flux-dev/lib/python2.7/site-packages/flux/wrapper.py", line 246, in __getattr__
    llib = self.__getattribute__("lib")
AttributeError: 'InnerWrapper' object has no attribute 'lib'
```

I am not sure what I am supposed to pass to the "name" argument either so I put `lwj.0.0.1`

**Comment by trws** [comment]
Name is the second argument to kz_open, so that should be fine.  It 
looks almost like there was a bad update on that class somewhere, but 
I’m surprised it could have made it through with this.  The 
“self.handle = None” is causing the error by trying to access a 
property before its required attributes are set.  Try just deleting that 
line, this error should go away, and the whole thing may just work.

**Comment by dongahn** [comment]
Thanks!
