### ISSUE TITLE
add newline character strip flag to flux_buffer_read_line()

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#1624]
While working on #1331, it occurred to me that dumping data from a buffer to a log was common.  By default, ```flux_buffer_read_line()``` returns a buffer with the newline character at the end, which should be stripped before dumping into a log.

It would be convenient if the library had an option to automatically strip it for you.  I'm imagining just a boolean flag, so a ```flux_buffer_read_line (flux_buffer_t *b, int *len, bool newline)``` prototype.

The flag would have to be propogated into APIs that call this too of course.

**Comment by grondo** [comment]
Not that this isn't a good idea, but since e7fd48cf01f1d44d56a50892fd2f8898d6c911d1 `flux_log()` at least splits log messages at newlines and strips any trailing newlines for you.

Just my opinion, but I'm not a fan of the extra argument to `flux_buffer_read_line`, which would then have to propagated throughout the API as you mention. I'd slightly prefer a `flux_buffer_trim()` which would nullify all trailing whitespace in a `flux_buffer_t`. Would something like that be acceptable?

**Comment by chu11** [comment]
Ohh, I wasn't even aware ```flux_log()``` did that.  I saw this newline stripping code in cron.

```
    char *p, *saveptr = NULL;                                                                                                          
    while ((p = strtok_r (s, "\n", &saveptr))) {                                                                                       
        flux_log (h, level, "cron-%ju[%s]: rank=%d: command=\"%s\": \"%s\"",                                                           
                e->id, e->name, e->rank, e->command, p);                                                                               
        s = NULL;                                                                                                                      
    }  
```

which I guess is unnecessary.

Not sure a ```flux_buffer_trim()``` would work, b/c what if there are multiple lines in the buffer?  Perhaps some type of flag option for the whole buffer would be best.

But for the mean time, this isn't important since ```flux_log()``` takes care of these things.

**Comment by grondo** [comment]
> Not sure a flux_buffer_trim() would work, b/c what if there are multiple lines in the buffer? Perhaps some type of flag option for the whole buffer would be best.

Oh yeah, sorry I wasn't thinking when I typed that. I was forgetting how the `flux_buffer_read_line` was being used -- and the returned buffer is const, so can't be easily modified in place by a simplistic trim function.

In the future we could add a flag to the buffer as a whole maybe, or a separate function `flux_buffer_read_trimmed_line()` -- I slightly prefer that to a flag on every call. However, this is just one person's opinion.

> I saw this newline stripping code in cron.

Yeah, that predates the changes to `flux_log()` I think, and could be  simplified now since `flux_log` also converts multiple lines to multiple log messages.
