### ISSUE TITLE
Allow initial programs to register services

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#1689]
In pursuit of implementing the simulator within an initial program, we need the initial program to replace the exec subsystem.  This requires the ability for the initial program to register services.

**Comment by garlick** [comment]
Thanks @dongahn, that's definitely one approach we could use to wire in the simulator as a stand-in for the exec service.  We were just exploring whether we could actually fix it properly with something like `flux_register_service()` that would allow any API user to receive requests for a particular service name.

It looks like we did some of the prep work earlier e.g. in this commit which modified `broker/service.[ch]`
```
commit 9b532f318a6125e1c1c7146a7547555fd2b13bb2
Author: Jim Garlick <garlick.jim@gmail.com>
Date:   Mon Aug 14 10:28:56 2017 -0700

    broker/service: allow multiple service names
    
    Instead of only allowing one service name with an optional alias,
    allow any number of services to be registered with the same callback.
    Pass in a uuid with each registration and add a function to remove
    all services registered by a given uuid.
    
    Modify the broker so that modules register their primary and
    alias service names with the module uuid, and remove all services
    by uuid when the module unloads.
    
    Optimize service_send() a bit so that a malloc is not incurred
    each time we want to lookup a service by a substring of a message's
    topic string.  (If it's short, use a stack variable).
    
    Fix up remaining spots where exit is called on malloc failure.
```

I think there would be three steps to complete this work:

1)  arrange so that comms modules can register additional services dynamically, by adding a request handler at the broker level like `service.add`, and `service.remove`.  Requests for those services would be routed down the socket for the comms module like they are now.

2) implement API that sends `service.add` and `service.remove` RPCs, using futures.

3) modify the `connector-local` module to handle `service.add` and `service.remove` from API clients.  It would need to register/unregister the service with the broker on behalf of the client using the API, perform the necessary routing of requests and responses (might require the connector itself to be modified), and automatically unregister upon client disconnect.

**Comment by dongahn** [comment]
Thanks @garlick. I also chatted with @SteVwonder about this. This is a great idea. I can see we can use this for more use cases beyond the simulator if we do this right. For example, the workflow themselves can register a service without having to do an additional load: https://github.com/flux-framework/flux-workflow-examples/pull/5. I can see how I can use this for the DYAD work, I'm sketching at the moments. 

But I can't still get my head around how the API client can inject its service code into the broker level though. Does it only work with preexisting service code or do you want to allow the API client to register a new service code with at the broker level. Or do I get this proposal completely wrong.

**Comment by garlick** [comment]
> But I can't still get my head around how the API client can inject its service code into the broker level though. Does it only work with preexisting service code or do you want to allow the API client to register a new service code with at the broker level. Or do I get this proposal completely wrong.

The fact that comms module code is in the broker address space is actually kind of immaterial to how requests are routed.  The comms module and the broker establish a connected socket pair when the module is loaded, and a "route" (mapping of service name to socket) is installed in the broker as part of the module loading process.

What's being proposed in 1) above is to add a registration service in the broker, so a comms module could send a request to the broker to register a new service name, like the sched module could register a "foo" service.  Thenceforth, requests to "foo.bar" (or whatever) are sent to the sched module's socket.

In 3) the connector-local module is extended so that any connected client can register a service with _it_, and it then registers that service with the broker.  So if my command registers "foo", then at the broker, requests to "foo.bar" get routed to the connector-local module, and the connector local-module knows to route it to the API client.

That's the local picture on a single broker at least.  If loaded on rank 0, the entire instance can access your service.  If loaded on rank > 0, only a subset will see it.  If we want to address that, we may need to do a little more design.

**Comment by SteVwonder** [comment]
> the connector-local module is extended so that any connected client can register a service with it

Just for clarification (not out of need/desire), this means that processes connected via the `ssh` connector couldn't register a service, correct?

**Comment by garlick** [comment]
> Just for clarification (not out of need/desire), this means that processes connected via the ssh connector couldn't register a service, correct?

If I'm remembering, the ssh connector remotely executes flux-proxy which connects to the local connector, so I think no further service dispatching code would be required, but some minor plumbing changes might be needed to allow requests and responses to flow in the opposite direction through the ssh connector and flux-proxy.

Excellent point I hadn't thought about until you mentioned it.

**Comment by dongahn** [comment]
Ah. This is really a process as a service, then. Love it. This will likley simplify my other workflow cases whole lot!
