### ISSUE TITLE
Flux API: replace json_object with string

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#169]
`json_object` appears in the Flux API, which creates a dependency on json-c for users. 

Consider revising the API so that strings are passed instead of `json_object`.  This may include revising RFC 3 so that `FLUX_MSGFLAG_JSON` is replaced with `FLUX_MSGFLAG_STRING`.

**Comment by garlick** [comment]
Issue #76 proposes replacing JSON with opaque data in the KVS.

**Comment by grondo** [comment]
To clarify (sorry if this is obvious) but you'd be replacing `json_object` with a valid JSON string (In which case `FLUX_MSGFLAG_JSON` actually still applies), or is the proposal to replace `json_object` with arbitrary, unformatted string?

**Comment by grondo** [comment]
Just throwing another idea out there, maybe this is what you had in mind anyway, but if there is already generic `get/set_payload` message methods, can we just drop the `json` specific calls from the public APIs (keeping them perhaps as internal convenience functions) and note the payload format in msgflags?

This may be a gross oversimplification of the problem because I haven't traversed the entire API in awhile...

**Comment by garlick** [comment]
@grondo: you're probably right on both counts.

**Comment by garlick** [comment]
I kept the `get/set_payload` message methods in in PR #189 as it seemed like it was appropriate to have the validation that payload has terminating NULL, etc., testing message flags, etc., down there in the low level code.

**Comment by garlick** [comment]
PR #215 gets rid of json_object from libflux-core.so.

Since #76 is tracking the removal of json_object from the KVS interface, and libkvs.so is a separate library from the core, I think we can close this one.
