### ISSUE TITLE
python: code coverage

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#1770]
Per our coffee discussion: it would be nice to have code coverage calculated for the python bindings/cmds.

It looks like [codecov recommends](https://github.com/codecov/example-python) using [coverage.py](https://bitbucket.org/ned/coveragepy)

**Comment by grondo** [comment]
I started looking into this today, because I wanted to rework the `flux-jobs` tests, but didn't want to drop any existing coverage.

Trying to set up the `coverage` module for use with a *system* testsuite instead of a single script (instructions are simply to "replace `python script.py` with `coverage run script.py`) is a bit of a chore.

What is *almost* working requires the following:

 * Edit the *global* `sitecustomize.py` to include `import coverage; coverage.process_startup()`
 * Create a `coverage.rc` with at least:
```ini
[run]
data_file = /path/to/flux-core/.coverage
parallel = True
include = /path/to/flux-core/src/*
```
 * run `make check` as `COVERAGE_PROCESS_START=/path/to/flux-core/coverage.rc make -j 6 check`
 * run `coverage combine .coverage*` to combine all per-process coverage reports
 * `coverage report` or `coverage html`

```
Name                                                    Stmts   Miss  Cover
---------------------------------------------------------------------------
src/bindings/python/_flux/__init__.py                       0      0   100%
src/bindings/python/flux/__init__.py                        5      0   100%
src/bindings/python/flux/constants.py                      12      0   100%
src/bindings/python/flux/core/__init__.py                   0      0   100%
src/bindings/python/flux/core/handle.py                    87     10    89%
src/bindings/python/flux/core/inner.py                      6      0   100%
src/bindings/python/flux/core/watchers.py                  71     12    83%
src/bindings/python/flux/debugged.py                        5      1    80%
src/bindings/python/flux/future.py                         70      4    94%
src/bindings/python/flux/job.py                           478     49    90%
src/bindings/python/flux/kvs.py                           184     21    89%
src/bindings/python/flux/memoized_property.py               8      0   100%
src/bindings/python/flux/message.py                        84     11    87%
src/bindings/python/flux/rpc.py                            35      1    97%
src/bindings/python/flux/util.py                          145     22    85%
src/bindings/python/flux/wrapper.py                       176      6    97%
src/cmd/flux-admin.py                                      22      2    91%
src/cmd/flux-jobs.py                                      299     13    96%
src/cmd/flux-jobspec.py                                   132     10    92%
src/cmd/flux-mini.py                                      210     28    87%
src/cmd/flux-resource.py                                  193     12    94%
src/modules/job-ingest/validators/validate-jobspec.py      33      4    88%
src/modules/job-ingest/validators/validate-schema.py       38      5    87%
---------------------------------------------------------------------------
TOTAL                                                    2293    211    91%

```

Maybe I will try to add this to our COVERAGE=t runs in travis and see how it goes.

**Comment by grondo** [comment]
Ah, I found that *if* `ENABLE_USER_SITE` is set in environment, then Python will load `usercustomize` module from `site.USER_SITE` on startup. Then we do not have to modify the global system config at least!
