### ISSUE TITLE
python: need explicit binding for flux_reactor_run

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#1779]
As suggested by @trws, I'm putting up issues for common libflux functions that do not have an explicit binding. Though still callable via the "automated" cffi binding as `flux_handle.reactor_run (reactor, flags)`, to make the functions more easily discovered for python users we should have a direct binding.

My inclination would be to have the python binding automatically use the embedded handle reactor if not set, and make flags optional so that
```python
f.reactor_run()
```
works as you'd expect.

On another note, the automated C bindings are *very* cool :+1:, however, at times I feel like you should have to explicitly ask for them, because it can get confusing whether you are using an automatic binding or an actual wrapped C function (in which case the return value may be a C type and not a python object). Maybe this is just because I'm new to python? I'm not sure how it would work exactly, but if the automatically bound functions required `raw` or some other keyword (e.g. `flux_handle.raw.flux_api_fn()` or just `raw.flux_api_function (flux_handle, ...)` that would be helpful for me...

**Comment by SteVwonder** [comment]
Thanks @grondo for the great suggestions!

> in which case the return value may be a C type and not a python object

Yeah, it is potentially even more confusing because base-type return values are automatically converted to python objects while structs aren't. So some automatically wrapped functions will "Just Work" (i.e., reactor_run) while others will cause lots of pain (i.e., flux_future_create).

> if the automatically bound functions required raw or some other keyword (e.g. flux_handle.raw.flux_api_fn() or just raw.flux_api_function (flux_handle, ...) that would be helpful for me...

Yeah, I can definitely see the value in that.  I wonder if we should wait for proper coverage of futures before we implement that.

**Comment by trws** [comment]
Thanks @grondo.  FWIW I completely agree, it never really struck me that way (probably because I was building it 🤷‍♂️ ) but after thinking about how to address some of this last week, I'm thinking it would be good to generate the base wrappers statically, rather than fully dynamically, so there's actually a source file to look at.  The dynamic binding could still be there, under a keyword or similar, but that way it would be much easier to see what's going on.  Also, it's really not that you're new to python, this is just an odd use of metaprogramming facilities.  Normally this is something that would only show up in say an auto-generating RPC facility or something like that, so it would be more pythonic to have this be clear as well.
