### ISSUE TITLE
audit use of zhash_t for upgrade to zhashx_t

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1804]
It was noted in #1797 that zhash_t has a largish memory footprint for use with a small number of items, and that it would appear zhashx_t might be a little smarter when presented with this sort of usage.

zhashx_t is also more configurable - I used it in the job-manager module because it allowed the hash function to be overridden so that integer jobid's could be used as keys, unlike zhash_t, which would have required string keys to be constructed from the integers.

We should look at how zhash_t is used in flux-core and see if there are any obvious places where a zhashx_t would be a better choice.

**Comment by garlick** [comment]
It seems like the "fastpath" in `libflux/msg_handler.c` is a prime candidate for a zhashx_t.  Before this code was added, all message handlers were appended to a zlist that is searched linearly for every received message.  This is because the `struct match` doesn't lend itself to other lookup methods, and was fine for a small number of message handlers, but became a performance problem as the number of concurrent RPCs went up.  Each RPC adds an ephemeral message handler that is destroyed when the RPC completes. The fastpath code was added to address the performance problem, and is based on a lookup table, only for response messages, that maps matchtags to message handlers in  O(1).

The fastpath code relies on the fact that matchtags are immediately recycled, and so generally their value is numerically low.  It then maintains a dynamically sized array that fits the highest numbered matchtag in use.  I guess I didn't use a zhash_t before because it seemed like a large memory footprint for the common case of low concurrency, and matchtags had to be "stringified" in order to be used as keys.  I question that decision now.  However, zhashx_t solves both of those problems, and would reduce code complexity over the dynamically resized lookup table.

For fun I quickly prototyped this last night and it was a simple change with a [sloccount](https://dwheeler.com/sloccount/) LOC delta of -66.  If it wouldn't be objectionable given our other priorities, I can turn this into a PR that also includes some cleanup and tests.  The prototype code is on my `dispatch_fastpath` branch, specifically 5d6536fa6b4a5e9ce4cbdbe786b8eb7128202a85 in case @grondo wants to retry his test from #1797 and see what the effect is on that test.  (It was his mention of it that got me looking at the code).

**Comment by grondo** [comment]
Nice, your fix saves almost all the 5.4MiB attributed to `fastpath_get` in my contrived reproducer vs current master!

Current master 1956120553b44ce7205e8d0bb9b21c30f9ea3c67:
![massif-before](https://user-images.githubusercontent.com/741970/48085112-41d77b00-e1ae-11e8-8c6b-bfcc81962a4e.jpg)

With your `fastpath_get` changes applied:
![massif-after](https://user-images.githubusercontent.com/741970/48085171-6c293880-e1ae-11e8-8c01-fa4536ea519b.jpg)


And on top of your `aux_list` branch, we get the peak usage down to 3.7MiB for the testcase:
![massif-aux_list](https://user-images.githubusercontent.com/741970/48085533-64b65f00-e1af-11e8-9064-6bc05902f6e8.jpg)


Nice work!

**Comment by chu11** [comment]
I was reminded of this issue and decided to look through `flux-core` and see if there are any obvious candidates to use `zhashx_t` over `zhash`.  AFAICT, `zhash` creates a hash with initial size of 255, while `zhashx_t` initializes at size 3.  On the cleanup end, the destroy iterates through all entries.  So that's not too good either.

So basically what we want to avoid is create/destroy of `zhash_t` hashes when we're unlikely to use the excess entries and create/destroying them with some frequency.  Anything long lived doesn't matter much b/c the create/destroy are one time each.

I identified a few spots that could benefit with `zhashx_t` over `zhash_t`:

- libsubprocess - channels are usually stdin, stdout, & stderr.  Sometimes pmi, so currently max of 4 I think.
- shell fds - at max stdout & stderr I think?  I think the hash was put in under the assumption there might be a file per rank output in the future, but that code never went in  (#2460)
- libkvs transaction compaction - simple stdout tests show ops max of 5, but beefier ones will have lengths into the thousands.  So depends on what we want to optimize on.  perhaps could pick a hash size of like 43 or something to be better on average.

but it's unfortunate we can't create a `zhashx_t` with an initial size other than 3.  If we could create a size just a bit larger, we could avoid the eventual re-hash that would go on internally (load to trigger re-hash = 75%), so an initial hash of perhaps 7 or 11 would be great (or we could even be conservative and do like 17).

Of course, since `zhashx_t` is internal now, we could just add a function for that.

**Comment by garlick** [comment]
Nice analysis.

> Of course the other side of this is that no profiling I ever did on any recent work (#3583, #3617) ever showed zhash to be a problem

Yeah, I'd be inclined to put this one on the back burner for now, given other demands.

**Comment by garlick** [comment]
Not a priority at present so closing.
