### ISSUE TITLE
0.11.0 Release Notes

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#1822]
Do we need a 0.11.0 release with SC coming up next week?  We've made some improvements to the API and so forth but I'm not sure we're exactly at a good tagging point, not to mention we've created some non-functional (yet) stuff that we'd need to warn people off of.  Or...we could do a fork at 0.10.0 and backport what's good.  Or do nothing at all yet.  Just wanted to raise the question.

**Comment by dongahn** [comment]
It is a good idea. But the most significant event at SC will be my talk on Nov. 11 (Sunday) and it is probably a stretch do a release in time. I have to think that alternative release point would be right before our next ORNL engagement in Dec. 11?

**Comment by grondo** [comment]
Yes, good thinking @garlick..

To me it feels like we should be ready with our 0.10.0 fork because there might be some gotchas with travis-ci, auto-release, and the docker stuff.

We don't have to fork at 0.10.0 then backport, we could instead fork at whatever point the more experimental stuff started going in (though actually looking back now we pulled in the job-ingest stuff pretty soon after 0.10.0 so maybe that is not too helpful)

**Comment by garlick** [comment]
What about building the new stuff conditionally and not forking?

**Comment by grondo** [comment]
It depends on how you mean conditionally :wink:

I'd be fine with not forking for now, and even including the new stuff as long as the default rc scripts set up the instance the same as in 0.10.0.

I guess I vote for whatever is easiest at this point, though once we have the stable fork we can rip out all the old wreck code from the development version, which would be nice.

**Comment by garlick** [comment]
The default rc does not load job-ingest now, just in test.  There's the `flux job` command and the `job.h` bits but that's not a very large surface area.

**Comment by grondo** [comment]
yeah, it would seem easiest to not worry about that for now. Release Notes could detail it as experimental.

**Comment by garlick** [comment]
Closed by #1894
