### ISSUE TITLE
What is the best practice to keep track of resource/job states over time?

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#1950]
Pilot2 workflow currently uses a periodic invocation of `flux wreck ls` to keep track to resource/job states over time? They were wondering what would be better practices to do this. Specifically, they were wondering if they can post-process the content store to reconstruct this information. (Probably pretty involved as this requires having to correlate time stamps with specific kvs states). Alternative, I suggested that they can use a timeout watcher and do this within a callback they register. Finally, @garlick suggested that they may be able to achieve this with `cron` support.

**Comment by grondo** [comment]
Since we are replacing the current execution system I would hate for anyone to do a bunch of work to more efficiently watch resource and job states over time.

Flux does have `flux cron` which can run a script on an interval or after a count of events, but I'm not sure that is a huge improvement.

If they do want to post process the kvs, every job entry under `lwj.x.y.<jobid>` will have logged absolute times that the job started and completed under `.starting-time` and `complete-time`, along with the simplistic job size parameters `ncores`, `ngpus`, `nnodes`, and `ntasks`, and of course `R_lite`.
