### ISSUE TITLE
kvs: transactionmerge test can be racy?

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#2021]
Saw this in PR #2018

```
expecting success: 
        THREADS=64 &&
        flux module remove -r 0 kvs &&
        flux module load -r 0 kvs transaction-merge=0 &&
        OUTPUT=`${FLUX_BUILD_DIR}/t/kvs/transactionmerge ${THREADS} $(basename ${SHARNESS_TEST_FILE})` &&
	test "$OUTPUT" = "${THREADS}"

lt-transactionmerge: timeout: saw 63 changes
not ok 17 - kvs: transaction-merge disabling works
```

First time this appeared after many runs in #2011, #2016, #2017, #2019.  Could perhaps have similar racyness as #2019?  Should check that number of watchers is correct before trying to write to the key.

Edit: OR perhaps travis was just really slow and the timeout (5 secs) happened?

**Comment by garlick** [comment]
The `watchthread()` defers signaling the `watch_init` condition to a prepare watcher, after sending the lookup request.  However, AFAICS there is no guarantee that the lookup request has reached the `kvs-watch` service by the time the condition variable is signaled.

It seems like what you want is to take the first lookup response synchronously before installing the continuation, but that won't work because the key is unlinked and there will be no response until it is given a value due to WAITCREATE.

So I guess I would assign it an initial value instead of unlinking it.

Also, the logic in `watchthread()` and its synchronization with `main()` could be simplified by just doing that stuff in `main()` before the `committhread()`'s are started (dropping the condition variable).
