### ISSUE TITLE
libflux: flux_future_wait_for() can return -1 errno == ESUCCESS

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2119]
@trws reported on slack that he was seeing this.

**Comment by trws** [comment]
I noticed this first with a rust test program:

```rust
    h.kvs_lookup("", 0, "thing")?
        .and_then(move |f| {
            // f is strongly typed with kvs future methods, not rpc future methods or what have you
            println!("in callback, async!");
            println!("kvs result:{:?}", f.lookup_get().unwrap());
        })?
        .wait_for(-1.0)?; // blows up here
```

Testing a little further, it's not the rust wrapper, I get the same with C and C++.  It looks like errno remains unset with a failure somewhere in wait_for, so you get whatever errno was set to before wait_for if it dies this way.

I'm starting to think I'm doing something wrong with the futures, and maybe don't understand the ownership model correctly.  When I run this code, the wait_for hangs until I kill it:

```c++
  flux_t *h = flux_open(NULL, 0);
  flux_future_t *f = flux_kvs_lookup(h, NULL, 0, "thing");
  std::cout << f << " and errno " << errno << std::endl;
  flux_future_t *f2 = flux_future_and_then(f, [](flux_future_t *f, void *d) {
      std::cout << "in callback async!" << std::endl;
      flux_future_destroy(f);
      }, NULL);
  std::cout << f2 << " and errno " << errno << std::endl;
  int res = flux_future_wait_for(f2, -1.0);
  std::cout << res << " and errno " << errno << std::endl;
```

Adding in a `flux_future_destroy` in the callback allows it to exit, but causes wait_for to return -1.  Do I somehow need to signal success in the callback before destroying it? Is it appropriate to destroy it there? When an `and_then` is called does the old future still need to be destroyed in the caller?

**Comment by trws** [comment]
Hm, helps to RTFD, 🤦‍♂️ .  I wasn't calling either continue or continue_error, so this is my fault.  The cause is destroying the future without calling one of those, or calling it without doing that causing an error with no errno or hanging respectively.

**Comment by trws** [comment]
I *think* this is a reasonable wrapper (in c-ish pseudocode) that takes care of that issue, but I'd love to hear your thoughts @garlick as I clearly missed some nuances in the usage before:

```c
void callback_wrapper(flux_future_t *f, void* arg)
     flux_continuation_f *fn = get_user_callback(arg);
     result_t res = fn(f, arg);
     if (res.err == ESUCCESS) {
     }
```

**Comment by grondo** [comment]
It might be helpful to know that the `and_then` and `or_then` functions were added on to futures after the fact, and chaining is not an innate property of `flux_future_t`. The chained futures work by embedded a placeholder `flux_future_t` in the `aux` hash of the previous future, and therefore when you create the *actual* "next" future in the chain in the callback function, you have to pass that future to the placeholder future which was returned by `and_then` and/or `or_then` with `flux_future_continue(3)`.

BTW, the only thing you really get out of `flux_future_and_then(3)` is avoiding the need to jump through a series of callbacks in order to follow the chain, however it adds the burden of requiring the user to call `flux_future_continue(3)` when appropriate, so sometimes it isn't an overall win, and a series of `flux_future_then(3)` in each callback might be more clear... :man_shrugging:

**Comment by trws** [comment]
I see what you mean @grondo.  This caught me a bit off guard because I didn't expect and_then to require a new future to work, in case you want to just add another piece of logic to run logically after the previous one you scheduled without necessarily giving it a new future. 

The "continue" call functionality usually ends up being done by returning the continuation in future-based models like TBB, and I'm vaguely tempted to model it that way to see what it looks like. You're probably right that nesting calls to `then` would be simpler in a number of cases.

**Comment by grondo** [comment]
Where it is really helpful is when you want to return a composite future to the user, e.g. in an API call that needs to lookup one kvs value, then use that value to lookup another value. Because of the way the `flux_future_t` is structured, the only way to do that is to create an empty future that can be subsequently fulfilled by the continuation of the 2nd lookup call (using `flux_future_continue`), and pass that back to to the caller.

**Comment by trws** [comment]
That makes sense, the followup question I think is, is there a way for a callback given to and_then be the last in the chain without producing an error.  I didn't mean to run down that rabbit hole but it seems like something that might occasionally be useful, in case you aren't sure if you'll need another future or not for example, or want to chain callbacks but not futures?

**Comment by grondo** [comment]
Sorry, I'm not sure I'm following. Are you asking if you could, for example, break out of a chain of futures in the middle, but without breaking the chain with an error?

There is not an easy way to do that right now, though it could probably be accomplished with a new new function that traverses the futures and fulfills the last one in the chain, without fulfilling any intermediate futures. If it is useful perhaps we could make a specific function in the API for it. (If you look at composite_future.c, the actual implementation is straightforward)

If I haven't understood the question correctly, perhaps a concrete example would help.

**Comment by garlick** [comment]
I'm kind of confused.  @trws, were you intending to use composite futures in the first example, or did you mean _then_ instead of  _and_then_ originally?

**Comment by trws** [comment]
It was pretty much a fundamental misunderstanding on my part. I was thinking of the callback or continuation itself as a node in the graph.  If I'm understanding correctly, currently each future is associated with an async request that may or may not have a callback, I was thinking originally that "and_then" was a way to add a callback itself as a request into the chain, scheduled to run after the preceeding callback but not necessarily implying another future would be provided by the continuation.

Now that I have a better idea how this is actually supposed to work, I'm trying to figure out how I can best model this API.  If anything is to be done in flux itself from this issue, it might be to have a way to detect a case when a callback doesn't do what it must and call one of the continues before it exits.

**Comment by grondo** [comment]
> . If anything is to be done in flux itself from this issue, it might be to have a way to detect a case when a callback doesn't do what it must and call one of the continues before it exits.

That is a good idea. In `libflux/composite_future.c` the continuation is implemented in `chained_continuation()` by directly calling the `and_then` callback (or `or_then` callback when the future has an error). After calling either of these functions, we could verify that at least the `next` future in the chain has a callback set or is fulfilled. We might have to add a flag to the future's aux hash though because I don' t think the underlying `flux_future_t` has an accessor for the continuation...

**Comment by trws** [comment]
So, this is tangentially related, but I honest to goodness can't figure out why I'm getting an EINVAL in the second callback:

```c++
  flux_future_t *f = flux_kvs_lookup(h, NULL, 0, "thing");
  flux_future_t *f2 = flux_future_and_then(f, [](flux_future_t *f, void *d) {
      const char * res = NULL;
      flux_kvs_lookup_get(f, &res);
      flux_future_t *f2 = flux_kvs_lookup(flux_future_get_flux(f), NULL, 0, "thing");
      std::cout << 2 <<  f2 << " and errno " << errno << std::endl;
      flux_future_continue(f, f2);
      flux_future_destroy(f);
      }, NULL);
  flux_future_then(f2, -1.0, [](flux_future_t* f, void *) {
      const char * res = NULL;
      int r = flux_kvs_lookup_get(f, &res);
      std::cerr << r << " " << errno << " in callback async2!" << res << std::endl;
      flux_future_destroy(f);
      }, NULL);
  int res = flux_reactor_run(flux_get_reactor(h), 0);
```

It's literally loading the same KVS value twice, and every single time I get EINVAL on the kvs_lookup_get in the second lambda. It's driving me a little batty, especially because doing the same thing (or with two different values) works reliably with `future_then` but not with `and_then`.  Looking at the tests and the one usage in kvs_clone this looks like it should work, but I'm clearly still missing something here.  (sorry for being dense on this 😦)

**Comment by grondo** [comment]
Sorry, this might be quirkiness of `and_then` since that functionality is kind of glued on to the side of futures, and not an inherent property of them.

Is it the `flux_kvs_lookup_get()` that is returning `EINVAL`?

I'm not familiar with those C++ lambdas. Are they closures or just simple lambdas? (wondering if there is a scoping issue with `flux_future_t *f`, though I doubt it)

If I can make a reproducer I'll help you debug this.

**Comment by grondo** [comment]
Hm, actually there is a fundamental problem here.  KVS lookup futures can't be the target of `flux_future_continue(3)` because the composite future implementation doesn't have access to the base `flux_future_t` type aux hash, which the kvs lookup uses to store the `lookup_ctx` required for `flux_kvs_lookup_get`. The only

We could fix this by adding a method in `future.h` to access the aux hash and duplicate items into the "next" future (the future actually being used), while being careful not to duplicate the free functions I guess. 

Or we could move the composite implementation into `future.c` and make all futures capable of being composed, but that wasn't acceptable when the original composite methods were proposed (though I can't remember exactly why)

The first suggestion above is a lot less work anyway.

Let me think about this further. And sorry you wasted some of your time on this!

**Comment by trws** [comment]
Thanks for digging into it, kinda thought I was crazy there for a minute.

Sorry about the C++ lambdas too by the way, I didn’t really think about it. Since they don’t capture any variables they decay to a function pointer, so the example is identical to writing those functions as static functions and specifying the names in the same location, no data storage associated with it.

The rust version was using captures, so those have a lifetime and use the void* parameter to re-construct it.


On Apr 15, 2019, at 8:16 PM, Mark Grondona <notifications@github.com<mailto:notifications@github.com>> wrote:


Hm, actually there is a fundamental problem here. KVS lookup futures can't be the target of flux_future_continue(3) because the composite future implementation doesn't have access to the base flux_future_t type aux hash, which the kvs lookup uses to store the lookup_ctx required for flux_kvs_lookup_get. The only

We could fix this by adding a method in future.h to access the aux hash and duplicate items into the "next" future (the future actually being used), while being careful not to duplicate the free functions I guess.

Or we could move the composite implementation into future.c and make all futures capable of being composed, but that wasn't acceptable when the original composite methods were proposed (though I can't remember exactly why)

The first suggestion above is a lot less work anyway.

Let me think about this further. And sorry you wasted some of your time on this!

**Comment by grondo** [comment]
> Sorry about the C++ lambdas too by the way

No problem. That was kind of cool to see, I just wasn't sure how they work ;-)

**Comment by grondo** [comment]
@trws, here's a patch I believe will resolve the issue above (writing tests and updating docs before posting a PR). In the unlikely event you have some spare time, it would help if you could apply this patch and see if that fixes your issue. (It's fine if you want to wait until there is a PR though)

```diff
index bc846193f..d751659f8 100644
--- a/src/common/libflux/composite_future.c
+++ b/src/common/libflux/composite_future.c
@@ -246,23 +246,13 @@ struct chained_future {
 };
 
 /*
- *  Continuation for chained futures: fulfill future `next` immediately
- *   with the result from `f`. Since a result freed by destruction of
- *   `f` will now be placed into `next`, the `next` future must steal
- *   a reference to `f`, thus we place `f` in the aux hash.
+ *  Fulfill "next" future in a chain with the fulfilled future `f`.
  */
 static void fulfill_next (flux_future_t *f, flux_future_t *next)
 {
-    void *result;
-    /*  Tie destruction of future `f` to future `next` since we
-     *   are fulfilling `next` via `f`
-     */
-    flux_future_aux_set (next, NULL, f, (flux_free_f) flux_future_destroy);
-
-    if (flux_future_get (f, (const void **)&result) < 0)
-        flux_future_fulfill_error (next, errno, NULL);
-    else
-        flux_future_fulfill (next, result, NULL);
+    if (flux_future_fulfill_with (next, f) < 0)
+        flux_future_fatal_error (next, errno,
+            "fulfill_next: flux_future_fulfill_with failed");
 }
 
 /*  Callback for chained continuations. Obtains the result of the completed
diff --git a/src/common/libflux/future.c b/src/common/libflux/future.c
index 46dc853f3..b2e6359b1 100644
--- a/src/common/libflux/future.c
+++ b/src/common/libflux/future.c
@@ -62,6 +62,7 @@ struct flux_future {
     struct now_context *now;
     struct then_context *then;
     zlist_t *queue;
+    flux_future_t *embed;
     int refcount;
 };
 
@@ -295,6 +296,7 @@ void flux_future_destroy (flux_future_t *f)
 {
     if (f && (--f->refcount == 0)) {
         int saved_errno = errno;
+        flux_future_destroy (f->embed);
         aux_destroy (&f->aux);
         clear_result (&f->result);
         free (f->fatal_errnum_string);
@@ -318,6 +320,7 @@ flux_future_t *flux_future_create (flux_future_init_f cb, void *arg)
     f->init = cb;
     f->init_arg = arg;
     f->queue = NULL;
+    f->embed = NULL;
     f->refcount = 1;
     return f;
 error:
@@ -559,11 +562,14 @@ int flux_future_then (flux_future_t *f, double timeout,
  */
 void *flux_future_aux_get (flux_future_t *f, const char *name)
 {
+    void *result = NULL;
     if (!f) {
         errno = EINVAL;
         return NULL;
     }
-    return aux_get (f->aux, name);
+    if (!(result = aux_get (f->aux, name)) && f->embed)
+        result = flux_future_aux_get (f->embed, name);
+    return result;
 }
 
 /* Store 'aux' object by name.
@@ -656,6 +662,25 @@ void flux_future_fulfill_error (flux_future_t *f, int errnum,
     }
 }
 
+int flux_future_fulfill_with (flux_future_t *f, flux_future_t *p)
+{
+    void *result = NULL;
+    if (!f || !p || (f == p)) {
+        errno = EINVAL;
+        return -1;
+    }
+    if (!future_is_ready (p)) {
+        errno = EAGAIN;
+        return -1;
+    }
+    if (flux_future_get (p, (const void **)&result) < 0)
+        flux_future_fulfill_error (f, errno, flux_future_error_string (p));
+    else
+        flux_future_fulfill (f, result, NULL);
+    f->embed = p;
+    return 0;
+}
+
 void flux_future_fatal_error (flux_future_t *f, int errnum, const char *errstr)
 {
     if (f) {
diff --git a/src/common/libflux/future.h b/src/common/libflux/future.h
index da9451efe..a0bf55353 100644
--- a/src/common/libflux/future.h
+++ b/src/common/libflux/future.h
@@ -56,6 +56,8 @@ int flux_future_get (flux_future_t *f, const void **result);
 void flux_future_fulfill (flux_future_t *f, void *result, flux_free_f free_fn);
 void flux_future_fulfill_error (flux_future_t *f, int errnum, const char *errstr);
 
+int flux_future_fulfill_with (flux_future_t *f, flux_future_t *p);
+
 void flux_future_fatal_error (flux_future_t *f, int errnum, const char *errstr);
 
 const char *flux_future_error_string (flux_future_t *f);

```

**Comment by garlick** [comment]
Followed up in #2135 which was closed.
