### ISSUE TITLE
flux-shell: add stdio support

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2190]
Add initial stdio support to the job shell:
* rank 0 job shell registers a service
* (need some syncronization here that service on 0 is ready?)
* other ranks forward stdio to that service
* service buffers I/O in memory
* when job completes, services writes I/O to keys in the KVS private namespace

Then `flux job attach` should be updated to fetch these keys after the `finish` event indicates that all job shells have exited.  It should then write the content to stdout and stderr of the command.

[RFC 16](https://github.com/flux-framework/rfc/blob/master/spec_16.adoc) may need to be updated to specify the location of these keys in the job schema.

Add tests.

**Comment by grondo** [comment]
> RFC 16 may need to be updated to specify the location of these keys in the job schema.

We may want to hold off on updating RFCs until we have the final output design. We'll need to update I/O design to handle line buffered and unbuffered I/O for the final product and might as well not change the RFC again if the KVS schema happens to change.

**Comment by grondo** [comment]
Created a new issue for an implementation of the service described above, since it doesn't necessarily have to implemented within the job shell.

This issue would then be closed once the implementation describd in #2201 is wired into a functional job shell.

(Sorry if I should not have split the issue up like that

**Comment by garlick** [comment]
Closed by #2246
