### ISSUE TITLE
flux-shell: add signal forwarding

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2191]
Implement signal forwarding.  A `flux job kill` subcommand should be able to send a signal to all procs of a job (limited to instance owner + job owner).

Design TBD.  One idea: `flux job kill` directly sends an event.  Job shell would subscribe to these events and forward signals to the procs.   Job shell would validate that sending user + role are appropriate.

Alternatively, a request containing jobid and signal number could be sent to the job manager, then on to the exec service, which could use `flux_subprocess_kill()` to forward the signal to the job shell(s), which could trap signals and forward them to the procs.

Maybe there are other ways to do this, those were just the first two that came to mind.

**Comment by grondo** [comment]
> `flux job kill` directly sends an event. Job shell would subscribe to these events and forward signals to the procs. Job shell would validate that sending user + role are appropriate.

This first design is appealing because it will be trivial to implement. The main drawback is the race during job startup where the job shell may miss a `kill` event. Since events are open loop there is no way to return an error to the initiating command or function. Additionally, results are complicated when only a portion of the job shells involved in a job receive the signal.

> a request containing jobid and signal number could be sent to the job manager, then on to the exec service, which could use flux_subprocess_kill() to forward the signal to the job shell(s), which could trap signals and forward them to the procs.

This approach has the potential for better correctness, however it would not allow forwarding of signals that can't be caught like SIGKILL.

I would say for now we use the event based approach to get something done for the current sprint and plan how to handle the gaps later.

**Comment by grondo** [comment]
In coffee talks with @garlick, it was suggested that the job-manager should handle kill request via a new `job-manager.kill` RPC (similar to `job-manager.raise`), so that invalid jobs, invalid user, and invalid job state conditions can be handled there. The job-manager would then generate the event to actually notify job shells of the signal.

@garlick, please correct me if I'm missing anything.

I can begin work on this now if nobody else is taking it on.

**Comment by garlick** [comment]
Yes that is what I was thinking FWIW.
