### ISSUE TITLE
x_ac_install_dirs.m4 fails to expand some dirs

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#22]
${prefix} is left unexpanded in some path defines, e.g. (config/config.h)

/* Expansion of the "mandir" installation directory. */
#define X_MANDIR "${prefix}/share/man"

**Comment by grondo** [comment]
We could fix this by incorporating m4 macro I've found to do recursive eval. However, reading comments in configure, these variables are *purposefully* not expanded because GNU says prefix should have the ability to be overridden at `make` time: http://www.gnu.org/prep/standards/standards.html#Directory-Variables

Ideally I think we'd get rid of `x_ac_expand_install_dirs.m4`, these expanded dirs are currently only used in `flux(1)` to determine if we're running in eventual install directory anyway, but maybe we can reverse that test (since build dir is known at configure)?

If you want to keep expanded install dirs, I could incorporate recursive eval macro and fix it that way.

**Comment by garlick** [comment]
I think we could go ahead and get rid of those macros, however now I'm wondering about other variables we set in configure.ac such as:
```
AS_VAR_SET(fluxlibexecdir, $libexecdir/flux)
AC_SUBST(fluxlibexecdir)

AS_VAR_SET(fluxcmddir, $libexecdir/flux/core)
AC_SUBST(fluxcmddir)

AS_VAR_SET(fluxlibdir, $libdir/flux)
AC_SUBST(fluxlibdir)

AS_VAR_SET(fluxmoddir, $libdir/flux/modules)
AC_SUBST(fluxmoddir)

AS_VAR_SET(fluxconnectordir, $libdir/flux/connectors)
AC_SUBST(fluxconnectordir)

AS_VAR_SET(fluxincludedir, $includedir/flux)
AC_SUBST(fluxincludedir)

AS_VAR_SET(fluxcoreincludedir, $includedir/flux/core)
AC_SUBST(fluxcoreincludedir)
```
which are then compiled in to executables, e.g. src/cmd/Makefile:
```make
AM_CPPFLAGS = \
        $(JSON_CFLAGS) $(ZMQ_CFLAGS) \
        -I$(top_srcdir) -I$(top_srcdir)/src/include \
        -DMODULE_PATH=\"$(fluxmoddir)\" \
        -DCONNECTOR_PATH=\"$(fluxconnectordir)\" \
        -DEXEC_PATH=\"$(fluxcmddir)\" \
        -DBROKER_PATH=\"$(fluxlibexecdir)/flux-broker\" \
        -DLUA_PATH_ADD=\"$(luadir)/?.lua\" \
        -DLUA_CPATH_ADD=\"$(luaexecdir)/?.so\" \
        -DPYTHON_PATH=\"$(pyexecdir)\" \
        -DMANDIR=\"$(mandir)\"
```
Doesn't compiling these in also violate the autoconf standard quoted above?

**Comment by grondo** [comment]
Hm, yeah.. maybe this isn't a tractable problem.

**Comment by garlick** [comment]
If the rule is that the prefix can be changed at install time, is it sane to generate a config file at that time that includes these paths?  Though I guess we would minimally have to hardwire the path to the config file...

**Comment by grondo** [comment]
That sounds painful, and I'm kind of doubting we could address this easily. As such, I propose recursive eval approach for now?

If so I can open simple PR against [grondo/issue#22](https://github.com/grondo/flux-core/commits/issue%2322)
