### ISSUE TITLE
Flux should sanitize environment for launched programs

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#223]
We are currently passing SLURM_* and MPIRUN_ environment variables set by Slurm on to MPI programs that we launch.  As discussed in #220 and #221 this may pass incorrect information to the MPI runtime, for example when launching on a subset of nodes/cores obtained from Slurm.

**Comment by trws** [comment]
This one I hadn't thought of, but is important for the tool.  It may be worth considering what the flux environment is going to look like, will we have equivalents in the "FLUX_" namespace for the node list and so-forth?

**Comment by grondo** [comment]
One thing I've had in the back of my mind is that passing around information in the environment seems kind of archaic. Maybe we don't set too many more "FLUX_*" environment variables but instead export the same information via `flux config` or other tools?

On a related note, I've also thought perhaps programs should not get the environment of a launcher or other program by default (i.e. don't just blindly forward current environment like we do with slurm). We could support a more reproducible and sane environment propagation scheme for programs by allowing them to explicit set and share their "flux" environment. Programs would inherit/override the instance environment (for instance owners anyway), and tasks would inherit/override the program environment, etc. Instance-as-a-program environment would be set by the enclosing instance, or based on some per-user "rc-like" file.

Not sure if I'm explaining myself well, but this scheme opens up the possibility to run programs with more controlled environment, run a program "with the same environment as program XYZ", environment override sharing (e.g. like environment-modules for jobs), etc.

Not sure how it would fly in the real world, but this issue is one reason it might be a good idea. (Thus why I'm updating this issue and not really opening a new one)

**Comment by trws** [comment]
I agree that having extra control would be good @grondo, but I would say that having it inherit the environment from the parent by default would be good just to comply with the principle of least surprise.

With the new env handling stuff, this should actually be pretty trivial, is there a list, or pattern, of environment variables that need to be stripped out?

**Comment by garlick** [comment]
We're not currently passing `SLURM_*` via wreckrun since `bindings/lua/wreck.lua::get_filtered_environment()` skips all `SLURM_` prefixed envirnoment variables when creating the environment for the job.

Here's a quick check:
```
$ srun -N1 ./flux start flux wreckrun printenv | grep SLURM_
$
```
Looks good.  Closing.
