### ISSUE TITLE
libsubprocess: add start/stop interface for streams

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2235]
As mentioned in #2208, the job shell needs to allow stdio to accumulate in the circular buffer until a service has been registered and a barrier completed.

Currently one must register `flux_subprocess_ops_t` (including `on_stdout`, `on_stderr` callbacks) at `flux_local_exec()` time.  Could we allow late registration, or maybe add a start/stop interface to deactivate/activate callbacks?

**Comment by grondo** [comment]
I like the start/stop idea!

**Comment by chu11** [comment]
Right now various buffers, prep/check watchers, etc. are created on subprocess creation given what on_stdout and on_stderr are set to.  So would be tricky for late registration, the start/stop idea sounds more doable shorter term.

**Comment by chu11** [comment]
some initial thoughts / questions

- doing this on the local subprocess side I think will be half easy, since we have read/write reactor buffers already done (`libflux/reactor`).  Short term, is doing this just on the local side the most important?

- doing this on the remote subprocess side may be trickier / involve more work.  Right now, if a buffer overflows, it just returns an error (e.g. EOVERFLOW).  This is b/c on the remote side all stdout/stderr is via rpc.  I can't remember if this was a "to be done later" or just not something I didn't think about at time.

 - not sure how to deal with this.  As RPCs come in (lets say containing stdout data), I could just save off copies of the rpc messages I've currently received and process them later when buffer space is available?  But I also need to send an RPC to "flow control" the server side too.  Hmmm ...
