### ISSUE TITLE
flux-shell: implement input modes

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2257]
Add support for supplying data on a task's standard input.

**Comment by garlick** [comment]
Trying to summarize some thoughts based on offline discussions with @grondo and @chu11 (please correct me if I've deviated):
* [RFC 24](https://github.com/flux-framework/rfc/blob/master/spec_24.adoc) describes `guest.input` eventlog
* default input mode should be to bcast  stdin to all tasks
* shells watch `guest.input` directly with  WAITCREATE flag, and send any `data` event content to tasks that match the `rank` idset using `flux_subprocess_write("stdin")` and/or `flux_subprocess_close("stdin")`
* jobs with no stdin can include a data event with `eof=true` that matches all tasks
* `guest.input` watch can terminate once all tasks on a shell reach EOF
* If all tasks exit but `guest.stdin` has not reached EOF for those tasks, or if it is not yet created, that should not prevent the shell from exiting.
* Front end tools like `flux job attach` _could_ write to `guest.input` directly, athough it's cleaner if the leader shell accepts input and is the sole writer, since then `job-exec` can ensure the guest namespace is quiesced before it is removed
* If we go that way, how to rendezvous between front end tool and leader shell?

**Comment by garlick** [comment]
Other input modes:
* tasks read directly from _files_ (file per task)
* leader shell reads from _file_ and redistributes to follower sells (file bcast)

Incidentally, does stdin need to be signed by the user like the jobspec to ensure instance owner isn't changing it along the way?

**Comment by grondo** [comment]
> Incidentally, does stdin need to be signed by the user like the jobspec to ensure instance owner isn't changing it along the way?

Thanks for bringing that up. We'd mentioned that before but I don't know that it was captured anywhere. We have to be careful to ensure that any input to a guest shell or its tasks is signed. (Though perhaps this can be relaxed for instances running as a "trusted" user (e.g. `flux`)?) Perhaps signed I/O (we might also need to sign output) can just be a different encoding type?

**Comment by grondo** [comment]
> * Front end tools like flux job attach could write to guest.input directly, athough it's cleaner if the leader shell accepts input and is the sole writer, since then job-exec can ensure the guest namespace is quiesced before it is removed
> * If we go that way, how to rendezvous between front end tool and leader shell?

There is a general synchronization required here, as other shell services might conceivably be used by external tools. These services aren't known beforehand so there should be an event generated by the shell after which all services should be ready for messages in the leader shell. The shell could generate this event after the shell barrier.

**Comment by grondo** [comment]
> tasks read directly from files (file per task)

This got me wondering, is opening a file and `dup`ing it onto a subprocess' input fd possible with libsubprocess?

**Comment by chu11** [comment]
> shells watch guest.input directly with WAITCREATE flag, and send any data event content to tasks that match the rank idset using flux_subprocess_write("stdin") and/or flux_subprocess_close("stdin")

Note issue #2346, WAITCREATE in `job-info` has several issues in current form.  Could be solved in several ways (see issues/attempts #2355, #2356, #2359).  But current solution is to wait for event in  `exec.eventlog` that says directory is ready.

**Comment by chu11** [comment]
For history on this thread, @grondo comment in #2423

```
We may want to see if we can support the flexible --input option from wreckrun:

       --input=HOW, -i HOW
           Indicate how to deal with stdin for tasks. HOW is a list of src:dst
           pairs where src is a source FILENAME which may optionally be a
           mustache template as in --output, or the special term stdin to
           indicate the stdin from a front end program, and dst is a list of
           taskids or * or all to indicate all tasks. The default is stdin:*.
           If only one of src or dst is specified, a heuristic is used to
           determine whether a list of tasks or an input file was meant. (e.g
           --input=file.in will use file.in as input for all tasks, and
           --input=0 will send stdin to task 0 only.
```

**Comment by chu11** [comment]
So began thinking about how to approach this.  Haven't really thought how the user would actually specify data they want for stdin or how stdin from a front end program even gets to the shell right now, I figure I'll deal with that later.  Just thinking about the shell part.

Initial idea given comments above:

- stdin is written to `guest.input`

- all shells event watch `guest.input` (must watch `guest.exec.eventlog` first to wait for its creation).

- Whenever the shell gets a `guest.input` event, they check if the rank is managed within the shell, and if so, writes data to it via `flux_subprocess_write()`.

- If user is doing input via a file(s), leader shell will read file(s),  and write data to `guest.input` with ranks data goes to.

  - Potential feature: configurable buffer size of writing to `guest.input`?  Don't want to read all data from file and write all to eventlog in one chunk.

Pro: it doesn't matter if data is piped in via front end program, a  single file, multiple files, etc., all of the above just works b/c it all goes through `guest.input`.

Con: Internally, `libsubprocess` has a buffer for `stdin`.  If a `guest.input` data were to overflow the buffer, we have to manage that data in some way to write to the buffer later.  And because different tasks may be reading stdin at different rates, may get complex to manage.

  - Potential bad solution: keep track of log entries read so far, cancel `guest.input` watch, re-start later using log entry count for tracking.

  - Con: stdin blocked for other tasks that aren't slow

  - Potential "ok" solution: each task has its own `guest.input`  watcher.

  - Con: tons more kvs watchers

  - Potential feature: need event-watch "start at offset" or "start at log-entry number" option.

  - Potential feature for solution: temporarily pause event-watch?  Would need pause feature in kvs watch as well.

  - For both of the above, how to know when the restart watching?  Don't know answer to this yet.

  - Potential feature: libsubprocess report "buffer has space" for writing.

  - Short term - could punt on this and just error if buffer  overflow.

Con: if stdin is a file, aren't taking advantage of libsubprocess's INPUT_FD option (PR #2345).  We're going to have a ton of eventlog / kvs writing & reading with little benefit.

  - Pro of INPUT_FD: INPUT_FD option avoids the buffering issue above, as task reads in stdin at whatever pace it wants.

  - Pro of INPUT_FD: If input is a file per task, all events in `guest.input` are for just 1 task and the shell leader will be opening/reading 1 file per task and writing mountains of data to `guest.input`.  Lots of time wasted, INPUT_FD would be better.

  - Con of INPUT_FD: if same file to all tasks, user is opening / reading same file many times.

Con: `flux_subprocess_write()` only writes to a single task, so if we're writing to all tasks managed by a shell, we'll have to iterate through all tasks on the node.  e.g.

```
iodecode (context, &stream, &ranks, &data, &len);
for rank in ranks:
    if (rank is managed by this shell):
         task = find_task_for_rank(rank)
         flux_subprocess_write (task, data, len);
```

  - Is particularly non-optimal for the file-per-task case.  Many shells are reading data for tasks it doesn't own.

Given all of the above, my initial thought at solution is:

- if stdin is from front end program, write to `guest.input`, shells will read `guest.input` and write to tasks accordingly.

- if single file to all tasks, shell leader reads from file and writes to `guest.input`.

- if > 1 file to tasks, use INPUT_FD method instead.  

- short term, will punt on the potential buffer overflow issue.  Just exit on overflow.

Given we don't have any stdin support yet, I'm thinking we can deal the more complex ad-hoc input of wreck later. Getting:

- stdin from front end program
- single file input
- per-task input via {{taskid}} 

is best place to start.

@grondo brought up possibility of using `redirect` eventlog entry for stdin as well.

- can't be used with INPUT_FD, b/c if we're reading from `guest.input`, task has already probably started.  It's too late to dup the FD to subprocess.  So perhaps not best for per-task needs.

- shell could use it to read from file and call `flux_subprocess_write()`.  Buffer overflow problem listed above still potentially there, but since it's reading from a file, may be easier to manage.

**Comment by grondo** [comment]
Creating an input eventlog watcher for each task is most flexible. This is the equivalent of what was in wreck, but we did end up running into scalability problems.

Use of INPUT_FD is just an optimization to bypass the KVS. For input not sure if that is needed initially, it is unlikely we'll have the same problem with thousands of lines of input per task that we do with output.

If you get stdin from `guest.input` eventlog working, then input from one or more files can just be a separate plugin in the shell, and writing input from a front-end tool is trivial, allowing multiple avenues for testing.

The normal state for most jobs, where `--input` is unspecified, is that no input is written or read. In order for a front end tool like `flux job attach` to come along later and write some input, the shell input plugin is likely going to have to be the creator of the first entry in the input log. Does that mean we'll need some sort of header?

**Comment by grondo** [comment]
> Given we don't have any stdin support yet, I'm thinking we can deal the more complex ad-hoc input of wreck later. Getting:

We'll want to nail down the front-end interface first, though. So we're not changing interfaces on users that might adopt an early release.

**Comment by grondo** [comment]
On flow control, I don't think we have a good story for that anywhere, so probably best not to worry about that for now. Only thing we want to avoid is blocking anywhere.

If you were able to have an eventlog watcher per task, then each task watcher could be started/stopped as needed, and buffering becomes a more tractable problem.

If you could start an eventlog watcher at an arbitrary offset, another idea would be to only spawn a new per-task eventlog watcher on-demand if writing to that task needs to block.

**Comment by chu11** [comment]
> The normal state for most jobs, where --input is unspecified, is that no input is written or read. In order for a front end tool like flux job attach to come along later and write some input, the shell input plugin is likely going to have to be the creator of the first entry in the input log. Does that mean we'll need some sort of header?

My assumption was the leader shell would create the header in `guest.input`.  I assumed the header to be the same format as what's in RFC24?

**Comment by grondo** [comment]
That seems reasonable, I just hadn't considered it before.

**Comment by chu11** [comment]
> Creating an input eventlog watcher for each task is most flexible. This is the equivalent of what was in wreck, but we did end up running into scalability problems.

Thinking about it more, perhaps I should implement this first, as its parity to wreck and (I think) easier to implement.  First.

**Comment by chu11** [comment]
Notes from some conversation with @garlick 

As a way to potentially limit the number of watchers on the KVS (via job-info), perhaps have a service on rank 0 of the shell.  It would be the only one watching `guest.input`.  Tasks can send requests to it for standard input (may it be via rpc, streaming, or mixture).

Having libsubprocess have its standard input buffer be auto-growable is probably an important need and we should look at that first.  `cbuf` can "auto-grow", but within limits placed on the buf (i.e. have to configure a max).

Under the assumption that stdin would be "piped" to the job via `flux job attach`, the stdin can only be written to `guest.input` after the job has started.  Not the most intuitive interface.  Is there a way for the user to write stdin after the job has started?  (Granted most users won't use `flux job attach`, they'll use `flux run`, so maybe not a big deal).

  - Side convenience, in order to broadcast stdin to all ranks, we have to write the stdin to `guest.input` specifying all ranks of the job (i.e. ranks=`[0-255]`).  This would require the additional step of reading/loading the jobspec and parsing it to determining the number of tasks in the job.  Could some special case string be used instead?  Or could the rank range be published elsewhere?

Working on issue #2378 is getting more important.  It was one thing for there to be `log_err_exit()` calls in the output plugin, but now it will be in the input plugin as well.

**Comment by grondo** [comment]
> Under the assumption that stdin would be "piped" to the job via flux job attach, the stdin can only be written to guest.input after the job has started. Not the most intuitive interface. Is there a way for the user to write stdin after the job has started? (Granted most users won't use flux job attach, they'll use flux run, so maybe not a big deal).

`flux run` will use the same APIs as `flux attach` to "attach" to the job once it starts running, and I imagine for a while longer `flux mini run` will still continue to use attach.

I'm probably just not understanding the statement, but I'm not seeing that it is unintuitive to not allow writing to a job's stdin until that job has started? That seems like expected behavior to me.

> Side convenience, in order to broadcast stdin to all ranks, we have to write the stdin to guest.input specifying all ranks of the job (i.e. ranks=[0-255]). This would require the additional step of reading/loading the jobspec and parsing it to determining the number of tasks in the job.

Yeah, I wonder if we should support "any" or "all" or "*" as a convenience for "match any" rank. Likely the value of `rank` will be one of "all ranks" or a single rank. Would it be too kludgy to say "The input data applies to all ranks unless the event context has a `rank` key."? Then you could just leave `rank` off for the broadcast case.


> As a way to potentially limit the number of watchers on the KVS (via job-info), perhaps have a service on rank 0 of the shell. It would be the only one watching guest.input. Tasks can send requests to it for standard input (may it be via rpc, streaming, or mixture).

Is the kvs watch really that bad? It would seem simpler if you could at least register a single watch from each shell, rather than redevelop another broadcast mechanism among the shells. I'm thinking of the case of a 16K task job -- do we really want 16K tasks all sending a request back to the leader shell?

> Working on issue #2378 is getting more important. It was one thing for there to be log_err_exit() calls in the output plugin, but now it will be in the input plugin as well.

Yeah, these are all over the shell. However, they are easy to fix with search and replace, so we probably don't need to worry too much until we have actual functionality.

**Comment by chu11** [comment]
> I'm probably just not understanding the statement, but I'm not seeing that it is unintuitive to not allow writing to a job's stdin until that job has started? That seems like expected behavior to me.

I think what @garlick and I were thinking about is:

```
id=$(flux submit jobspec)
cat myfile | flux job attach $id
```

does the `flux job attach` hang until the job starts?  Maybe this is non-worthwhile use case.  If the user wants to input via stdin whenever the job starts, via filename is the best way.

> Yeah, I wonder if we should support "any" or "all" or "*" as a convenience for "match any" rank. Likely the value of rank will be one of "all ranks" or a single rank. Would it be too kludgy to say "The input data applies to all ranks unless the event context has a rank key."? Then you could just leave rank off for the broadcast case.

I'm beginning to think this as well.  I'll propose something in a PR for RFC24.  In my initial implementation of stdin in the shell, I've had to call the `libidset` library a few more times than I think should be necessary just to broadcast to all nodes.

> Is the kvs watch really that bad? It would seem simpler if you could at least register a single watch from each shell, rather than redevelop another broadcast mechanism among the shells. I'm thinking of the case of a 16K task job -- do we really want 16K tasks all sending a request back to the leader shell?

I think we're just trying to think farther ahead scalability wise.

**Comment by grondo** [comment]
> does the flux job attach hang until the job starts? Maybe this is non-worthwhile use case. If the user wants to input via stdin whenever the job starts, via filename is the best way.

To me, it seems like it *must* work this way. How else is any interactive job going to work? The way `echo hi | flux run` and `echo | hi flux mini run` work will have to use the exact same interfaces, so if your example above doesn't work, then we've prevented interactive input.

(probably something to worry more about is multiple writers:

```
id=$(flux submit jobspec)
cat myfile | flux job attach $id &
cat myotherfile | flux job attach $id &
wait
``` 

Though I see why we shouldn't allow it. Slurm's `attach` only allowed one writer at a time, but I'm not sure how we'd accomplish that with the eventlog input approach)

**Comment by grondo** [comment]
In addition to multiple writers, you may also have to protect against "late writers". E.g. first `flux job attach` or equivalent has already written all stdin streams and sent EOF. Then another `flux job attach` is launched that tries to write more data.

Maybe it would be better if went back to idea of input from front-end tools is always written to a service on the leader shell (Apologies if you already went there and I was just slow on the uptake).

**Comment by chu11** [comment]
> Maybe it would be better if went back to idea of input from front-end tools is always written to a service on the leader shell (Apologies if you already went there and I was just slow on the uptake).

Nah, hadn't thought about that.  Hmmm.

**Comment by garlick** [comment]
Just wanted to say I'm amenable to whatever you guys work out on the input handling.  I am not sure I was thinking very clearly when we were talking yesterday @chu11 - apologies if I got us off track!

**Comment by grondo** [comment]
It solves a couple of the issues mentioned above:

 - early/late writer -- you can send an error response or the rpc gets ENOSYS
 - multiple writers - you can allow it, just like multiple `screen(1)` attach (fun!), or you can let the first UUID win (listening for disconnects to see when they go bye-bye)

We may need to allow a bypass for input eventlog for the tty case anyway, so we'd eventually need a service anyhow (thought that could be a separate service)

**Comment by chu11** [comment]
> multiple writers - you can allow it, just like multiple screen(1) attach (fun!), or you can let the first UUID win (listening for disconnects to see when they go bye-bye)

Similarly, if the user specifies two inputs for stdin.  e.g. tries to pipe in via stdin and also specified a file redirect for stdin.  In the latter case, I'd say the service shouldn't even start.

**Comment by chu11** [comment]
> Maybe it would be better if went back to idea of input from front-end tools is always written to a service on the leader shell (Apologies if you already went there and I was just slow on the uptake).

I initially worked on piped in stdin being written from the `flux-job` directly to `guest.input`.  

In addition to the reasons listed above, I realized another somewhat obvious inconvenience of writing from `flux-job`.  We don't technically know if the job is still running when the user calls `flux job attach`.  We could read the `eventlog` to get a clue, but then we have to handle the racy scenario of "job is still running when I read the eventlog, it's not by the time I try to send stdin to it".  So perhaps having a service on the leader shell to receive stdin is the easiest/best choice given all the reasons we have so far.

**Comment by chu11** [comment]
As I ponder how to deal with the fact that `libsubprocess` has a buffer for stdin, I'm leaning to two options, which are not mutually exclusive, they both could be done.

1) We could slightly alter buffering (`libflux/buffer`, and subsequently buffer reactors) so that instead of specifying a buffer size, you specify a maximum buffer size and allow the internal `cbuf` to autogrow the buffer as needed.  So instead of the typical 1M buffer size in libsubprocess, we can start it at something much smaller like 64K.  This would also help / solve #1853.

  - So while this would allow us to have a bigger max buffer size, ultimately there is still some cap that can become a problem.
  - With this solution, perhaps this is a setting that users have to configure?  If they truly intend to pipe in many many megs of data via stdin, they just have to deal with this configuration?

2A) If we stick with per task `guest.input` watchers, it would be a little tricky, but not too hard to simply have the watcher pause / re-start the `guest.input` watcher if the buffer hits its max.

  - Some check/prep watchers can be used to determine when the buffer has space again.
  - would have to add some "buffer space left" function into `libsubprocess`
  - would have to add some "log offset" to `job-info` event watch module.

2B) If we eventually go with a single `guest.input` watcher per shell, 2A above becomes trickier, but ultimately is not too different.  We could

  - pause / re-start `guest.input` and pause stdin for all processes
  - create another `guest.input` watcher for any stdin that is slow to process its buffer, eventually performance is just like 2A.

But as I think about 2A & 2B, I think this is a non-trivial amount of effort and perhaps is not useful for our wreck-parity goal and improve exec system work.  https://github.com/orgs/flux-framework/projects/18.  So I'm thinking this could be for down the road as an enhancement?  Part 1 is something we can do for our exec system work.

**Comment by grondo** [comment]
> Part 1 is something we can do for our exec system work?

Yeah, part 1 seems reasonable for now.

>  So instead of the typical 1M buffer size in libsubprocess, we can start it at something much smaller like 64K. This would also help / solve #1853.

I would start even smaller, like 4K or 8K.

**Comment by chu11** [comment]
> I would start even smaller, like 4K or 8K.

Any opinion on the max to grow to for `libsubprocess`?  8MB? 32MB?

**Comment by grondo** [comment]
I don't have too much of an opinion, sorry! :slightly_frowning_face:

**Comment by chu11** [comment]
With the merger of #2448, I'm going to declare this issue closed.  However I'll open up a few issues to tackle some lingering nice-to-haves.
