### ISSUE TITLE
design: include hostname (or other key) in KVS resources and R_lite

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2292]
In the scheme where a broker can own the resources of multiple nodes, and jobs are launched on remote nodes by the broker using a remote job shell, we need some way to address the individual nodes.

A hostname could be passed to ssh for remote launch as proposed #2290, and is readily available from cerebro/whatsup for monitoring as proposed in #2291.

Presumably we would need

A new level in the hierarchy of `resource.hwloc.by_rank` summary, which currently looks like:
```json
{"0": {"Package": 2, "Core": 12, "PU": 12, "cpuset": "0-11"}}
```
(The hostname is already present in the `resource.hwloc.xml` keys)

A new level in R_lite which looks like:
```json
{"version":1,"execution":{"R_lite":[{"rank":"0","children":{"core":"0"}}]}}
```

**Comment by garlick** [comment]
One thought:  could we introduce a "host rank" that maps an integer to a hostname?   Then we could refer indirectly to a set of hostnames with an idset?

**Comment by grondo** [comment]
One thought: perhaps pushing the broker rank into the resource representation is not the best long term plan. When R_lite is pushed into a child instance, the resource set would ideally be valid without having to filter out or remap broker ranks. The ranks included in `R_lite` are only meaningful while the instance is still running, and assuming that the rank assignments never change.

In the end, the broker ranks are more about communications and not resources and their relationships. 

That being said, it does seem reasonable to include hostnames in R/R_lite as a unique mapping of an os name as well as for job provenance. I like your idea of including a host rank or id that then has a mapping introduced somewhere (perhaps even included in each emitted `R_lite` so that the format is self documenting)

A separate service or configuration would be needed to allow the `job-exec` module to lookup an exec implementation for each host id in the job's R_lite. That is, some hosts may have a broker running, while others require ssh to launch the shell. (This isn't supported by job-exec currently, but could be).

We'd also have to do some work in resource.hwloc to populate data by generic host id or host name instead of broker rank. Perhaps using resource.hwloc doesn't make sense for the system instance anyway, which should be configured statically.

For a long running instance we'd have to ensure new hosts can be arbitrarily added, so it might be good to make no assumptions about continuity of hostids.

Sorry, I feel like I got off on a bit of a tangent there.

**Comment by dongahn** [comment]
> In the scheme where a broker can own the resources of multiple nodes, and jobs are launched on remote nodes by the broker using a remote job shell, we need some way to address the individual nodes.

How do you plan to populate the hwloc xml file within KVS for this remote case where we won't have a running broker? `flux-sched`'s `resource` uses an xml file per rank when hwloc is used as its resource reader. I can imagine a few different ways but it seems this needs to be worked out.

**Comment by grondo** [comment]
In a system instance it seems like we'd want to populate from configuration, not dynamically gathering hwloc data. (For instance, what if some nodes are down when you first start the flux instance)

It seems like we'd want a "config reader" implementation for `resource` in this specific case. If not, in the meantime we could just `flux kvs put` previously gathered XML?

**Comment by dongahn** [comment]
> One thought: could we introduce a "host rank" that maps an integer to a hostname? Then we could refer indirectly to a set of hostnames with an idset?

Using the hostname to disambiguate which host to use when a rank manages multiple hosts and having this level of indirection sounds sensible. As asked above, the schedulers need to be able to associate all the hosts with their managing rank correctly to be able to emit this info correctly though.

**Comment by dongahn** [comment]
> It seems like we'd want a "config reader" implementation for resource in this specific case. If not, in the meantime we could just flux kvs put previously gathered XML?

For a quick solution for testing, pre-generating XML makes sense. Will we need to combine multiple xml files into one large xml (hwloc has this capability) and put that under the rank key? Or put multiple xml files in there. Either way, we need some adjustment.

Yes, ultimately we need to add one more research reader that read the resource config and populate the scheduler's resource data. This should be straightforward. But as @SteVwonder and I discussed at some point, we will need to refactor the reader code so that we will have an "abstract reader class" and other concrete reader classes such as GRUG reader and hwloc reader will derive and implement this class. I currently don't have this planned. But if we go to this route, we will need to refine our plan. 

In general, this is really a good work item to tackle anyway.

**Comment by dongahn** [comment]
> One thought: perhaps pushing the broker rank into the resource representation is not the best long term plan. 

This is true. For the long term, I would love to emit a rank-less R!

In any case, for normal cases, hostname should uniquely identify which broker to use. But for testing where we can have multiple brokers per node, hostname itself won't be sufficient. 

If multiple ranks manage a single host in a shared fashion, some consistent protocol at the flux-core level, which chooses which rank on the host executes the tasks will do (e.g., round robin). 

If multiple ranks, each manages a distinct partition of the host exclusively, however somehow the scheduler needs to this partition info for the rank. I don't have a good solution there. 

> When R_lite is pushed into a child instance, the resource set would ideally be valid without having to filter out or remap broker ranks. The ranks included in R_lite are only meaningful while the instance is still running, and assuming that the rank assignments never change.

This is true. flux-sched will currently plan to abandon the `execution` section entirely and use the JGF portion for R_lite the nested scheduling.

**Comment by grondo** [comment]
> If multiple ranks, each manages a distinct partition of the host exclusively, however somehow the scheduler needs to this partition info for the rank. I don't have a good solution there.

@garlick, @chu11 and I briefly discussed this issue and perhaps what we should do is differentiate the concepts of "nodes", "hosts" and "ranks" (and maybe there are better differentiating terms).

In this case a node is a resource object which we know from traditional context. A rank or broker rank is an instance-specific rank assigned to brokers in a flux instance. Zero or more broker ranks may be running on a node. In this context, a "host" is a reference to where processes can be run -- more specifically "a maximum resource set which can host a process that has access to all children in the set". By that definition a "rack" or "cluster" cannot be a host, though they could be if they were running something like bproc. More to the point, if multiple brokers are running on a single *node*, then that node could be divided into multiple *hosts*, especially if each broker was running in a container.

Once we've settled on the terminology above, we could rethink where "rank" "host" and "node" are conflated in our current design and tease them apart. Eventually we could devise a rank-less *R* format along with flux-core services that map hostids to nodes and ranks, and vice versa.

> This is true. flux-sched will currently plan to abandon the execution section entirely and use the JGF portion for R_lite the nested scheduling.

Does this mean that flux-sched can only be launched by itself, or will you fall back to hwloc if JGF portion of R is missing?

**Comment by dongahn** [comment]
> Once we've settled on the terminology above, we could rethink where "rank" "host" and "node" are conflated in our current design and tease them apart. Eventually we could devise a rank-less R format along with flux-core services that map hostids to nodes and ranks, and vice versa.

Sound like a plan. Let's continue this this discussion at a 2PM meeting. (Will be pretty busy until next week though.)

> Does this mean that flux-sched can only be launched by itself, or will you fall back to hwloc if JGF portion of R is missing?

It is currently using hwloc. I don't have JGF reader yet. And yes if JGF portion is not there, flux-sched will fall back to hwloc reader.

**Comment by dongahn** [comment]
> I don't have JGF reader yet

The current plan is to do this in late Oct and early Nov. This will also be needed to reconstruct resource state using R (planned late Nov and mid Dec). https://github.com/flux-framework/flux-sched/issues/470

**Comment by garlick** [comment]
> Sound like a plan. Let's continue this this discussion at a 2PM meeting. (Will be pretty busy until next week though.)

That sounds great.  Maybe when we meet we can discuss what is feasible to get designed by Sept 27 - perhaps an RFC for R_lite that includes this nuanced terminology, and language about sub-instance schedulers populating resource set from R_lite.

**Comment by dongahn** [comment]
Are you going to meet at 2PM tomorrow or Friday?

**Comment by garlick** [comment]
@grondo will be gone Friday, but Thurs should be OK, or if you're too busy this week, want to choose  a day next week?

**Comment by dongahn** [comment]
OK. Be there tomorrow then. I have a travel next week. So actually tomorrow is actually the best.

**Comment by grondo** [comment]
Copied from #2295, since this response is not apropos in that issue:
@garlick stated:
> > (I got here wondering how we would support letting a user request to run on a specific hostlist, and how that is affected by the design issue being discussed in #2292)

I feel like we've discussed this before in the context of jobspec. Since we're matching generic resources with jobspec, not nodes as in traditional RM, it is more complicated than just allowing users to request a specific hostlist (as with everything and jobspec). Once we figure out how to specify exact resources in jobspec, then it is probably trivial to support this in whatever front end tools we want to add that functionality. (For our current work, probably support for `flux srun -w` makes more sense than `mpiexec`?)

There is also the srun `-x` option, which is probably much more utilized. I don't even know if jobspec can support *excluding* resources...

BTW, only slightly related, and we may have already noted this somewhere else, but we should have an issue for gathering requirements for the minimum set of existing `srun` options we will be able to support at our 1 year milestone.

**Comment by dongahn** [comment]
If we introduce the name field into jobspec, the schedulers can be augmented to do name matching as well. Right now flux-sched does only type matching but additional property matching and name matching need to be done before not too long anyway.

I think adding the name field into the jobspec should be trivial for spec and implementation.

For exclusion, a simplest idea might be to introduce `except` field which has a list consisting of a subset of the fields in the corresponding resource vertex like name and properties...

**Comment by dongahn** [comment]
Now that I think about it, we can view this model as a jobspec resource vertex containing a simple whitelist and blacklist.

**Comment by grondo** [comment]
Summarizing from today's 2pm meeting. I'm sure I'll get some of this wrong:

 - We discussed 3 or 4 cases for instance configuration:
   1. 1 broker rank per node
   2. multiple brokers per node with disjoint resource sets
   3. multiple brokers per node with overlapping resource sets
   4. multiple nodes per broker rank

 - We decided we don't care too much about handling case 3 natively, as it is only a useful case in testing.
 
 - We've settled on the term "execution target" to denote the disjoint sets of resources within an instance that are a target for execution of the job shell.

 - Each exec target resource set will have some per-instance configuration that maps an integer execution set id to a configuration blob that includes exec implementation for that the given target, along with configuration for that target. The exec system would use the configuration to determine how to get a shell running on that execution target, (e.g. `cmb.exec` or execute `ssh user@host:port ..`, etc.)

 - We'll propose a new version of `R_lite` which replaces current broker rank with an execution target identifier. This solves the problem in case 4 where a job needs to be executed on remote nodes which do not run a broker. This is also useful for the scheduler, which may need the execution target resource sets as a factor in scheduling granularity.

I don't remember if we brought this up in today's discussion, but in comments above we had discussed including the execution target identifier to hostname mapping in R/R_lite, which would make `R_lite` less instance-specific and  uniquely identify resources assinged to a job outside of the context of any instance. However, I'm not seeing specifically how to do that anymore, and since in most cases we've just switched broker ranks for execution target identifiers, I'm not sure if we've made `R_lite` any less instance specific.

Perhaps when we work through some examples the answer will become more apparent.

**Comment by garlick** [comment]
I think we're done here, at least in broad strokes.
