### ISSUE TITLE
guest namespace in dot hex format can cause parsing issues

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#2306]
Currently, guest namespaces are formatted in dot hex format based on the jobid.  For example the jobid 36842766336 converts into the namespace name `0000.0008.9400.0000`.

In some stats output, the namespace name is part of the output.  For example, the following comes from running `flux module stats kvs-watch` in a test I have.

```
{
 "watchers": 1,
 "namespace-count": 1,
 "namespaces": {
  "0000.0008.9400.0000": {
   "owner": 8556,
   "rootseq": 3,
   "rootref": "sha1-031e4517fcb5f59cc71dba34ab6dc245c3b9da7d",
   "watchers": 1
  }
 }
}
```

As you can see, the namespace "0000.0008.9400.0000" is listed right there in the middle.

The `--parse` option in `flux module` will not be able to parse the namespace correctly because there are periods in the name.

Although this is just one example, I'm sure there are other examples.  Parsing with `jq` can also be trickier.

So the question is how to do deal with this.

1) Should the namespaces with known periods in them be "sanitized" or re-formatted in some way when output in stats?  Pro: easy and doesn't mess up any other code.  Con: inconsistency to actual namespace name.

2) Should the namespace name be re-done?  In slack discussion, @grondo says that namespace name format was picked somewhat arbitrarily.

**Comment by grondo** [comment]
Also from slack: if using dots in namespace names is a problem, then creation of a namespace name with a dot in it should be an error.

Also, maybe we could just fix the `--parse` option in flux-module? Otherwise we might hit the same issue in the future for some other module stat key that might have a dot in it (e.g. some sort of per service name)

**Comment by garlick** [comment]
My vote is:
1. (generally) avoid periods in stats keys since they confuse both `jq` and `--parse`, even though there is no "standard" for expressing a hierarchical key name in JSON
2. if namespace names are converted directly into stats keys in kvs or job-info, then disallow periods in namespace names
3. change the namespace name to something like `guest-<id>` where `<id>` is the integer job id

**Comment by grondo** [comment]
Feels very wrong to me since `.` is not special to JSON in any way, just special here for a specific (debug only?) case (and really just a quoting issue). However, I don't have any other good counterarguments to your arguments above, so... :sob:

> change the namespace name to something like guest-<id> where <id> is the integer job id

I'd suggest `job-<id>` instead, only because that is what the `id` actual is, and it is two characters shorter.

When FLUIDs get large, integer ids will also be a bit longer (and much harder to read) than "dothex". Another idea would be to have a "dasherized" version of the dothex notation for FLUIDs, or just drop the dots.. (Just throwing that idea out there. In general the hex representation gives a much better user experience)

**Comment by garlick** [comment]
Well, you have a point.  Would it be better to add quoting support to --parse?  Or just eliminate --parse and give jq the job?

**Comment by grondo** [comment]
Well, If we were to go that direction,  I'd argue for dropping `--parse` since `jq` seems to be pretty ubiquitous. If there is a module stat for which we're continually using `jq`, maybe that indicates the data needs to be presented from a different service or specific command/utility.

However, in this case, the choice of guest namespace name was really arbitrary so we could just change  it and kick another can down the road? (much easier than the other work mentioned above)

**Comment by chu11** [comment]
I like the idea of renaming the guest namespace to `job-<id>` or something similar.

But thinking about it, I think dropping `--parse` is probably a good idea.  Effectively that option is parsing json "by hand", which may not be the best thing to support.

**Comment by grondo** [comment]
Ok, let's open an issue on dropping `--parse`.

It will be trivial to change the guest namespace name, which will close this issue.
