### ISSUE TITLE
shell: create shell fatal cleanup function for after tasks have started

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#2378]
Per some discussion in #2366, there are some scenarios where the tasks for a job have started but a fatal-ish error has occurred.  For example, in shell output, if the output header or output ready event did not get emitted / written correctly, that is basically a fatal error.

There should be a function to deal with this case, likely involving `flux_shell_killall()` and possibly other things.

**Comment by chu11** [comment]
As a reminder, from PR #2448 discussion, in `flux job attach` we currently work around a potential case where a future does not receive a ENOSYS response.

> I was able to reproduce a hang in flux-job in the following way:
>  - I inform the shell I want to use a file for stdin, but it's a bogus file.
>  - B/c we're using a file for stdin, shell starts up and WILL NOT start the stdin service.
>  - In flux-job, I send an RPC for stdin's EOF to the service (shell-<jobid>.stdin) b/c it doesn't know a file was used for stdin.
>  - Shell encounters an error on the bogus file and exits.
>  - In flux-job, I never get a response for the EOF rpc. I would expect an ENOSYS response.
>
> To solve this for the time being, in flux-job I destroy the futures of any in flight RPCs that have not returned as I'm tearing down watchers / reactors. But I'm not 100% sure this is correct.

As @grondo points out, 

> Perhaps this will be better when we have proper shell cleanup on exit. On a fatal error, the shell should unregister the shell- service and wait for a response. In the meantime, the ENOSYS message should be able to be generated since we're waiting in the reactor.

**Comment by grondo** [comment]
Thanks for the reminder. Currently the shell doesn't call `flux_service_unregister` so that will have to be added.

**Comment by grondo** [comment]
Hm, this still might be tricky. Even if you call `flux_service_unregister()` and then a synchronous `flux_future_get()` to wait for the result, some messages could still be delivered in the mean time to the shell's handle, but since the shell won't ever enter the reactor again those messages will be lost on exit.

I wonder if it would be sufficient for the shell to enter the reactor one more time before destroying the flux handle, however I worry that this would be very prone to a hang.

It would be nice if there was an interface to get a callback for all pending messages in the dispatcher, or more specifically, ensure all pending messages get an ENOSYS response sent before handle destruction.

**Comment by garlick** [comment]
Maybe a "router" should track unresponded-to requests and ENOSYS them when client owning service goes away?
