### ISSUE TITLE
libsubprocess: Do not export this lib

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#2383]
AFAICT this is only used internally, no need to export?

- remove from flux core lib.
- do not prefix with `flux_`

**Comment by grondo** [comment]
It was always meant to be a public interface to allow 3rd party tools to start remote processes.

As an example of an upcoming user, the `flux_subprocess_t` and `flux_cmd_t` handles are exported to shell plugins in `task.*` callbacks so that plugins can flexibly query and modify task processes. (e.g. this is how task environment has to be modified)

It might help to know the reason you want to move it private.

To be fair, there aren't many (any?) external users of flux-core right now except flux-sched, so we probably don't want to go removing all interfaces that *currently* have no external users...

**Comment by chu11** [comment]
> It might help to know the reason you want to move it private.

No particular reason, was something brought up in discussion.  If there is a distinct plan for use that isn't internal, then we can close this.
