### ISSUE TITLE
libsubprocess: don't call flux_log_* after fork(2)

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2384]
In `libsubprocess/local.c:local_child()`, errors are being reported via `flux_log_error()` using the flux handle of the parent process.

Though perhaps low risk in this case, it is probably unsafe to use a flux handle from multiple processes at the same time. Also, it isn't clear if it makes sense to use `flux_log` in this context. Probably the errors should just be emitted on stderr.

**Comment by chu11** [comment]
Makes sense.  There is a tricky part in this function, as there is stderr before and after the `dup2()` call (i.e. after the `dup2()` call, stderr is not what we think is stderr).  Maybe want to re-order a few calls and be clever about when I call the `local_child_ready()` function, so that errors can be received by the caller.

**Comment by grondo** [comment]
Good point, but not sure if it matters (though I'm likely forgetting something). Even before `exec()` we can consider the process to be the child, and stderr is going where the caller directed it to go. E.g. in the case of a shell task, either back into the output eventlog, or into an output/error file. In either case this is the right place, since someone will actually see it :-)
