### ISSUE TITLE
shell: flux_shell_getopt_unpack() return codes

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#2394]
After reading the header for `flux_shell_getopt_unpack()`:

```
/*  Unpack shell option from attributes.system.shell.options.<name> using
 *   jansson style unpack arguments.
 *
 *  Returns 1 on success, 0 if option was not found, or -1 on error.
 */
int flux_shell_getopt_unpack (flux_shell_t *shell,
                              const char *name,
                              const char *fmt, ...);
```

I interpreted the return code to be:

- -1 on error (EINVAL, etc.).
- 0 if 'name' does not exist
- 0 if 'fmt' does not unpack validly (e.g. 'name' exists, but a sub-key does not)
- 1 if 'fmt' does pack validly

But it seems that -1 is returned if `fmt` does not unpack validly.  IMO, it makes this function harder to use b/c many options are optional.  So I would expect -1 for a fatal-like error, 0 for option not set in any way, and 1 for got the option.

**Comment by grondo** [comment]
> IMO, it makes this function harder to use b/c many options are optional. 

I'm probably not understanding the use case, but can't you just make optional unpack keys optional with `s?`?

I guess I was thinking that if `attributes.system.shell.options.foo` does not exist then return 0 from `flux_shell_getopt_unpack (shell, "foo", "i", &val)`, but if `attributes.system.shell.options.foo` is set, but is not an integer, that is an error because you've set the option to an invalid value.

**Comment by grondo** [comment]
Part of the problem is there is no way with `json_unpack` that I know of to differentiate between "this JSON is all wrong" and "subkey missing", besides using the optional key flag in the unpack format. So I don't think we can return 0 for this case generally in `flux_shell_getopt_unpack()` and still return -1 for an invalid option format.

**Comment by chu11** [comment]
> I'm probably not understanding the use case, but can't you just make optional unpack keys optional with s??

I completely missed in the documentation that this was available.  `s?` is listed for `json_pack()`, but `?` is listed as this footer text in the `json_unpack()` documentation.  Let me give this a shot.  Should work out.

**Comment by chu11** [comment]
`s?` is going to work.  Thanks.  Closing
