### ISSUE TITLE
t2603-job-shell-initrc.t picks up environment from installed Flux

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2403]
On a system with an older version of flux installed, I'm getting the following failures in `t2603-job-shell-initrc.t` tests 12 thru 16.  Here's output from test 12:
```

expecting success: 
	${FLUX_SHELL} -v -s -r 0 -j j.initrc -R R1 --initrc=${initrc} 0
    
flux-shell: 0: task_count=1 slot_count=1 cores_per_slot=1 slots_per_node=1
flux-shell: 0: tasks [0] on cores 0,1
flux-shell: Loading /home/garlick/proj/flux-core/t/shell/initrc/tests/0000-basic.lua
/usr/local/bin/flux: symbol lookup error: /usr/local/bin/flux: undefined symbol: flux_msg_sendfd
/usr/local/bin/flux: symbol lookup error: /usr/local/bin/flux: undefined symbol: flux_msg_sendfd
flux-shell: /usr/local/share/lua/5.1/fluxometer.lua:45: module 'flux.alt_getopt' not found:
	no field package.preload['flux.alt_getopt']
	no file '/usr/local/share/lua/5.1/fluxometer/flux/alt_getopt.lua'
flux-shell: loading rc file /home/garlick/proj/flux-core/t/shell/initrc/tests/0000-basic.lua: No such file or directory
not ok 12 - flux-shell: initrc: runtest 0000-basic.lua
#	
#		${FLUX_SHELL} -v -s -r 0 -j j.initrc -R R1 --initrc=${initrc} 0
#	    
```

This seems to address the failures, though I'm not sure if it's exactly the right fix?
```diff
diff --git a/t/t2603-job-shell-initrc.t b/t/t2603-job-shell-initrc.t
index 8393cc0fc..f80401770 100755
--- a/t/t2603-job-shell-initrc.t
+++ b/t/t2603-job-shell-initrc.t
@@ -117,7 +117,7 @@ test_expect_success HAVE_JQ 'flux-shell: initrc: add test options to jobspec' "
 
 for initrc in ${INITRC_TESTDIR}/tests/*.lua; do
     test_expect_success "flux-shell: initrc: runtest $(basename $initrc)" '
-       ${FLUX_SHELL} -v -s -r 0 -j j.initrc -R R1 --initrc=${initrc} 0
+       flux ${FLUX_SHELL} -v -s -r 0 -j j.initrc -R R1 --initrc=${initrc} 0
     '
 done
 
```

**Comment by grondo** [comment]
This is  concerning because all those tests run under `test_under_flux` (so running the shell under `flux` to get the right env shouldn't be necessary)

Also the test works/worked on fluke, with 0.11 installed in /usr.

I wonder what is different about the environment during your test.

**Comment by grondo** [comment]
I was able to reproduce this locally so it isn't specific to your environment. I don't think running the shell under an extra layer of flux is quite the correct fix though. (Though I'm surprised it even works, so something still to understand there.)

The issue is specific to finding the correct version of `fluxometer.conf` at runtime, so I don't think this is a general flux env issue, but specific to this test (and others that use the `fluxometer` module for testing)

**Comment by grondo** [comment]
Ah, the issue is that on the failing system, the default `LUA_PATH` includes `./?.lua` *last*, whereas on RHEL7 system like fluke `./?.lua` is included *first* in the default LUA_PATH.

This might be distribution dependent (failing test is on Ubuntu 18.04), or could be Lua 5.1 vs 5.2 (failing test for me is on a system with Lua 5.2).

The right fix is probably to add an explicit path to `$(top_builddir)/t/?.lua` for in-tree flux LUA_PATH_ADD.
