### ISSUE TITLE
bindings/python: add jobspec generator

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2415]
As discussed in #2379, it may be advantageous to have a jobspec generator in the python bindings, for use by commands like `flux mini run` and `flux jobspec srun`, or by users who are generating ensembles with a python script, as an alternative to calling out to command line programs.

The `JobSpec()` class in `flux-mini.py` might be a starting point for a v1 specific class.

**Comment by SteVwonder** [comment]
Based on a recent coffee discussion, I think this is the current plan/structure:

Create a `JobSpec` class that will support canonical jobspec.  The constructor arguments will be the top-level keys of canonical jobspec (i.e., `resources`, `tasks`, `attributes`, and `version`).  It will (eventually) validate that the input follows the canonical jobspec definition and produce error message that are (hopefully) more helpful than the ones that jsonschema produces.  This class will also have plenty of methods for accessing, setting, and validating various aspects of the canonical jobspec.

Create a `JobSpecV1` class that inherits from `JobSpec` and has a similar constructor (perhaps without the `version` argument).  It will perform is own validation based on the restrictions in V1.  It may also provide additional methods or override many of the methods of `JobSpec`, again based on differences between V1 and canonical jobspec.  For example, since V1 is node/core/gpu-centric, it may provide `num_nodes`, `num_cores`, `num_gpu` methods.

Create a factory function to produce V1 jobspec from its primitive pieces (i.e., `command`, `num_tasks`, `cores_per_task`, `gpus_per_task`, `num_nodes`).
