### ISSUE TITLE
exec: request to augment error messages

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#2481]
Was working with @jameshcorbett, and he ran into a problem running a program under Flux.

Under the new exec system, the error was:
```
> flux mini run myScript.py
flux-job: task(s) exited with exit code 1
```

Under wreckrun, the error was:
```
> flux wreckrun myScript.py
execvp: No such file or directory
wreckrun: task0: exited with exit code 255
```

The underlying problem was that the command should have been prefixed with `./`, but the error message in the new system wasn't as helpful as the one from wreck.   If we could get a similar error message in the new system, that would be great!  I'm not sure if this is as simple as calling `errstr` on `errno` somewhere or if there is more to it.

**Comment by grondo** [comment]
Yeah, this issue will be addressed by the fix for #2384, which is already pending in one of @chu11's PRs I think (it might make sense to split this one out though).

**Comment by SteVwonder** [comment]
We saw this again while preparing for the ECP tutorial.  There was a script with a bad she-bang line and it was hard to track it down since the error was vague.

We don't necessarily need this fixed for the tutorial, but @grondo suggested it might be a good idea to peel the fix for this out of #2460 and submit it as a separate PR (cc @chu11).

**Comment by chu11** [comment]
I think this issue is separate from #2384.  An errno from `execvp()` may not be passed to the parent correctly.   Taking a look.

**Comment by grondo** [comment]
I think if you print an error in the child to stderr if execve returns, instead of using `flux_log`  that wil likely be sufficient. e.g. this is what we had in wreck:

```c
        if (execvp (ctx->argv [0], ctx->argv) < 0) {
            fprintf (stderr, "execvp: %s\n", flux_strerror (errno));
            exit (255);
        }
```

**Comment by chu11** [comment]
So I think this issue is simply more of an error handling and outputting an appropriate message than the issue in #2384.  In `libsubprocess`, if then path is bad, an errno is passed back up to the caller via an errno.  But we don't seem to be doing anything with this errno on error.  This

```
diff --git a/src/shell/shell.c b/src/shell/shell.c
index 589f9b0..4ddbe1b 100644
--- a/src/shell/shell.c
+++ b/src/shell/shell.c
@@ -1099,7 +1099,7 @@ int main (int argc, char *argv[])
             shell_die (1, "failed to initialize taskid=%d", i);
 
         if (shell_task_start (task, shell.r, task_completion_cb, &shell) < 0)
-            shell_die (1, "failed to start taskid=%d", i);
+            shell_die (1, "failed to start taskid=%d ERROR IS = %s", i, strerror (errno));
 
         if (zlist_append (shell.tasks, task) < 0)
             shell_die (1, "zlist_append failed");
diff --git a/src/shell/task.c b/src/shell/task.c
index 243467e..08557fe 100644
--- a/src/shell/task.c
+++ b/src/shell/task.c
@@ -197,8 +197,10 @@ int shell_task_start (struct shell_task *task,
     };
 
     task->proc = flux_local_exec (r, flags, task->cmd, &subproc_ops, &hooks);
-    if (!task->proc)
+    if (!task->proc) {
+        fprintf (stderr, "LOCAL EXEC FAILED errno = %s\n", strerror (errno));
         return -1;
+    }
     if (flux_subprocess_aux_set (task->proc, "flux::task", task, NULL) < 0) {
         flux_subprocess_destroy (task->proc);
         task->proc = NULL;
```

leads to

```
>flux mini run hfadsfsadfsadfsdaf
0.099s: flux-shell[0]: FATAL: failed to start taskid=0 ERROR IS = No such file or directory
0.101s: job.exception type=exec severity=0 failed to start taskid=0 ERROR IS = No such file or directory
flux-job: task(s) exited with exit code 1
```

and in the broker log

```
2020-01-24T23:14:02.882700Z job-exec.info[0]: 57780731904: 0: stderr: LOCAL EXEC FAILED errno = No such file or directory
2020-01-24T23:14:02.882740Z job-exec.info[0]: 57780731904: 0: stderr: flux-shell: FATAL: failed to start taskid=0 ERROR IS = No such file or directory
```

Would an `strerror (errno)` output on the `shell_die()` line be sufficient?

**Comment by chu11** [comment]
@grondo oh, i guess we raced posting :-)   I didn't know the old libsubprocess was not called in wreck, which confused me a tad when I was looking through v0.10.0 code.

I suppose just adding a `fprintf()` call on `execvp()` would work, but do we really want to expose that to the caller?

**Comment by grondo** [comment]
> I suppose just adding a fprintf() call on execvp() failure would work, but do we really want to expose that to the caller?

I don't think we're exposing anything to the caller. Since this is the child process, it should be expected that errors will be written to stderr I think.

E.g. if you instead ran `sh -c nosuchprocess` then you'd get the expected error users are used to seeing.

I do think we could clean up the shell errors a bit to avoid duplicate information. We could also add the command we're executing to the error message, e.g. with Slurm:

```
slurmstepd: error: execve(): nosuchthing: No such file or directory
```

or the shell:

```
$ sh -c nosuchthing
sh: nosuchthing: command not found
```

**Comment by grondo** [comment]
On thinking this over a bit more, I think I can see your p.o.v.. If the caller has the errno from execve() maybe it makes more sense to log the error appropriately from that context, rather than printing a message to `stderr`. I especially like that the error message would be logged in the job exception in this case.

If we do go this route, we should update other callers to issue the more explicit error message. E.g. `flux exec` is a bit vague in this case:

```
~$ flux exec nosuchthing
flux-exec: Error: rank 0: No such file or directory: Success
```

**Comment by chu11** [comment]
> If we do go this route, we should update other callers to issue the more explicit error message.

I'll put together a PR attempting this path.
