### ISSUE TITLE
[idea] implement named pipe service

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#250]
This is an idea in search of a use case, originally brought up in #206

Implement a "named pipe" service that can act as a multi-producer, multi-consumer queue, is patterned after a UNIX named pipe e.g. mkfifo(3), and has the following characteristics:
- A pipe can be created or removed by name
- Any number of producers can append to it
- Any number of consumers cab pull items out of it
- Consumers don't have to exist at the same time as producers

A way to implement this is to make it a service of the rank 0 broker, with operations like:

```
cmb.fifo.create
cmb.fifo.remove
cmb.fifo.put
cmb.fifo.get
```

Each get and put operation could transfer a JSON messsage payload from/to the fifo.  A get on an empty fifo would block or return EAGAIN depending on flags.  A put could similarly block upon reaching some predefined item count or memory usage.

This kind of structure could be used to implement a distributed work crew.

**Comment by trws** [comment]
One use-case that I think would benefit from this immensely, load-balancing and/or work-stealing systems.  We don't have any such yet, but it would make implementing high-throughput/UQ workload execution easier to address if it is available and sufficiently scalable.  Really good idea. :+1:

**Comment by trws** [comment]
So, I had an idea today that I wanted to bring up here, since I think it may simplify some things and get us some functionality we could use.  I was looking over how etcd, a kvs-like service used by our counterparts on the kubernetes project, exposes its API, and they offer an atomic directory operation which creates a key with the next available sequential number and adds the payload data to that key.  This interests me because:

1) that's how wreck is handling IO right now
2) The response from an operation like this would carry the ID, which could be used for everything an atomic add could do
3) Combining it with an atomic delete/pop, which could use the same mechanism with a second counter, would be enough to give us a MPMC queue through the KVS

It wouldn't quite completely subsume #251, sometimes you just have to have a test-and-set or compare-and-swap, to my chagrin, but I'm thinking this could cover several of our use-cases, (unique job-id/entry creation, IO consistency for merged output, queues for scheduling, natural append-based logs like the JSC could use in #206),  and give us an easy-to-use synchronization primitive too.

What do you think?

**Comment by garlick** [comment]
Here's a ref: [etcd-api](https://coreos.com/etcd/docs/0.4.7/etcd-api/) under _Atomically Creating In-order Keys_.  One interesting detail is a global counter is used to assign the keys (so there may be gaps).

Doing this in a way that would perform no worse than `kvs_commit()` seems quite doable, although that may not be efficient enough for demanding workloads like stdio.  Maybe we could supplement with an append operation that doesn't return the key, and is only atomic across a `kvs_commit()`, but preserves order within a commit?  Then a block of keys could be assigned at commit time.

**Comment by trws** [comment]
I completely agree. It dovetails with what we were talking about the other day, all it needs is "atomically append" where append does not guarantee any kind of ordering. In fact, having the second version could make the IO handling quite efficient depending on the target storage.



Sent with Good (www.good.com)

________________________________

**Comment by trws** [comment]
As we discussed at the meeting, this would be especially useful if combined with a "get all updates since" call that could provide the last key it looked at, then expect the reply to contain all key/value pairs that are logically "after" it in the ordering in that directory.  Something like:

```c
//producer
kvs_append_dir(h, "lwj.state", json_create("{s:i,s:s,s:i}", "job_id", jid, "state", new_state, "timestamp", time);
//consumer
void state_cb()//entered on a watch
{
  static const char previous[50] = {0};
  const char * json_str = NULL;
  if (previous[0] == '\0') {
    kvs_get_dir_recursive(h, "lwj.state", &json_str);
  } else {
    kvs_get_dir_since(h, previous, &json_str);
  }
  // unpack json_str
  const char *key, value;
  FLUX_ITER_ITEMS(key, value, json) {
    //Do something with each update
  }//last key preserved
  strncpy(previous, key, sizeof(previous)-1);
}
```

As an alternative to a json_str it could be a generic key-value iterator, but we don't have a good way to spec that yet.

**Comment by garlick** [comment]
Good discussion, no actionable work.
