### ISSUE TITLE
configure picks older python version

### ISSUE THREAD

**Issue by andre-merzky** [flux-framework/flux-core#2556]
#1673 introduced Python3 support.  The discussion on the PR states:
> AFAIK, it searches from the newest, stable python version (3.7) and works its way down (to 2.1).

This seems not to be the case:

```sh
$ python -V
Python 2.7.17rc1

$ python3 -V
Python 3.7.5rc1

$ env | grep PYTHON
$ ./configure --prefix=/home/merzky/projects/flux/install
[...]
checking for python... /usr/bin/python
checking for a version of Python >= '2.1.0'... yes
checking for a version of Python >='2.7'... yes
checking for the distutils Python package... yes
checking for Python include path... -I/usr/include/python2.7
checking for Python library path... -L/usr/lib -lpython2.7
checking for Python site-packages path... /usr/lib/python2.7/dist-packages
[...]
```

I don't think this is an error, but using `$PYTHON` should be documented, as the default is surprising.  I assume (but did not test) that this works correctly when `python` is in fact a Python3 binary, as [configure first looks](https://github.com/flux-framework/flux-core/blob/master/config/ax_python_devel.m4#L82) into the default `python` executable's version info.

**Comment by garlick** [comment]
Just to link in some background

* We tried to drop python 2 support in #2452 and included a configure fix 6327a7ab1abff2f34dc0042bfee03e19115456bd that preferred the `python3` executable over `python`  (falling back to `python`) because current distros generally make `python` refer to python 2.
* Because our production systems had python 3 but not all the python 3 variants of our prereqs, and because it's a lengthly process to get new packages installed on our systems, we reverted those changes in #2482
* I think the plan is once we get through that process, we'll reinstate #2452 and that should address this issue.

However, agreed: documenting `$PYTHON` behavior is a good idea.
