### ISSUE TITLE
job-info: race between submit response and info query

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2592]
The following scenario is racy
1. user submits job with `job-ingest.submit` RPC, gets jobid in response
2. user queries job-info job state with `job-info.list` or a future `job-info` single job info method (#2591), gets list/info response (doesn't find jobid)
3. job-info module receives initial `job-state` event message for the job

We discussed up front that this "eventually consistent" semantic should be acceptable in the design for a job listing service, however I think our design has evolved to the point where `job-info` is now the central clearinghouse for job information, not the job manager, and it would be good to close this race.

I think the code already exists in the "lookup" section of the job-info service to retrieve job info from the KVS.  The KVS _is_ guaranteed to be up to date before the user receives the job ID from a `job-ingest.submit` request.   Therefore, it seems like this could be solved with some refactoring?

**Comment by chu11** [comment]
>  Therefore, it seems like this could be solved with some refactoring?

Hmmm, right now the `job-info` module isn't aware that a job exists until it receives the `job-state` event message.  So I'm not sure that this race can be fixed in the general sense.  i.e.

1. user submits job
2. user do `flux job list --count=ALL | grep MYJOBID`, won't work
3. job-info module receives initial `job-state` event message

But as @grondo mentions in #2591, having a user job id specified could create a more specific case that is probably more handle-able.

Another racy thing that could perhaps be fixed, is that the `job-info` module also has to lookup data from the KVS before the job listing service will return data about the job.  So the race above is really more like:

1. user submits job
2. job-info module receives initial `job-state` event message
3. job-info module does KVS lookup on data about job
4. Now `flux job list --count=ALL | grep MYJOBID` works

if the user specified a specific job, then we could simply wait until all data is available and respond afterwards (this also relates to the R data case, see #2590), but its more complicated for the "give me a list of all job info" case.

**Comment by grondo** [comment]
> But as @grondo mentions in #2591, having a user job id specified could create a more specific case that is probably more handle-able.

Yeah, I think the important race to fix is for the single job query. There is a specific use case for MPIR debugger attach, see #2538.

**Comment by garlick** [comment]
Agreed.

**Comment by chu11** [comment]
It just ocurred to me, how could one differentiate between in invalid job id vs a jobid that has not yet been seen?  Lookup in kvs is only thing that comes to mind (i.e. does jobid path exist)

**Comment by garlick** [comment]
RIght, sorry my description was not very clear but it did include this at the end:

> I think the code already exists in the "lookup" section of the job-info service to retrieve job info from the KVS. The KVS is guaranteed to be up to date before the user receives the job ID from a job-ingest.submit request. Therefore, it seems like this could be solved with some refactoring?

**Comment by chu11** [comment]
just want to clarify something.  For this issue, is the user passing in 1 jobid sufficient?  Allowing the user to pass in an array of jobids is the somewhat obvious case to support.

1) the current code to list all jobs maps well to a list of jobids
2) the current code returns an array of json objects with job info, so the return of an array makes sense for the code for listing jobs in `flux-job` and `flux-jobs`.
3) the current job list service supports "max_entries", "attrs", "userid", "states" (states is in PR #2697), and "flags" as "filtering" options.  "max_entries" makes no sense when specifying jobids, but everything else continues to make sense if an array of jobids is specified.  e.g. user passes in a list of jobids and only wants jobs in a specific state, or those for a specific user, etc.

So I think we want to support an array of job ids passed in by the user.

the tricky part about the user specifying multiple job ids will be the raciness parts, looking up multiple job ids in the KVS, waiting for multiple job ids to be noticed by the job-info module, maybe something else I can't see right now.

If it gets more tricky than care for this round, I"m thinking "array of length 1" might be something to do for now.
