### ISSUE TITLE
[idea] named reduction approaches and named reduction module

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#266]
This is a placeholder to generate some discussions about named reduction support:
- Using unique names to provide isolation over reduction operations for programmability and security
- Creating a named reduction module

This was mentioned in both #251 and #221

**Comment by garlick** [comment]
> [@dongahn from #221] ... my current conclusion after prototyping with flux_red_t is that the reduction can be further extended into a module to provide a bit better isolation. As is, it seems difficult to create a logically isolated reduction operation without having to worry about other overlapping reduction operations (of the same type.)

> In this particular case of having to reduce hostnames, it is ideal if the same hostname reduction operations performed by wrexec and wrexecd sessions are all logically separated. Overall, if we were to generalize such extended reduction support through a module, isolation would be not only good for programmability but also security. We probably don't want one program owned by user A maliciously to try to have its reduction input data merged into an overlapping reduction operation issued by another program owned by user B.

> I think we can solve the isolation problem with 'named' reduction approach similar to the current named barrier. As mentioned in #251, I am creating a new idea issue to discuss general named reduction support.

Here's a random thought on isolation: the flux_t handle is (in a way) like an MPI communicator, in that it abstracts the instance (program), a user can call `flux_rank()` and `flux_size()`, send messages to other ranks, do barriers, fences, etc, over all ranks or a subset of ranks via this handle.  One could argue that it's inappropriate for a program to get such a handle to its enclosing instance, at least not without going through some kind of security boundary or abstraction layer.

Right now that layer consists of PMI, which chroots the KVS, provides rank and size information for the program, and limited collectives, but implemented in terms of a hidden flux_t handle for the enclosing instance.  I guess wrexecd is also operating on this boundary, moving stdio and signals to chrooted KVS locations, etc..  It seems like we should get very clear about this layer and the abstractions that it provides to programs.

Anyway, I don't know if that argues for using the KVS for reduction/collectives in order to avoid a proliferation of namespaces that we have to "chroot"?

**Comment by dongahn** [comment]
@garlick in fact I had similar thoughts when I was looking at the services like barrier. If the  barrier name can be somehow guessed by a malicious program owned by a user, one could easily create an overlapping barrier and can potentially do harm to another program owned by a different user.

Yes if we are not really really clear about isolation, it will be hard to create secure software. I was thinking to have that separation by prependung the reduce name with a unique program id. 

However, overall if we can limit such vulnerability point to only a very small set of services like kvs  and protect it with some secure mechnism, security will be more tractable.

Having said that, perhaps we should look at creating kvs_reduce instead?

If we can begin to provide basic reduction operator like min max sum and integer - compression (and also integer - compression by the same key) we can cover whole lot. 


BTW will wrexecd ultimately be run as root or user?

**Comment by grondo** [comment]
It is unknown at this point how the task manager will access privileged
functions like changing user IDs, initgroups, managing containers, and
other program setup requiring elevated permissions. The easiest way to
implement, but least secure, is to have the task manager run as root then
drop  privileges as is done in slurmstepd. We may be able to do something
more clever by leveraging privileged helpers or some other scheme.

In any event, if flux-broker runs as the instance owner, we'll need some
novel way to launch programs as other users to have a functional RM system.

**Comment by dongahn** [comment]
Leaving some of our discussion yesterday:
- Reduction has many utilities
- Is kvs is the right place to add the reduction? -- but since kvs_fence() is already a collective, the machinery might be already there
- What types of reduction should be supported? Reduction properties can be anywhere between a fixed-length reduction (the length of the reduced output is equal to the input) and a variable-length reduction (sources are reduced but not completely -- the worst case will be concatenation which will be the same as gather.) 
- Building known reduction operators (min, max, sum, list-compress, etc) and have both module/api users choose a built-in operator should be relatively straightforward. But since an external program (e.g., api user) will not be able to inject a custom reduction code, support for user-provided reduction operator needs some thoughts. Use of Lua script was mentioned. Building custom reduction module was mentioned. 

In any case, if I were to build a library that consist of collectives (barrier, reduction, gather, scatter ... broadcast) to support tools and PMGR, I will use kvs as much as possible, if scalable. Of the collection, it seems reduction is the only one that cannot not be done with kvs scalably at this point...

**Comment by garlick** [comment]
@dongahn following up on face to face discussion on a "named reduction module", i.e. trying a few things to prototype reductions that land the result in the KVS.  After you left, I recalled that this is very much like the monitoring work of last summer which we did work on/think about quite a bit but failed to take over the finish line.

The main challenge IMHO with building a dedicated module for reductions is leveraging the reduce.h stuff is making the source, sink, and reduce operations configurable.  Last summer we had discussed allowing "monitoring plugins" to be loaded into a monitoring module to supply these functions for a given reduction (and since then we added the libflux/module.h stuff which is generalized for modules loading plugins, e.g. scheduler loading sched plugins, monitoring loading monitoring plugins).  A step after that was going to be to allow lua scripts to be loaded from the KVS.

Maybe a good way to get a feel for the general case is to start with a hardwired reduction.  Perhaps transplant the hostlist reduction you've prototyped in `wrexec` module into a new module called `reduction` which has a request handler for `reduction.hostlist` that takes a hostname, KVS key name, and reduction parameters (count, timeout - depends how the user wants the reduce to proceed).  Checkout src/util/hostlist.[ch] which handles a lot of different corner cases covering different cluster node naming schemes.

 hostnames would be passed upstream (over a different "method" e.g. `reduction.hostlist.push`), reduced, and ultimately stored under the KVS key at the end.  Possibly the module could generate an event when that happens, and that event could be used to trigger responses to the original `reduction.hostlist` requests, similar to how the barrier module works.  So clients would be blocked in the reduce RPC until the result is in the KVS, while the reduction.hostlist handler would have created some state for the caller and returned, so that it can send a reply asynchronously upon receipt of the event while remaining responsive. 

Anyway, after getting a couple of hardwired reductions that work this way, maybe it'll be clearer how to generalize for user-configurable reductions.  

You could have a look at the [prototype we did last summer](https://github.com/chaos/ngrm/blob/master/zmq-broker/monsrv.c) although it's pretty old now.

**Comment by dongahn** [comment]
@garlick: great feedback! This validates what I thought I should be headed after our discussion. For hardwared reduction operators, I will probably want to go for simple primitives like sum, min, max... and also list-compression (`{"1"} op {"2-5"} = {"1-5"}`) and list-comparession across the same key (`{"cab" : "1-2", "hype": "2"} op {"cab" : "3-6", "hype": "4"} = {"cab": "1-6", "hype": "2,4"}` ) . Then, I can use the last for the hostlist reduction. 

By utilizing the path within the kvs as the name, into which the reduced output should go, I thought I could even hide sink from the users. A ready-made sink will be registered to `flux_red_t`, but it will call end up invoking the user-provided reduction operator. Similarly a ready-made reduce_fn will be registered and do some name and count management and end up calling the  user-provided reduction operator like merge (flux_t h, JSON lhs, JSON rhs, void *arg). For the hardwired one will have a set of these merge functions that the user can select. 

I will think about how general reduction operator can be loaded and one while I am doing this. It could be lua -- perhaps it can now be a python script...

**Comment by garlick** [comment]
Oops I gave you the wrong path to hostlist.h, it is `src/common/liblsd/hostlist.h`.  It gives you a list-like data structure that can be converted to a compressed hostrange string, and that can accept hostrange strings as elements (or plain hostnames).

Here's a teaser from the pdsh man page:

> **HOSTLIST EXPRESSIONS**

> As  noted  in  sections  above  pdsh accepts lists of hosts the general form: prefix[n-m,l-k,...], where n < m and l < k, etc., as an  alternative  to explicit lists of hosts. This form should not be confused with regular expression character classes  (also  denoted  by  ‘‘[]’’).  For example,  foo[19]  does  not  represent  an expression matching foo1 or foo9, but rather represents the degenerate hostlist: foo19.

> The hostlist syntax is meant only as a convenience on clusters  with  a "prefixNNN" naming convention and specification of ranges should not be considered necessary -- this foo1,foo9 could be specified as  such,  or by the hostlist foo[1,9].

> Some examples of usage follow:
> Run command on foo01,foo02,...,foo05
>         pdsh -w foo[01-05] command

> Run command on foo7,foo9,foo10
>          pdsh -w foo[7,9-10] command

>  Run command on foo0,foo4,foo5
>          pdsh -w foo[0-5] -x foo[1-3] command

> A suffix on the hostname is also supported:

> Run command on foo0-eth0,foo1-eth0,foo2-eth0,foo3-eth0
>          pdsh -w foo[0-3]-eth0 command

**Comment by garlick** [comment]
Closing old reduction discussion.
