### ISSUE TITLE
support job time limits

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2735]
Time limits are still not enforced, is that expected?

```console
$ flux mini run --time-limit=5s --dry-run sleep 10 | jq '.attributes.system.duration'
5
$ time flux mini run --time-limit=5s sleep 10

real	0m10.419s
user	0m0.125s
sys	0m0.055s
```

**Comment by grondo** [comment]
Yeah, that's expected. Currently `.attributes.system.duration` is set but ignored. For proper implementation, the scheduler should set an *expiration* time in *R* per [RC 20](https://github.com/flux-framework/rfc/blob/master/spec_20.rst#execution). Then (I suppose) the exec system would set a timer to fire at expiration to kill off the job.

If we don't want to implement that just yet since the exec system may be getting a rework, we could add a shell plugin to kill self at timeout (this is what we had in wreck). The shell plugin could later be adapted to (optionally) send a non-fatal signal to jobs some configurable number of seconds before *R* expiration...

**Comment by garlick** [comment]
Ah sorry, I had lost track of that.  I was thinking of using it as a timeout in a flux-runs-flux test but I don't _need_ it.  IMHO if our workflow users don't find a sudden urgent need for this, it can wait until we circle back.

**Comment by grondo** [comment]
NP. I did forget about it as well. We should ask if anyone was using the time limits in wreck. If so then an advisory timelimit implemented in the shell for now would work short term (and take about 10 minutes to implement)

**Comment by dongahn** [comment]
I just left a comment in #2787. This is pretty significant for the correctness of flux-sched.

**Comment by grondo** [comment]
Since job-exec rework in #2874, a temporary fix for this issue in the current job-exec module should be implemented for our next release.

I think as a first cut, job-exec module will just emit a sev=0 exception when the job timelimit is reached (resource allocation expiration).

I'm not clear on the established rules and conventions for job exceptions. Currently job-exec marks all exceptions it emits as type=exec, will that work for now?

Later we could have a less severe exception generated a configurable amount of time before the final time limit, as a way to warn the job of impending timeout.
