### ISSUE TITLE
bindings: binding for "job-info.list-inactive"

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#2776]
Forgot to add this binding, b/c it was not needed for `flux-jobs`, but will (likely) be needed for flux sched work.

**Comment by cmoussa1** [comment]
So I think I've got a pretty good start on this so far, but I wanted to bounce some ideas and maybe get some feedback:

```python
def job_list_inactive(flux_handle, max_entries=100, timestamp=0.0, attrs=[]):
```

I'm trying to think of the default values for the function, specifically `max_entries` and `timestamp`. If a user doesn't specify a timestamp, then should we just default to jobs that have completed in the last _t_ minutes? Something like `time.time() - 10000`? I just used the `time.time()` function since fields like `t_submit`, `t_inactive` return time values in the same format. I was also thinking we could set `max_entries` to a default value like 100 (referenced from @grondo's suggestion in #2738).

**Comment by grondo** [comment]
I think the defaults above make sense. That way by default you get 100 (or you could make this 1000) of the most recently inactive jobs if you just call `job_list_inactive(h)`.

One suggestion (more personal preference) -- I wonder if renaming the `timestamp` parameter to `since` would be slightly more user friendly; it gives a better hint at what the parameter does.

```python
# get all jobs that went inactive in the last hour
job_list_inactive(h, since=time.time()-3600., max_entries=0)
```

**Comment by grondo** [comment]
>  then should we just default to jobs that have completed in the last t minutes? Something like time.time() - 10000? 

I think sticking with default `max_entries` will be safer. A *lot* have jobs could have finished in the last 10K seconds :wink:

**Comment by cmoussa1** [comment]
> One suggestion (more personal preference) -- I wonder if renaming the timestamp parameter to `since` would be slightly more user friendly; it gives a better hint at what the parameter does.

I like this suggestion! Thanks.

**Comment by chu11** [comment]
@grondo always beats me to a response :-)

I was pondering if the default `max_entries` for `job_list` is good.

`def job_list(flux_handle, max_entries=0, attrs=[], userid=os.geteuid(), states=0):`

I think I did `max_entries=0` b/c that's the default in `flux job list`.  But calling python code is quite different than calling C code.  With C code you have to consciously decide to pass in `max_entries=0`, but with Python, you could just call `flux.job.job_list (h)` and be none the wiser, causing DOS (#2601).

I wouldn't be against a non-zero `max_entries` for `job_list`, but would it need to be consistent to `job_list_active`?

**Comment by chu11** [comment]
> One suggestion (more personal preference) -- I wonder if renaming the timestamp parameter to since would be slightly more user friendly; it gives a better hint at what the parameter does.

I like `since`.  If we go with that, probably should be adjusted everywhere (`job-info` module, `common/lib/job.[ch]`, `cmd/flux-job` option, tests).

**Comment by dongahn** [comment]
Maybe related. Yesterday, I found myself wanting to find all the jobids since a point in time. I didn't think "time" would be best to capture this point because it can be skewed and other distribute-system side effects can occur 

Will there be a safer synchronization mechanism that will allow me to define the point state in job list and fetch the status of jobs completed afterward that point?

**Comment by grondo** [comment]
> Will there be a safer synchronization mechanism that will allow me to define the point state in job list and fetch the status of jobs completed after that point?

Good comment. For @cmoussa1's case, we had discussed using the last consumed jobid as a "point state" in the inactive list. I can't remember the details, but I assume that the sorting of jobids wasn't stable in some corner cases, so a timestamp was considered the most reasonable approach for now (@chu11 could fill in details)

Since the inactive timestamp of a job can never change, I don't think it could be "skewed", but I'm worried you may have some other cases in mind, so perhaps we should open a specific issue for your comment?

**Comment by chu11** [comment]
> Good comment. For @cmoussa1's case, we had discussed using the last consumed jobid as a "point state" in the inactive list. I can't remember the details, but I assume that the sorting of jobids wasn't stable in some corner cases, so a timestamp was considered the most reasonable approach for now (@chu11 could fill in details)

The timestamp approach was mostly chosen b/c the inactive job list is already sorted by `t_inactive`.  So it just sort of made sense.  Going by `jobid` would be nearly equivalent code wise, as we simply replace a `job->t_inactive > timestamp` with a `job->id != point_state_id` check.  The latter case is perhaps a tad more dangerous, b/c if you have a bad input, you'll likely get all jobs??

> Since the inactive timestamp of a job can never change, I don't think it could be "skewed", but I'm worried you may have some other cases in mind, so perhaps we should open a specific issue for your comment?

Yeah, I was thinking the same thing.  I'm thinking you perhaps want all jobids after a jobid, but possibly some that have not completed yet?

**Comment by dongahn** [comment]
My use case is with `flux-tree`. Yesterday, I tried to detect the maximum exit code among all the the jobs submitted by a jobscript, an input to `flux-tree`. With `flux tree --leaf` option, `flux-tree` executes the jobscript at the current level. Thus, `flux jobs -ano {id} -c 0` give both the already completed and newly completed jobs".

I could get the last job before executing the jobscript and use that as my state point. If that's the case, would `flux jobs -ano {id} -c 1` provide this?

**Comment by grondo** [comment]
>  Thus, flux jobs -ano {id} -c 0 give both the already completed and newly completed jobs

Sorry, I didn't follow this statement. At a leaf, what jobs are "already completed" vs "newly completed". I was assuming a leaf only ran the user jobscript.

In general `flux-tree` could capture the jobids of the jobs it is directly submitting, and then filter those out of the `flux jobs` listing before collecting exit status or doing any other analysis.

**Comment by garlick** [comment]
> Going by jobid would be nearly equivalent code wise, as we simply replace a job->t_inactive > timestamp with a job->id != point_state_id check.

That threw me for a second since the inactive list is not ordered by jobid, but I guess since jobs are only ever appended to that list, it works just as well as time.  Either way you have to scan search through the list to find where you left off (bummer actually).

Maybe that scan could be avoided by caching the list cursor for the last N queries (by "state point" whatever that is)

**Comment by dongahn** [comment]
> Sorry, I didn't follow this statement. At a leaf, what jobs are "already completed" vs "newly completed". I was assuming a leaf only ran the user jobscript.

If jobscript.sh:
```bash
#! /bin/bash

flux mini submit -N 1 -n 1 bash -c 'exit 2'
```

```console
flux start
flux mini run -N 1 -n 1 bash -c 'exit 8'
flux tree --leaf -J 10 ./jobscript
```

If flux tree is used this way, you want to be able to detect 2 as the max exit code not 8. So `flux jobs -ano {id} -c 0` won't work for this case. 

> In general flux-tree could capture the jobids of the jobs it is directly submitting, and then filter those out of the flux jobs listing before collecting exit status or doing any other analysis.

I already do that for internal flux instances. No problem. It is just those jobs that are indirectly submitted by the jobscript, that is harder to treat using the current mechanisms.

For now, I just don't support this. But if the support you are talking about here provide a well-defined state point , I thought I could use that to add support for indirectly submitted jobs.

**Comment by grondo** [comment]
Ah, thanks @dongahn. That makes sense now. In this case you can't use the previously submitted jobids as a point state because they may not all yet be inactive (so they have no inactive timestamp, obviously)

About the only thing I can think of for this case is to capture all current jobs, active & inactive, in `flux-tree` before you launch `jobscript`. Then exclude all those jobids from the exit status gathering. 

Another solution would be the standard Flux solution: run jobscript in a new instance! :wink:

**Comment by dongahn** [comment]
> Another solution would be the standard Flux solution: run jobscript in a new instance! 😉

Yes, that's `flux tree -T1`. Maybe `--leaf` is hidden from the user so that users won't run this.

**Comment by dongahn** [comment]
> About the only thing I can think of for this case is to capture all current jobs, active & inactive, in flux-tree before you launch jobscript.

Yes, this was sort of job state point support I was imaging, a handle that represent this point state. Seems too much to ask..

**Comment by chu11** [comment]
> Maybe that scan could be avoided by caching the list cursor for the last N queries (by "state point" whatever that is)

Not following.  Even if you cache the "state point", you still have to iterate through the list to grab everything to return.   We'd avoid the condition check, which I guess is a small improvement.

**Comment by garlick** [comment]
I meant if each successive query has to start over at the beginning of the
list to find its place from the previous call, maybe that could be
avoided.  Does that make sense at all?

**Comment by grondo** [comment]
> I meant if each successive query has to start over at the beginning of the
list to find its place from the previous call, maybe that could be
avoided.  Does that make sense at all?

AFAIK,  a "restart" timestamp is not currently supported (correct me pls @chu11), so the RPC always starts from the at the beginning of the list. That might be the source of confusion here.

Once we do support restarting from the last RPC, I really like @garlick's suggestion for a simple optimization! (Perhaps this should go in a new issue :smile:)

**Comment by garlick** [comment]
Oh sorry, I picked up the thread late!

**Comment by chu11** [comment]
> I meant if each successive query has to start over at the beginning of the
list to find its place from the previous call, maybe that could be
avoided.  Does that make sense at all?

Jobs on the inactive list are sorted by `t_inactive`, with more recent (i.e. larger timestamps) on the list first.  So we always have to start at the beginning of the list and work our way down until we hit the first timestamp <= to the one input.

Perhaps you're thinking if the list was sorted with smaller timestamps first?  Then it'd be a good idea to cache a prior query's cursor?

Or am I just missing something.

**Comment by grondo** [comment]
> Perhaps you're thinking if the list was sorted with smaller timestamps first? Then it'd be a good idea to cache a prior query's cursor?

I think @garlick was pondering about RPC restart (i.e. there are more job entries to fetch, but `max_entries` was hit). I opened #2778 to cover this case.

We should make sure there is room in the RPC response message for a `more=True` flag to be added in the future though.

**Comment by SteVwonder** [comment]
Per the example in https://github.com/flux-framework/flux-core/issues/2776#issuecomment-591561937:
```python
# get all jobs that went inactive in the last hour
job_list_inactive(h, since=time.time()-3600., max_entries=0)
```
Just a heads up that the default arguments are only constructed on the first call to a function, not every time you call it.  That is an unfortunately common "gotcha" in python. [More info](https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments).  So that `time.time()` will only be evaluated once and cause all sorts of odd behaviour.  The common python idiom for situations like this is to use `None` as the default value, then check for `None` and do your function call/object creation there.  For example:
```python
# get all jobs that went inactive. By default, in the last hour
def job_list_inactive(h, since=None, max_entries=0):
  if since is None:
    since=time.time()-3600.
  # do more stuff here
```

**Comment by grondo** [comment]
> Per the example in #2776 (comment):

> `# get all jobs that went inactive in the last hour`
> `job_list_inactive(h, since=time.time()-3600., max_entries=0)`

Thanks @SteVwonder! That is definitely enlightening! (and when you think about it, it makes sense).

To avoid confusion, this example was supposed be an example function *call* not a defintion. I think principle of least surprise dictates here that the default value for `since` (if that's what we're calling it) is `0.` and `max_entries=1000` (for parity with `job_list()`).

**Comment by chu11** [comment]
`max_entries=1000 (for parity with job_list()).`

FYI, `job_list()`'s `max_entries` default is `0`, but agreed that should be updated to 1000.  To go along with this issue.
