### ISSUE TITLE
Support Xterm in Interactive Jobs

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#2801]
To better support debugging, it would be useful to have `flux mini run xterm` work.  It may already work, but someone needs to investigate if we need to do anything special for DISPLAY (and possibly tunneling it).

**Comment by grondo** [comment]
Bingo bango, it works!

```console
 grondo@fluke108:~$ env | grep DISPLAY
DISPLAY=192.168.128.108:10.0
 grondo@fluke108:~$ srun flux start flux mini run xterm
```

and an xterm hath appeared upon my desktop!

![Screenshot from 2020-03-05 16-15-50](https://user-images.githubusercontent.com/741970/76037734-a585cb80-5efc-11ea-8137-f91e68431ba9.png)

**Comment by grondo** [comment]
This seems to work within a cluster since the `DISPLAY` environment variable contains an ip address, ports are not blocked on the mgmt ethernet, and `DISPLAY` is forwarded along to jobs.

Slurm also has an `--x11` option to `srun(1)`, which, after a cursory investigation, seems to port forward using libssh2 from the selected remote node(s) during the job prolog to create a `localhost` `DISPLAY`.

**Comment by grondo** [comment]
Closing old issue in favor of #3987
