### ISSUE TITLE
t0013-config-file.t hangs

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#2834]
The last two tests in the config file test are regularly, but semi-randomly, hanging for me.  I attempted to add run_timeout to the broker in start_broker, but got nowhere.  Somehow the waits are not behaving as I would expect, and I'm not sure where to go from here, especially because no broker seems to be running during the hang.

**Comment by chu11** [comment]
```
test_expect_success 'start size=2 instance with ipc://' "
	start_broker ${TCONFDIR}/good-ipc2 fake0 flux getattr size >ipc.out &&
	start_broker ${TCONFDIR}/good-ipc2 fake1 &&
	wait &&
	wait &&
	echo 2 >ipc.exp &&
	test_cmp ipc.exp ipc.out
"
```

here's a guess to the hang.  Is it possible one of the backgrounded processes had already completed before the wait call.  Thus the call to `wait` will just hang?  Similar the test after this one.

**Comment by trws** [comment]
That is a very good point actually, I was thinking it should just 
proceed if there’s nothing to wait on, but maybe there’s a 
backgrounded process that isn’t stopping so it keeps waiting on it 
after missing what it’s meant for.  Thanks Al.

**Comment by SteVwonder** [comment]
Definitely not the source of the hang but from the documentation for wait:
```
wait [n]

If n is not given, the command waits until all jobs known to the invoking shell have terminated. 
```

So I think only one `wait` is necessary, but two doesn't hurt because like @chu11 pointed out, it returns 0 if there are no children backgrounded to wait on.

**Comment by grondo** [comment]
One other point - since sharness tests are eval'd they are all running in essentially the same shell. There is a chance that something *earlier* left a background shell process running and that could be why the 2nd (or 3rd or..) `wait` could block. Definitely safer to wait on pids explicitly, that is a good lesson to remember with sharness. *also* as @garlick pointed out to me before, if  a pid is not given, then `wait` will always return `0`, so we don't collect the possibly nonzero exit codes of the background processes, potentially missing a failure.
