### ISSUE TITLE
tests picking up installed libflux-core

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#284]
I have flux-core and flux-core-devel RPM's from a few weeks ago installed on a test system.

I added a new symbol `flux_msg_iobuf_init()` to libflux-core in my working copy, and used it in the `local` connector.  Everything seemed to be working superficially, but in a make check,`t/lua/t10002-kvs.t` failed here:
```
 ok 35 - Can set arbitrary members of kvswatcher object
 flux: symbol lookup error: /home/garlick/proj/flux-core/src/connectors/local/.libs/local.so: undefined symbol: flux_msg_iobuf_init
```
After `rpm -e flux-core flux-core-devel` the test passed.

**Comment by grondo** [comment]
Ooh, that's not so good -- but a good catch.

Did it only affect the lua tests? (which probably incorporate at least one extra dlopen() since the flux.so lua lib is loaded, which then pulls in libflux-core.so...)

**Comment by garlick** [comment]
The tests prior to that one worked.  It hung there so I don't know about after (but there's not much after).

**Comment by grondo** [comment]
Oops, oversight in `fluxometer.lua` package paths ordering is probably the problem:

 https://github.com/flux-framework/flux-core/blob/master/t/fluxometer.lua.in#L52-L55

I'm trying to set up a docker instance and strategy to test the fix, then I'll push up a "fix"

**Comment by grondo** [comment]
Actually, the above is a problem, but doesn't explain the issue you saw since it should cause *all* lua tests to fail. I think I see a similar issue with `PATH` in the `fluxometer` test driver (geez, I wasn't being very smart in this thing..). 

Since `PATH` to in-tree flux is appended instead of prepended, I think what is happening is any call to `flux` in the lua tests is getting the system instead of in-tree command driver.
