### ISSUE TITLE
`flux job info JOBID` behavior with no key

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#2851]
`flux job info` is a really useful tool.  One thing that I run into using it: I forget what keys are available for querying.  I'm not sure what the best behavior would be, but two ideas are when `key` is not provided:

- list the available set of keys
- list the available set of keys with their values

**Comment by chu11** [comment]
this seemed like an easy issue to tackle at 5am :-)

so started to think about this, but the issue is how to do this without just hard-coding a list of well known keys.

I could output something equivalent to this:

```
>flux kvs dir -R job.0000.004e.6700.0000 | awk '{print $1}' | sed "s/job.0000.004e.6700.0000.//"
J
R
eventlog
guest.exec.eventlog
guest.input
guest.output
jobspec
```

but dunno if we want users doing an info lookup on input & output, which can get big?  But at the same time, `flux job info` is not a user facing tool.  So I think this is ok?

I could output only the first level?

```
J
R
eventlog
guest
jobspec
```

But `guest` doesn't work b/c its a dir.

```
>flux job info f9r3AUA3 guest
2020-09-12T12:53:11.536409Z job-info.err[0]: info_lookup_continuation: flux_kvs_lookup_get: Is a directory
flux-job: flux_rpc_get_unpack: Is a directory
```

so I think the former case is preferred, accepting that the user may do something stupid in the end.
