### ISSUE TITLE
don't sign jobs if running as the instance owner

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2920]
If flux-core is configured `--with-flux-security`, then jobspec will be signed with the default signing mechanism (munge).  This adds the latency of a RTT with the munge daemon to job submission time.  If the instance owner is submitting the job, the jobspec doesn't need to be signed, but right now there is not an easy way for the submission program to know that it is running as the instance owner.

A possible optimization is to have the broker set an environment variable like FLUX_OWNER, then have `flux_job_submit()` use the "none" signing method when that matches `getuid()`.  Then the initial program (and hence jobs submitted by workflows) would be able to skip the munge encoding.

I'm not sure if this is all that helpful, but the discussion in #2915 reminded me of this possible avenue so thought I'd at least open a bug which we can close if it's not worth it.

**Comment by grondo** [comment]
> A possible optimization is to have the broker set an environment variable like FLUX_OWNER, then have flux_job_submit() use the "none" signing method when that matches getuid(). Then the initial program (and hence jobs submitted by workflows) would be able to skip the munge encoding.

Not a bad idea. My first thought is that environment variables should be avoided when dealing with matters of security,  but here I think the only result if FLUX_OWNER is wrong or modified is that unsigned jobs would be rejected. (Though this might not occur until they hit the IMP?)

Eventually, even non-owners might want to be able to fetch the instance owner uid, so that jobs can be targeted to run *only* on an instance owned by the expected user (i.e. owner userid would be embedded in J). However, that use case is likely a ways off.

Hm, maybe instead of a FLUX_OWNER env variable, we could be more explicit and set the sign-type in an environment variable? This might be useful in testing as well (it would allow us to still sign jobspec even though all tests run as instance owner.)

**Comment by garlick** [comment]
I believe this should have been closed by #3306.
