### ISSUE TITLE
need capability to override service methods

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#293]
We discussed the need to be able to extend or override flux services without having to completely replace them.  For example if a service named "foo" implements methods "foo.a" and "foo.b", it should be possible to add a "foo.c" or override "foo.b" without having to replace "foo.a".

One way to implement this might be to allow new service instances to be pushed into the service plumbing, implementing a stack, so that a request to "foo" is routed to the top instance which can either handle the request or forward it to the next instance, and so on, until the bottom is reached and an ENOSYS response is generated for unimplemented methods.  All instances below the top would not have a direct broker connection; messages would be routed through the instances "above" it.

It should also be possible for all instance to collaboratively handle requests.  For example, the built-in shutdown request would need to be handled "bottom up" by all instances.  The ping request might be implemented only in the bottom instance.  The stats request might need to sum message counts at each instance.

**Comment by grondo** [comment]
The idea of overriding service methods is really powerful.

Now, allow me to go off the deep end for a bit.

You could perhaps get halfway there if the module and service "routes"(?) were decoupled. Thinking of a module kind of like a package, and the service a public instance of that package, loaded ~~packages~~modules could override services by registering their service last (perhaps even the init script could do this.)

You could easily compose services from a bunch of different modules because modules could make inter-module calls (as they do now), but utilities/tools would target the publicly registered service names.

So module `bar` could implement the base `foo` service with `bar.a` and `bar.b`. Then module `baz` is loaded and overrides service `foo`, but it can forward method `a` to `bar.a` if necessary, and can easily override `b` and add extension method `c`.

The only benefit to this is that the plumbing would not have to change (I say that without being sure).
And having every module implement a routing stack sounded like a little bit of work. (Would that also be supported for modules-as-processes?) Also might make the shutdown path more sane, and the bottom-up-top-down shenanigans reduced.

It is also a lot like interface composition or maybe duck typing, which seems to be popular with the kids these days (though your proposal of modules with a routing stack is a similar interface)

What I do like about your proposal above is that you also get a kind of scope hiding, which would be nice. I just thought I'd throw another idea on the pile.

**Comment by garlick** [comment]
I like the decoupling of service name and module name in your proposal.  That probably needs to happen for services to be implemented in non-module contexts anyway (e.g. maybe a `cmb.register` handler would be added to register services in the broker).

It seems like rather than having `baz` forward messages to `bar`, it might be more efficient to register the individual methods with the broker.  Requests could then be routed to the correct destination without having to travel extra hops or be decoded multiple times.

**Comment by grondo** [comment]
> It seems like rather than having baz forward messages to bar, it might be more efficient to register the individual methods with the broker. Requests could then be routed to the correct destination without having to travel extra hops or be decoded multiple times.

Yeah, I was going to suggest the same thing (but didn't want to take it too far at first)

Registering sets of methods under a service name as an "interface" would have some nice properties. For example, standardized services could have a base set of methods, and if a new module tried to register for the service, but didn't have the same methods and/or method signature the registration could fail. Additionally, this ability could offer a more lightweight introspection into the flux instance -- i.e. instead of sending queries to `foo.x` to see if method `x` exists in service `foo` and checking for `ENOSYS`, there could be a `cmb` service that directly replies with the methods registered for `foo`.

**Comment by garlick** [comment]
Old issue.  Open a new one if we want to revisit.
