### ISSUE TITLE
simple mechanism to select scheduler

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#2946]
Problem:  `sched-simple` is unconditionally loaded, then unloaded and replaced by an EXTRA_RC if flux-sched is installed into the same prefix.  flux-sched's rc scripts implement some fine grained control using environment variables.

The general problem of how to best support external projects that provide flux modules has had us stuck for a while; however, it seems like we could make an incremental improvement over the current situation for the scheduler.

Here's a straw man proposal:

1) Define a broker attribute `sched.modules`

2) Replace the hardwired load/unload of `sched-simple` in rc1/3 with e.g.
```sh
SCHED_MODULES=$(flux getattr sched.modules)
test -n "$SCHED_MODULES" || SCHED_MODULES=sched-simple
for modname in $SCHED_MODULES; do
    flux module load $modname
done
```
3) allow attribute to be set from TOML to configure scheduler in system instance
```toml
[sched]
modules = [ "sched-fluxion-qmanager", "sched-fluxion-resource" ]
```

Ideas for embellishments:
* get initial value of `sched.modules` from enclosing instance (inherit the default)
* convenience option for users to choose scheduler by name in batch submission

Maybe that's not a great idea but wanted to start a discussion and see if we can come up with something better.

**Comment by grondo** [comment]
See also #2273, and before that #1039.

Proposal above seems like it could work, but it would be nice to come up with something generic instead of sched module specific.

How do you pass options to the multiple scheduler modules if necessary? 
How do you enforce order of sched module loading (if that happens to be required)?

**Comment by garlick** [comment]
Thanks for the back refs (I should have searched those out).  I'll go ahead and close this and make a comment in #2273, since there's more intelligent life over in that issue :-)

**Comment by grondo** [comment]
> How do you enforce order of sched module loading (if that happens to be required)?

Ah, well that was a dumb question, since the proposed config key is an array. Sorry not thinking clearly today I suppose.

Thinking about use cases, it would be nice if there was a way to encapsulate the scheduler choice into a single string, eg.

```
$ flux start -o,-S sched=fluxion 
```

instead of 

```
$ flux start -o,-S,sched.modules=sched-fluxion-qmanager,sched-fluxion-resource
```

Which also gives the user the opportunity to cause modules to load in the wrong order, if order matters.


Could each scheduler (or other replaceable service) provide a toml config, with enough info to load itself, into a well known location under a specific name. Then with `flux-start` or `flux-broker` we add an option to select from these named configs?

In fact, since reading a toml table will override the previous table, would it work to have a default 

```toml
[sched]
modules = [ 'sched-simple' ]
```

Then if another `sched` config is selected, the default is overridden?

**Comment by grondo** [comment]
> I'll go ahead and close this and make a comment in #2273, since there's more intelligent life over in that issue :-)

Ah, oops. I'll paste my comment over there as well.

**Comment by garlick** [comment]
Oops sorry!
