### ISSUE TITLE
possible cleanup to reactor "message watchers"

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#296]
I've always been a bit bothered by the fact that we have a flux_t handle that can behave like a file descriptor in its ability to be polled or to operate in non-blocking mode, but we have no "handle watcher" in the reactor; instead we have "message watchers" that take a `const flux_msg_t` argument and are driven by a message dispatcher.

Another way to go about this might be to add "filter handles", message queues for messages matching specific criteria
```
flux_t flux_filter_open (flux_t h, struct flux_match match, int flags);
```
Instead of dispatching messages directly to message watcher callbacks, messages could be dispatched to the filter handle, which could be watched with a "handler watcher".  A handle watcher would look similar to an "fd watcher" monitoring FLUX_POLLIN. The callback would call `flux_recv()` on the filter handle, be stopped and started without affecting message dispatch, etc..

A handle watcher might come in handy for other flux_t handle "extensions".  For example in #271 we discussed creating handles as notification channels.

**Comment by grondo** [comment]
Is this just a kind of rename of msg watchers? It feels a bit more awkward to me as a user of the interface to create new handles (which I think of as my connection to a local broker) as a filter for incoming messages, than to just register my interest in specific message.

(Some other questions come up immediately like can I `flux_send()` on the filter handle,
what happens if I use it for an RPC but the `match` parameter doesn't match the reply?, etc.)

However, I don't really see a problem with not having a "handle watcher" because the API doesn't really expose the handle as a file descriptor, so I'm probably missing part of the story here.

Maybe some examples here might help me.

**Comment by garlick** [comment]
Closing as the message dispatcher and reactor are being refactored a different way
