### ISSUE TITLE
pymod: remove outdated module?

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#2991]
Now that we have the `service.add` method, which allows python scripts to register services, there may not be as much of a use case for embedding python into the address space of the flux-broker.

Given that there are no extant users of `pymod`, its limitation to only loading one "script" at a time, and the extra burden of maintenance, perhaps we should remove the module?

I'm fine with keeping it if someone is using it, or there is an opinion it is a good example, though.

**Comment by SteVwonder** [comment]
:+1: I'm fine with removing it.  I don't know of any users of it currently.

Any objections @trws?

**Comment by trws** [comment]
Yeah, if there aren't any users, feel free to nuke it.

That reminds me in a round-about way, is `service.add` also the go-to solution for the module naming in non-C languages issue? I remember we talked about having a fallback to calling a function rather than externing a c-compatible string, but it seems like `service.add` from a process could get to the same place.

**Comment by grondo** [comment]
Yes, `service.add` is a good workaround for now. The only drawback is that instead of using a direct connected ZMQ socket to the broker, these services will be jumping through a connector-local socket.

Eventually it would be nice if even DSO modules could be loaded as external processes, and I've twice done some work that would get us halfway there, but I think it will have to wait awhile.
