### ISSUE TITLE
`flux start` doesn't respect --cores-per-socket

### ISSUE THREAD

**Issue by rountree** [flux-framework/flux-core#3003]
Running on Quartz using 773c0819e6.... from Friday June 12th.

```
salloc --nodes=4 --sockets-per-node=2 --cores-per-socket=18 --threads-per-core=1 --time=12 --partition=pdebug

srun --pty --mpi=none --ntasks=8   --nodes=4 --sockets-per-node=2 --cores-per-socket=1  --threads-per-core=1 -ppdebug flux start

flux mini run -o cpu-affinity=on --ntasks=8 hostname
```

`hostname` returns the same node name despite `flux start` inheriting 2 sockets per node and 1 core per socket.  Expected behavior is 4 different node names, two from each node.

**Comment by grondo** [comment]
Flux isn't aware of any of the `--extra-node-info=` options specified via `srun(1)`. It only respects CPU affinity set by the parent RM.

The Slurm "extra node info" (`--sockets-per-node`, `--cores-per-socket`, and `--threads-per-core`) is just that -- extra requirements placed on nodes allocated to your job. It isn't telling Slurm how to bind tasks in the job.

E.g. from the documentation:
```
       -B --extra-node-info=<sockets[:cores[:threads]]>
              Restrict  node  selection  to  nodes with at least the specified
              number of sockets, cores per socket  and/or  threads  per  core.
```

E.g. in the example above (using just one allocated node as an example), the `--sockets-per-node`, etc options to `srun(1)` have no effect, and in fact since the node is already allocated they are (probably?) ignored:

```
 grondo@quartz1:~$ srun -N1 --sockets-per-node=2 --cores-per-socket=18 --threads-per-core=1 --ntasks=4 --mpi=none sh -c 'taskset -c -p $$'
pid 56189's current affinity list: 0-8
pid 56190's current affinity list: 9-17
pid 56192's current affinity list: 27-35
pid 56191's current affinity list: 18-26
 grondo@quartz1:~$ srun -N1 --ntasks=4 --mpi=none sh -c 'taskset -c -p $$'
pid 56856's current affinity list: 9-17
pid 56855's current affinity list: 0-8
pid 56858's current affinity list: 27-35
pid 56857's current affinity list: 18-26
```

**Comment by grondo** [comment]
This or something similar might be good for the FAQ (@SteVwonder)

**Comment by grondo** [comment]
Closing the issue since the question has been answered.
