### ISSUE TITLE
`mini batch`: create nested instance without copying script

### ISSUE THREAD

**Issue by jameshcorbett** [flux-framework/flux-core#3021]
While I was working on #3020 I started to think that there might (maybe) be some use for `mini batch`-like behavior that doesn't involve copying the script, and I would be happy to implement it if you like the idea. The only use-case I can think of is when using Python venvs. If you put `#!/path/to/my/venv` in your script, you're stuck with that particular venv and it's an extra step to share it with others. My usual work-around in this case is to execute the script with `python script.py`---or better yet, `sys.executable script.py`---so the interpreter is chosen at execution time. However, that's not possible when the first positional argument to `mini batch` is assumed to be an executable text file. 

I think the above would be simple enough to implement as a flag like `--no-copy` that would make `mini batch --no-copy CMD` expand to `flux mini run RESOURCES [tasks-per-node=1] flux start CMD`. (@grondo implemented `mini batch` slightly differently and probably for good reason, but I think what I have above would work...)

I would also want to implement something similar in the python bindings. It can already be done, of course, I'm just not sure that `jobspec.setattr_shell_option("per-resource.type", "node")` is the best look...

**Comment by grondo** [comment]
> I think the above would be simple enough to implement as a flag like --no-copy that would make mini batch --no-copy CMD expand to flux mini run RESOURCES [tasks-per-node=1] flux start CMD. (@grondo implemented mini batch slightly differently and probably for good reason, but I think what I have above would work...)

I'm not sure I follow this 100% (my fault not yours). The `mini run` equivalent of `mini batch` is `mini alloc` (sorry, not the greatest name). Is it perhaps that command for which you need a variant?

I'll just mention that `mini batch` copies script contents because that is what users are used to. It lets you submit a script, edit it, and resubmit a different script. Since jobs may sit in the queue for awhile, copying script contents allows typical batch users to not have to keep an unchanged copy of their script for each batch job sitting around until their jobs run.

That being said, I think you are on to something here. I wonder if your simpler `--no-copy` interface could be a new `flux mini` subcommand. Would that simplify the use case?

**Comment by grondo** [comment]
>  I'm just not sure that jobspec.setattr_shell_option("per-resource.type", "node") is the best look...

Definitely! We should hide the `per-resource.type` shell option from users because it is a kludge to (hopefully temporarily) work around the fact that support for this doesn't exist in any official jobspec version at this point.

So any direct use of that shell option will likely break in the future.

Maybe you could implement a straw man proposal in the bindings first, then we could see how that might fall out into a new `flux mini` command or new options for existing commands?

Thanks for all your help, BTW! These are great improvements.

**Comment by jameshcorbett** [comment]
> I'm not sure I follow this 100% (my fault not yours). The `mini run` equivalent of `mini batch` is `mini alloc` (sorry, not the greatest name). Is it perhaps that command for which you need a variant?

My mistake, I should have said that `mini batch --no-copy CMD` would expand to `flux mini submit RESOURCES [tasks-per-node=1] flux start CMD`, I forgot that `mini run` is blocking and `mini batch` is not. Does that make more sense? (Although see below---I don't actually think this option is necessary any more.)

> I'll just mention that `mini batch` copies script contents because that is what users are used to. It lets you submit a script, edit it, and resubmit a different script. Since jobs may sit in the queue for awhile, copying script contents allows typical batch users to not have to keep an unchanged copy of their script for each batch job sitting around until their jobs run.

I think copying the script is exactly the right thing to do in the default case, I don't want to suggest otherwise.

> Note there is also an existing --wrap option to flux-min batch which is meant for a similar use-case

I knew about `wrap` although I didn't really think through the uses. So yeah, for the CLI, `mini batch --wrap /path/to/python foo.py` sounds like it would handle my nonblocking use-case quite well, and so would `mini alloc /path/to/python foo.py` for the blocking use-case.

Just to be clear, all I really want to do is start a Flux instance running a Python script with a flexible interpreter, that's all, and I thought I couldn't do that.

Anyway, this just makes me think that the CLI works great, I just need to think of a way to get the kind of behavior in the bindings. I'll think about it and then make a proposal.

Thanks for all the info @grondo. I was more than a little bit confused about what I wanted, it seems...
