### ISSUE TITLE
flux_respond_error: accept an errnum of 0

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#3036]
It was discussed on Slack that `flux_respond_error` considers `errnum` == 0 to be invalid and errors out with `EINVAL`.    From the man page: 
> flux_respond_error() returns an error response to the sender. errnum must be non-zero. If errmsg is non-NULL, an error string payload is included in the response. The error string may be used to provide a more detailed error message than can be conveyed via errnum.

This was surprising to both @grondo and I.  One suggestion was to allow an `errnum` of 0 for `flux_respond_error` since we've been shifting to using descriptive `errmsg`s anyways.  Maybe we only allow an `errnum` of 0 when an `errmsg` is provided?

**Comment by garlick** [comment]
I agree this is a problem area.  It's easy to encounter an error and call `flux_respond_error (...errno)` but find that `errno` wasn't actually set by the function that failed.  No response is sent so someplace else hangs waiting for it.  At best the `flux_respond_error()` failure is logged.  Meanwhile stuff is hung and you don't know why.

Since RFC 3 requires the `errnum` field in the response to be nonzero on error, we should maybe just substitute a generic errno if it is called with `errnum = 0`?
