### ISSUE TITLE
need way to report early job execution errors

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#3185]
(This issue arises from testing PR #3168 in a system instance config)

Problem: If munge keys are mismatched across nodes, runtime failures are hard to diagnose:
```
$ flux mini run hostname
flux-job: task(s) exited with exit code 1
flux-job: No job output found
```

This may be unlikely to happen on one of our well-run clusters, but it's much more likely when  trying to test flux by hand on cobbled-together nodes or containers.

**Comment by grondo** [comment]
Possibly related: #2206.

The problem described in that issue may also affect the IMP, possibly that is where the error is coming from in this case?

It might be helpful to see what the job-exec module logged to `flux dmesg` for the job above.

**Comment by garlick** [comment]
Looks like we do get a reasonable log message.
```
2020-09-02T14:46:53.310198Z job-exec.info[0]: 1214804656128: 1: stderr: flux-imp: Fatal: exec: signature validation failed: sign-munge-verify: munge_decode: Invalid credential
```

**Comment by grondo** [comment]
Since the shell hasn't started, there is no job output or log service in which to place these errors.

We can't use the output eventlog for these early errors since the initial header event is emitted by the shell. However, perhaps like wreck used to have we can have a an "error log" which `job-exec` can append stderr from jobs? This would really help diagnose errors early in job execution.

**Comment by garlick** [comment]
Dropping from 0.20.0 milestone since it's not a quick fix, and also not likely to bite admins on our clusters where munge is already properly set up.
