### ISSUE TITLE
python bindings for libflux-hostlist

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#3250]
For frontend tools we'll probably want a `flux.hostlist` interface to `libflux-hostlist`.

It will be best to use a Python binding to the C API for direct compatibility.

@trws or @SteVwonder, where would one start if they wanted to add a new binding wrapper under `src/bindings/python/_flux`, e.g. for `libflux-hostlist` or `libflux-idset`.

**Comment by SteVwonder** [comment]
>  where would one start if they wanted to add a new binding wrapper under src/bindings/python/_flux, e.g. for libflux-hostlist or libflux-idset.

I think the security bindings are a good example to copy for hostlist and idset.

I'd start with `src/bindings/python/_flux/Makefile.am`, copying the security section to produce a `_idset.so` and `_hostlist.so`.  Then I'd add two files to `src/bindings/python/flux`: `idset.py` and `hostlist.py` whose contents are similar to `security.py`.

For those two `.py` files, I'd start with the outer class that inherits from `WrapperPimpl` and the inner class that inherits from `Wrapper`.  As long as the `prefixes` constructor argument is set to `idset_` and the match is set to `struct idset *`, the wrapper should automatically pick up all of the relevant functions.

I think the automatic wrapping should work for all of the idset functions except `idset_equal` (the second struct argument will need to be manually unwrapped from the idset Python class that is passed in), `idset_decode`/`idset_ndecode` (handle unicode), and `idset_format_map` (the callback will need to be handled explicitly).

**Comment by trws** [comment]
That's good advice.  One thing I'm not sure about, I'm probably misremembering but I thought the argument interpretation code would take care of unwrapping handle-bearing objects even as arguments other than the first.  Does it not do that anymore? I ask specifically because of the note about `idset_equal`.

**Comment by SteVwonder** [comment]
> I'm probably misremembering but I thought the argument interpretation code would take care of unwrapping handle-bearing objects even as arguments other than the first. Does it not do that anymore?

Thanks for catching that! You are totally right.  It does unpack arguments beyond the first: https://github.com/flux-framework/flux-core/blob/master/src/bindings/python/flux/wrapper.py#L190

So IIUC `idset_equal` shouldn't require any manual wrapping.

**Comment by grondo** [comment]
ok, I have something working for wrapping libhostlist and libidset. However, it isn't clear how to best handle functions that return a `malloc()`'d `char *` in Python cffi. It is "working" to just return the memory, e.g.

```Python
    return self.pimpl.encode(flags).decode("utf-8")
```

However, I assume that leaks memory if the corresponding C function is `char * idset_encode(struct idset *, int flags)` and the caller is responsible for freeing the returned memory.

Strangely, it isn't clear to me from the documentation the best way to handle this. One example has you copy the result to an `ffi.string` then manually free the C result:

```python
    result = self.pimpl.encode(flags)
    retval = ffi.string(result)
    lib.free(result)
    return retval
```

or there is a function `ffi.gc`:

```python
    result = self.pimpl.encode(flags)
    ffi.gc(result, lib.free)
    return result
```

However, [the docs](https://cffi.readthedocs.io/en/latest/ref.html#ffi-gc) for `ffi.gc()` note that its use should be avoided in some situations.

Anyone know offhand the "right" way to do it?

**Comment by grondo** [comment]
Oh, nevermind, I guess ffi.string() is already called on any function with `char *` return type:
https://github.com/flux-framework/flux-core/blob/master/src/bindings/python/flux/wrapper.py#L212

@SteVwonder, @trws - This doesn't leak memory that the caller is responsible for freeing?

**Comment by grondo** [comment]
I did verify this causes a leak (I think), by running `idset.encode()` in a loop and watching memory grow without bound (though I don't know enough about

By changing my `decode` function to this:
```python    
    def encode(self, flags=None):
        if flags is None:
            flags = self.default_flags
        val = lib.idset_encode(self.handle, flags)
        result = ffi.string(val)
        lib.free(val)
        return result.decode("utf-8")
```

Then calling `decode()` in a loop doesn't cause the RSS of the python interpreter to grow without bound.

**Comment by trws** [comment]
So... the ffi.string() part itself does not.  It produces a python string, or unicode depending on version, from the data that's passed into it which is managed by the interpreter and freed appropriately.  

If the cdata string it's being called on is supposed to be freed by the caller, then that would almost certainly cause a leak. I don't remember ever building logic in for that purpose since the strings were being managed by the lifetime of something else like an RPC or a Message object and were not meant to be freed separately.  If this returns strings the caller is supposed to free, that will need some new logic.  It wouldn't be too hard to add a property or a matcher or something to do the free after the ffi.string call, or if it's rare enough then circumventing it like this makes it clear what's going on.

**Comment by grondo** [comment]
Excellent! Thanks for the reply @trws, that is really helpful because I honestly didn't know what i was doing here. :laughing:
