### ISSUE TITLE
update flux_dmesg() API?

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#3359]
Since `log.dmesg` was updated to be a streaming RPC, perhaps the API should also be updated. Currently we have:
```C
int flux_dmesg (flux_t *h, int flags, flux_log_f fun, void *arg);
```

Instead of a callback, would it be more consistent with other Flux API calls to return a future or `flux_rpc_t *`?

Also, only slightly related, but we might consider updating the log message format to use json instead of the fixed structure currently used (at least, for clients of the flux_dmesg() api)

**Comment by garlick** [comment]
Oops yeah, that interface does seem like it needs an update.

Actually, could we just drop this code from the public API and push it into `src/cmd/builtin/dmesg.c`?  I'm not really imagining a public API use case although maybe you were looking at it because you had one in mind?

If we don't need to provide public access, then I'd advocate to stick with the fixed encoding, but drop the superfluous JSON `{"buf":s}` envelope, which probably should have been dropped when `seq` was dropped from responses, and implement `dmesg.c` using `flux_rpc_pack()`, `flux_rpc_get_raw()`, and `stdlog_decode()`.

If we do need public access, then maybe encoding the payload as JSON does make sense.  I'm not sure if it's all that helpful to have dmesg-specific functions for decoding it then, or if we could just let people use `flux_rpc_get_unpack()` directly then (especially if users are expected to be few)?

**Comment by grondo** [comment]
The main use case I had in mind was indeed for testing, but there is a proliferation of "log watching" implementations ou there, so I could imagine a future use case where a script or service would watch the logs for matching messages that could trigger some action (e.g. skummee service?) or simply forward these messages to a local syslog server.

Either way, it is probably fine to just drop the public `flux_dmesg()` API for now, and add something later if needed. Current use cases can use `flux_rpc` directly.

My only other thought is that sticking with syslog wire format may be unnecessarily limiting in the long run.

Some interesting points from a more modern log server here: https://www.graylog.org/post/log-formats-a-complete-guide

**Comment by garlick** [comment]
I opened #3360 on changing the encoding - feel free to tack on there.

I thought maybe we could consider this issue closed once the API and the extra json envelope are removed?

**Comment by grondo** [comment]
Sure.

**Comment by garlick** [comment]
One other note: it looks like our current implementation assumes that the encoded buffer is a NULL terminated string.  If that's safe (?) then I would say let's add a terminating `\0` to the payload so it can be parsed directly as a C string, e.g. from `flux_rpc_get()`.
