### ISSUE TITLE
wreck: emit event at job state changes

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#337]
For extra super advanced reliable job completion of wreck-based jobs, have wrexecd emit a completion event just after updating `lwj.<id>.state` to complete.

Would an event like "wrexec.complete" with payload `{ lwj = <id> }` be sufficient? Or the jobid could be part of the topic string. Any advice?

JSC or other interested entities could then key off this event instead of watch on `lwj.<id>.state`

**Comment by dongahn** [comment]
I need to page this one in. Will get back to you.

**Comment by grondo** [comment]
Also, please comment if we should open separate issue to turn `lwj.<id>.state` into a state log. This also should not be too difficult.

**Comment by dongahn** [comment]
@grondo: 

A question first: Is this issue to improve the current wreck to get more lessons or to directly add this support in the new wreck replacement? Either is fine by me, but I thought I should ask. If this is for the wreck replacement, I might actually change the current wreck myself to support Stephen and Suraj's effort to merge their emulators into the scheduler framework service. 

In any case, I looked through some of my notes, most of which are spread across #206, #234, #247 and #249 as well as RFC 9. There are three major issues we have learned from JSC and scheduler framework service implementation and just  make sure we all look at the same page again... (Others, please correct me if my recollection is wrong):

1. watch-chaining is used for JSC to get notified of the new job creation events (`lwj.next-id`) and to collect the state-change events about jobs. We need to avoid using this pattern and to enable reliable harvesting of both the new job-creation event and other general job events (currently, starting, stop_children_in_exec/running, and complete), we desired to use the first-class pub-sub eventing mechanism instead of KVS watches. 

2. state-drift issue - because there are use cases where a consumer wants to retrieve the exact state of KVS at the time when the event occurred, we desired to have a KVS snapshot capability (though this isn't the issue being asked here.)

3. For the cases where a producer wants to be sync'ed with a job, we desired to have a programmable sync points. 

You asked about the `complete` event, but can I assume that the same mechanism will be used for other events -- that is, both new job creation and other general state changes?

Now, to answer your first question, I think `{ lwj = <id> }` payload will do. A topic string would be another way to encode this, but I have no idea which one of these two scheme will incur less overhead. Further, although I don't know if this will be used or not for HTC workload ultimately, there could a case where `rexec` will emit a job-creation event in a bulk fashion (i.e., create the schema for many jobs first; then emit one batched event), it seems `{ lwj = <id> }` would give a better way to be extended for such a bulk eventing case: `{ lwj = 1-50}`

To answer your second question, JSC won't need the state log support once the eventing is supported. It will just get notified of all the job events after it gets started. I don't think it needs to parse the old states of a job.

**Comment by grondo** [comment]
@dongahn, sorry this issue deals only with wreck prototype service. The idea is to satisfy minimal request to get the near term [milestone](https://github.com/flux-framework/flux-core/milestones/Flux%20in-job%20scheduling%20tool%20-%20minimal) functional. One of the requirements from @trws is reliable notification of lwj termination.

All of your points above are great and thanks for the detail. We should probably copy some of this text into issue #333, #334, or #335. It would be really good if JSC and JSC-like service requirements *for* the program/parallel program execution service could be detailed in that issue.

**Comment by dongahn** [comment]
Ok I will try to capture that. But while you are at it, can you make other job state  including job creation using the same eventing mechanism? This will allow us to get rid of the race work around within wreck and help Stephen ' effort to merge his emulator into the main scheduler framework service and also turn back on th e JSC sharness test.


________________________________________

**Comment by grondo** [comment]
Job creation event might be handled in new job submission api #338?

However, we could also emit an event in every wreck state change (includes, starting, running, sync, complete) by adding event to [`rexec_state_change`](https://github.com/flux-framework/flux-core/blob/master/src/modules/wreck/wrexecd.c#L797). That is actually just as simple... I'll update the description of this issue.

I need to refresh my memory on the w/a for the emulator, but my feeling is it will require this minor kludge along with a fix for job module described in #338

**Comment by grondo** [comment]
Thinking about this a little more, consumers might want to filter on topic string specific to wreck job state changes, so would a topic like `wreck.state.<string>` be better?

**Comment by dongahn** [comment]
Yes, job creation event can come from there. I considered keeping using the watch mechanism, but one worry was JSC might get a job-creation event (signaled through a watch) and a staring event (signal through a pub). I thought this out-of-order sequence is possible because of eventual consistency of KVS. 

If Job submission API uses pub to signal a job-creation, I think we won't have the out of order problem... Is it true, though? If two publish events are posted back to back through two different service modules,  they will arrive to a different module in order? 

Regarding your second comment, yes, that's how I saw we could do this. So go for it :-)!

Regarding your 3rd comment, yes, that was added to overcome the problem of black-out period described in #206. If the eventing is used, IOW watch-chaining is avoided, that problem will go away.

**Comment by dongahn** [comment]
@grondo: I like that. I was considering "programmable event notification" within JSC, but this mechanism will facilitate that and also allows other non-JCS modules to directly write to this.

**Comment by garlick** [comment]
> If two publish events are posted back to back through two different service modules, they will arrive to a different module in order?

There is no guarantee of ordering there unless the two service modules explicitly synchronize, since the events enter different queues which might have different contents, be serviced in random order by the broker, etc..

**Comment by dongahn** [comment]
Isn't job-submission module and wreck sync'ed though? 

If they are not, placing the new job creation eventing to a single module so that all related job-events get emitted and arrived in sequence would be desirable.

**Comment by garlick** [comment]
Just spoke with @grondo and probably the easiest thing to do is for the job module to subscribe and wait to receive its own event before allowing the next state transition, after which events would be serialized by a single sender in another module.

Events are currently fire and forget, then serialized at the rank 0 broker, so receipt of the event on any rank is sufficient to know that the next event sent will always come after the first one.

**Comment by dongahn** [comment]
Sounds great! Yes this will create a clean sequence consistency. Thanks.

**Comment by trws** [comment]
This all sounds good, I'm working around it for now by adding a watch on the state of the job between the creation and submission phases, ensuring I get all the events, but this will make the control flow significantly cleaner, and let me use a more abstract submission API later.
