### ISSUE TITLE
job-info / flux-jobs: support query of job priority and urgency

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#3377]
question is what to name these fields on output ("A-PRIORITY", "Q-PRIORITY", ?) and what the default should be.  What does the average user consider "priority" to mean.

**Comment by garlick** [comment]
FWIW I'm fine with those field names.

IMHO `job-info` must support both.

`flux jobs` would want to list jobs in queue priority order, breaking ties with jobid, reflecting the job manager's ordering.

As far as what's displayed, I think the 32-bit queue priority should not be in the default listing, but should be available on request, for testing if for no other reason.

Maybe same for the admin priority?  I'm less sure on that one.  Seems like it generally would not be of interest for the columnar `flux jobs` output at least, since it's likely to have the default value most of time?

**Comment by chu11** [comment]
@garlick, oh sorry, When I said "what the default should be", I was thinking if the attribute "priority" should still be something a user can request.  Somewhat for backwards compatibility, but more because the average user wouldn't know the difference between admin & queue priority?

But perhaps the average user just doesn't care about priority, so "priority" shouldn't be an option.  They can look up the difference between admin & queue priority, or i can just document it a bit in the manpage.

**Comment by grondo** [comment]
admin priority is at most two digits so maybe its column heading could be `PRI`, and the queue priority can be `QPRIORITY`. Neither should be in the default output, but they should still be available via the `--format` option.

I do think some users/admins will want to query actual priority values for jobs, and I think they will want the "queue prioirty" by default since it is what directly affects the order of one job in the queue vs another. However, it is probably ok to have that be queried via `queue-priority` (I could really wish the "admin priority" had been some other name, though)

**Comment by garlick** [comment]
This keeps coming up so maybe we ought to go ahead and rename.  My vote would be for "urgency"...?

**Comment by garlick** [comment]
@chu11 any thoughts on how much work it would be to change the code?  I could put together a PR for the RFC repo pretty easily I think.

**Comment by chu11** [comment]
> This keeps coming up so maybe we ought to go ahead and rename. My vote would be for "urgency"...?

to clarify, the suggestion in "urgency" for admin-priority, and "priority" for queue_priority?

It would perhaps take a medium length of time, since we'd be updating a lot of the events as well.  But wouldn't be horrific.

I got a PR up for #3345, ready for one for #3342, and working on this one.  It might be easier for me to do a priority -> urgency name change after those are done, since the "infrastructure" for admin vs queue priority will have been done and its mostly a search and replace.

**Comment by garlick** [comment]
OK, well why don't I go ahead and propose RFC changes and see how that goes.  We can have further discussion over there, and meanwhile your PRs can progress.
