### ISSUE TITLE
job-info: remove t_priority list attribute, maybe more?

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#3395]
per initial discussion in https://github.com/flux-framework/rfc/pull/278

`t_priority` is ambiguous since it is a job state that can be reached multiple times.  as is `t_sched`

so the question becomes, if we're removing multiple `t_<STATE>` fields, should we remove more / all?

Edit: depends on PR #3371, as that PR is the one that introduces the `flux-restart` event and the potential for a cycle

**Comment by grondo** [comment]
There is no good reason I can think of to remove them all, though I'd be fine with removing timestamps for states where a single timestamp doesn't make sense.

The other state timestamps provide the Python `job.t_*` properties which may be useful in scripting or other commands, so since they are already there I'd not remove them unless for cause.

**Comment by cmoussa1** [comment]
I also use the `t_submit`, `t_run`, and `t_inactive` timestamps from the job-archive interface and job usage calculations for fairshare, so those would be nice to keep as well.

**Comment by chu11** [comment]
@cmoussa1 will it be a problem if `t_sched` is removed from `job-archive` and the database schema is changed?  Or shall it be left there and dummy values put there instead?

**Comment by cmoussa1** [comment]
I think it should be fine if `t_sched` is removed. I don't think I use that field anywhere. 👍
