### ISSUE TITLE
jobspec: enabling mutability post-submission

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#3416]
There are a few use cases that require some modification of jobspec post-submission.  The most obvious is a user deciding to change a particular parameter (e.g., number of nodes, walltime, job queue, bank) after the job has been queued.  Another more specific use case is an external service providing input to the partial or complete resource requirements of a job post-submission.  In the former, the user is intervening and thus we theoretically have access to their keys to resign if necessary.  In the latter, we wouldn't, so re-signing would not be possible.  (If we ultimately don't want to support the latter use case, we could always push the service interaction into the submission CLI, but that could affect submission throughput/parallelism).

During a coffee call conversation, @grondo mentioned that A) the only parts that really need to be signed and verified are the environment and the binary/arguments B) we are already "redacting" jobspec by stripping out the environment (to reduce jobspec size).  Thus it could be possible to reserve a specific place in the KVS for unsigned changes to the jobspec's resource or attribute sections (minus the environment).  This could enable users or an external service (both proxied via a module) to make jobspec modifications by adding values to a well-known KVS location.  Maybe we can then create a library that reconstructs the new, modified jobspec by reading the original jobspec and previously mentioned well-known KVS locations and taking a union of the two.

**Comment by SteVwonder** [comment]
Noted during a team call today: if there is a need to modify the environment or insert environment variables before running the job, we could have the IMP or job-shell insert them.  This would require some mechanism for verifying the trust of the env vars.  We could have an allowlist or maybe some signing of the additional environment variables.

This would be useful for submitting an ensemble of jobs whose jobspecs are identical other than one env var (see #3426).  This is also for integrating with external services that want to create and insert env vars after submission.

**Comment by grondo** [comment]
We now have an implementation that allows specific parameters of jobspec to be updated post-submission, and currently the duration and queue can be updated for pending jobs by users with the `flux update` command. Other attributes can be updated provided a jobtap plugin specifically allows and validates the update. A caveat is that these updates apply only to the instance's redacted copy of the jobspec, and thus the job's command(s) and environment cannot be updated with this solution.

I wonder if we should close this issue as complete, and open specific issues for missing functionality as it comes up, since this issue is a bit general.

**Comment by grondo** [comment]
Closing this one based on previous comment.
