### ISSUE TITLE
add synchronous event sending mechanism

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#342]
In #337 the following use case for events was discussed, where the order of events a and b must be assured:
- client A sends event a
- client A synchronizes with client B
- client B sends event b

This is currently not sufficient to ensure a comes before b since events are fire and forget at the client, then serialized (and assigned sequence numbers) at the rank 0 broker.

Currently, A would have to subscribe to and listen for its own event in order to know that a sequence number has been assigned before proceeding to synchronize with B.

Consider some way to (optionally) synchronize event sending.  For example sending an event could receive an optional response from the rank 0 broker after the sequence number has been assigned.

**Comment by dongahn** [comment]
This was discussed as part of JSC reliably collecting job-creation event (that comes from the job submission module) and other job state-change events (that come from wreck.) *in order." 

But now that I think about this (and talking w/ @trws yesterday), perhaps, JSC doesn't need to get the job-creation event. Currently, it only uses the job-creation watch trigger to install a job-state watch. But now that job-event payload has jobid in it, I can simply use `wreck.state.reserved` on a new jobid as the trigger to raise an JSC event  for J_NULL and J_RESERVED back to back. This way, I don't have to worry about the this cross-module event ordering and solve the race issue. I am hoping @SteVwonder and @trws to move onto JSC in a near future.

**Comment by garlick** [comment]
Good!  That sounds like progress @dongahn.

**Comment by dongahn** [comment]
It turns out lwj.<id>.state = `reserved` is actually coming out of the job module where as the rest of the events are from wreck. 

But because the job module and wrexec module is synchronized via an RPC between job<->wreckrun and followed by wreckrun <-> wrexec, there is a clear happens-before relationship between `reserved`event and `starting` event. 

I will add the job-state eventing from within the job module as well and see if this allows all of the jsc tests to pass. (I think this should.)

**Comment by garlick** [comment]
Just to be clear, if job is publishing an event a then synchronizing via RPC with wrexec, then wrexec is publishing an event b, b _could_ be published before a since job has no indication from the broker that its event was actually published when it synchronizes with wrexec.  This is the problem that this issue is about.  On the other hand if job waits for its own event before synchronizing, that works around the issue.

**Comment by dongahn** [comment]
Oh well... Sorry I didn't think this through. 

So without using a work-around like this, the only existing way to implement sequential consistency of multi-module events (events generated from multiple modules) is through KVS (e.g., put and commit) then? Here, I define my sequential consistency as this: the receiving order of events is the same as the synchronized order of the modules. And of course, this order is a partial order because there can be a period of time these modules are not synchronized (concurrent.) E.g., 

1. The consumer installs a watch on a key
2. `A` performs `kvs_put()` followed by `kvs_commit()` on this key
3. `A` synchronizes with `B` with RPC (so events that occur within `B` after receiving the RPC response clearly happened after 2), one of which is 
4. `B` performs `kvs_put()` followed by `kvs_commit()`

Because the kvs master will send the watch trigger events for 2 and 3 in order (assuming, through publish?) and w/ ordering guarantee of the single publisher case, the consumer can achieve multi-modul event sequential consistency?

It seems it would be useful to document (or augment) even consistency models (kvs vs. pub/sub). Not sure, if all these are covered in one of the current RFCs.  

In any case, I went back and changed the JSC code to still use the `next-id` watch to get the job-creation event and then use subscription for wreck.state events to collect wreck events (other than `reserved`). Then, to overcome the out-of-order event arrival (between next-id watch and wreck events), I made a modification to JSC such this job-creation watch event and the first state event  (`starting`) can come out-of-order and adjusted the logic. That is, if these events appear out of order, JSC simply raises the new-job JSC event additionally on receiving "starting" and simply discard the late arrived  the new-job watch event.  

I need to put some test cases and also do some experiments with the scheduler framework service module as it also update the job state.

**Comment by garlick** [comment]
This is hard to think about.  Any reason not to just implement the work around and then take it out once this issue is resolved?

**Comment by garlick** [comment]
Events are currently not sent in any envelope - they pass straight through the brokers to rank 0 where they are relayed out via the selected event distribution mechanism.

I propose change this behavior to encapsulate events in an RPC and then implement both fire and forget and "respond with event sequence number" methods.  Then the sync/async RPC interfaces can be used to manage event publication with more sophistication than we have now.

This would require an update to RFC 3 which currently specifies the unencapsulated event flow.
