### ISSUE TITLE
job-manager:  refine urgency/priority relationship

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#3452]
(opening for @grondo who had to go offline for a bit)

We defined urgency=0 to be "hold" and urgency=31 to be "expedite".   Those are translated by the job manager to priority=0 and priority=(maxint-1), respectvely.  I believe the design was that if urgency is hold or expedite, then the priority plugin is bypassed.  Any priority changes it tries to make are ignored, keeping the humans firmly in charge.

What happens if the urgency is not one of those values, but the priority plugin sets the priority to 0?  I believe in the current code, the job will not be held and will run.  It seems like it should be held (not scheduled).

Are there any other subtle cases here we need to worry about?

**Comment by grondo** [comment]
> I believe (after #3428 merged) that the job will still be held.

This isn't the case. If a job manager plugin sets priority=0 in the PRIORITY state, but urgency != 0, the job still runs. I assume this is because in code like this, we're checking job->urgency instead of job->priority:

```c
   /* The queue is sorted from highest to lowest priority, so if the
    * first job has urgency=HOLD (priority=MIN), all other jobs must have
    * the same priority, and no alloc requests can be sent.
    */
    if ((job = zlistx_first (alloc->queue))
        && job->urgency != FLUX_JOB_URGENCY_HOLD)
        flux_watcher_start (alloc->idle);

```

I ported the job manager plugin prototype on top of #3442 to see what conflicts exist, and enabled the experimental "hold" plugin which sets all job priorities to 0. Jobs still run as seen from this eventlog:

```
ƒ(s=4,d=0,builddir) grondo@asp:~/git/flux-core.git$ flux job eventlog ƒ63TEXwxs
1609880900.335414 submit userid=1000 urgency=16 flags=0
1609880900.349486 depend
1609880900.349544 priority priority=0
1609880900.352463 alloc annotations={"sched":{"resource_summary":"rank0/core0"}}
1609880900.359547 start
1609880900.413465 finish status=0
1609880900.417601 release ranks="all" final=true
1609880900.418460 free
1609880900.418495 clean
```

**Comment by chu11** [comment]
> This doesn't seem to be the case. If a job manager plugin sets priority=0 in the PRIORITY state, but urgency != 0, the job still runs. I assume this is because in code like this, we're checking job->urgency instead of job->priority:

Yeah, I just realized that too.  I think those prep/check calls should be checking priority instead of urgency, as we do set the priority accordingly.  e.g. in `job-manager.urgency`

```
        if (urgency == FLUX_JOB_URGENCY_HOLD)
            job->priority = FLUX_JOB_PRIORITY_MIN;
        else if (urgency == FLUX_JOB_URGENCY_EXPEDITE)
            job->priority = FLUX_JOB_PRIORITY_MAX;
        else
            job->priority = urgency;

```

**Comment by chu11** [comment]
> Yeah, I just realized that too. I think those prep/check calls should be checking priority instead of urgency, as we do set the priority accordingly. e.g. in job-manager.urgency

No, I take that back, as we defined HOLD/EXPEDITE specifically for urgency.  Do we want to define for HOLD/EXPEDIATE for PRIORITY as well in the RFCs, thus leading to the change I mention above?

**Comment by grondo** [comment]
> No, I take that back, as we defined HOLD/EXPEDITE specifically for urgency.

Yeah, that is to define a way to *administratively* hold or expedite a job. The meaning of which is that HOLD will force the job priority to MIN, and EXPEDITE will force the job priority to MAX. I don't think we need to also define HOLD/EXPEDITE for priority, since it is the value by which jobs are sorted (except maybe to define that jobs with 0 priority will not be run)

**Comment by grondo** [comment]
>  I believe the design was that if urgency is hold or expedite, then the priority plugin is bypassed. Any priority changes it tries to make are ignored, keeping the humans firmly in charge.

Going back to this statement, things should work out with the following rules

 * jobs with priority == 0 are not run (job hold)
 * jobs with urgency == HOLD are held administratively, any plugin calculated priority is ignored and priority is set to 0

Therefore, if a plugin sets priority to 0, it can later increase it as long as job->urgency != HOLD.

If a user holds a job, a job manager plugin can't unhold it since job->urgency == HOLD and so plugin priority values are ignored.

I think the one use case we might be missing is if, in a multi-user instance, the instance owner wants to hold a guest user's job, I believe the guest can currently release or unhold the job since users are allowed to set urgency anywhere between 0-16. I'm not sure how important this use case is though.

I guess the above could be simulated by an advanced job manager plugin which could allow administrative hold/release via a plugin-specific RPC, restricted to instance owners.
