### ISSUE TITLE
Python: event-watching from multiple threads causes a crash

### ISSUE THREAD

**Issue by jameshcorbett** [flux-framework/flux-core#3470]
While working on #3468 I found that trying to listen for events on two different ``flux.Flux()`` handles in two different threads causes `libev` to abort with the following message: ``python: ev.c:4146: ev_signal_start: Assertion `("libev: a signal must not be attached to two different loops", !signals [w->signum - 1].loop || signals [w->signum - 1].loop == loop)' failed.``

I'm using ``/usr/global/tools/flux/toss_3_x86_64_ib/flux-c0.18.0-s0.10.0/`` and I would be happy to provide core dumps if it helps.

Here is a script that reproduces the issue:

```
import threading
import time

import flux

def job_state_cb(*args, **kwargs):
    pass

def get_events():
    f = flux.Flux()
    f.event_subscribe("job-state")
    f.msg_watcher_create(job_state_cb, 0, "job-state").start()
    for i in range(1000):
        f.reactor_run(f.get_reactor(), 0)
        time.sleep(0.01)


def main():
    t = threading.Thread(target=get_events)
    t.start()
    get_events()

if __name__ == '__main__':
    main()
```

**Comment by grondo** [comment]
This is a great reproducer, thanks! It also triggered a bug in the setup of thread-local "reactor_depth" variable in even the most recent version of flux-core:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./tst.py", line 10, in get_events
    f = flux.Flux()
  File "/home/grondo/git/flux-core.git/src/bindings/python/flux/__init__.py", line 19, in Flux
    return flux.core.handle.Flux(*args, **kwargs)
  File "/home/grondo/git/flux-core.git/src/bindings/python/flux/core/handle.py", line 59, in __init__
    if not self.tls.reactor_depth:
AttributeError: '_thread._local' object has no attribute 'reactor_depth'
```

The reason for the libev crash is that there is a `SIGINT` signal watcher that is always registered with the reactor before `reactor_run()` to ensure that Python programs are interruptible while sleeping in the C reactor.
Obviously, this needs to protect against multiple threads setting up signal watchers.

There's probably two ways to handle this:
 * only let the first thread that calls into reactor_run() add signal watchers.
 * only let the main thread add signal watchers

The second is easier, and will probably be the approach I'd take for now, especially since there is another case already extant in the code that restricts signal handling to the main thread. A multithreaded python program would still be interruptible even with threads sleeping in reactor_run(), since the main thread could still receive signals and be terminated/interrupted.

**Comment by jameshcorbett** [comment]
I don't know anything about what's going on in the C reactor, but in case it's relevant, here is how Python handles signals:

> Python signal handlers are always executed in the main Python thread of the main interpreter, even if the signal was received in another thread. This means that signals can’t be used as a means of inter-thread communication. You can use the synchronization primitives from the threading module instead.

>Besides, only the main thread of the main interpreter is allowed to set a new signal handler.

From https://docs.python.org/3/library/signal.html

**Comment by grondo** [comment]
Thanks! The C reactor uses "signal watchers" which use a signalfd to get signal delivery, so the same rules do not apply per se, though a given signal can only be handled by a given reactor (which is the specific problem here).

I have a fix and I'll create a PR shortly.
