### ISSUE TITLE
need a way to enforce limits (like max pending jobs per user) at submit time

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#3472]
This was discussed as part of https://github.com/flux-framework/flux-core/pull/3464

In order for a priority plugin to ultimately enforce a dynamic limit like (limits as to how many jobs from the same user can occupy the pending job queue), it may need a way to indicate a job reject. 

@grondo said:
> We should open a separate issue on this one. In the near term would it be ok to 'hold' jobs that exceed some limit. Otherwise, perhaps the priority plugin could generate a job exception and cancel the job. (This won't be user friendly however, since flux mini submit would appear to be successful but the job will be immediately canceled.)

The right place to reject job is at the validator. But when a job needs to be rejected based on the queue state for certain limits, my guess is it will be difficult or impossible to do this at the job-ingest module level.

**Comment by grondo** [comment]
There are a couple ways we could solve this as a first cut:

 1. Add a `job.validate` or similar plugin hook that would be called from the job-ingest module. The hook would allow a plugin to reject a job before it is assigned a jobid and the job submit response is sent back to the requestor. On rejecting a job the plugin callback should add an appropriate error message which would be returned in the response.
 2. Allow multiple python validator scripts, or plugins to the existing validator script.

In both of these cases the validator will need to go back to a single point in order to validate the dynamic limits we're discussing here. To start, the priority plugin in the job-manager could register a service endpoint which could be contacted with the necessary relevant information (e.g. the `uid` of the new job), and the priority plugin could use internal state to respond if the job should be accepted or rejected.

The benefits of solution 1 above include:
 - The job-ingest plugin DSO could actually be the same as the job-manager plugin. The plugin API would need to be enhanced to tell the plugin the context in which it is loaded.
 - The job-ingest module could make use of the job-ingest handle to do asynchronous work (e.g. the RPC to the job-manager plugin)
 - a job-ingest plugin which modifies submission arguments, including the redacted jobspec sent to the job-manager could be written if needed (I think there was a use case for this)
the drawbacks would be:
 - more complicated plugin management (now plugins have to be loaded in job-manager and job-ingest, and the job-ingest module may be loaded on more than one node)

The benefit of solution 2 would be increased simplicity, but the python validator would have to be extended to work asynchronously so that the RPC back to the job-manager doesn't block other incoming job validation.

Of course, either of these solutions will impact maximum job ingest rates, but that might not be an issue in the situations where we need this support.

**Comment by garlick** [comment]
Hope you don't mind @dongahn - I generalized the issue description since I think @grondo made a good case for doing this in the ingest path, rather than in the job manager priority plugin.

**Comment by dongahn** [comment]
This is fine. We need a bit more discussion about what should be trigged at job-ingestion level and what should be at the priority plugin level though. 

I think we have a good solution to enforce limits for things like # of running jobs per user per fluxion queue.

Maybe, one thing we can do is to allow the multifactor plugin to register a RPC that can provide pending job stat per user per Fluxion queue so that the flux-accounting provided validator can retrieve the info from this RPC.

**Comment by grondo** [comment]
> Maybe, one thing we can do is to allow the multifactor plugin to register a RPC that can provide pending job stat per user per Fluxion queue so that the flux-accounting provided validator can retrieve the info from this RPC.

I general, I think this is the right approach (though it sounds a bit like flux-accounting will be fluxion-specific, in that it would need to know about Fluxion queue definition in jobspec?).

I have an experimental WIP (very early progress, will be a few days before I have something working), that extends the Python validator to allow registration of multiple validators as plugins. One of these validators could be provided by flux-accounting to forward the request for job validation to another service via an RPC (e.g. a service registered by a job manager plugin). For job submission validation to be successful, all validators must succeed.

> We need a bit more discussion about what should be trigged at job-ingestion level and what should be at the priority plugin level though.

It is better if jobs are rejected at ingest. Jobs rejected by the priority plugin after ingest will have to raise a job exception and this will not be very convenient for users.

**Comment by dongahn** [comment]
> I general, I think this is the right approach (though it sounds a bit like flux-accounting will be fluxion-specific, in that it would need to know about Fluxion queue definition in jobspec?).

flux-accounting can be multiple plugins but the plugin I plan to develop is fluxion-specific. Yes the queue info will be fetched from jobspecs' attributes key.

**Comment by dongahn** [comment]
> I have an experimental WIP (very early progress, will be a few days before I have something working), that extends the Python validator to allow registration of multiple validators as plugins. One of these validators could be provided by flux-accounting to forward the request for job validation to another service via an RPC (e.g. a service registered by a job manager plugin). For job submission validation to be successful, all validators must succeed.

Yes, this sounds like a good starting point. Can the priority plugin register multiple RPCs?

**Comment by grondo** [comment]
> Yes, this sounds like a good starting point. Can the priority plugin register multiple RPCs?

Yes.

**Comment by grondo** [comment]
It occurred to me this scheme can't enforce exact limits. When the the priority or other plugin accepts a job due to a limit, there is some amount of time between the response and when that ingest request becomes a job. During that time more jobs could be accepted that would put a user over the limit. The amount of jobs would could be accepted over the limit depends on the ingest rate relative to the time between validation and the `job.new` callback for the priority plugin.

The plugin could try to be smart and have a counter of outstanding accepted jobs I guess, but those jobs could be rejected by other validators (e.g. jobspec), so this isn't necessarily safe.

**Comment by dongahn** [comment]
Good observation. Perhaps a better place to enforce this limit is at the priority plugin level then? We don't have a wait for the plugin to reject a job though (at least just yet).

**Comment by garlick** [comment]
The ingest modules (running on all ranks) do batch up submissions and send them to the job manager, and wait for the job manager to accept them before responding to the submitter.   I believe right now it is an all or nothing proposition, e.g. send a list of jobs, get back a single OK.  The purpose is to ensure the job ID is valid (known to the job manager) by the time the user gets ahold of it.

However we might be able to add a jobtap hook here so that a job manager plugin could insert itself into the acceptance process.  Maybe we could enhance the protocol so individual jobs can fail with human-readable reasons passed back to the ingest module.

This could bottleneck job submission, but as was mentioned before, we don't necessarily mind having a reduced ingest rate in the system instance since we hope workflows and such are in sub-instances of Flux.

**Comment by grondo** [comment]
Oh, that might work fairly well, and would remove the immediate need to extend the validator. Good thought!

**Comment by grondo** [comment]
This should have been closed by #3494
