### ISSUE TITLE
job-manager: use new data structure for alloc queue

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#3474]
The alloc queue uses a `zlistx` internally.  This leads to O(n) insertion time, which over many priority changes can get costly.  Especially once regular priority changes occur via the priority plugin (O(n^2) if we're updating all priorities).  In PR #3473 we also introduce a `pending_jobs` list, which may have similar problems.

Generally speaking, we want O(log n) insertion time, but we would probably need "pop()" and "tail()"  to get max/min priority jobs (former for scheduling a new job, latter for determining if a job needs be sent a cancellation request).  Iteration over the data structure might also be convenient if all priorities need to be updated.

A heap-like data structure immediately comes to mind as an option, with the (traditional) downside being memory allocation up front.  And (traditionally) heap is of max N size.

This issue also exists in `sched-simple`.

**Comment by grondo** [comment]
In the near term this can be mitigated by sorting the zlistx after setting the priorities on more than just a couple jobs, instead of removing and re-inserting jobs. This is the approach taken in #3464.

However, zlistx_t has a design flaw where `zlistx_sort()` invalidates all handles (since data is swapped between nodes during a sort), so the handles have to be acquired again after the sort. (This is still faster than re-insertion though). Therefore a new data store which implements a priority queue might be a good idea.

However, for now my testing shows these flaws don't currently limit job throughput (so there might be other areas on which we want to focus first)

**Comment by grondo** [comment]
Nothing has come of this old issue and we haven't noticed any issues with the current alloc queue implementation, so I'm going to close this for now. If future performance analysis indicates an issue here we can open a new issue.
