### ISSUE TITLE
Assertion `flux_watcher_get_ops (w) == &handle_watcher' failed.

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#3493]
To evaluate delayed scheduling per https://github.com/flux-framework/flux-sched/issues/805#issuecomment-772112443, I am trying use `flux_handle_watcher_get_flux(3)` to get the flux handle within check/prepare watcher handlers. But t I'm getting the following assertion failures. 

Is this expected? 

```console
flux-broker: reactor.c:325: flux_handle_watcher_get_flux: Assertion `flux_watcher_get_ops (w) == &handle_watcher' failed.
```

**Comment by grondo** [comment]
`flux_handle_watcher_get_flux(3)` will only work with watchers created by [`flux_handle_watcher_create(3)`](https://flux-framework.readthedocs.io/projects/flux-core/en/latest/man3/flux_handle_watcher_create.html). AFAIK, there isn't a way to get a flux handle with the check/prep watchers since they are associated with a reactor, not a flux handle. You'll have to pass the flux handle in as part of the `arg` in `flux_check_watcher_create(3)` and/or `flux_prep_watcher_create(3)`.

**Comment by dongahn** [comment]
@grondo: I see. 

> You'll have to pass the flux handle in as part of the arg in flux_check_watcher_create(3) and/or flux_prep_watcher_create(3)

I wanted to avoid this as I am passing the qmanager cb ctx (not qmanager ctx where I keep the flux handle)... Time for a bit of refactoring.

**Comment by grondo** [comment]
Unfortunately `flux_watcher_t` predates our practice of adding `aux_set` and `aux_get` methods to all objects, otherwise I might suggest that approach. For now though, closing this issue as a question answered. Let me know if you'd like it back open.

**Comment by dongahn** [comment]
No the answer was satisfactory. Thanks.
