### ISSUE TITLE
`FLUX_JOB_DEBUG` causes an ENOSYS when waiting on a job

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#3595]
I don't have a simple reproducer yet, but @vchuravy was putting together a submission interface for Julia and had `FLUX_JOB_DEBUG` hardcoded for every job along with `FLUX_JOB_WAITABLE`.  When we created a nested instance in his test, submitted a job, waited on it, and tried to get the status with `flux_job_wait_get_status`, the future had an error of `Function not implemented` which I believe is `ENOSYS`.

After briefly chatting about it on the ☕ hour, one of the possible causes of `ENOSYS` to a wait request is when the `job-manager` is being unloaded due to the instance shutting down.  So @vchuravy : one thing to check is that your initial `bash` process isn't exiting prematurely.  Otherwise, something else more nefarious is going on.

**Comment by SteVwonder** [comment]
Ah. Looks like some of the code involved in the issue is posted here (I believe other parts of it are still uncommitted as of this posting): https://github.com/flux-framework/FluxRM.jl/pull/10/files

**Comment by vchuravy** [comment]
Ok this seems a twice-cursed issue. I distinctly remembered while debugging with @SteVwonder to have narrowed it down to the singular cause of adding `FLUX_JOB_DEBUG`. I failed to reproduce that today and instead found the issue to be with the side-loading of Flux. 

The Julia tests (similar to the Go and Python tests) use a side-loaded Flux instance (https://github.com/flux-framework/FluxRM.jl/blob/e3279923c5520ac8c47228c11c8e97fd71b0307c/test/runtests.jl#L17-L37) to run tests.

Test case: https://gist.github.com/2cb37da4a0d01685e6084f080dd0f4b3

### Under `flux start`
```
~/s/FluxRM (vc/jobsubmission)> flux start --size=1 -- julia --project=. test_wait.jl
[ Info: Without debug
[ Info: Running under Flux
FluxRM.encode(job) = "ƒ2ymdQKH"
[ Info: With debug
[ Info: Running under Flux
FluxRM.encode(job) = "ƒ3TRk1EP"
```

### Side-loading
```
~/s/FluxRM (vc/jobsubmission)> julia --project=. test_wait.jl
[ Info: Without debug
[ Info: Side-loading Flux
FluxRM.encode(job) = "ƒYoHbZy"
2021-04-16T01:38:49.562248Z broker.err[0]: cleanup.2: flux-queue: 1 pending jobs
ERROR: LoadError: SystemError: flux_job_wait_get_status: Function not implemented
Stacktrace:
 [1] systemerror(p::String, errno::Int32; extrainfo::Nothing)
   @ Base ./error.jl:168
 [2] #systemerror#62
   @ ./error.jl:167 [inlined]
 [3] systemerror
   @ ./error.jl:167 [inlined]
 [4] wait(job::FluxRM.Job)
   @ FluxRM ~/src/FluxRM/src/core/job.jl:59
 [5] (::var"#5#6")(flux::Flux)
   @ Main ~/src/FluxRM/test_wait.jl:43
 [6] with_flux(f::var"#5#6", size::Int64)
   @ Main ~/src/FluxRM/test_wait.jl:20
 [7] under_flux(f::var"#5#6")
   @ Main ~/src/FluxRM/test_wait.jl:31
 [8] top-level scope
   @ ~/src/FluxRM/test_wait.jl:39
in expression starting at /home/vchuravy/src/FluxRM/test_wait.jl:39
```

This is twice-curse since I added tests that exactly do this and they pass CI and local tests.
https://github.com/flux-framework/FluxRM.jl/pull/10/files#diff-3b9314a6f9f2d7eec1d0ef69fa76cfabafdbe6d0df923768f9ec32f27a249c63R77-R83

```
~/s/FluxRM (vc/jobsubmission)> flux --version
commands:               0.21.0
libflux-core:           0.21.0
build-options:          +hwloc==2.4.0
```

**Comment by vchuravy** [comment]
With @SteVwonder we narrowed this down to the the started process `bash` terminating early because the input pipe got closed early.

I think this issue can be closed.

**Comment by grondo** [comment]
Nice job running this down!

**Comment by SteVwonder** [comment]
Thanks @garlick and @grondo for the hints during ☕ hour!
