### ISSUE TITLE
libflux-core.so depends on libzmq.so

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#3617]
Problem:  As noted in #3611, the `flux-shell` takes a long time to start up on a FIPS compliant system due to crypto self-tests in `libcrypto.so` (openssl).   This seems to be due to this chain of DSO dependencies: `libflux-core.so` -> `libzmq.so` -> `libgssapi_krb5.so` -> `libcrypto.so`.

Since  0MQ sockets are used only by the broker and the shmem connector, it seems like we should be able to eliminate the 0MQ dependency in `libflux-core.so` by migrating some code to static internal libraries.  Doing so would also benefit other users of our APIs.

Some obvious areas iin `libflux` that would need attention:
* reactor: zmq watcher
* message use of zframe, zsock
* log use of `zmq_strerror()`
* use of czmq containers

**Comment by grondo** [comment]
> Doing so would also benefit other users of our APIs.

It is probably obvious, but this includes users of the Python APIs since `import flux` will presumably also be impacted negatively by the FIPS selfcheck on library initialization.

**Comment by garlick** [comment]
On the use of czmq containers - we could pull in the other container types (zlistx, zlist, zhash) to `libczmqcontainers` and then try to make it work without referencing the externally packaged czmq.

I don't think this is too difficult if we comment out some of the functions that we don't need that require other czmq classes.  In zhashx, that would include `zhashx_test()`, `zhashx_load()`, `zhashx_save()`, `zhashx_refresh()`, `zhashx_pack()`, and `zhashx_comment()`, for example.

A small number of support functions would need to be added to `czmq_internal.h`, and I think we'll need a `czmq_internal.c` for at least one function - `zstr_free()` since its used a default destructor via function pointer in `zhashx_new()`

**Comment by garlick** [comment]
On the message functions: here is a small brain dump.

I think the general approach could be to switch the internal implementation from zframe/zmsg to a native format, expose that format in an internal header, then re-implement the 0MQ send/recv functions in librouter using methods similar to usock/sendfd.

Specifically the functions that would need to be re-implemented/moved are these
```c
/* Send message to zeromq socket.
 * Returns 0 on success, -1 on failure with errno set.
 */
int flux_msg_sendzsock (void *dest, const flux_msg_t *msg);
int flux_msg_sendzsock_ex (void *dest, const flux_msg_t *msg, bool nonblock);

/* Receive a message from zeromq socket.
 * Returns message on success, NULL on failure with errno set.
 */
flux_msg_t *flux_msg_recvzsock (void *dest);
```

The internal implementation of a `flux_msg_t` is currently:
```c
struct flux_msg {
    zmsg_t *zmsg;
    json_t *json;
    char *lasterr;
    struct aux_item *aux;
    int refcount;
};
```

The zmsg could be specialized to a set of 1-3 decoded frames that match our protocol definition, e.g.
```c
// A message consists of from 1-3 message frames
struct flux_msg {
    // optional topic frame, if FLUX_MSGFLAG_TOPIC
    int topic; 

    // optional payload frame, if FLUX_MSGFLAG_PAYLOAD
    void *payload;
    size_t payload_size;
  
    // required proto frame
    uint8_t magic;
    uint8_t version;
    uint8_t type;
    uint8_t flags;
    union {
        uint32_t nodeid;  // request
        uint32_t sequence; // event
        uint32_t errnum; // response, keepalive
    };
    union {
        uint32_t matchtag; // request, response
        uint32_t status; // keepalive
    };
    uint32_t data[2]; // use depends on message type

    json_t *json;
    char *lasterr;
    struct aux_item *aux;
    int refcount;
};

**Comment by garlick** [comment]
I have a small PR going to pull in the other czmq containers - since I got part way there yesterday, may as well finish it off and post.

**Comment by garlick** [comment]
Well, I _think_ it would pull in `zframe`, `zsock`, and `zsys`.  Maybe others.

I'd prefer we try to wean ourselves off of these czmq classes anyway.  They were great for prototyping, but the fact that they assert on malloc failure, are built on the generic containers (thus not memory/cache efficient), and set up that irritating `atexit()` handler makes them a bit "heavy" for the critical message path IMHO.

(Aside, just noticed `topic` is defined as an `int` in the struct I posted above.  Pretty sure I meant `char *`. :-)

**Comment by chu11** [comment]
Just posted PR #3746, but there was a lot of prototyping that I did afterwards that didn't really work out.  I thought I'd post and see what thoughts others have.

Given some prior discussions, it might be good to add some `flux_msg_router_next/prev()` functions to go along w/ `flux_msg_get_route_first/last()`.  That way we can eliminate many of the internal `list_for_each()` calls.  By using these public iterating functions, it would make it easier for us to migrate some functions out of `libflux` into `librouter` and we might be able to avoid creating a "message private" helper library.

To support an iterator, I'd have to support some internal variable like `struct route_id *iter` to maintain our iterator location in the list.

This caused a ton of problems b/c we pass `const flux_msg_t *msg` around a lot (i.e. I'd be modifying a const struct by updating the iterator location).  I tried removing the `const` where needed, but b/c of `flux_msg_incref()`, it became hard to do.  (i.e. I think `flux_msg_incref()` cannot be made non-const, so we should not remove const-ness in most places)

Sooo ... to try and get things to work, I tried creating an alternate set of public functions, e.g.

```
int flux_msg_get_route_first (const flux_msg_t *msg, const char **id);
int flux_msg_get_route_last (const flux_msg_t *msg, const char **id);

const char *flux_msg_route_iter_first (flux_msg_t *msg);
const char *flux_msg_route_iter_last (flux_msg_t *msg);
const char *flux_msg_route_iter_next (flux_msg_t *msg);
const char *flux_msg_route_iter_prev (flux_msg_t *msg);
```

and I also tried creating internal functions only, i.e.

```
static const char *msg_route_iter_first (flux_msg_t *msg);
static const char *msg_route_iter_last (flux_msg_t *msg);
static const char *msg_route_iter_next (flux_msg_t *msg);
static const char *msg_route_iter_prev (flux_msg_t *msg);
```

but const issues were still hit in both.

Not wanting to break const-ness, I eventually did:

```
static const char *msg_route_iter_first (flux_msg_t *msg, struct route_id **iter);
static const char *msg_route_iter_last (flux_msg_t *msg, struct route_id **iter);
static const char *msg_route_iter_next (flux_msg_t *msg, struct route_id **iter);
static const char *msg_route_iter_prev (flux_msg_t *msg, struct route_id **iter);
```

where the caller passes in a variable to manage the iterator location.  This made using the iterator functions more work / confusing and it was debatable if it was a net win.

I'm still mulling over this, but I thought I'd post just to see if any thoughts pop into folks minds.  This prototyping suggests to me that perhaps a `message private` library might be unavoidable.

As an aside, `flux_msg_get_route_first/last()` return routes based on the "hop" location.  This is logically different than what I think an iterator first/last should do, which is return first/last based on the list its on (i.e. head vs tail of list).

That lead me to a thought, perhaps `flux_msg_get_route_first/last()` should be renamed?  With the removal of `zmsg` from internal structs, `get_route_first/last()` makes a little less sense?  Perhaps `flux_msg_get_route_sender/receiver()`?  Which could determine the sender based on if its a request/response?  I'm not 100% sold on this idea (and leaning that its bad), but just thought I'd mention the idea for kicks.

**Comment by chu11** [comment]
I began an experimental branch based on the RFC3 change here:

https://github.com/flux-framework/rfc/pull/295

which requires flux messages to have UUID's as routes.

This experiment went pretty badly and eventually gave up given the much greater amount of changes than I thought would have to happen.

1)

We don't really have a flux uuid library.  The few locations that need to generate uuid's simply use `libuuid`, convert a UUID to string format and pass that around (as a `char *`).  Introducing UUIDs into the flux message API is sort of a pain b/c it introduces uuid into a lot more areas than we'd probably want.

Here's what I initially changed:

```
int flux_msg_push_route (flux_msg_t *msg, const void *uuid, unsigned int len);
int flux_msg_pop_route (flux_msg_t *msg, void **uuid);
int flux_msg_get_route_first (const flux_msg_t *msg, void *uuid, unsigned int len);
int flux_msg_get_route_last (const flux_msg_t *msg, void *uuid, unsigned int len);
```

I think `flux_msg_push_route()` looks about right.  But the rest are meh.  It really stems from the fact that we don't have a flux uuid library in which its obvious that the returned value is a 16 byte buffer.

I think we'd need a flux uuid library of sorts, like:

```
#define FLUX_UUID_LEN 16
#define FLUX_UUID_STR_LEN 37

typedef {
       unsigned char uuid[FLUX_UUID_LEN];
} flux_uuid_t;

flux_uuid_generate (flux_uuid_t);
flux_uuid_tostring (flux_uuid_t, char *buf, ...);
flux_uuid_cmp (flux_uuid_t, flux_uuid_t);
... etc.
```

that we can use everywhere, it would make a big differences.  Then we can use the route functions like this.

```
int flux_msg_push_route (flux_msg_t *msg, flux_uuid_t uuid);
flux_uuid_t *flux_msg_pop_route (flux_msg_t *msg);
const flux_uuid_t *int flux_msg_get_route_first (const flux_msg_t *msg);
const flux_uuid_t *int flux_msg_get_route_last (const flux_msg_t *msg);
```

2)

We automatically assume UUID's as strings throughout flux, so the "chain" of changes might be extensive.  As one example, `router_entry_add()` pushes a route onto a message.  It's passed a uuid from `connector-local`, which in turn gets its uuid via `usock_conn_get_uuid()`.  So all those would have to turn into `flux_uuid_t`s as well.

3)

I initially thought we'd only have to do uuid -> string conversion in debugging locations or perhaps locations where UUIDs are printed out.  But we actually use the uuids as strings in hashes for lookups.  So all those locations would still have to do a uuid -> string conversion anyways, or replace with a hypothetical `flux_uuid_cmp()`.

Overall:

I didn't prototype very far until I decided this was going to be a lot more work than I originally thought, and the "win" isn't as large as I was hoping for.  Atleast not without a `flux_uuid_t` kinda data structure.

And ultimately, this entire prototyping stemmed from one thing.  I didn't like the idea of having:

`flux_msg_push_route (flux_msg_t *msg, const char *id);`

and

`flux_msg_append_route (flux_msg_t *msg, const void *id, unsigned int id_len);`

b/c the API styles would be different.

and the only reason we'd want a `flux_msg_append_route()` is so that we can avoid having a special `message_private.c` file that would have a `message_append_route()`.

One alternate idea is that we could have:

`flux_msg_push_route (flux_msg_t *msg, const void *id, unsigned int id_len);`

which would allow some flexibility in the future.

But I'm leaning more towards having a `message_private.c`, including my previous comments, its seeming more inevitable.

**Comment by chu11** [comment]
wanted to cut & paste from #3701 so don't forget this comment from @garlick

```
Maybe we should keep message.[ch] a complete implementation of RFC 3. That is, perform encoding in there down to the level of frames. The encoding that would go in librouter in support of sendfd/sendzmq would translate an opaque list of frames to the underlying wire protocol.

That would mean adding some interfaces to message.[ch] for the frame based encoding/decoding.

We could reinvent zframe for this, but I would think it might be a little nicer to use something like an array of iovecs, similar to readv(2), writev(2).

Any thoughts? I'm wondering if we ought to make some time to chat about this in a coffee meeting to get on the same page?
```

**Comment by chu11** [comment]
Thinking about this today.  Various thoughts:

1)

When calling `zmsg_recv()` (or underlying equivalent), we don't know the number of frames coming in.  So we can't pre-allocate the array of `iovec`.  So it strongly suggests we need a list-like data structure.

On the other hand, perhaps calling `realloc()` after each frame is read probably isn't that much worse than regularly calling `zmsg_pushmem()` or equivalent.  As I think about it more, it might be a wash or even better.

2)

I like the idea of an `iovec` like array on encoding b/c we can have most of the "data pointers" point to the internals of `flux_msg_t` (topic, payload, route ids.).  If we have a pre-allocted `proto` frame, we would not have to allocate / copy any data for the "iovec array".  This would be faster than building a `zmsg_t`.

On the `decode` side, presumably the "data pointers" could be set to whatever is returned from `zframe_data()` and thus could be similarly const.

3)

Should the hypothetical `flux_msg_encodev()` and `flux_msg_decodev()` be private or public?  I'm inclined to make them private.  I'm not entirely sure of the need to make them public.  I'm also not the most enthused with the idea of setting const pointers inside data structures that are non-const and have the user trusted with all this.  This is slightly related to ...

4)

Should the user allocate `iovec` or should the API allocate it for them?  I've gone back and forth with the idea, even toying with the idea of the array being stored internally w/n `flux_msg_t`.  But under the assumption of the functions being private, I think having the user allocate seems ok for now.

For the time being, I'm going to prototype under the belief we'll do something like this.

- `flux_msg_sendzsock()` and `flux_msg_recvzsock()` will be reimplemented using "raw" zmq calls, not going through the `zmsg` or `zframe` layers.

- re-implement using array of `iovec`-like structs

- support something like:

```
int flux_msg_encodev (flux_msg_t *msg, struct flux_iovec *iovec, int iovec_len);
flux_msg_t flux_msg_decodev (flux_msg_t *msg, struct flux_iovec *iovec, int iovec_len);
```

- then hopefully `flux_msg_recvzsock()` and `flux_msg_sendzsock()` can be moved to `librouter` quite easily and we only have to support a ``message_private.h`.

**Comment by chu11** [comment]
whoah, look at what i found

```
/******************************************************************************/
/*  These functions are not documented by man pages -- use at your own risk.  */
/*  If you need these to be part of the formal ZMQ API, then (a) write a man  */
/*  page, and (b) write a test case in tests.                                 */
/******************************************************************************/

struct iovec;

ZMQ_EXPORT int zmq_sendiov (void *s, struct iovec *iov, size_t count, int flags);
ZMQ_EXPORT int zmq_recviov (void *s, struct iovec *iov, size_t *count, int flags);
```

although the header is scary.  not entirely sure if it's safe / portable / future proof.

**Comment by chu11** [comment]
Been prototyping w/ an iovec-like solution.  Couple of notes from the experiment:

- `flux_msg_sendzsock()` worked out beautifully.  As expected, we only have to do a single `malloc()` call to allocate our `iovec` array and then set all of the pointers & sizes to internally decoded data.  The one exception is the `proto` frame, which isn't yet "decoded".  For the time being I pass in a "proto buffer" into "msg_to_iovec()" rather than add 20 bytes into `flux_msg_t`.  (The latter ending up breaking `const` in one location.)

- `flux_msg_decode()` worked out pretty well.  B/c we don't know the number of frames, allocating the `iovec` array ahead of time couldn't be done.  I elected to do a `realloc()` to extend the array on each iteration.  Non-ideal but I figure it's a net win.  Before we allocated a zframe and copied data into each frame.  But w/ iovec we avoid the copy.

- `flux_msg_recvzsock()` on the other hand was trickier.  Basically data recveived via zeromq is stored inside a `zmq_msg_t` data structure.  So we need to have a `zmq_msg_t` in memory when we set each iovec pointer.  I ended up adding an `aux` parameter to the iovec struct like so.

```
+struct msg_iovec {
+    const void *data;
+    size_t size;
+    void *aux;
+};
```

that `aux` can be used for any purpose.  In the case of `flux_msg_recvzsock()`, I malloc space for a `zmq_msg_t`.  It introduces an extra malloc that I wish I could have avoided but in terms of total mallocs, we're even.  And instead of allocating a new zframe that goes on a list for each frame, the `realloc` is probably faster on average.

- i also experimented moving the zsock functions over to `librouter`.  Was relatively easy to do.  Pros & cons of various approaches above as a result (I could avoid exporting many macros if I put a proto buffer into `flux_msg_t`).

Naturally was curious if this had a positive impact on performance, over many tests it is beginning show it does.  A sample result using job throughput benchmark.

master

```
Running throughput.py 2048 jobs per iteration, 5 iterations
throughput:     33.0 job/s (script:  32.8 job/s)
1: 63 seconds
throughput:     28.5 job/s (script:  28.3 job/s)
2: 135 seconds
throughput:     29.4 job/s (script:  29.2 job/s)
3: 206 seconds
throughput:     27.1 job/s (script:  27.0 job/s)
4: 282 seconds
throughput:     28.2 job/s (script:  28.1 job/s)
5: 355 seconds
Total of 355 seconds for everything
```

After PR #3746 (I buitl on top of this, this branch isn't merged yet)

```
Running throughput.py 2048 jobs per iteration, 5 iterations
throughput:     32.2 job/s (script:  32.0 job/s)
1: 64 seconds
throughput:     29.4 job/s (script:  29.3 job/s)
2: 134 seconds
throughput:     29.5 job/s (script:  29.3 job/s)
3: 204 seconds
throughput:     27.4 job/s (script:  27.2 job/s)
4: 280 seconds
throughput:     28.9 job/s (script:  28.7 job/s)
5: 352 seconds
Total of 352 seconds for everything
```

After the iovec work

```
Running throughput.py 2048 jobs per iteration, 5 iterations
throughput:     35.4 job/s (script:  35.2 job/s)
1: 59 seconds
throughput:     32.3 job/s (script:  32.1 job/s)
2: 123 seconds
throughput:     32.4 job/s (script:  32.2 job/s)
3: 187 seconds
throughput:     30.0 job/s (script:  29.8 job/s)
4: 255 seconds
throughput:     29.2 job/s (script:  29.0 job/s)
5: 326 seconds
Total of 326 seconds for everything
```

I'm consistently seeing throughput about 8-10-ish% percent better.

Will post a PR for review shortly.

**Comment by chu11** [comment]
began thinking about how to migrate czmq out of the reactor portion of `libflux` and get `czmq` out of libflux-core.

- `flux_zmq_watcher_create ()` is only used in the broker.  This suggests we could move it into the broker, we could perhaps make a `reactor_private.h` header file similar to our ideas for messages.  We'd have to make some helper functions (e.g. events_to_libev()) available as well.  In an experiment, I did this via static inline functions declared in the header and it worked.

- `flux_zmq_watcher_create()` internally uses `libutil/ev_zmq`, so we'd probably have to move that into `broker` as well.

- `flux_zmq_watcher_get_zsock ()` appears to be only used in tests.  Therefore that's an easy function to drop publicly and only use privately.

I did all of the above in a hacked up experiment.  Along with moving `flux_msg_sendzsock/recvzsock()` to `librouter` I wanted to see how smoothly we could disintegrate czmq from `libflux-core`.  Hit a bunch of bumps.

- `-lczmq` is linked everywhere.  Like even `liboptparse`, so `libflux-core` still had the czmq dependency after the above changes.  So it needs to be disentangled.  I think some of this was before `libczmqcontainers` so some areas are still linking for `zlist_t` and what not.  I had trouble figuring out how to disentagle everything and still haven't completed it.  I suspect it's going to be a "disentangle one at a time" and see how far we can go.  We'll start with issue #3776 as a starting point.

- `libflux-core` depends on `libflux-internal`, which `libflux-internal` depends on `librouter`, which uses libczmq.  So as an experiment I split off `librouter` into `libflux-internal-router`.  Generally speaking works, but ...

- by moving the sendzsock/recvzsock to `librouter` we hit a circular dependency issue with `libtestutil` (i.e. each depends on each other for testing).  I had to re-order the ldadds to make it work.  Along with previous bullet, maybe sendzsock/recvzsock should be in another util lib?

we're getting closer, one little refactoring at a time :-)

**Comment by chu11** [comment]
To make sure our general plan going forward made some sense I experimented with the above notes:

- moving `flux_msg_sendzsock()` and `flux_msg_recvzsock()` to `librouter`.
- move `flux_zmq_watcher_create()` and `ev_zmq` to `broker`
- remove `-lczmq` everywhere possible ()
- split off `librouter` from `libflux-internal` into its own lib

to my surprise, `FIPS_selfcheck()` was still being run after these changes.  After a ton of digging, it ended up the issue was `connector/local`.  B/c it depends on `librouter`, it still linked to `czmq`.  And when the shell would call `flux_open()`, that module got dynamically loaded for the "local://" scheme.

sooo i split off just `flux_msg_sendzsock()` and `flux_msg_recvzsock()` putting it into its own library only to be used in the handful of places its needed (only `broker`, `connector/shmem`, and `libtestutil`).

We got the desired results.  Running profiling:

`perf record -g --call-graph=dwarf -D 60000 src/cmd/flux start ./throughput_loop.sh 1024 1 ; perf report`

On current master (only showing the flux-shell stuff and if it was > 2% of cycles)

```
+   10.10%     0.00%  lt-flux-shell  lt-flux-shell          [.] main
+   10.10%     0.00%  lt-flux-shell  libc-2.28.so           [.] __libc_start_main
+   10.10%     0.00%  lt-flux-shell  lt-flux-shell          [.] _start
+    8.46%     8.46%  lt-flux-shell  [unknown]              [k] 0xffffffffba2001a3
+    7.01%     0.00%  flux-shell     bash                   [.] main
+    7.01%     0.00%  flux-shell     libc-2.28.so           [.] __libc_start_main
+    7.00%     0.00%  flux-shell     bash                   [.] _start
+    6.56%     0.00%  flux-shell     bash                   [.] reader_loop
+    6.41%     0.00%  lt-flux-shell  lt-flux-shell          [.] shell_init (inlined)
+    6.01%     0.03%  flux-shell     bash                   [.] execute_command_internal
+    6.01%     0.00%  flux-shell     bash                   [.] execute_command
+    5.84%     0.00%  lt-flux-shell  libflux-core.so.2.0.0  [.] flux_plugin_call
+    5.07%     0.00%  lt-flux-shell  ld-2.28.so             [.] .annobin_rtld.c (inlined)
+    5.05%     0.00%  lt-flux-shell  ld-2.28.so             [.] call_init.part.0
+    5.05%     0.00%  lt-flux-shell  ld-2.28.so             [.] _dl_init
+    5.05%     0.00%  lt-flux-shell  ld-2.28.so             [.] _dl_start_user
+    4.99%     0.00%  lt-flux-shell  lt-flux-shell          [.] affinity_init
+    4.94%     0.00%  lt-flux-shell  lt-flux-shell          [.] shell_affinity_create (inlined)
+    4.93%     0.00%  lt-flux-shell  lt-flux-shell          [.] shell_affinity_topology_init (inlined)
+    4.90%     0.00%  lt-flux-shell  ld-2.28.so             [.] _dl_start
+    4.90%     0.00%  lt-flux-shell  ld-2.28.so             [.] _dl_sysdep_start
+    4.89%     0.00%  lt-flux-shell  ld-2.28.so             [.] dl_main
+    4.88%     0.00%  lt-flux-shell  libcrypto.so.1.1.1g    [.] 0x00001555512e906f
+    4.70%     0.00%  lt-flux-shell  libcrypto.so.1.1.1g    [.] 0x00001555513e5cfe
+    4.70%     0.00%  lt-flux-shell  libcrypto.so.1.1.1g    [.] FIPS_selftest
+    4.31%     0.74%  lt-flux-shell  ld-2.28.so             [.] _dl_relocate_object
+    4.23%     0.00%  flux-shell     bash                   [.] 0x0000555555598fd6
+    3.39%     0.74%  lt-flux-shell  ld-2.28.so             [.] _dl_lookup_symbol_x
+    3.36%     3.36%  flux-shell     [unknown]              [k] 0xffffffffba200b87
+    3.00%     0.00%  lt-flux-shell  libcrypto.so.1.1.1g    [.] BN_mod_exp_mont_consttime
+    2.81%     0.05%  lt-flux-shell  ld-2.28.so             [.] _dl_map_object
+    2.73%     2.20%  lt-flux-shell  ld-2.28.so             [.] do_lookup_x
+    2.56%     0.03%  lt-flux-shell  ld-2.28.so             [.] _dl_map_object_deps
+    2.49%     0.00%  lt-flux-shell  libcrypto.so.1.1.1g    [.] EVP_DigestSignFinal
+    2.48%     0.00%  lt-flux-shell  ld-2.28.so             [.] openaux
+    2.45%     2.45%  flux-shell     [unknown]              [k] 0xffffffffba2001a3
+    2.19%     2.19%  lt-flux-shell  [unknown]              [k] 0xffffffffba200b87
```

fluke experimental branch

```
+   12.44%     0.00%  lt-flux-shell  libc-2.28.so           [.] __libc_start_main
+   12.44%     0.00%  lt-flux-shell  lt-flux-shell          [.] _start
+   12.44%     0.00%  lt-flux-shell  lt-flux-shell          [.] main
+    9.40%     0.00%  flux-shell     bash                   [.] main
+    9.39%     0.00%  flux-shell     libc-2.28.so           [.] __libc_start_main
+    9.38%     0.00%  flux-shell     bash                   [.] _start
+    8.65%     8.65%  lt-flux-shell  [unknown]              [k] 0xffffffffba2001a3
+    8.13%     0.00%  lt-flux-shell  lt-flux-shell          [.] shell_init (inlined)
+    7.41%     0.00%  lt-flux-shell  libflux-core.so.2.0.0  [.] flux_plugin_call
+    6.32%     0.00%  lt-flux-shell  lt-flux-shell          [.] affinity_init
+    6.24%     0.00%  lt-flux-shell  lt-flux-shell          [.] shell_affinity_create (inlined)
+    6.23%     0.00%  lt-flux-shell  lt-flux-shell          [.] shell_affinity_topology_init (inlined)
+    4.54%     4.54%  flux-shell     [unknown]              [k] 0xffffffffba200b87
+    3.23%     3.23%  flux-shell     [unknown]              [k] 0xffffffffba2001a3
+    2.92%     0.02%  flux-shell     bash                   [.] make_child
+    2.29%     0.00%  lt-flux-shell  libhwloc.so.15.4.1     [.] 0x0000155553f80afc
+    2.27%     0.02%  lt-flux-shell  ld-2.28.so             [.] _dl_map_object
+    2.12%     0.00%  lt-flux-shell  libhwloc.so.15.4.1     [.] 0x0000155553f8cb86
```

As one can see, `libcrypto` is gone and `ld` is a lot less.

Some throughput tests.  Note that these were run on fluke, vs the original tests that were run on opal.  Opal performance is far worse, ~10-11 jobs/s.  don't know why.

master


```
Running throughput.py 1024 jobs per iteration, 5 iterations
throughput:     23.2 job/s (script:  23.0 job/s)
1: 45 seconds
throughput:     22.7 job/s (script:  22.5 job/s)
2: 91 seconds
throughput:     21.2 job/s (script:  21.1 job/s)
3: 139 seconds
throughput:     21.0 job/s (script:  20.8 job/s)
4: 189 seconds
throughput:     21.3 job/s (script:  21.2 job/s)
5: 237 seconds
Total of 237 seconds for everything

fluke108|/tmp/achu/flux-core 43>src/cmd/flux start ./throughput_loop.sh 2048 5 
Running throughput.py 2048 jobs per iteration, 5 iterations
throughput:     21.9 job/s (script:  21.8 job/s)
1: 94 seconds
throughput:     19.2 job/s (script:  19.2 job/s)
2: 201 seconds
throughput:     18.4 job/s (script:  18.4 job/s)
3: 313 seconds
throughput:     18.8 job/s (script:  18.7 job/s)
4: 422 seconds
throughput:     19.3 job/s (script:  19.3 job/s)
5: 528 seconds
Total of 528 seconds for everything
```

experimental branch

```
fluke108|/tmp/achu/flux-core 36>src/cmd/flux start ./throughput_loop.sh 1024 5
Running throughput.py 1024 jobs per iteration, 5 iterations
throughput:     27.3 job/s (script:  27.0 job/s)
1: 38 seconds
throughput:     23.9 job/s (script:  23.8 job/s)
2: 81 seconds
throughput:     23.0 job/s (script:  22.8 job/s)
3: 126 seconds
throughput:     23.5 job/s (script:  23.3 job/s)
4: 170 seconds
throughput:     22.6 job/s (script:  22.5 job/s)
5: 216 seconds
Total of 216 seconds for everything

Running throughput.py 2048 jobs per iteration, 5 iterations
throughput:     25.5 job/s (script:  25.4 job/s)
1: 80 seconds
throughput:     21.9 job/s (script:  21.8 job/s)
2: 174 seconds
throughput:     19.9 job/s (script:  19.9 job/s)
3: 277 seconds
throughput:     21.7 job/s (script:  21.6 job/s)
4: 372 seconds
throughput:     20.8 job/s (script:  20.7 job/s)
5: 471 seconds
Total of 471 seconds for everything
```

time on `make -j4 check` (just on `t` directory) b/c we noticed a lot of test timeouts in the past

master

`1223.430u 493.893s 12:15.89 233.3%      0+0k 32+191336io 0pf+0w`

experimental branch

`1164.363u 484.993s 11:51.87 231.6%      0+0k 0+188176io 0pf+0w`

There's a nice bump in performance, about a 10% win on throughput, but not as much as I thought there'd be.  Obviously, flux-core code has changed a lot since #3612 was first posted and there have been many performance improvements since then (including a ~3% and then ~8% on just refactoring `libflux/message` before this experimental branch), so its possible the win is just smaller than would have been expected before.

Fluke is also weak-sauce (4 core, 16 gigs) vs some beefier nodes I've run on (catalyst - 24 core, 132 gig login nodes).  Could play a role.

So I think we have a general path towards getting this solved.  But it does involve making a new convenience library, one that we were hoping to avoid making.

Since we "have" to make a new convenience library, we could consider putting all zmq like things in this one library instead (zmq watcher, send/recv zsock, `ev_zmq`)

**Comment by garlick** [comment]
> After a ton of digging, it ended up the issue was connector/local. B/c it depends on librouter, it still linked to czmq. And when the shell would call flux_open(), that module got dynamically loaded for the "local://" scheme.

My (perhaps naive) expectation was that the local connector would be able to just pull in the objects from librouter (a static, internal library) that it needs, and then not add czmq/zmq to its LDADD.  The fact that another (unused by local.so) object in librouter would require linkage against czmq/zmq would not cause local.so to need it.  Am I confused?  (Or is this untrue in-tree because...libtool?)

**Comment by chu11** [comment]
> My (perhaps naive) expectation was that the local connector would be able to just pull in the objects from librouter (a static, internal library) that it needs, and then not add czmq/zmq to its LDADD. 

I can't remember if I tried that or not, but I just gave it a shot and building `connector/local` said it was missing czmq symbols.

I don't have the greatest knowledge of the linker, but I think if you build a `.so` all symbols need to be resolved?  It may not be the case if you build a static lib?  (the `.so` I'm referencing here is `local.so`).

**Comment by garlick** [comment]
When I `nm src/connectors/local/.libs/local.so`, it seems like a ton of unexpected symbols are in there with a little `t`.

I wonder if our method of linking dynamic modules against large swaths of internal static libraries is too sloppy, resulting in unnecessary shared library dependencies and dead code in the module?  For example we combine several static libraries into `libflux-internal.la`, I believe just to avoid specifying the libraries individually.  Maybe the direction you went here (separate static lib for objects that bring in the zmq dependency)  is how we should be doing things more broadly?

Geesh, that's not how I thought things worked.  More study required.

**Comment by chu11** [comment]
> Maybe the direction you went here (separate static lib for objects that bring in the zmq dependency) is how we should be doing things more broadly?

yeah, that was one of the big gotchas while doing the experiment.  `libflux-internal` and `libutil` include so much stuff, so suddenly everything that uses them often links to the libs.  So then there was this constant hunting for "why the heck is `flux-shell` still loading `libcrypt`?

Per your comment in #3778, perhaps we should minimally split out `libsodium` dependent stuff (or move to ccan base64, that's another approach).
