### ISSUE TITLE
Prototype support for launching child instances from within an existing instance

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#364]
This is to generate a discussion for enabling child-instance launching from within an existing flux instance. I believe any hierarchical-launching prototype at this point can facilitate @surajpkn's dynamic-scheduling investigation. 

The information that would be particularly useful:

1. What modifications are needed to launch an Flux instance (or instances) from an existing Flux instance. 
  * `wreck`:  to launch a new instance and the broker processes of this instance will be contained within the specified resources. If this can be supported relatively easily, what should be the command line of the broker that will be provided to `wreckrun`. Should we harvest this info by looking at `flux-start`? 
  * `flux-exec`: is this an option to launch a new instance?

2. Assuming (1) is done, how a service module (e.g., scheduler framework service) of a chile instance communicate with the parent instance and vice versa? We talked about having a new module (or augment scheduler framework service) that can translate a packet from a child to the parent and vice versa. Are there any other models that should explored so that our experience can provide good lessons  for the actual hierarchical launching in the future. 

3. There are other questions on how we can hook emulation environment across the hierarchical instances but they should go to a flux-sched issue.

**Comment by garlick** [comment]
The best current way to do this would be to launch flux with `flux wreckrun`.  Wreck sets up the environment so PMI can work in the programs it launches, and the broker in turn can use PMI to bootstrap.

As you point out, `flux-start` contains the logic to construct `srun` and `flux-broker` command lines to start an instance using PMI.  As a first step we might just want to add a `--flux` option to` flux-start` that constructs the `flux wreckrun` and `flux-broker` command lines similar to the slurm ones.

Another obstacle is communicating with the parent.  The bootstrap code that acts as a PMI client already does this, but thereafter it overwrites the value of FLUX_TMPDIR with its own information so that _its_ children can connect with it.  I would suggest that we examine more closely when this variable should be changed.  Ideally it would only be set to the current instance for programs spawned by the instance, not in the instance itself, but I think that would require a fork/exec that is not currently done for the initial program or programs spawned by the cmb.exec service.

Anyway these are relatively minor obstacles.  The design from start has been for Flux to launch Flux so it should work, and indeed we should be doing it in our tests.

For starters I think we should get a PR going to add a `--slurm` option to `flux-start`, with a sharness test.  I'll get on that.

**Comment by grondo** [comment]
> For starters I think we should get a PR going to add a --slurm option to flux-start, with a sharness test. I'll get on that.

Did you mean a `--flux` option here? 

It might actually be useful if `flux-start` grows a very small plugin or module system which registers methods or handles construction of command lines to actually launch new flux brokers. This way flux-start code doesn't need to be modified directly for each new start method. Launch methods could be available under a `--method=` or `--tool` command line option (with a `--method=list`  option to list available methods). This seems more tractable for multiple start options, than a different command line option for each one. Also, it would be nice if each method could register options for flux-start instead of having separate (but intersecting) options for each method. 

Anyway, just an idea to throw out there...

**Comment by garlick** [comment]
Yes I meant `--flux` sorry!

That sounds like a good idea although it might take me a while to get my head around the best way to go about it.  Would you like to sketch a design for this?

As a side note I was just wishing that I could call `flux wreckrun` from `flux start` and be assured I had the right one; this harkens back to #310.  Also, it seems like running flux which runs flux-start which runs flux which runs flux-wreckrun is a bit repetitious.  Should we have some method for commands to call other commands without going through the front end again?

**Comment by grondo** [comment]
#310 is mergeable I think.  Really all it does is prepend to PATH... nothing too special there.

I'm not sure about removing flux command driver. This would require more thought. For instance it wouldn't work for builtins. Are you mainly worried about the extra fork/exec? I guess any flux command cognizant of the flux cmd path could directly execute `flux-CMD`...? However, flux executable itself will probably already be paged in so I'm not so convinced this will be a huge speedup. Maybe scripts that are creating new commands/utilities from other commands could make use of this though?

**Comment by garlick** [comment]
I was mainly thinking about re-loading the config from the KVS, though I guess it could be called with `-F`.

I'll go merge #310.

**Comment by dongahn** [comment]
`--flux` or @grondo's equivalent would be a perfect starter for us. We'll look forward to a PR for this one. Do you plan to consider $FLUX_TMPDIR in this PR as well? If you need some help, I can take a look at that as well. Please let me know. 

Once the physical connection is there for the parent and child to use, @surajpkn and I will have to start to add some glue logic to route a packet between two appropriately. 

An important glue logic there will be what I call *bridge module* as a distributed service for routing parent/child dynamic-scheduling information. This module will create and maintain a routing table between a jobid and a port  (or some communication handle) so that a message sent from a child scheduler service can be routed to the parent scheduler and vice versa, for example.

To help @surajpkn get some hands-on experiences to flux programming, I was thinking to ask him to work on this module to begin with and I thought I should ask your opinion about this.

**Comment by garlick** [comment]
I think enabling communication with the parent after the PMI bootstrap is likely a separate PR.

The idea would be that from a module or process in a child instance, you would open a handle to the parent, and be able to operate as an entity within the parent, send/recv events, requests, responses, etc..    

Presumably that would be the second `flux_t` handle, and at the moment, the reactor and message dispatcher is tied to one handle.   We already mentioned in our discussion earlier today in the hall that this would require a "handle watcher" so that the reactor can incorporate the additional handle.  There are also complications iwth registering message handlers on the second handle and keeping them separate from the first handle.  This may require some reactor rethinking.

So more thought required on that one, and let's get the hierarchal _launch_ working first.

Why would routing tables be necessary?  Were you thinking of enabling a parent to route through an instance to children?  I would be very careful of giving parents knowledge of grandchildren and the other way round.

**Comment by dongahn** [comment]
Yes what you are describing would be a more suitable solution. Since we have some time bound for this project, I wanted to have a duck-tape solution that we can use when there is no full-up solution like this. 

To answer your question on the need for the bridge module (and routing tables), with the support you are talking about above, communication from a child to the parent will be straightforward. A child module can simply send a packet to the parent handle, which will then be routed as specified (ANY or UPSTREAM).

However, a communication from the parent to a child needs some thoughts. 

Say, the parent flux instance spans 4 nodes and a child instance (as a job to the scheduler) is running on 2 nodes (a proper subset). Unless one of these two nodes is the root node of the parent, where its scheduler service is running, the parent scheduler's packet will need to be somehow routed to a broker that is co-located with a child broker, next forwarded to the child instance and then routed to the child's scheduler module (the root of the child instance). 

Also a parent broker can be co-located with multiple child brokers (multiple child flux instances are created and over-committed). In that case, the packet from the parent needs to have the child's jobid information such that that the packet can be routed to the right child instance. 

@surajpkn and I were thinking a bridge module, which maps a jobid to the right routing path, can be loaded to every broker and be responsible for forwarding for dynamic scheduling in the absence of general inter-instance routing service. 

One can of course extend our communication model to start to support such inter-instance routing service for general cases, but I feared that this cannot be done in a time frame that we can still make good progress for the next 3.5 months. You may of course think differently about the time needed for this. 

So to make a quick progress to set up the dynamic scheduling evaluation framework exploration, I thought we could perhaps achieve this by prototyping such a bridge module as part of a companion module to the scheduler framework service within a flux-sched branch.

**Comment by garlick** [comment]
Well the problem of whether a service in the parent is co-located with the child is not an issue since the routing protocols in the parent will take care of that.  E.g. any node of an instance can send a request to "sched.whatever" and it will be routed up the tree until there is a match, and back again using the source address routing stack.  So don't worry about that one - a connection to any rank of the parent should be sufficient to be able to fully communicate within the parent.

**Comment by dongahn** [comment]
Ah! This might work out far easier than I thought then :) So even for a communication from the parent to a child, as far as the child starts the communication and the parent holds that packet header (which has the route information to the child module), the parent can send back a packet to the child's scheduler service? Did I get this right?

**Comment by garlick** [comment]
Correct.

**Comment by surajpkn** [comment]
Just for my clarity, if I understand this correct, we wouldn't need a bridge module but to only save the route information after a parent flux-instance starts a child flux-instance (by making the child talk to the parent first). That way, the scheduler module of the parent flux-instance needs to save up that info for all the child flux-instances it starts. If that is correct, then the way for the child instance to communicate with the parent instance is still to be worked on?

**Comment by dongahn** [comment]
Right, we won't need the bridge module. 

The child instance will send a packet to the parent 'flux_t' handle (not its own 'flux_t' handle) and will rely on the parent's routing scheme to get to the scheduler module. I would say, we rely on @garlick to work on that new handler watcher for this work. 

Meanwhile, let's chat a bit to work on some other flux programming work to support your investigation while helping you have some hands-on experience. (meet tomorrow?)

**Comment by surajpkn** [comment]
Sure. Let me know what time you will drop by.

**Comment by garlick** [comment]
@surajpkn: it should be possible for a child to do something like:
```
flux_t h;
flux_rpc *rpc;
const char *json_in;
const char *json_out;

h = flux_open (NULL, 0);
rpc = flux_rpc (h, "sched.whatever", json_in, FLUX_NODEID_ANY, 0);
flux_rpc_get (rpc, &json_out);
flux_close (h);
```
This will connect to the enclosing instance if FLUX_TMPDIR still points to it (right now FLUX_TMPDIR is overwritten after the PMI bootstrap, so we have to fix that).   The above example would work immediately once FLUX_TMPDIR is fixed, but it is a synchronous RPC.  To use asynchronous, event driven programming, you need to involve the flux reactor, and that requires the "handle watcher" @dongahn referred to and possibly some other plumbing changes.

It should also be possible to publish and subscribe to event messages using this handle.  That may be a way for siblings and the parent to communicate without the coupling implied by RPC.

You can start learning the API beginning with the (hot off the press) manual pages in doc/man3.  Use `flux help topic` to format them in the build tree.  For example there are pretty detailed manual pages for `flux_rpc`, `flux_open`, flux_send`, etc..

**Comment by garlick** [comment]
Just wanted to note here that #369 now should include support for communicating between hierarchical instances but it's not quite like I described above.  If you want to open a second handle to the broker of the enclosing instance, you would need to call (error handling omitted):
```
char *parent_uri = flux_getattr ("parent-uri");
flux_t parent_h = flux_open (parent_uri, NULL);
...
free (parent_uri);
```

With the parent handle, you can do things like make a synchronous rpc, send an event, receive an event, etc..  What you can't do yet is integrate it into a flux reactor loop based on another handle.  So that means a `flux_rpc_get()` or `flux_recv()` for example, would block, and your module would be unresponsive during that time.

Maybe enough to get started?

**Comment by grondo** [comment]
> `char *parent_uri = flux_getattr ("parent-uri");`

probably obvious, but should that be
```C
char *parent_uri = flux_getattr (h, FLUX_NODEID_ANY, "parent-uri");
```

Where `h` is the handle passed to module `main()`
(Sorry if you just mean to show psuedocode, but the `FLUX_NODEID_ANY` might not be obvious)

**Comment by garlick** [comment]
Right!  Thanks @grondo.

**Comment by garlick** [comment]
This changed yet again with PR #392, just merged.  Here's a little test program that you can run like this
```
$ ./flux start flux start flux foo
[ignoring log output]
session-id: 49585
parent-uri: local:///tmp/flux-49523-SDfaPO/0
parent-session-id: 49523
$ 
```
flux-foo.c
```C
#if HAVE_CONFIG_H
#include "config.h"
#endif
#include <flux/core.h>
#include <stdio.h>
#include "src/common/libutil/log.h"
#include "src/common/libutil/xzmalloc.h"


int main (int argc, char *argv[])
{
    //open handle to "my" instance and print session-id and parent-uri
    flux_t h = flux_open (NULL, 0);
    if (!h)
        err_exit ("flux_open");
    const char *sid = flux_attr_get (h, "session-id", NULL);
    if (!sid)
        err_exit ("flux_attr_get session-id");
    printf ("session-id: %s\n", sid);
    const char *parent_uri = flux_attr_get (h, "parent-uri", NULL);
    if (!parent_uri)
        err_exit ("flux_attr_get parent-uri");
    printf ("parent-uri: %s\n", parent_uri);
    flux_close (h);

    //open handle to enclosing instance and print its session-id
    flux_t parent_h = flux_open (parent_uri, 0);
    if (!parent_h)
        err_exit ("flux_open %s", parent_uri);
    const char *parent_sid = flux_attr_get (parent_h, "session-id", NULL);
    if (!parent_sid)
        err_exit ("flux_attr_get session-id");
    printf ("parent-session-id: %s\n", parent_sid);
    flux_close (parent_h);

    return (0);
}
```

**Comment by grondo** [comment]
Is there more to do here, or can we close this particular issue?

**Comment by garlick** [comment]
I'm thinking it can be closed but let's get an ack from @dongahn.

**Comment by dongahn** [comment]
From my perspective this is really nicely done. But to make sure, @surajpkn, could you ack since you are the main user of this capability?

**Comment by surajpkn** [comment]
Yes, this issue can be closed. Thanks again for this piece!

**Comment by garlick** [comment]
Thanks, that was actually a fun one for me.  It was nice having you guys put a little pressure on this part of the design. :-)
