### ISSUE TITLE
multiple simultaneous single-node OpenMPI jobs cause shmem errors

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#3649]
Edit: This is for OpenMPI 4.0.5

It appears that currently, running multiple simultaneous single-node OpenMPI jobs will fail under Flux, most likely  due to reuse of shm filenames:

```
$ flux resource list
     STATE NNODES   NCORES    NGPUS NODELIST
      free      1       34        0 opal158
 allocated      1        2        0 opal158
      down      0        0        0 

$ flux mini submit --cc=1-2 --watch --progress -n2 ./mpihello 
ƒGv1uixym
ƒGv1uixyn

...--------------------------------------------------------------------------
A system call failed during shared memory initialization that should
not have.  It is likely that your MPI job will now either abort or
experience performance degradation.

  Local host:  opal158
  System call: open(2) 
  Error:       No such file or directory (errno 2)
--------------------------------------------------------------------------
[opal158:30431] mca_common_sm_mpool_init: unable to create shared memory mapping (/var/tmp/grondo/ompi.opal158.6885/jf.0/0/shared_mem_cuda_pool.opal158)
```

The errors are different on each attempt, and sometimes the jobs actually succeed (likely due to a fallback to non-shmem MPI?).

**Comment by garlick** [comment]
[this ompi commit](https://github.com/open-mpi/ompi/commit/611d7c2d27de30034ef599c03d42137702ccfe91)  adds `OPAL_PROC_MY_NAME.jobid` to the "vader" shared memory segment.  Apparently under flux the jobid is always zero as evidenced in this particular failure (path suffix is hostname.jobid.rank).
```
--------------------------------------------------------------------------
--------------------------------------------------------------------------
A system call failed during shared memory initialization that should
A system call failed during shared memory initialization that should
not have.  It is likely that your MPI job will now either abort or
not have.  It is likely that your MPI job will now either abort or
experience performance degradation.
experience performance degradation.


  Local host:  system76-pc
  Local host:  system76-pc
  System call: unlink(2) /dev/shm/vader_segment.system76-pc.5588.0.1
  System call: unlink(2) /dev/shm/vader_segment.system76-pc.5588.0.0
  Error:       No such file or directory (errno 2)
  Error:       No such file or directory (errno 2)
--------------------------------------------------------------------------
--------------------------------------------------------------------------
```
I'm not sure if fixing the flux ompi plugin to correctly set the jobid would solve all cases of this type of failure, but I'll try to do that and see how much it helps.

It may be that we also need to set `OMPI_MCA_orte_tmpdir_base` to cover other cases.  We used to set it to the broker rundir, but that was not a good long term solution and was reverted by 3d1a9efa5b5ca598bb874c57cc7190686af3c58f

**Comment by garlick** [comment]
Oh, it's the f58 FLUX_JOB_ID that's causing ompi to think the jobid is zero (because it's passed to `strtoul()`).    A quick hack to encode the jobid as an integer makes the repro no longer repro, e.g.
```diff
diff --git a/src/shell/task.c b/src/shell/task.c
index 5d1912db7..78d5fa5e6 100644
--- a/src/shell/task.c
+++ b/src/shell/task.c
@@ -133,7 +133,7 @@ struct shell_task *shell_task_create (struct shell_info *info,
         goto error;
 
     /* Attempt to encode jobid as F58 by default */
-    if (flux_job_id_encode (info->jobid, "f58", buf, sizeof (buf)) < 0)
+    if (flux_job_id_encode (info->jobid, "dec", buf, sizeof (buf)) < 0)
        snprintf (buf, sizeof (buf), "%ju", (uintmax_t)info->jobid);
     if (flux_cmd_setenvf (task->cmd, 1, "FLUX_JOB_ID", "%s", buf) < 0)
         goto error;
```
although Flux 64 bit jobids are also being truncated at 32 bits.

**Comment by grondo** [comment]
Hm, that's an unfortunate assumption that JOBIDs will be 32bit integers. Is that only in the flux plugin for OpenMPI or is it a requirement for PMI/PMIx?

**Comment by garlick** [comment]
In openmpi, the flux plugin calls `opal_proc_set_pname()` to set a `opal_process_name_t` parameter that includes the jobid.  A comment says the jobid can be [any type of integer](https://github.com/open-mpi/ompi/blob/e6b751e69b309c312233efe53f120ed124ed4d15/ompi/mca/rte/rte.h#L20) but thus far, I am having trouble following the trail of typedefs, unions, and casts to if we could somehow make 64 bits work.  I guess ultimately it's not going to work for this case because the shmem path is constructed with `asprintf()` using `%x` for the job ID.

PMI-1 has an int "appnum".  We leave it set to 0 and that seems to be fine - I'm not sure it's used.

PMI-2 has the same int appnum, but also a `PMI2_Job_GetId()` that returns the id as a string.

As far as I can tell, PMIx treats the jobid as a [string](https://github.com/openpmix/openpmix/blob/74327dd61ffa01d7e0a731887118c28aefd78683/include/pmix_common.h.in#L288)

**Comment by garlick** [comment]
For the short term, we should probably figure out how to make the `openmpi.lua` plugin force decimal encoding of FLUX_JOB_ID, and accept that it will be truncated, since this at least makes this error unlikely.

Given that the flux plugin has already been removed upstream in ompi master, maybe that's good enough until either #3539 or #3536 happen.

**Comment by grondo** [comment]
Since the openmpi.lua plugin is always run, we might as well just encode FLUX_JOB_ID as a decimal as your patch above does. I don't think there is anything that requires the f58 representation (it is just nice when it matches the default `flux jobs` and `{{id}}` mustache template expansion)

**Comment by garlick** [comment]
Good point.  Let me dig further and see if there is a way to override the shmem path.
