### ISSUE TITLE
t/python/t0010-job.py occasionally fails

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#3666]
Problem: `t/python/t0010-job.py` routinely fails here  on a busy system
```
not ok 33 __main__.TestJob.test_32_job_result
  ---
    message: |
      Traceback (most recent call last):
        File "python/t0010-job.py", line 574, in test_32_job_result
          self.assertEqual(
      AssertionError: 143 != -15
  ...
1..33
```

**Comment by grondo** [comment]
What is the new failure?

**Comment by garlick** [comment]
Same failure as in the description.  (Sorry, that wasn't very clear)

**Comment by grondo** [comment]
My current thought is that the test is broken, and we were testing that the shell was signaled and not the sleep. Thanks for catching this subtlety.

There's a known problem with the way we report exit/wait status for jobs using the shell's exit status. If tasks are killed by a signal, the shell can't "simulate" that, and instead exits with the 128+signal idiom. Therefore, when tasks are killed with SIGTERM, the `JobInfo` `returncode` attribute will never be negative, instead it will be 128+sig as you've found here.

Related #2773

I think the fix for now is to use your patch above to wait for the `shell.start` event, and update the expected `waitstatus` to 143 in the failing test.

**Comment by garlick** [comment]
Awesome!  Thanks for the help there.  I'll tack this onto my current PR and push shortly.
