### ISSUE TITLE
 ./t3300-system-basic.t fails on a TOSS3 machine

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#3736]
```console
rzhasgpu18{dahn}50: pwd
/usr/global/tools/flux/toss_3_x86_64_ib/build/2021-06-21-c0.28.0.pre-s0.17.0.pre/flux-core/t

rzhasgpu18{dahn}49: ./t3300-system-basic.t
lt-flux-broker: overlay_connect: Cannot allocate memory
lt-flux-broker: overlay_connect: Cannot allocate memory
lt-flux-broker: overlay_bind: File name too long
lt-flux-broker: bootstrap failed
flux-start: 0 (pid 27065) exited with rc=1
flux-start: 1 (pid 27066) Killed
flux-start: 2 (pid 27068) Killed
```

Maybe there was a change in security authentication which hit a short file path limit for my /usr/global configuration?

**Comment by dongahn** [comment]
Same issue with two more tests:

```console
rzhasgpu18{dahn}71: ./t3301-system-latestart.t
lt-flux-broker: overlay_bind: File name too long
lt-flux-broker: bootstrap failed
flux-start: 0 (pid 30591) exited with rc=1

rzhasgpu18{dahn}73: ./t3302-system-offline.t
lt-flux-broker: overlay_bind: File name too long
lt-flux-broker: bootstrap failed
flux-start: 0 (pid 30788) exited with rc=1
```

**Comment by garlick** [comment]
That test does use the `system` personality which  is new, and would select the bind address to be in the sharness trash directory instead of in /tmp, e.g.
```
/usr/global/tools/flux/toss_3_x86_64_ib/build/2021-06-21-c0.28.0.pre-s0.17.0.pre/flux-core/t/trash-directory.t3300-system-basic/tbon-0
```
Oh!  Ot sounds like the max path for UNIX domain sockets is on the order of 100 bytes!   (I did not know or had forgotten this)
https://unix.stackexchange.com/questions/367008/why-is-socket-path-length-limited-to-a-hundred-chars

We will need to fix that.

**Comment by dongahn** [comment]
Yes I agree with your assessment. I had a similar issue with one of my tests and wasn't immediately clear how to fix it, though.

**Comment by garlick** [comment]
I think what we need to do is place those sockets in the `rundir` like the FLUX_URI, since normally that is a short path relative to /tmp.  The config file referencing the socket paths is created before `flux start` runs.

So I think either
- sharness creates and cleans up the rundir, and provides it to `flux start --rundir`
- sharness creates the directory and provides it to `flux start --rundir` and we add an additional option to tell `flux start` to clean up the user-provided rundir
- add toeken `%r` token or simlar that can be placed in the configured URI path and represents the ephemeral rundir

Just need to figure out which of these is less ugly :-)
