### ISSUE TITLE
flux-shell crashes with imbalanced jobs

### ISSUE THREAD

**Issue by ggouaillardet** [flux-framework/flux-core#3747]
I ran flux on two nodes with 24 cores each.

The following command
```
$ flux mini run -N 2 -n 5 -c 5
```
causes flux-shell to crash (stack trace in the inlined image).

![image](https://user-images.githubusercontent.com/7233259/123589963-fa053680-d824-11eb-9f81-a622d094697a.png)

I do not fully understand the logic, but from my observations:
 - `rcalc_distribute()` is invoked with `r->ncores` = `30`, so `cores_per_task` is assigned `6`.
 - if I manually force `cores_per_task` = `5` with a debugger, no crash occurs

I guess `flux` internally did something like 5 tasks on 2 nodes ~= 3 tasks per node
3 tasks per node * 2 nodes * 5 cores per node = 30 cores (but we requested only 25)
And then, we end up popping a `NULL` `ai` from the `l` `zlist`, shortly followed by a crash when `allocinfo_add_task()` dereferences the `NULL` pointer.

**Comment by grondo** [comment]
Thanks @ggouaillardet! This is appears to be a bug in sched-simple which in turn triggers a bug in the shell's rcalc code. I will start looking for a fix.

Just to verify, you are using sched-simple and not Fluxion (flux-sched)? If so, you may want to try Fluxion since it will likely have better results (I haven't been able to try it just yet)

**Comment by grondo** [comment]
Interesting, this is actually an issue in the Python Jobspec class, or at least when I run `flux mini run -N 2 -n 5 -c 5` the resulting jobspec is explicitly asking for 3 task slots of size 5 across 2 nodes:
```
$ flux mini run -N2 -c5 -n5 --dry-run --env=-* hostname | jq .resources
  [
    {
      "type": "node",
      "count": 2,
      "with": [
        {
          "type": "slot",
          "count": 3,
          "with": [
            {
              "type": "core",
              "count": 5
            }
          ],
          "label": "task"
        }
      ]
    }
  ]
```

**Comment by grondo** [comment]
Ok, looks like the problem above is perhaps a known limitation of JobspecV1 when forcing the number of nodes:

https://github.com/flux-framework/flux-core/blob/0c7f52ad660598e0e30db2f40263726342510f66/src/bindings/python/flux/job/Jobspec.py#L632-L634

**Comment by grondo** [comment]
The problem, as you pointed out @ggouaillardet, is that `rcalc_distribute()` assumes that the exact number of slots of the given size were allocated to the job and thus calculates an incorrect slot size. To fix, we'll add a parameter to explicitly set the slot size in `rcalc_distribute()` so that the incorrect size is not derived within the function.

Note: as the comment in the referenced `Jobspec` code states, this will idle one slot (5 cores) in this case.

I wonder if a warning should be issued to the user in this case?

**Comment by ggouaillardet** [comment]
@grondo thanks for the quick fix, I am happy to confirm it solves the issue I faced !
(and yes, I used `sched-simple`)
