### ISSUE TITLE
broker should retain environment set up by its enclosing instance

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#381]
As discussed in #369, within the broker, a `flux_open (NULL, flags)` should establish a connection with the enclosing instance.

Within programs launched by the broker, `flux_open (NULL, flags)` should establish a connection with _their_ enclosing instance.

So really the environment of the broker should be left as set up by its parent, and the environment should be altered only in programs during launch.  These points are (currently):
* launching the initial program
* wrexec launching wrexecd
* cmb.exec launching tasks

**Comment by garlick** [comment]
Further, I think FLUX_TMPDIR could be replaced by FLUX_URI for transmitting the URI to use when `flux_open` gets a NULL URI.

Internally, the broker can share its tmpdir (e.g. to the connector-local module for socket creation) with `flux_getattr`.  It doesn't need to be transmitted through the environment.

**Comment by grondo** [comment]
This seems pretty well summarized. I really like your proposal for `FLUX_URI`.

By "within the broker" do you mean the broker and any of its modules? Since modules already get passed a handle to their broker, do module authors assume `flux_open (NULL, flags)` will connect to parent? (I ask this anyway, even though I'm pretty sure it isn't the case due to your final comment above)

Given the above, will broker store its URI to parent in an internal context then remove `FLUX_URI` from environment? This will actually be really helpful, because it will be quick to catch actors inadvertently relying on the in-broker environment.

We are already vectoring toward a common method for creating programs, so I think this is good. The initial program is a bit tricky because (at least for now) we don't want to use `cmb.exec` so we can easily keep pty support. That can be special cased until we've resolved that issue. And as you know wrexec will be replaced by the "shell" launched with `cmb.exec` (again special case).

I'd hate to throw too much into the kvs `config`, but something that is considered the "default program environment" for an instance would be really helpful (right now this is the broker environment). Actually this "default environment" can be thought of as the top level environment in the program hierarchy, and per-program environment need only have "overrides" or any new environment (and the same could be done per-"task" within a program if need be). Done right we could avoid the massive duplication of environments we're doing now in wreck/cmb.exec...

**Comment by garlick** [comment]
I did mean that the broker and its modules, which share an environment containing FLUX_URI that points to the enclosing instance, would all get the same behavior with `flux_open (NULL, ...)`.

I guess we could remove FLUX_URI from the environment after stashing the parent's URI somewhere (maybe as a `flux_getattr()` attribute).  Users of the parent instance would then have to explicitly obtain the URI and plug it into `flux_open()`.  That removes all ambiguity and makes sense to me.  Is that what you were proposing?

I'm getting a little lost thinking about the default program environment.  Let me chew on that for a while.

**Comment by grondo** [comment]
> Users of the parent instance would then have to explicitly obtain the URI and plug it into flux_open(). That removes all ambiguity and makes sense to me. Is that what you were proposing?

Yes, it seemed like it would be good to require module authors to be explicit about the instance to which they want to connect.

**Comment by grondo** [comment]
> I'm getting a little lost thinking about the default program environment. Let me chew on that for a while.

Maybe my wording was confusing. I don't think it is any different than what we've talked about before. For single-user instances, it makes a lot of sense to have the default environment for everything set somewhere in the broker (`config.environment`?). As new kvs-based programs are created, the shell would only have to place an environment diff into `program.<id>.environ` (or whatever). If a program being launched needs task-specific environment for some reason (MPMD?), a similar thing could be done as the task level `program.<id>.task.<taskid>.environ`, where the `environ` kvs entries could be directories that contain `setenv`, `unsetenv` commands or some other mechanism to modify instead of just instantiate the new environment. An empty or missing `environ` entry would just get the default.

If launching a new instance as a program, the aggregated environment for tasks in the enclosing instance's `program.<id>.task.<taskid>.environ` now becomes the broker's actual environment, and the broker copies this into `config.environment` changing `FLUX_URI` and other specific environment variables there accordingly.

Hm, actually this simple idea *is* turning out to be a little tricky to explain.

The simplest use case would be a set of 1000 programs that all run under the same environment, except for one variable that is updated per program.

The other possibility here is that if we have a per-task environment entry as well, we could place task specific `FLUX_*` environment variables there and perhaps save them for provenance. (For now they are set directly for each task lost after task exit).

**Comment by garlick** [comment]
The tricky bit here is cmb.exec and the initial program launch can't (well, shouldn't) access the KVS since they are running inside the broker, so that can't really be the environment cache used by those services.  No reason we can't have another cache though.

Perhaps the new program execution service could be responsible for setting the default program environment in a broker cache once or whenever it changes?  E.g. `cmb.setenv`?  We could implement that broker cache now and initialize it directly from the broker's environment, then when the new program execution service comes along it can synchronize it with the KVS?

The config.* stuff has a little different semantics than I think you want here.  It's initialized either from a file or from the enclosing instances's KVS.

**Comment by grondo** [comment]
Yeah, sorry my examples were meant to be illustrative. I like your idea of creating the cache now and synchronizing with kvs later.

**Comment by garlick** [comment]
I guess I didn't properly reference this issue from pr #383.  Closing as that was just merged.
