### ISSUE TITLE
Environment to load external plugins

### ISSUE THREAD

**Issue by eleon** [flux-framework/flux-core#3866]
* Goal: Use the environment to load external plugins in Flux without having to write them into the Flux plugins directory. 
* Problem: In Spack, or using system installations of Flux, one cannot change the Flux installation. Having an environment variable or something similar to point Flux to additional plugins to load could address this problem.

**Comment by grondo** [comment]
For example, the job shell will automatically load all `*.so` plugins in the default shell `pluginpath` via the default shell `initrc.lua`. For a Flux spack package, the default pluginpath will by definition not contain any external plugins since external packages are not supposed to place anything in the flux-core package root.

Ideally the spack environment exported by packages that want to extend the job shell would be able to append to the built in shell pluginpath or otherwise extend the default list of loaded plugins.

At this time, I'm not certain of the most efficacious method to do this, but it does seem like a reasonable request. I'll come back with a proposal if someone else doesn't beat me to it.
