### ISSUE TITLE
Clarifying the Flux Hierarchical Job Model

### ISSUE THREAD

**Issue by lipari** [flux-framework/flux-core#388]
This issues continues the discussion of [Issue 369]https://github.com/flux-framework/flux-core/pull/369) with regard to launching flux within flux.  The Flux design provides for a hierarchy of jobs but differs from the traditional job/job step model.  The following is a summary I provided to describe the Flux model...

`flux-start` instantiates a Flux instance and optionally runs a command.  Right now, flux-start invokes its comms sessions all on the same node or on the Slurm nodes when running within a Slurm job.  I think eventually `flux-start`, when running instead of Slurm, will have to be told which nodes/cores to launch each comms session on.

`flux-run` (real name TBD) launches a Flux program.  It needs a task count as well as a map of which tasks launch on (and optionally are confined to) which resources.  Unlike srun where an internal scheduler selects the nodes and cores on which to launch each task, `flux-run` will need to have that task:resource mapping given to it.

`flux-submit` is by nature the input to a scheduler.  It conveys requests for resources - wherever they can be found.  `flux-submit` places jobs in a queue which don't go anywhere until a scheduler sees them, qualifies them, selects resources for them, and clears them to be run.

`flux-capacitor` is a specific scheduler designed for ats and uq style jobs.  It cracks open a command file and selects resources for each "job" in the file and invokes `flux-run` for each on the available resources it selects (or alternately leverages the current scheduler to do this).

I don't see a need to standardize on the same protocol for `flux-submit` and `flux-start`, nor do I see a need for the `-H` flag.  `flux-submit`'s arguments will be a resource request (with optional task info provided, based on all the details we're discussing in [Issue 354](https://github.com/flux-framework/flux-core/issues/354)) while flux-start's arguments will be something equivalent to: rank0:node57/core0, rank1:node58/core0, ... [command]

In my mind, parent/child scheduling works like this:

`flux-submit -r <resources> [command]` submits a "job" to the scheduler.  The scheduler selects the resources and assigns them to the job record in the kvs and earmarks that job as ready to launch.  A comms-session-launching service sees the ready job and launches the equivalent of `flux-start [command|shell]` on the specified resources.

The child job now runs the command|shell on rank 0 and it may instantiate its own scheduler which receives new `flux-submit` commands from the remainder of the command(script) or from the user's interaction with the shell.

To complete the picture... when the user's job requests a shell, and their job runs and the shell appears, the user doesn't have to launch a scheduler or run `flux-submit`.  They can invoke `flux-run` across any of the resources within their instance, as long as they provide `flux-run` with a task:resource mapping.  Or, said user running is said shell, can launch `flux-start [command]` on any or all of the resources within their instance.

**Comment by grondo** [comment]
Thanks @lipari!

Two points:

 1. Your summary above seems to assume that every `flux-submit` is a hierarchical job request. I don't think this is the case, nor could it be, since how would you queue programs other than flux instances to a scheduler?

2. One big difference between our runtime and other resource manager is that `flux-run` or any other front end command is not necessary to run a parallel program. Conceptually, the parallel program is transmitted to the instance along with a request for resources and when the scheduler allocates resources the program can be started directly. Therefore the old way of "running a command or batch script on rank0 of the job" is no longer necessary or desired.

**Comment by lipari** [comment]
@grondo, thanks for the input.  I did not mean to imply that `flux-submit` was only for hierarchical jobs.  It can indeed queue programs other than flux instances.

As to `flux-run`, I can see that I mis-characterized it.  What I meant was, "the thing that initiates a flux program", or "the thing that will replace flux-wreckrun".

I still see a need for a script however, to support all the batch scripts that currently run multiple job steps.  Perhaps each `srun` line in those scripts will be replaced by a `flux submit` equivalent, but for the short term anyway, we're still going to need to support batch scripts.

Even long term, user's are still going to describe their workload as a collection of program invocations, and I expect they will use a script to capture and convey these instructions.

**Comment by grondo** [comment]
@lipari -- yeah, good points all.

My comment was directed at this description:
> `flux-submit -r <resources> [command]` submits a "job" to the scheduler. The scheduler selects the resources and assigns them to the job record in the kvs and earmarks that job as ready to launch. A comms-session-launching service sees the ready job and launches the equivalent of `flux-start [command|shell]` on the specified resources.

Reading this in combination with your clarifying comment above, did you mean "When `flux-submit` is used to create a child instance..."?

Going back to terminology from [rfc  8](https://github.com/flux-framework/rfc/blob/master/spec_8.adoc) `flux submit` submits a *program* for scheduled execution then exits. The program may or may not be a new instance.

Here we're kind of just talking about the UI for differentiating whether to submit a new instance and its initial program, vs a more typical parallel program (MPI job or other non instance).

For now `flux-start` is the thing that constructs a instance-as-program, so as @trws pointed out the low cost approach for now would be to have an option for flux-start to use `flux-submit` instead of `flux-wreckrun` when requested (or directly use wreck lua module).

Later, or here in this issue, we could decide what the most intuitive user interface for this is long term. It might make sense that, at high-level parent jobs, all resource/job requests are translated into instances + program, especially if the request includes an old style batch script, I can definitely see that would make users more comfortable.

Maybe long-term this should be something optional, perhaps enabled by job creation filters we've been talking about. (Just throwing ideas around now)

**Comment by garlick** [comment]
Yeah it does seem like we just need to decide what UI makes sense for users.

The batch script is analogous to the initial program in an instance - is that viable when someone submits one to simply create an instance and run the script as the initial program?

One point I did want to add:  `flux-start` has an actual job to do when launching directly on a single node, but when launching via slurm/flux, it's just a wrapper that creates a single command line and executes it.  The arguments to the broker are practically non-existent since it bootstraps with PMI, so all we are doing is hardwiring srun/wreckrun options.  That seems at best pointless, and at worst confining.  Thus having `flux-start` grow a `flux-submit` method seems backwards to me.  `flux-submit` could more easily learn how to start an instance directly, since it already knows how to start programs.

**Comment by lipari** [comment]
@grondo, thanks for the clarification.  That certainly helps align my thinking.

I'm still lobbying to inexorably pair `flux-submit` with a scheduler, such that if there is no active scheduler, `flux-submit` is an invalid command.  The fact that they're both in flux-sched reinforces this bond.

For simplicity, I would also lobby to design `flux-submit` to handle any request, be it to launch an instance + program or just a program within a current instance.  In both cases, the scheduler needs to translate a description for required resources into the actual resources for running the program.  Once that is done, the flux system takes care of the actual launching on the specified resources.

I view `flux start` as the means to launch an instance + program when no scheduler is running.  Similarly, within an instance `flux TBD` would be used to run a program within an active instance.  But since no scheduler has identified the resources, both `flux start` and `flux TBD` need to specify exactly which resources from the enclosing instance to launch on.

Anyway, that's the way that I think makes most intuitive sense (albeit to me).

**Comment by grondo** [comment]
@lipari, @garlick seems like you are on the same page. Like we said before `flux submit` is probably the preferred method for submitting an instance to the scheduler.

> I'm still lobbying to inexorably pair flux-submit with a scheduler, such that if there is no active scheduler, flux-submit is an invalid command. The fact that they're both in flux-sched reinforces this bond.

This seems reasonable.

> One point I did want to add: flux-start has an actual job to do when launching directly on a single node, but when launching via slurm/flux, it's just a wrapper that creates a single command line and executes it. The arguments to the broker are practically non-existent since it bootstraps with PMI, so all we are doing is hardwiring srun/wreckrun options. That seems at best pointless, and at worst confining. Thus having flux-start grow a flux-submit method seems backwards to me. flux-submit could more easily learn how to start an instance directly, since it already knows how to start programs.

Ok, that actually makes the preferable option easy.
For now, it seems like you could even just do:
```
flux submit src/broker/flux-broker --pmi-boot --command="inital_program"
```

Alternately, a wrapper script `instance.sh` that has something like
```
#!/bin/sh
${FLUX_BROKER_PATH} --pmi-boot "$@"
```
and
```
flux submit instance.sh inital_program
```

Or an option for `flux submit` could do the same
```
flux submit --instance initial_program
```

Sorry @garlick, forgot about the PMI boot thing and was thinking more work was done by `flux start` in this case!

**Comment by trws** [comment]
While I may be converted, I am opposed to having submit tied to, at least a particular instance of, a scheduler. If no scheduler is available, I would be fine with submit either devolving into a backgrounded run, failing if resources are not immediately available, or any number of things, but having it just not be there feels unnecessarily inconsistent. On that topic, submit should be moved either now or when flux core grows a basic scheduler of its own.  Either that or when we figure out our generic run interface it could just be an asynchronous flag on run, that being the only actual difference between the two.

As to the rest, I too forgot that it was that straightforward, sounds like just a little wrapper or flag is the way to go.



Sent with Good (www.good.com)

________________________________

**Comment by grondo** [comment]
@trws, I agree with you but didn't take @lipari's comment to mean submit wouldn't be available at all without a scheduler. It probably should fail if there is no scheduler system loaded instead of submitting jobs that never run.

I also agree that `submit` is just an asynchronous run, and everything else is the same (except `submit` sets a flag that says to run async, while `run` stays "attached"). We should revisit this when we actually have a job creation service (with submit filters, feasibility checks, etc), however I would caution that we tried initially with slurm to make everything one command and in the end had to split srun into srun, sbatch, salloc. I think from a usability perspective that is where we'll likely end up (but I'm not saying it *must* be that way)

Likely we'll want to have an API which job submission tools can easily be built from (without duplicate and divergent code)

**Comment by grondo** [comment]
I also agree we'll have to pull a version of `submit` into `flux-core`. We'll want a standard interface for submitting jobs to any scheduler used with `flux` -- not a version of `flux-submit` per scheduler project.

I suggest this can possibly occur along with #338...

**Comment by lipari** [comment]
There is no problem creating a generic `flux submit` and housing it in flux-core.  However, I don't see it doing anything other than entering a job into the KVS where it will lay dormant until a scheduler is loaded.

A fundamental characteristic of `flux submit` is that it specifies a resource request, not actual resources (ignoring for the moment a rarely used option where the exact resource *is* specified).  It takes a scheduler to discover *which* resources to provide to satisfy that request.  If a scheduler is not active, there is nothing to associate a request for 4 cores on a node to node57:core[0-3].  And if you already know you want to launch your instance on node57:core[0-3], then that is what `flux start` is for.

Also, with all the complexities available in our RDL and all the complexities supported in requesting those resources as evidenced in [Issue 354](https://github.com/flux-framework/flux-core/issues/354), I would content that a 'basic' scheduler for flux-core looks a lot like flux-sched/sched does now.

Lastly, I think that the decision to separate srun into sbatch, salloc, and srun was a giant leap toward usability, simplicity and understandability for the user.

**Comment by trws** [comment]
Implementing resource queries is the job of a resource service, not a scheduler.  The scheduler determines which resources of those available should be provided.

Either way, if there is always some kind of scheduler available, it may not be a problem, but I would compare the argument that submit should just silently fail to be equivalent to saying sbatch should silently ignore your request if you try to run it.  At least in my mind either it should fail and provide an error, or it should work.  Failing silently is the worst possible outcome, right up there with users being able to submit jobs that can never run.

**Comment by garlick** [comment]
I think this discussion fizzled out, and I'm not sure there is anything here that needs to remain open as an issue.  Closing (tentatively)
