### ISSUE TITLE
A mechanism to gracefully shut down a Flux instance

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#3895]
One of LLNL major workflow teams runs instances with `[s|js]run ... flux start sleep inf` one on Lassen for ML and the other on Ruby for simulations. And then uses a domain specific workflow adapter to submit workflow jobs dynamically into those instances for their producer-consumer workflow. 

They are currently looking for a good way to gracefully shut down flux when all molecules are processed. Without this, this workflow can lead to some idling of resources. 

I gave them the following scripts for now. But this is a kludge at best and it seems a flux shutdown command can go a long way for them to do this in a portable way.

```bash
#! /bin/bash
#set -x

declare -r prog=${0##*/}

die() { echo -e "${prog}:" "$@"; exit 1; }

if [[ $# -ne 1 ]]
then
    echo "Usage: kill_gracefully JOBID"
    exit 1
fi

if [[ ${SYS_TYPE} = "blueos_3_ppc64le_ib_p9" ]]
then
    output=$(/usr/tcetmp/bin/attach-helper $1)
    if [[ $? -ne 0 ]]
    then
        die "attach-helper failed: wrong JOBID?"
    fi

    head_node=$(echo ${output} | awk -F ":" '{print $1}')
    launcher_pid=$(echo ${output} | awk -F ":" '{print $2}')
    ssh ${head_node} "kill ${launcher_pid}"
elif [[ ${SYS_TYPE} = "toss_3_x86_64_ib" ]]
then
    squeue -j $1 -tr -o "%.7i %B" > /dev/null
    if [[ $? -ne 0 ]]
    then
        die "squeue report failed: wrong JOBID?"
    fi
    output=$(squeue -j $1 -tr -o "%.7i %B" | tail -n1)
    head_node=$(echo ${output} | awk '{print $2}')
    sleep_pid=$(rsh ${head_node} pgrep sleep)
    rsh ${head_node} kill ${sleep_pid}
else
    die "unsupported SYS_TYPE"
fi
```

**Comment by garlick** [comment]
That's a good idea.  The current way for a sys admin to shut down the system instance is to tell systemd to stop the rank 0 broker, which may be less obvious than a nice imperative command, particularly since the effect of doing it on a rank > 0 is to shutdown just the subtree rooted at that rank, which people might find counterintuitive?

Just in case it is more usable than the current method, you _could_ launch the instance with `-o,-Sbroker.rc2_none` instead of the `sleep inf`, then arrange to send a SIGTERM to the rank 0 broker when you want to shut down, like the system instance.

In fact, the instance should still shut down cleanly if all the brokers get a SIGTERM simultaneously, so you could use the tools from the RM that launched flux to send it (like `scancel --signal=TERM <jobid>`).  My only concern about doing it that way would be making sure that the RM doesn't SIGKILL the brokers if it is taking too long stopping jobs or writing out its content cache to disk.

**Comment by dongahn** [comment]
This is great info @garlick. In fact, if this team can make use of use `-o,-Sbroker.rc2_none`, this seems ideal. 

There is one more implication, though.

An addition reason that this team needs a graceful shutdown is because we need to get the [PerfFlowAspect](https://github.com/flux-framework/PerfFlowAspect) traces to be dumped on shutdown. (For debugger support, I used to call it "kill support" :-)

But somehow on SLURM, sending `SIGTERM` to the controlling `srun` doesn't cause its flux to have a chance to dump it. There could be how flux handles this signal affecting this [destructor](https://github.com/flux-framework/PerfFlowAspect/blob/main/src/c/runtime/advice_chrome_tracing.cpp#L361) being called... What does broker do when receiving `TERM`?

**Comment by garlick** [comment]
> What does broker do when receiving TERM?

The broker traps SIGTERM and a number of other signals [here](https://github.com/flux-framework/flux-core/blob/c87339a3cceef7cf7cca67d88784ee8a9605c150/src/broker/broker.c#L951).  It does this using libev's signal handling capability, so that we don't directly implement the signal handler, but register a reactor callback instead.  The reactor callback triggers the state machine to initiate shutdown, which  ultimately leads to an `exit(3)` call.

**Comment by SteVwonder** [comment]
Related conversation about `flux stop` over in #1951

**Comment by grondo** [comment]
If SIGTERM works, then that is pretty nice. If we don't want or need to implement that service-based shutdown, then perhaps an initial `flux shutdown` command could be something as simple as a wrapper for
```sh
kill $(flux getattr broker.pid)
```
or
```sh
flux exec -r 0 kill $(flux getattr broker.pid)
```
However, either way, requiring users to run with `-o,-Sbroker.rc2_none` is a little awkward. Maybe we can think about a way to expose the setting of some of these broker attributes in a more convenient form.

The parallel is that we have a way to set generic jobspec attributes with `flux-mini`, but we don't require that users set _everything_ using this option, e.g. `flux mini run --setattr=system.shell.options.foo=1`. Since `flux-start` knows it is running the broker, maybe we could even add a `--setattr, -S` option to flux-start as well?

But for this case maybe a specific option for `-o,-Sbroker.rc2_none`, like `-n, --no-rc2` or something?
