### ISSUE TITLE
Python 3.6 EOL

### ISSUE THREAD

**Issue by jameshcorbett** [flux-framework/flux-core#3929]
Python 3.6 is [scheduled to be deprecated in a month](https://devguide.python.org/#status-of-python-branches) so it might be a good idea to move to 3.7+.

In my fluxrm:centos8 container it seemed that there were no 3.7 packages available, although there were for 3.8 and 3.9.

LC's default ``python3`` is 3.7, although 3.8 is available via ``module load python-3.8`` or just ``python3-3.8.2``.

As far as I know moving to 3.7+ would require changes to the readme, ``configure.ac``, and to some of the Dockerfiles.

**Comment by garlick** [comment]
As far as I can tell there are no python versions newer than 3.6 available through [EPEL](https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/p/).  Since we are building flux RPMS on the TOSS 3 build farm where all the dependencies have to be provided by RPMs I think we are stuck with 3.6 as the minimum for now.

**Comment by dongahn** [comment]
I cannot find a ticket with python version agnostic request. @davidbloss said today that he would be interested in this topic and offer some expertise. I'm tagging him here. If we find a better ticket, we can move our discussion to there.

**Comment by garlick** [comment]
This issue is about raising the minimum python version required by flux-core at configure time.  In fact, there's not a lot we can do about this due to the above constraint, so this issue should probably be closed.

I'll go ahead and do that.   @dongahn or @davidbloss, would you mind opening new issues for the problems you are facing today?  Just start with the initial complaint, e.g. "can't build flux-core on TOSS4 in /usr/tce environment" + cut and paste of any useful  error output, etc)

**Comment by vsoch** [comment]
booo
