### ISSUE TITLE
Flux instance shutdown 

### ISSUE THREAD

**Issue by surajpkn** [flux-framework/flux-core#395]
I want to be able to initiate a shutdown of a flux instance from within the scheduler service running at rank 0. I figured out that there is a shutdown event and a callback for it. Can I send that message from the scheduler and expect a shutdown of all the brokers associated with a flux instance?

**Comment by garlick** [comment]
That will work more or less.  You can try it on the command line like this:
```
flux event pub shutdown '{"reason":"testing...", "grace":1.0, "rank":0, "exitcode":0}'
```
The design was for the initial program to exit, and for the broker to then initiate shutdown, not for other parties to initiate the shutdown.  One result of this is that there is no mechanism to try to terminate the initial program if the shutdown is initiated elsewhere.

Maybe we should amend the design, but first probably it would be good to discuss why the scheduler should be initiating shutdown of the instance.

**Comment by surajpkn** [comment]
The idea is the following. A child flux instance is started by a parent for the purpose of executing a hierarchical job (let's say an aggregation of jobs). Only the child flux scheduler can notice that all the jobs in its queue are complete, and therefore must be able initiate a shutdown.

**Comment by garlick** [comment]
Could perhaps the initial program fill an executive role here, accepting work from parent (however that is done), submitting the work, blocking until it is complete, then exiting?

**Comment by surajpkn** [comment]
If my understanding about "initial_program" is right, the initial program of that is a shell? And you are suggesting that instead of running jobs with wrexec, use a shell script to derive jobs and run them?

**Comment by lipari** [comment]
@surajpkn, A design goal of mine is to minimize the duties of the scheduler.  Hence, I've relegated things like setting job priority to an external agent.  I would also like to get the scheduler out of the business of managing its jobs, once they have been scheduled.  The jobs will have a time limit and I am hoping we create some external mechanism for terminating a flux program/instance once its time limit is reached.
I propose for the scenario above that the child flux scheduler terminate itself when the conditions you describe are met - in this case all jobs have completed + there are no pending jobs remaining in the queue + (some grace time has elapsed).
Now I realize you are counting on a parent scheduler negotiating resource add/remove requests with child jobs, so most of what I've said is a starting goal of keeping it as simple as possible.

**Comment by garlick** [comment]
The initial program is conceptually anything you want.  Think of it like UNIX init(8).

I wasn't suggesting a method of submitting jobs other than via wrexec.  That is the only way we have right now.

Your initial program _could_ be a shell script, say one that calls a new utility to get jobs from parent, then `flux-submit` on them, and another to block until the work is complete.  Or it could be all of that rolled into a C, lua, or python program.

**Comment by dongahn** [comment]
It seems clear we need some child component that should monitor all of the sub-jobs scheduled and running as part of the child flux instance and to make sure to initiate a shutdown when done. 

@garlick's proposal is good if the initial program can monitor the status of these jobs and block wait until all of them get "complete" status, in fact this can be easily done as an extension to `flux-waitjob` utility i recently wrote (flux-sched). 

IMHO, it is not a bad idea to have this kind of all-job-done logic directly in the scheduler framework service either. This is because we will utilize an flux instance as this kind of "off-line mode" or "push model" for many use cases. So building support like this into the framework seems benefit many use cases without other additional tricks, going forward. 

I think this can be also easily done -- even having a job-count and complete-job-count in its scheduler framework service context, which get incremented on "J_RUNNING -> J_COMPLETE" transition. When job-count == complete-job-count, a shutdown action is initiated.

**Comment by surajpkn** [comment]
> The jobs will have a time limit and I am hoping we create some external mechanism for terminating a flux program/instance once its time limit is reached.
I propose for the scenario above that the child flux scheduler terminate itself when the conditions you describe are met - in this case all jobs have completed + there are no pending jobs remaining in the queue + (some grace time has elapsed).

This is one of the easiest methods and i could actually use this for my purposes. Although with the current capabilities, this would leave the brokers alive (as there is no mechanism to kill them at walltime), for my simulation purposes, I would be using only one broker for each flux instance. I think their staying alive will not really affect anything. However, I in production, there is a chance that this leads to a flux instance (with large number of brokers) being alive without a scheduler for a long time, especially when the walltimes are bad. 

@garlick's suggestion is also something I can use for now. 
But in general, a parent could pass on more jobs to a child flux (online scheduling and online aggregation). That means the initial_program should also keep listening to new jobs arriving and ends up being a mini scheduler (for a lack of better term) and lead to race conditions.

**Comment by garlick** [comment]
> But in general, a parent could pass on more jobs to a child flux (online scheduling and online aggregation). That means the initial_program should also keep listening to new jobs arriving and ends up being a mini scheduler (for a lack of better term) and lead to race conditions.

Perhaps that's the difference between an initial program that submits a bunch of jobs to its own instance then exits when they are complete (like capacitor) or an initial program that accepts job requests on a socket and exits when both the socket has been closed by the other end _and_ the work has completed.

The scheduler in the child instance is the same as the one in the parent right?  How would that lead to races?  Or were you thinking that the scheduler in the parent would be launching work directly in the child?

**Comment by surajpkn** [comment]
An online job addition protocol would be: parent sched sends a job to child sched. Child sched accpets/acknowledges it and adds that job to its queue. I was thinking of the case where an initial program, a jobs watcher, could exit when seeing that all jobs are complete while the child sched just acknowledged/accepted a job from parent. 
But yes, this can be avoided by making the initial program do an exit only after the sched module itself exits so that there are no inconsistencies.

**Comment by garlick** [comment]
OK.  I was suggesting doing all of that in the initial program (or its subprograms), allowing the scheduler to be oblivious to the fact that it's taking work from the enclosing instance.

**Comment by surajpkn** [comment]
That means a new communication mechanism between a parent and the initial program of a child flux instance. Since the parent pushes jobs down, it should be able to initiate and directly talk to the initial program of child flux instance. Layers before the leaves will be passing jobs from parent sched to child sched, but the parent just above the leaf alone must send it to the initial program rather than the child sched. IMHO, its not a very natural flow. 

For my purposes, I will not do any of these. But in the long run, as scheduling logic and methods grow, parent sched - child sched interaction for pushing and pulling jobs could play a large role. You may want to keep an instance alive even if there are no jobs in it for pushing jobs as they arrive for some specific purposes (may be similar to advanced reservations for certain aggregations). If such scheduling methods are used, then an instance would probably need to die only at the order of the parent (which would indeed be a result of a scheduling/aggregation decision). Perhaps most of this can also be achieved by expanding the initial program of an instance to handle all these functionality. But may end up as double implementation, and like @dongahn mentioned, sort of "tricks" approach.

My vote is for the scheduler to be able to initiate a shutdown. That can be a result of anything - a scheduling decision, completion of all the jobs, time limit, order from parent etc. IMHO this will blend with scheduling techniques (as they grow with features) very well.

**Comment by grondo** [comment]
I am still not entirely sure I fully understand this use case. However, it does seem like a special case (child instances started fully under control of the enclosing instance, instead of started on behalf of user request for resources).

Instead of writing a unique scheduler for this case, use of a purpose built initial program has merits in that you could load any scheduler implementation to schedule the work instead of relying on a scheduler built with direct parent-child communication path. So, while admitting I may be wrong for this case, the initial program approach does seem to be the more generic approach (I don't really understand the reference to "tricks" sorry)

This kind of initial program will also be required for a parent-less instance running on a cluster for example, to which external jobs are submitted, perhaps from login nodes of a cluster or users' desktops. This program could support a more universal API (e.g. REST over HTTP) and accept other auth methods easily (krb5), and could therefore support an authorized shutdown request.

Since we'll likely have to build something like this anyway for real-world usage, it would seem that having a second path, only for parent-child scheduler-specific communication might be duplicating effort. Why not use a similar service for this research?

For now, if you really want to support shutdown from any entity in a session, you could run an initial program that blocks until a shutdown event is received. This is a kind of bare services initial program (only takes shutdown event), but could be expanded to accept other requests

```lua
#!/usr/bin/lua
local f,err = require 'flux'.new ()

if not f then error (err) end

local rc, err = f:subscribe ('program.shutdown')
if not rc then error (err) end

local msg, tag = f:recv_event ()
if msg and msg.exit_code then
    os.exit (msg.exit_code)
end
os.exit (0)
```

**Comment by surajpkn** [comment]
@grondo for my current work actually, I will simply use an initial program that exits after jobs are done like @garlick mentioned. That suffices my purposes. Other than that, my idea was only to brainstorm some future scheduling problems/cases that would be of interest in flux and is relevant in this context, which you may want to consider for the final design.

**Comment by grondo** [comment]
Yes, I thought those were good discussion points, thanks!

**Comment by trws** [comment]
> Perhaps that's the difference between an initial program that submits a bunch of jobs to its own instance then exits when they are complete (like capacitor) or an initial program that accepts job requests on a socket and exits when both the socket has been closed by the other end and the work has completed.

On a quick side-note, capacitor actually reads its commands in the current job collector from an arbitrary number of file-like objects until they all return EOF.  If you give it a socket as a command file, it will take commands on that until you close the socket.  Then it will stick around until all of the jobs so submitted are complete.  If another interface would be helpful with that let me know, but something like `mkfifo stuff; produce_commands > stuff & ; flux start flux capacitor -c stuff` should be enough to at least get it to minimum-working.

**Comment by grondo** [comment]
Closing. See #1951
