### ISSUE TITLE
`flux mini bulksubmit` hangs?

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#3952]
Was doing some demos today, and when I tried to run `flux mini bulksubmit` off the cuff (first mistake) in a docker container running in WSL2 (second mistake), it hung indefinitely.  A simple reproducer:

```
❯ docker run -ti fluxrm/flux-core:latest flux mini bulksubmit --progress --wait --cc 1-10 hostname
```

I think I'm probably just using it wrong (I vaguely remember something about it reading from stdin, so maybe it is blocked on that?), but I thought I'd open an issue just in case.

**Comment by garlick** [comment]
Right, it reads stdin by default, one line per job, e.g.
```
seq 1 3 | flux mini bulksubmit hostname
```
or equivalently I think
```
flux mini bulksubmit hostname ::: 1 2 3
```

Usage is similar to gnu parallel.

**Comment by grondo** [comment]
FYI - That command line would work with `flux mini submit`...

**Comment by grondo** [comment]
Sorry, that was unhelpful. I meant that in the original command from this issue:

`docker run -ti fluxrm/flux-core:latest flux mini bulksubmit --progress --wait --cc 1-10 hostname`

You could just use `flux mini submit`:

```
$ docker run -ti fluxrm/flux-core:latest flux mi submit --progress --wait --cc 1-10 hostname
flux-mini: ERROR: [Errno 2] Unable to connect to Flux
PD:0 R:0 CD:0 F:0 │ │ 0.0% 0:00:01
```

Hm, except the default docker container doesn't run `flux start` by default I guess, maybe add `flux start` too:

```
$ docker run -ti fluxrm/flux-core:latest flux start flux mini submit --progress --wait --cc 1-10 hostname
ƒMrktxP
ƒMtEtEj
ƒMtEtEk
ƒMtEtEm
ƒMuisX5
ƒMuisX6
ƒMuisX7
ƒMwCroR
ƒMwCroS
ƒMxgr5m
PD:0 R:0 CD:10 F:0 │██████████████████████████████████████████│100.0% 0:00:00
```

The `--watch` option (which implies `--wait`) is also useful since it will also show output from all jobs.

The `--cc=idset` option can be used with `bulksubmit` but this submits size(idset) copies of each job expanded from the inputs.

```
$ flux mini bulksubmit --watch --progress --cc=1-3 echo {} ::: 1 2 3
ƒ4r8KHoyR
ƒ4r8KHoyS
ƒ4r8KHoyT
ƒ4r8LmoFm
ƒ4r8LmoFn
ƒ4r8NFnY7
ƒ4r8NFnY8
ƒ4r8NFnY9
ƒ4r8PjmpT
1
2
1
1
2
2
3
3
3
PD:0 R:0 CD:9 F:0 │██████████████████████████████████████████████│100.0% 0:00:01
```

The `--dry-run` option can be useful with `bulksubmit` since it will print what would have been submitted without submitting any jobs (though I just noticed it doesn't work with `--cc`, I'll have to open an issue):

```
$ flux mini bulksubmit --dry-run echo {} {1} ::: 1 2 ::: 3 4
flux-mini: submit echo 1 3
flux-mini: submit echo 1 4
flux-mini: submit echo 2 3
flux-mini: submit echo 2 4
```

**Comment by grondo** [comment]
I've proposed a new FAQ entry for this one in https://github.com/flux-framework/flux-docs/pull/117

**Comment by SteVwonder** [comment]
Thanks!
