### ISSUE TITLE
improve job-exec host unreachable errors

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#3960]
Problem: when a broker becomes disconnected from the overlay network, `job-exec` may print "host unreachable" errors without calling out the broker rank or hostname.

Example [here](https://github.com/flux-framework/flux-core/blob/34f894d4ae471fb0295080f6dd4760748b48c836/src/modules/job-exec/exec.c#L306).

That specific error was  noted when reviewing broker logs from a failed AHA Moles dedicated application time run, but we could probably do a little audit of job-exec and see if there are other places where error messages could be made more useful.

Bonus points if we can include both the hostname and the broker rank, since correlating these logs with other system failures is easier with the hostname.

**Comment by grondo** [comment]
Just a note: there may be diminishing returns fixing the current job-exec implementation, though this improvement seems easy enough.

> Bonus points if we can include both the hostname and the broker rank, since correlating these logs with other system failures is easier with the hostname.

Including this kind of thing in general will require that all modules and services in Flux be made aware of hostname/rank mapping for the instance.

Would it be better to detect these failures at a lower level, and call out the hostname/rank once at that level, then correlating rank-specific module/service failures back to the originally reported failing rank?

**Comment by garlick** [comment]
> Would it be better to detect these failures at a lower level, and call out the hostname/rank once at that level, then correlating rank-specific module/service failures back to the originally reported failing rank?

We should certainly log the problem at the lower level IMHO.

Given the diminishing returns you noted, I agree that we shouldn't invest in a huge change here, but if it's relatively simple to provide more context in the error message, it may help in a post mortem to be able to classify that error as fallout from the lower level one and not something else that has to be run down.

**Comment by grondo** [comment]
> but if it's relatively simple to provide more context in the error message, it may help in a post mortem to be able to classify that error as fallout from the lower level one and not something else that has to be run down.

Agreed. I was mainly arguing against requirement to include the _hostname_ as well as rank at these higher levels, which would require hostname to rank mapping be kept within every module that might report these errors, and if the hostname is reported at a lower level this extra state and effort might be considered wasteful.

Reporting the rank in error messages like this will currently require that the target rank of the RPC be stashed in the future as an aux_item. I wonder if we could extend the `flux_rpc_t` API to add a getter for the target rank, so that the boilerplate of stashing an integer in a `flux_future_t` could be avoided, making it easy and idiomatic to report the target rank for failed RPCs?

**Comment by garlick** [comment]
> I wonder if we could extend the flux_rpc_t API to add a getter for the target rank, so that the boilerplate of stashing an integer in a flux_future_t could be avoided, making it easy and idiomatic to report the target rank for failed RPCs?

That seems like a good idea.  I've been tempted in the past to stash a ref to the request message in the RPC.  If we did that then we could provide an accessor  for this and later, for other RPC parameters if needed.

**Comment by grondo** [comment]
>  I've been tempted in the past to stash a ref to the request message in the RPC. If we did that then we could provide an accessor for this and later, for other RPC parameters if needed.

Yeah, that seems like the right way to do it. I was already poking in there, so I can give it a try and the job-exec module can be the first user.

**Comment by grondo** [comment]
If we use the `nodeid` from the request, it appears that for `flux_rpc(3)` to `FLUX_NODEID_UPSTREAM`, `flux_rpc_get_nodeid()` would always return the current rank due to this code:
```c
    if (nodeid == FLUX_NODEID_UPSTREAM) {
        msgflags |= FLUX_MSGFLAG_UPSTREAM;
        if (flux_get_rank (h, &nodeid) < 0)
            goto error;
    }
```

Not an issue here, but I could see that being confusing. It also appears that for responses, since the routes are popped off as the response returns to the sender, there is no way to determine the actual rank that sent the error response.

This will work for the job-exec module which currently sends its requests to specific ranks, but not for more generic upstream requests. I wonder if that should just be documented in the interface?

**Comment by garlick** [comment]
Maybe the rank accessor should return FLUX_NODEID_UPSTREAM if FLUX_MSGFLAG_UPSTREAM is set?  Then we could document that FLUX_NODEID_ANY or FLUX_NODEID_UPSTREAM are possible return values.

If we do the mustache template for logging, the two special nodeid values could be special cased.

**Comment by grondo** [comment]
Also, `flux_msg_get_nodeid(3)` returns `EPROTO` for `FLUX_MSGTYPE_REQUEST`:
```c
int flux_msg_get_nodeid (const flux_msg_t *msg, uint32_t *nodeidp)
{
    if (!msg || !nodeidp) {
        errno = EINVAL;
        return -1;
    }
    if (msg->type != FLUX_MSGTYPE_REQUEST) {
        errno = EPROTO;
        return -1;
    }
    *nodeidp = msg->nodeid;
    return 0;
}
```

Maybe the right thing to do for now is to add a `nodeid` member to the rpc struct, set it to the target `nodeid` (maybe optionally updating to the `nodeid` set in the response when available if that has any value)

**Comment by garlick** [comment]
I think you mean it returns EPROTO for type != FLUX_MSGTYPE_REQUEST?

**Comment by grondo** [comment]
> I think you mean it returns EPROTO for type != FLUX_MSGTYPE_REQUEST?

Ugh, sorry, yes I read that backwards, so please ignore my comment above.
