### ISSUE TITLE
provide mechansim to log broker hostnames

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#3961]
Problem: brokers usually log errors with the broker rank, but hostnames would be useful when "bad nodes" need to be tracked down.

As noted in #3959, #3960, and #3897, a bad node can ruin your whole flux instance, and when that happens, it's useful to know the culprit.  We do have `flux overlay gethostbyrank`, but that's not very convenient and it's not available when looking at logs post mortem.

We have `config.hostlist` broker attribute, and a nodelist in `resource.R` which `flux overlay gethostbyrank` falls back to if not a system instance.  It may be helpful if we standardized a single broker attribute name for the hostlist (maybe `hostlist`) and had resource fill it in if not already set.   Code that needs to log hostnames could fetch this attribute and then hold the cached mapping.

A complication is that a dynamically discovered `resource.R` doesn't show up until QUORUM is reached, so it would not be useful for pre-QUORUM errors (like in #3959) when launched by slurm.  Maybe the SLURM_JOB_NODELIST environment variable could be used as the initial value of the hostlist if available.

Finally, rather than require every module that needs the hostlist to fetch this attribute, I wonder if we could find a way to map ranks to hostnames automatically in `flux_log()` if a special token is logged like `@gethostbyrank:RANK@` or `@gethostsbyranks:IDSET@`?

Edit: RANK is just a degenerate IDSET so second token not needed!

**Comment by grondo** [comment]
> Finally, rather than require every module that needs the hostlist to fetch this attribute, I wonder if we could find a way to map ranks to hostnames automatically in flux_log() if a special token is logged like @gethostbyrank:RANK@ or @gethostsbyranks:IDSET@?

This is a great idea and I was having a similar thought. I wonder if we can use [mustache(5)](https://mustache.github.io/mustache.5.html) templates for this. Then we could, perhaps, add other template substitutions in the logs (though I can't think of what that would be at the moment).

Unfortunately, I think the mustache template to render a "callable" would be a little more verbose, e.g.
```
{{#gethostsbyranks}}IDSET{{/gethostsbyranks}}
```
and currently our simplistic mustache template implementation doesn't support "sections". But it would be nice to use one templating system in Flux instead of multiple...

**Comment by garlick** [comment]
Although mustache templates might still be a cool thing to do, the main problem of this issue was solved by #3966 and #3971, so closing.
