### ISSUE TITLE
Unknown endian issue on ubuntu 20.04 baremetal 

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#4002]
On my baremetal x86 ubuntu 20.04 with all the packages listed in README.md installed:

```console
Making all in libccan
make[3]: Entering directory '/home/dahn/workspace/fluxdev_baremetal/flux-core/src/common/libccan'
  CC       ccan/str/str.lo
  CC       ccan/str/debug.lo
  CC       ccan/str/hex/hex.lo
  CC       ccan/list/list.lo
  CC       ccan/bitmap/bitmap.lo
In file included from ./ccan/bitmap/bitmap.h:10,
                 from ccan/bitmap/bitmap.c:5:
./ccan/endian/endian.h:112:2: error: #error "Unknown endian"
  112 | #error "Unknown endian"
      |  ^~~~~
```

I could resolve that by installing `build-essentials`

```
dahn@dahn-B450-AORUS-PRO-WIFI:~/workspace/fluxdev_baremetal/flux-core$ sudo apt install build-essential
```

**Comment by grondo** [comment]
`AC_C_BIGENDIAN` is a builtin macro in `autoconf` so I'm a little surprised it fails!

I guess we don't say you need a C compiler in our README, though it looks like you have that and `make`, so I wonder what package was missing? We probably shouldn't specify that `build-essential` is a requirement for flux-core, since it installs requirements for building `.deb` package, which we don't necessarily need.

**Comment by dongahn** [comment]
Yes this surprised me as well. I added `autotools-dev` and `build-essential`, which fixed the issue. I think it was the latter that fixed the issue, not the former. But I was moving pretty quickly so I could be mistaken.

**Comment by grondo** [comment]
`build-essential` is a meta-package which includes these other packages: `gcc`, `g++`, `libc6-dev`, `make` and `dpkg-dev`. Clearly, `gcc` and `make` were already present, so the missing package must have been `libc6-dev`.

We'll have to add that to our list of requirements I suppose.
