### ISSUE TITLE
shell: need a way to wait for namespace after reconnect

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#4018]
after reconnect to the broker as described in #3901, the job shell cannot immediately restart because the job-exec module may not have re-established namespaces, or might not have even started yet, since a reconnect could complete as soon as the broker loads the connector-local module.

Once `flux_reconnect()` or equivalent succeeds, the shell needs a way to synchronously wait until the job-exec module is loaded and at least the job's namespace has been re-established.

**Comment by garlick** [comment]
It looks like namespaces are restored by the exec module asynchronously, e.g. after the module load completes?

At first glance, it would seem like the shell could just do `flux_kvs_get()` with the WAITCREATE flag on a key in its namespace (like the guest eventlog) but this could fail because 1) the kvs modules might not be loaded, and 2) we have a mechanism on rank > 0 to reject RPCs that arrive before broker has wired up upstream (67bcb6c6897caa9b01d886157355ff3f36941966)

I wonder if we need a special RPC to wait until the local broker enters RUN state?  When it does, we know that rc1 has completed on the local broker and all upstream brokers.  We could special case this RPC to allow it through no. 2 above. 

So the shell would first do this special RPC, then do the KVS wait?

**Comment by grondo** [comment]
> So the shell would first do this special RPC, then do the KVS wait?

That sounds like a good approach to me!
