### ISSUE TITLE
idea: allow users to query "uptime" of enclosing instance

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#4033]
It is a small thing, but it might be of interest to be able to query the uptime of the current enclosing instance.

This came up in development of `flux pstree`, where we try to approximate a `JobInfo` for the current enclosing instance, even if that instance isn't technically a Flux job (otherwise we can query the `job-list` module of the parent)

One simple approach would be to add a `broker.starttime` or similar attribute, though that would track the last broker restart and not necessarily the uptime of something like a system instance, which may persist across many restarts (though perhaps the broker starttime is of interest in and of itself)

Another idea would be to fill in the starttime member of `R` whenever it is not already set when the resource module initializes from configuration or by gathering R from hwloc. Then, I think, users could get at this information by querying the resource list from the scheduler.

There's probably many other acceptable ways to do this as well.

**Comment by garlick** [comment]
Good idea.  Maybe we should have a simplistic `broker.starttime` attribute that just tracks an individual broker start time (with rank 0's acting as a kind of stand in for "instance (re-)start time"), AND fill in the starttime member of `resource.R` in the KVS so that we have an instance incept time that persists across a system instance restart?

(Actually I think `resource.R` gets overwritten on each rank 0 restart in the system instance, so we might need to add something to preserve an existing starttime in that case)
