### ISSUE TITLE
flux broker looking for incorrect TMPDIR

### ISSUE THREAD

**Issue by bhatiaharsh** [flux-framework/flux-core#4329]
**Summary.** on a multi-node flux instance, flux jobs fail when they are submitted from within another job. the failed jobs are picking incorrect `TMPDIR`. the picked path corresponds to the node that the job was ***submitted from***, rather than the path for the node it is ***submitted to***.

**Details.**
(1) after a successful 2-node launch, the `uri` for rank-0 node is `ssh://h50n09/tmp/flux-thQxwt/local-0`
(1b) I have verified that:  `rank0` node has path `/tmp/flux-thQxwt/` and `rank1` has path `/tmp/flux-gURv5q/`. 

(2) our workflow job is running on node rank-1 node -- all jobs that are scheduled on the same node are successful, but those that are put on rank 0 are all failing with the following error 
```
$ flux job attach fPyAofG3
X11 forwarding request failed on channel 0
0.373s: job.exception type=exec severity=0 error creating TMPDIR: No such file or directory
flux-job: task(s) exited with exit code 1
0.339s: flux-shell[0]: stderr: flux-shell: ERROR: tmpdir: mkdir /tmp/flux-gURv5q/jobtmp-0-fGdQ3utb: No such file or directory
0.339s: flux-shell[0]: stderr: flux-shell: FATAL: tmpdir: error creating TMPDIR: No such file or directory
0.339s: flux-shell[0]: ERROR: tmpdir: mkdir /tmp/flux-gURv5q/jobtmp-0-fGdQ3utb: No such file or directory
0.339s: flux-shell[0]: FATAL: tmpdir: error creating TMPDIR: No such file or directory
```

The job `fPyAofG3` above is running on rank-0 and submitted by rank-1. it is picking the `TMPPATH` for `rank1`

This is on `summit` with the following version of flux:
```
$ flux --version
commands:               0.31.0
libflux-core:           0.31.0
X11 forwarding request failed on channel 0
broker:                 0.31.0
FLUX_URI:               ssh://h50n09/tmp/flux-thQxwt/local-0
build-options:          +hwloc==2.5.0+zmq==4.3.4
```

**Comment by bhatiaharsh** [comment]
also related to: https://github.com/flux-framework/flux-core/issues/4328

**Comment by grondo** [comment]
Thanks @bhatiaharsh!

This can occur if a job is started without `TMPDIR` set, and that job is used to submit new jobs.

When `TMPDIR` is not already set, the job shell will set `TMPDIR` to `FLUX_JOB_TMPDIR`, which is a unique directory per node and job, and is typically under the local broker's `rundir`. If that job then submits another job, the `TMPDIR` is propagated to the new job. If that new job runs on a different node, then the path to `TMPDIR` doesn't exist (since it was under the node-specific broker `rundir`). When `TMPDIR` doesn't exist, the Flux job shell will try to create it, but it raises a fatal error if the `mkdir(2)` fails, which it does in this case since the parent directory does not exist. (i.e. #4238)

We can detect this condition in the job shell `tmpdir` plugin I think -- i.e. unset `TMPDIR` if it is already set to an existing `FLUX_JOB_TMPDIR`.
