### ISSUE TITLE
How to get the cluster's name?

### ISSUE THREAD

**Issue by lipari** [flux-framework/flux-core#442]
When populating resources using hwloc, we have no definitive means to derive the cluster's name other than to assume a name+id node name convention and peel away the id from one of the nodes to derive the name for for the cluster.

This practice has been deemed to be unreliable per this comment:  https://github.com/lipari/flux-sched/commit/c059dbfbd4afca619fef6fa6541a23099a15b0a0#commitcomment-13701281

Hence, I'm wondering whether the cluster name should be stored in the kvs or otherwise provided by flux core in some way.  The alternative that was proposed would would be to use a generic name like, "cluster".

**Comment by garlick** [comment]
Would it make sense to assume a cluster name like "default" or "hwloc" unless one is specifically configured via the RDL?

**Comment by grondo** [comment]
Is there a reason we even need a cluster name in this case? It seems like using hwloc is a special case and you should only have to capture as much hierarchy as you need. For instance if you're only running on one node and using hwloc, the root of the tree should be the Node. I suppose with multiple nodes or resources at the same level you do need some name for the composite, but I would suggest "default" like @garlick.

If RDL configuration is provided, then merging that with hwloc would be tricky, but I would think for now RDL would take precedence over hwloc (because it details the configured resources we care about), and therefore they do not need to be merged.

**Comment by lipari** [comment]
Ok, I'll close this issue.  I just pushed a mod to https://github.com/flux-framework/flux-sched/pull/79 that,when no RDL file is specified and resources are loaded from the kvs's resource.hwloc.xml.<n> entries, replaces the node-derived cluster name with a generic name.  I used @dongahn 's suggestion:  "cluster".
