### ISSUE TITLE
flux-jobs: document job status / result can report TIMEOUT

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#4498]
it would be useful if job resutls also showed jobs that timed out.

TBD: do we need a new color for timeouts in the job output display?  Could be the same color as CANCELED, as they are both in that group of jobs that are "indeterminate" to some extent.

**Comment by grondo** [comment]
What version of Flux are you using? It works for me
```
ƒ(s=1,d=0,builddir) grondo@asp:~/git/flux-core.git$ flux jobs -a
       JOBID USER     NAME       ST NTASKS NNODES  RUNTIME NODELIST
    ƒ75ZkCyD grondo   sleep      TO      1      1   0.505s asp
    ƒ32qXv8f grondo   hostname   CD      1      1   0.038s asp

```

**Comment by chu11** [comment]
ahhh, in that case the manpage just needs to be updated.  I assumed it hadn't been added.

**Comment by chu11** [comment]
and it appears the only `flux-jobs` timeout tests are in `t2900-job-timelimits`, we should probably add some to t2800 too.

**Comment by grondo** [comment]
Why? That doesn't seem necessary

**Comment by grondo** [comment]
Oh, I guess it does make sense for some of the tests that take jobs input on stdin. Sorry.

**Comment by chu11** [comment]
> Why? That doesn't seem necessary

As I was skimming t2800-job-cmds, I realized that the "permutations" of tests were never covered for a job that times out.  For example, a timed out job should output `{nodelist}` or  `{runtime}` similarly to a successful running job, but it should output things like `{exception.*}` similarly to a failed job.  That mixture wasn't covered.

**Comment by grondo** [comment]
Yeah, though I think we avoided that because that "permutation" is covered more explicitly in the timelimits specific tests (we don't want too much duplication in the testsuite, because this creates multiple places to update tests if and when things change). However, if it can be done without adding a 1sec delay to those tests I suppose it doesn't hurt too much. (I would actually be inclined to leave it alone for now)
