### ISSUE TITLE
overhaul flux config

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#452]
The current config system needs a rethink due to:
* oddball ZPL format, with no Flux RFC defining use of namespace
* no built-in mechanism to locate the current active config
* no mechanism for get/set of single values in the current active config (only bulk load/store)
* loading the entire config from the KVS requires RTT for each config key (slow)
* `flux` command driver has to load the config just to get paths; is there a way to avoid this?
* inheritance model for hierarchical jobs is not well defined
* source is awkwardly split between libkvs.so and libflux-core.so
* unit test is minimal

**Comment by grondo** [comment]
Good list! Thanks for putting this together.

> flux command driver has to load the config just to get paths; is there a way to avoid this?

Paths may have to be embedded in `flux.c`, optionally overridden by config?

The inheritance model for hierarchical jobs seems really important, but I'm having trouble wrapping my brain around that one. I'm hoping some careful discussion here will help.

**Comment by trws** [comment]
Embedded or using system defaults probably.  This is something I'm increasingly thinking is important, after both the issues in #588 and trying to address the default module list problem.  The latter is mainly coming up because the config must be loaded *after* modules are loaded right now, which makes life both peculiar and complicated.

Perhaps it would be good to look at some of this in connection with the jobspec stuff, and use the same configuration file format for both.  They'll need different contents, but I can't think of a reason they can't both use yaml or lua or whatever we decide on there.  What do you think?

**Comment by garlick** [comment]
I used lua for the config file for [diod](https://github.com/chaos/diod/blob/master/etc/diod.conf) as discussed in [Programming in Lua](http://www.lua.ohttps://github.com/chaos/diod/blob/master/etc/diod.confrg/pil/25.html).  I'm not sure the admins liked this very much.  Also, I'm not sure whether the programmability of lua will eventually cause unanticipated problems (computing config values, etc) or whether that's a benefit.

[libyaml](http://pyyaml.org/wiki/LibYAML) seems the common choice for parser in C.  At first glace its api seems pretty complicated, but I guess we can deal with it.

I hesitate to mention this but an incremental improvement over ZPL with llittle work would be INI format.   [libini](https://github.com/pcercuei/libini) is a simple embeddable INI parser.

I sort of wonder if we should back out the inherited config implementation that we have now and go exclusively with the more usual (command line, environment, compiled in) precedence, then think more carefully about what we want before adding inherited back in again?  I forget, is there a benefit to the current setup that we can't live without (maybe some tests will break?)

**Comment by trws** [comment]
I think some tests will break for the moment, but they could be fixed by encoding the settings in the appropriate environment variables, which has the advantage of being something a user program can override if they want.

If we want a static config I would argue for JSON, since we're already using it, YAML, because it's expressive, common and has several reasonable implementations, or TOML, which is an ini-like but more expressive format that's becoming popular for various embedded tasks.

As to whether having it be able to do computations in the config is a problem, I'm somewhat on the fence.  It could cause problems for people if they write complex configs, but I'm also thinking of just how often I've wished that I could do that in ssh config files for example.  Enough so that at one point I replaced the file with a fifo connected to a scripted daemon that would serve up values so I could actually make it do what I want... I really wish I were kidding, but that's not actually the most unreasonable workaround for a static config I've had either... If we can avoid, now and forever, users ever having to do that kind of wretched workaround for flux, without introducing undue insecurity or work for ourselves, it might be worth it.

**Comment by grondo** [comment]
Probably not surprisingly, I'd also suggest Lua if we ever think we're going to need any kind of conditionals, simple function support, or extensibility of the config file. You can really design any kind of config language around Lua using metatables, but it in its simplest form it can just be `key=value` or `table = { key = value }`. I can't imagine how anyone wouldn't "like" a `key = value` config file -- what was the sysadmins problem with diod config?

That being said, I don't think the problem with the config right now is the syntax of the config file, which I think works for what it is right now. 

The issue currently is when and where config parameters are read and stored, and confusion between system vs. internal vs. user vs. environmental defaults...

I like your idea that we remove the kvs config and instead go back to well known behavior, something like the following order of precedence (from lowest to highest)

 1. Internal, built-in defaults
 2. default config file
 2. current environment
 3. config file passed on cmdline (we may want to add a `--config-file` option, the `config-dir` thing is confusing)
 4. individual cmdline arguments, if applicable

For "inherited" configuration settings, we can use the environment for now. I don't think any tests would break, but I could be wrong.

**Comment by grondo** [comment]
I guess above I'm missing the "user" ~/.flux/config -- I think we should leave that one out for now, until there are some configuration items that users would actually want to override for all flux instances they may run (my guess is that we wouldn't have many of these?)

**Comment by garlick** [comment]
I like the idea of tabling the config file _format_ and focusing on the other problems.

For fun, I just disabled KVS config inheritance [here](https://github.com/garlick/flux-core/tree/config_simplify) and things mostly worked, minor test fallout that I"ve not run down
```
[snip]
ok 1 - baseline works
ok 2 - flux prepends to FLUX_MODULE_PATH
not ok 3 - flux prepends to FLUX_CONNECTOR_PATH
#
#               FLUX_CONNECTOR_PATH=/xyz flux -F /usr/bin/printenv \
#                       | grep "FLUX_CONNECTOR_PATH=.*:/xyz"
#
not ok 4 - flux --uri sets FLUX_URI
#
#               flux -F --uri xyz://foo /usr/bin/printenv \
#                       | egrep "^FLUX_URI=xyz://foo$"
#
ok 5 - flux --trace-handle sets FLUX_HANDLE_TRACE=1
ok 6 - flux --uri fails for unknown connector
ok 7 - flux --uri fails for unknown path
ok 8 - cmddriver: --uri fails for non-connector dso
ok 9 - flux env works
ok 10 - flux env runs argument
not ok 11 - flux env passes cmddriver options
#
#               flux -F --uri foo://xyz env | grep "^export FLUX_URI=\"foo://xyz"
#
not ok 12 - flux env passes cmddriver option to argument
#
#               flux -F --uri foo://xyx env sh -c 'echo $FLUX_URI'             | grep ^foo://xyx$
#
ok 13 - cmddriver removes multiple contiguous separators in input
ok 14 - cmddriver adds its own path to PATH if called with relative path
ok 15 - flux --secdir overrides config
ok 16 - FLUX_*_PREPEND environment variables work
ok 17 - flux-env output can be passed to eval
# failed 4 among 17 test(s)
1..17
flux-start: 1 (pid 51885) exited with rc=1
flux-start: 3 (pid 51891) exited with rc=1
flux-start: 2 (pid 51888) exited with rc=1
flux-start: 0 (pid 51884) exited with rc=1
FAIL: t1005-cmddriver.t
[snip]
ok 1 - require 'posix'
not ok 2 - require 'lalarm'
#     Failed test (./lua/t0007-alarm.t at line 5)
#     module 'lalarm' not found:
#       no field package.preload['lalarm']
#       no file '/home/garlick/local/share/lua/5.1/fluxometer/lalarm.lua'
#       no file '/home/garlick/proj/flux-core/src/bindings/lua/lalarm.lua'
#       no file '/home/garlick/local/share/lua/5.1/lalarm.lua'
#       no file './lalarm.lua'
#       no file '/usr/share/lua/5.1/lalarm.lua'
#       no file '/usr/share/lua/5.1/lalarm/init.lua'
#       no file '/usr/lib64/lua/5.1/lalarm.lua'
#       no file '/usr/lib64/lua/5.1/lalarm/init.lua'
#       no file '/home/garlick/proj/flux-core/src/bindings/lua/lalarm.so'
#       no file '/home/garlick/local/lib64/lua/5.1/lalarm.so'
#       no file './lalarm.so'
#       no file '/usr/lib64/lua/5.1/lalarm.so'
#       no file '/usr/lib64/lua/5.1/loadall.so'
not ok 3 - lalarm: is function
#     Failed test (./lua/t0007-alarm.t at line 6)
#     module 'lalarm' not found:
#       no field package.preload['lalarm']
#       no file '/home/garlick/local/share/lua/5.1/fluxometer/lalarm.lua'
#       no file '/home/garlick/proj/flux-core/src/bindings/lua/lalarm.lua'
#       no file '/home/garlick/local/share/lua/5.1/lalarm.lua'
#       no file './lalarm.lua'
#       no file '/usr/share/lua/5.1/lalarm.lua'
#       no file '/usr/share/lua/5.1/lalarm/init.lua'
#       no file '/usr/lib64/lua/5.1/lalarm.lua'
#       no file '/usr/lib64/lua/5.1/lalarm/init.lua'
#       no file '/home/garlick/proj/flux-core/src/bindings/lua/lalarm.so'
#       no file '/home/garlick/local/lib64/lua/5.1/lalarm.so'
#       no file './lalarm.so'
#       no file '/usr/lib64/lua/5.1/lalarm.so'
#       no file '/usr/lib64/lua/5.1/loadall.so' isn't a 'function' it's a 'string'
/usr/bin/lua: ./lua/t0007-alarm.t:9: attempt to call local 'alarm' (a string value)
stack traceback:
        ./lua/t0007-alarm.t:9: in main chunk
        [C]: ?
FAIL: lua/t0007-alarm.t
[snip]
====================
2 of 48 tests failed
====================
```

**Comment by garlick** [comment]
I submitted that as PR #595 - easier to share that way I think.

**Comment by garlick** [comment]
(um that lua/t0007-alarm.t test is failing even after I reverted those changes so that may be a different thing)

**Comment by trws** [comment]
The user config would start to be useful pretty fast if the KVS load requirement goes away.  In that case I would pretty quickly put together a patch to add an "initial_modules" or similar configuration variable, and could definitely see individual users wanting to override that.

As to format, I agree what it is doesn't really matter a great deal, but brought it up more from the standpoint of hoping we can get to a point of consistency.  I don't think we're planning to use that config file format for anything else, but we do have several other config-like formats we use or are going to use soon, so it seemed to make sense to unify if we can.

**Comment by garlick** [comment]
> In that case I would pretty quickly put together a patch to add an "initial_modules" or similar configuration variable

but see #518 - I was just getting started prototyping that approach

**Comment by grondo** [comment]
I think we're going to be using the "initial program" style for that sort of thing, and it kind of feels like that initial program/init script/set of scripts will become the "user config".

e.g. eventually the little scripts that might make up an initial program for a session might be little shareable bits of code that systems and users end up plopping into a flux.d director or something. Then you could choose a starting point by name that starts one or more of these scriptlets.

That might be one approach anyway...

**Comment by trws** [comment]
In principle that could completely replace the config file approach come to think of it.  If you have the run-level scripts, and that's the way people are meant to do this, then everything could be environment variables managed by the scripts.  It puts me a bit in mind of some of the fluxbox configuration environment, which is not a bad thing.  The only thing that would make me a bit wary is I'm not sure how an everyday user would feel about runlevel script style configuration rather than a static config for certain things.  It also raises the question of how things like the `flux config` command would work, though script-style configuration management programs abound in places like Gentoo I suppose... That actually might just take care of it, assuming we are comfortable with using environment variables and commands in a file for all of these things.  The only downside I really see to that is we can't parse it and give the user feedback if something is broken, we'd be depending on the scripting language and command errors for that... hmm...

**Comment by garlick** [comment]
> The only downside I really see to that is we can't parse it and give the user feedback if something is broken, we'd be depending on the scripting language and command errors for that... hmm...

That's a valid point and I have to say that batch scripts and user dot files have always been painful for our center to manage, because of their flexibility and difficulty auditing in an automated way.  I am still pretty in love with the idea in #518 though (as I play with it).  I guess let's take it slow and see how it goes.

By the way flux-broker-attributes(7)  are another "config" that might need to be part of this discussion.  By dumping the config in the KVS, we make it global (all ranks); by contrast the attributes are local to a broker rank.

**Comment by garlick** [comment]
Actually, looking at what we have in the config right now, there's nothing that requires it to be global.  It could probably be subsumed by broker attributes if we wanted to go that way.

**Comment by garlick** [comment]
See @grondo's final comment in #104 regarding config as "flux environment".

**Comment by garlick** [comment]
Is it OK to close this?  We've dropped the current config file so we have a blank slate for a redo when the time arises.  I don't think that is for 0.4.0, the milestone this issue is currently tied to.

**Comment by grondo** [comment]
Ok with me
