### ISSUE TITLE
display nnodes for pending jobs in 'flux jobs'

### ISSUE THREAD

**Issue by ryanday36** [flux-framework/flux-core#4530]
'flux jobs' currently only displays 'nnodes' for running and completed jobs, but that information is important to understanding when a pending job might run, especially on node scheduled clusters. E.g. the following two jobs are very different, but appear to the the same in the `flux jobs` output:
```
[day36@corona211:~]$ flux mini batch -N96 -n96 -t 1d --wrap hostname
ƒ86Z4duezHM
[day36@corona211:~]$ flux mini batch -N2 -n96 -t 1d --wrap hostname
ƒ86Z8NyRqPd
[day36@corona211:~]$ flux jobs
       JOBID USER     NAME       ST NTASKS NNODES  RUNTIME NODELIST
 ƒ86Z4duezHM day36    hostname   PD     96      -        - -
 ƒ86Z8NyRqPd day36    hostname   PD     96      -        - -
 ƒ86Nznv7K6w day36    flux        R      1      1    22.3m corona177
[day36@corona211:~]$
```
Would it be possible to display the requested NNODES for pending jobs?

**Comment by grondo** [comment]
One problem is you can't tell how many nodes a user is requesting from jobspec alone, i.e. they may have only requested cores, and it will be up to the scheduler to decide how many nodes that is. 
However, maybe we can make an estimate, or some other resources count that will have the desired effect? Also, in some cases the number of nodes will be known..

**Comment by chu11** [comment]
if the user specifies a number of nodes (`flux mini -NX`) I think the jobspec will always specify a number nodes.  I suppose in that case we could always list `nnodes` for that job.

The only question for me is if it is acceptable for some pending jobs to have `nnodes` listed and others not.  I feel it should be ok.  If the user didn't require a node count, then they are trusting the scheduler to do what is best.  This differs from slurm, but perhaps users would learn over time this is the expected behavior?

Another thought is if this should be a configurable option, dunno if we want this to be default behavior in job-list.

> However, maybe we can make an estimate, or some other resources count that will have the desired effect?

Would it be possible to tell the scheduler to "pretend" schedule the job and return an estimated resources list?  like, ask the scheduler to hypothetically schedule this job if all resources were available, what would you do?  I imagine this could be useful in other ways too.

**Comment by grondo** [comment]
> Would it be possible to tell the scheduler to "pretend" schedule the job and return an estimated resources list? like, ask the scheduler to hypothetically schedule this job if all resources were available, what would you do? I imagine this could be useful in other ways too.

I _think_ this is what the feasibility RPC does. However, it doesn't respond with a set of potential resources assigned to the job (at least not now). Also, in general a jobspec won't necessarily always result in the same number of nodes when it is finally scheduled. It may depend on what other resources are available at the time. With node exclusive scheduling and a homogeneous system, this perhaps seems trivial, but if nodes are being shared or have a different amount of resources, then I don't think there is a "nice" solution to this problem.
