### ISSUE TITLE
flux-jobs: should duration be used in RUNTIME column for non-running jobs?

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#4613]
Problem: the RUNTIME column doesn't convey useful information for non-running jobs:
```
       JOBID QUEUE    USER     NAME       ST NTASKS NNODES  RUNTIME NODELIST
 ƒAnP2EUJgNB batch    garlick  sleep       S      4      4       0s -
 ƒAnNpvHtZ67 debug    garlick  stress      R      1      1   30.58s picl6
 ƒAnNnmJF73u batch    garlick  stress      R      2      2   35.48s picl[4-5]
 ƒAnNmGEhHDR batch    garlick  stress      R      2      2   38.87s picl[2-3]
 ƒAnNjh4TT1R batch    garlick  stress      R      1      1   42.45s picl1
```
Could we show the jobspec duration in this column when the job is pending?

Edit: if that's thought to be a good idea then maybe DURATION would be a better column heading?

**Comment by grondo** [comment]
I think that seems like a reasonable idea. Note in the common, non-system-instance case a duration may not be set either so the column would still be empty.

I had the idea last week to make some contextual properties for the `JobInfo` class. I had prototyped an attribute to replace the NODELIST column that displays something like `priority-wait` for jobs in PRIORITY, the dependencies for jobs in DEPEND, any `sched.t_estimate` or `sched.reason_pending` if available in SCHED state, or otherwise the NODELIST.

We could do something similar here for RUNTIME/DURATION?

**Comment by grondo** [comment]
Oh, one prerequisite here is that the `job-list` module capture the duration from jobspec, when set. Currently the duration doesn't appear to be an attribute provided by the service.

**Comment by chu11** [comment]
> Edit: if that's thought to be a good idea then maybe DURATION would be a better column heading?

Since they provide two different pieces of information, I like the idea of keeping them separate just in case.

I'll throw out the idea that we simply use a new field name, perhaps generically named TIME, that can represent the RUNTIME/DURATION.  It'd be similar to the `status` field,which is a combination of job state and job result.
