### ISSUE TITLE
flux proxy to system instance results in sign-type=none error

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#4648]
@ryanday36 reported this:

If you try to use `flux proxy` to connect to the system instance and submit a job, you get an error about the use of `sign-type=none`:
```
$ flux proxy local:///var/run/flux/local flux mini run hostname
flux-mini: ERROR: [Errno 1] only instance owner can use sign-type=none
```
The connector must be returning the wrong owner ID and fooling `flux_job_submit(3)` into thinking it is submitting to a single user instance in the case of flux-proxy?

**Comment by garlick** [comment]
Correct analysis I believe - `flux_job_submit()` is assuming because the "peer" is the same as the user, that the user is the instance owner and doesn't need a strong signature.

This may fix it by disabling the false hint when the socket belongs to `flux-proxy` (untested):
```diff
diff --git a/src/connectors/local/local.c b/src/connectors/local/local.c
index 0c7c54578..e1057d3fd 100644
--- a/src/connectors/local/local.c
+++ b/src/connectors/local/local.c
@@ -126,7 +126,9 @@ static int op_getopt (void *impl, const char *option,
     size_t val_size;
     int rc = -1;
 
-    if (option && !strcmp (option, "flux::owner")) {
+    if (option
+        && !strcmp (option, "flux::owner")
+        && strstr (ctx->path, "flux-proxy-") == NULL) {
         val_size = sizeof (ctx->owner);
         if (size != val_size) {
             errno = EINVAL;
```

OTOH  wouldn't a system instance typically allow direct connection from everywhere on cluster, and wouldn't submitting from off cluster to a system instance typically fail because of the disjoint munge realms?  What's the use case that demands that this work?

Just wondering if maybe the right answer is to have `flux-proxy` refuse to connect to an instance that has a different owner than the proxy process.

**Comment by grondo** [comment]
I think the use case was submitting a new job to the system instance from within a batch instance. The correct fix was to use `flux --parent`, but it seemed like the error here was confusing enough to report it.

At least for now it seems like an error would be fine. If a user wanted to perform many operations against the system instance from within a batch job, then `flux proxy` might be handy as a uniform way to do that sort of thing. However, for this specific case they could also just unset `FLUX_URI`.

**Comment by ryanday36** [comment]
This seems like an unlikely use case, but what if someone wanted to submit to the system instance from within a batch instance that was multiple levels deep? I assume `--parent` only goes up one level. Would that case be handled by Mark's suggestion of unsetting `FLUX_URI`?

**Comment by grondo** [comment]
Yes, that would work, or you can specify multiple `--parent` options, e.g. if the `instance-level` attribute was 3, `flux --parent --parent --parent` will get you back to the system instance/root instance. Hm, I wonder if we need a `flux --root` option?
