### ISSUE TITLE
singleton MPI job fails within a Flux allocation

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#4671]
@adammoody noticed that singleton MPI jobs (running a single copy of an MPI application locally, not under `flux mini run`) do not work within an allocation. For example, with OpenMPI 4.1:

```console
$ flux mini alloc -n1 ./hello
[corona180:573210] PMI_Init [pmix_flux.c:389:flux_init]: Operation failed
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  pmix init failed
  --> Returned value Error (-1) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  orte_ess_init failed
  --> Returned value Error (-1) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "Error" (-1) instead of "Success" (0)
--------------------------------------------------------------------------
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[corona180:573210] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
2022-10-11T01:14:05.596409Z broker.err[0]: rc2.0: ./hello Exited (rc=1) 0.1s
[detached: session exiting]
```

On a login node (not under a flux allocation), the singleton works:

```console
$ ./hello
Hello from task 0 on corona212!

MASTER: Number of MPI tasks is: 1
```

**Comment by garlick** [comment]
If I unset  both `OMPI_MCA_schizo=flux` and `FLUX_JOB_ID` in the allocation, my hello program works there.   The former says "only try the flux schizo plugin", which prevents fallback to the schizo plugin that would select openmpi's singleton mode.  The latter tells the flux schizo plugin that it's running in the flux job environment, and so short circuits the schizo search, only to fail when PMI is tried, becuase that FLUX_JOB_ID refers to the allocation's Flux instance.

For better or worse, our libpmi.so is designed to fail when it cannot find a PMI server:
```c
 * PMI_Init() will fail if PMI_FD, PMI_RANK, or PMI_SIZE is unset.
 * It is up to the caller to fall back to singleton operation, if desired.
```
The rationale was that a hard failure was better than maybe starting a user's job as `size` singletons, and also a reaction to confusion caused by slurm's PMI library in behaving this way and masking problems during development of Flux.

I'm not sure what the right solution is here but wanted to get this explanation out there.

Also: note that slurm's `/usr/lib64/libpmi.so` is still out there on corona to trip over.  I performed my testing on fluke where slurm is not installed, although I don't think it was causing problems in this case.

Alsø alsø: I think `openmpi-tce` is still broken in some other regards, documented in (not public) jira tickets TCE-29, TCE-31

**Comment by grondo** [comment]
Thanks! Note that @adammoody's symptom on another system is that the MPI application segfaults. I haven't been able to reproduce this, but that issue is supposedly with mvapich2.

**Comment by garlick** [comment]
Yeah I was having the same thought.  Maybe just the variables that our "mpi plugins" are setting.

**Comment by grondo** [comment]
Yeah, unfortunately the plugins are kind of like configuration (they can be modified by sites) and the set of sanitized environment variables is currently compiled into the broker. I wonder if we need a way to allow the list of remove environment variables to also be modified at runtime? (i.e. move the `env_blocklist` to an external config file). Perhaps that is a separate issue...

**Comment by garlick** [comment]
Maybe we need a `-o mpi=none` option that prevents the always-loaded MPI plugins from loading when flux launches flux?

**Comment by grondo** [comment]
Oh that's such a good thought I wonder why we didn't think of it before!
