### ISSUE TITLE
add flux config load

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#4678]
> Yeah, we should get a separate issue open for the `flux config reload --stdin` (or should it just be `flux config load`?) option. This is the only way you can configure an instance that has already started without a configuration directory set. For instance, this would give users a way to configure their batch jobs from within the batch script.

_Originally posted by @grondo in https://github.com/flux-framework/flux-core/issues/4676#issuecomment-1276659750_

**Comment by grondo** [comment]
I'd argue for a `flux config load` since it obviates the need for `--stdin` option, and if you are sending configuration over stdin you aren't really "reloading". Also, it might be nice if this command explicitly _did not_ reload from config files, so you could temporarily override configuration until the next `flux config reload`.
