### ISSUE TITLE
python: supply to_dict() function to JobInfo

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#4760]
via @vsoch in #4757 

> Can confirm - I autocompleted the functions [edit: `job_list_id()`], saw that one, and then called it (with the handle and job id) and then was confused to get another object back to explore. Adding the attrs with "all" worked beautifully but (as a user) I wouldn't have been able to figure it out. In that APIs should be intuitive, I would err on the side of returning what the user expects (and making the object not the default). If you do keep the object, I would add an obvious to_dict() (akin to_str()) so it's stupidly obvious how to "get all the data."

**Comment by vsoch** [comment]
Are you looking for someone to try working on this? If y'all like the idea it would be good experience for me to try and add the function. It's probably super easy, but that's makes it perfect for a "first issue!"

**Comment by grondo** [comment]
Sure @v! Thanks!!

**Comment by chu11** [comment]
@vsoch i was going to take a shot at it next week, but if you wanna take a crack, even better, since you're the user :-)

**Comment by vsoch** [comment]
Yay, thank you! I wound up working on two other projects this evening and writing a blog post, but it’s on my list TODO for tomorrow!

**Comment by vsoch** [comment]
@chu11 my suggestion above was to add the to_dict to the rpc returned, not JobInfo. I'm not actually sure how to interact with a JobInfo. That's what I'm going to work on - stop me if this is wrong.

**Comment by vsoch** [comment]
But actually I'm not sure, because there is a "get" function that seems to already do this?

```
def get(self):
        resp_str = self.get_str()
        if resp_str is None:
            return None
        return json.loads(resp_str)
```
I think this is just bad naming - I wouldn't have guessed that "get" returns a dictionary with what I want, it's too generic. 

I think my proposal is to go back to the flux.job and have an explicit function for get_job. That will retrieve the rpc and then call get to return the dictionary or None. I don't think the user should be needing to dig into these complex objects and searching for conversion functions.

**Comment by grondo** [comment]
The issue is that the payload returned from `job-list` is not as useful as the `JobInfo` class, which makes a lot more user friendly attributes of a job available to the user (and are created on demand). The `JobInfo` class is probably what most users should use IMO (as I think that's true for Python in general, not every Python class is just a dict right?)

The `.get()` semantics come directly from Flux futures interface since they are calling `flux_future_get()` under the covers.

**Comment by vsoch** [comment]
It may be more useful, but the problem (as I see it) is that we cannot require someone to know how to instantiate an entire other class when they are interacting with courtesy functions in flux.job. This is my first shot proposal, which I think is most intuitive for the user.

https://github.com/flux-framework/flux-core/pull/4761

We could do something similar using the JobInfo class (instantiated for the user under that same name) but I'd need an example of how to do that, because I've played around with JobInfo but never got it to do what I wanted.

**Comment by vsoch** [comment]
woo! :partying_face:
