### ISSUE TITLE
two events emitted at rank 0 for event originating on another rank?

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#477]
I'm seeing strange behavior with events on current master d5c493c. I'm seeing that an event originating on non-zero rank seems to get delivered twice to rank 0 listener (though I'm not completely willing to say this isn't because of me doing something dumb, so I'm sorry if so):

This is the reproducer:
```
grondo@flux-core:~/workspace (master) $ src/cmd/flux start --size=4
flux-start: setrlimit: could not remove core file size limit: Operation not permitted
[1447600164.911818] broker.info[0]: nodeset: [0-3] (complete)
[1447600164.911899] broker.info[0]: starting initial program
grondo@flux-core:~/workspace (master) $ flux event sub testevent &
[1] 15468
grondo@flux-core:~/workspace (master) $ flux event pub testevent
testevent
grondo@flux-core:~/workspace (master) $ flux exec -r 3 flux event pub testevent                                                                                                                  
testevent
testevent
grondo@flux-core:~/workspace (master) $ flux exec -r 3 echo hello
hello
```

Even more strangely, after publishing the event once from rank 3, now even published events from rank 0 appear to be delivered twice:
```
grondo@flux-core:~/workspace (master) $ flux event pub testevent
testevent
testevent
```

I haven't dug any further than this yet.

**Comment by garlick** [comment]
I can reproduce this.  Have a look at the broker event routing logic.

**Comment by garlick** [comment]
Er I mean to say I am having a look at the event routing logic.

**Comment by garlick** [comment]
Running the reproducer above with a new `flux-event sub --raw` option:
```
$ ./flux exec -r 3 flux event pub testevent                                                              
--------------------------------------
e[009] testevent
e[012] 8E0104010000011300000000
--------------------------------------
e[009] testevent
e[012] 8E0104010000011300000000
```
it is evident that the same message _with the same sequence number_ is being received.

**Comment by garlick** [comment]
OK, this is an embarrassing combination of problems in which rank 0 doesn't check for duplicate event sequence numbers (because it thinks it will never receive its own events), and then at some point, thinking we had robust duplicate event handling and that it would "just work", I allowed events to also be sent out on the ring network, which loops back from the highest numbered rank to rank 0.

Since the ring connections are established on demand, the duplication doesn't start until rank (size - 1) becomes the target of a request (e.g. the `flux-exec -r 3` in the reproducer)

PR with test is in the works.
