### ISSUE TITLE
job-manager: default queues to disabled and stopped

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#4822]
from a discussion in #4776

> Another related thought is that we could make the initial state of a named queue disabled and stopped so that we could add them on the fly without there being a race where they might be used before that is intended. For example, the admins could add a DAT queue to the config and then enable but not start it to allow jobs to be submitted before the DAT. It would not be good to do that for the anonymous queue though, since that would break batch jobs. Just a thought to consider.

**Comment by chu11** [comment]
Note that queues automatically being enabled/started led to this annoyance in some flux-accounting tests

https://github.com/flux-framework/flux-accounting/pull/302

newly created queues were automatically enabled/started and jobs began to run, leading to errors in tests.

**Comment by chu11** [comment]
hmmm, its sort of annoying having to do

```
flux queue enable
flux queue start
```

after every new queue that is setup.  Admittedly this is mostly annoying in testing b/c we're making new queues all of the time.  Wondering if we could combine into a single command.  like

`flux queue enable --start`

**Comment by chu11** [comment]
OR ... should queues be defaulted to enabled and stopped?  i.e. jobs can be submitted, but none schedulable?

**Comment by garlick** [comment]
Or maybe the reverse (disabled, running)?  If no jobs are enqueued then none can be scheduled right?

We're only talking about brand new queues since their state is saved/restored on each Flux restart after that.

**Comment by chu11** [comment]
> (disabled, running)

I assume you mean `disabled/started`.

My assumption is the common situation is gonna be for a DAT, so the admin sets up a new queue named `DAT_queue_jan_5_2023` or something.    We allow the user(s) of the DAT to start submitting, and when the DAT begins, the admin just starts it (`flux queue start`)??

**Comment by garlick** [comment]
Oops, yeah I meant `disabled/started`.

I had assumed there would be a single, long-lived "all" queue for DATs and hadn't considered queues created for each one, but that seems like something people might want to do since it would allow preparations for multiple DATs (or DAT phases) to be made in parallel.

Pondering a bit more, you're  probably right about `enabled/stopped` being the preferred initial state.  I was thinking the admin would want control over when to allow jobs to be submitted, but it might be surprising if the queue is enabled and the jobs start running!  Yeah, I'm voting for your original proposal now.
