### ISSUE TITLE
allow users to set default output formats

### ISSUE THREAD

**Issue by ryanday36** [flux-framework/flux-core#4839]
The flux-jobs man page makes it pretty clear that users can't create a named output format that's the same as an existing name such as 'default'. Is there a way for users to set a default custom output format?

**Comment by garlick** [comment]
I think the answer is no, and it was a purposeful decision to avoid creating confusion, like
- output in tutorials no longer matches what the user sees
- hotline tells a user to run flux jobs and look for something that's is not present in the user's default output
- user is perplexed by different behavior at different sites
- installed flux default output changes and user finds announced functionality is missing 

All premised on the idea that people might set up their config and forget about it

Are those reasonable concerns?

**Comment by ryanday36** [comment]
I'm not sure. On the one hand we do get issues in the hotline from people who have been given some .bashrc from some other group member or code team and are confused by something in it, so I'm sure that there will be users who use custom configs without really understanding what they're doing and don't know where to look when things break. On the other hand, it seems like most users who get as far as editing a .toml, .yaml, or .json file are going to be fairly motivated/sophisticated and will remember that there are custom configurations even if they have to look up where they put them. Also, if they do forget, it's a pretty easy thing for support to check.

I think that the 'I want to change the default' use case seems likely to be the most common use case for custom output formats. I don't know how wide the adoption of this is, but I know that Ines has pushed the use of Slurm's SQUEUE_FORMAT environment variable a lot. So it's something that people are used to having, and it would make Ines happy.

**Comment by garlick** [comment]
That seems like a reasonable counterpoint.  Making Ines happy is often a good policy :-)

**Comment by grondo** [comment]
The original PR that added named formats allowed users to override `default` to change the default output format, but that was withdrawn due to largely the arguments @garlick delineated above. Currently a system or user config cannot override any of the "builtin" formats defined in flux-jobs or flux-resource.

My guess is that the 'named formats' approach will help placate users and Ines, since you may want a different format from these utilities in different situations, however, if a way to override the default would really be useful we can look at removing the code that prevents overriding builtin formats.

However, perhaps we could also look into a `FLUX_JOBS_FORMAT` environment variable which sets the `--format` option on the command line of `flux jobs`. This would solve the testing problem (this variable is easily sanitized from the environment), and the variable could be set to either an existing named format, or a full custom format string.
