### ISSUE TITLE
libflux/python: convenience function to read stdio 

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#4854]
@ofaaland mentioned in a chat that it'd be nice to be able to read stdio from the KVS from a python function, vs `flux job attach`.  To my knowledge, we do not have any convenience functions to handle the reading from the KVS and parsing the eventlog format.  `flux job attach` just reads from the KVS directly.

`flux job attach` handles many corner cases, like if the job hasn't started.  Conceptually perhaps a convenience function doesn't have to do that, just read the data that exists in the KVS and just error if its not there / job not started yet.

Dunno if we should have a C function as well,

**Comment by ofaaland** [comment]
In case it helps, my use case is for SCR.  SCR has a python script whose task is to launch a job, monitor it, and then re-launch the job if it fails.  Before launching the job, and after it fails, the script does setup and cleanup.

For this use case, the convenience function would be much more useful if it handled the "job hasn't started yet" and "job already completed" corner cases, at least.  Without that, I think it's possible that the convenience function would be a booby trap rather than a useful addition.

Note that I haven't evaluated other options (e.g. using subprocess.Popen, or passing temp file paths via flux.job.jobspec properties) thoroughly yet, so it might be premature to put work into this now.
