### ISSUE TITLE
Feature request: custom metadata specification for flux keygen

### ISSUE THREAD

**Issue by vsoch** [flux-framework/flux-core#4875]
We are currently using flux keygen to generate a certificate for our indexed jobs:

```bash
flux keygen /mnt/curve/curve.cert
```
This step happens in a one-off pod to generate the cert in advance, and then it is passed to the indexed job pods via a config map. We do this so we don't require any actual shared filesystem volumes with read/write for the actual job. However, one issue that is bothering me (that I don't think has any implications I can see beyond being incorrect) is that the hostname always corresponds to the generator container name, e.g.,:

```
#   ****  Generated on 2023-01-21 00:07:17 by CZMQ  ****
#   ZeroMQ CURVE **Secret** Certificate
#   DO NOT PROVIDE THIS FILE TO OTHER USERS nor change its permissions.

metadata
    name = "lammps-cert-generator"
    time = "2023-01-21T00:07:17"
    userid = "0"
    hostname = "lammps-cert-generator"
curve
    public-key = "n!cCGTX^([hM}!bdX7DDG%M]@l#J8(/J=gRK!ped"
    secret-key = "/>N&+vHYdlr-]S9!9igcSAUI!>v4r416%M)NfAFc"

✨ Curve certificate generated by helper pod
#   ****  Generated on 2023-01-21 00:07:17 by CZMQ  ****
#   ZeroMQ CURVE **Secret** Certificate
#   DO NOT PROVIDE THIS FILE TO OTHER USERS nor change its permissions.
```
The actual host of the broker would be something different like lammps-0. What I'm hoping might be possible is to allow specifying metadata to keygen, e.g.,:

```
flux keygen --hostname lammps-0 /mnt/curve/curve.cert
```
And that way this service container can generate the cert on behalf of the TBA broker. Is this a possibility? It looks like now I only have access to the cert name:

```bash
$ flux keygen --help
Usage: flux-keygen [OPTIONS] [PATH]
  -h, --help             Display this message.
  -n, --name=NAME        Set certificate name (default: hostname)
```
Ty! :turtle:

**Comment by garlick** [comment]
Flux logs the cert name when a peer broker authenticates:
```
2023-01-22T05:35:38.148589Z broker.debug[0]: overlay auth cert-name=picl0 OK
```
Beyond that, the metadata is just recording a little extra info about where the cert came from in case that's useful to posterity.  The hostname is where it was generated not where it is intended to be used.  E.g. Later maybe someone could ask if the cert was generated on a machine that was compromised or if it was generated before some bug was fixed.

Maybe we should do something to make the purpose of the `time`, `userid`, and `hostname` more clear, like prefix it with `keygen.`?  Simple to do now since nothing depends on it....

It would also be easy to allow these and arbitrary other metadata keys to be set on the `flux-keygen` command line.  Is that useful?

**Comment by garlick** [comment]
> E.g. Later maybe someone could ask if the cert was generated on a machine that was compromised or if it was generated before some bug was fixed.

On that note, automatically adding software versions might be useful too (flux-core and zmq, minimally; for extra credit, czmq and libsodium)

**Comment by vsoch** [comment]
> Is that useful?

Yes I think so!
