### ISSUE TITLE
flux resource drain should indicate if node is also offline

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#4909]
Problem: sys admins require a way to see at a glance which drained nodes are running flux vs not.

In LC, nodes do not start flux until they have a clean bill of health.  Thus a drained that is offline is one that is not fixed, and a drained node that is online is one that has been fixed and can be undrained. 

It would be a help to the sys admin workflow if `flux resource drain` denoted which nodes are offline.

Here picl4 is both drained and turned off:
```
$ flux resource list
     STATE QUEUE    PROPERTIES NNODES   NCORES    NGPUS NODELIST
      free debug,al                 1        4        0 picl1
      free debug,al 4g              1        4        0 picl2
      free batch,al                 2        8        0 picl[3,6]
      free batch,al 4g              1        4        0 picl5
      free batch,al testprope+      1        4        0 picl7
 allocated                          0        0        0 
      down batch,al                 1        4        0 picl4
```
I think what's being requested is for offline to be incorporated into the `flux resource drain` output?
```
$ flux resource drain
TIME         STATUS   REASON                         NODELIST
Feb02 18:19  drained                                 picl4
```

**Comment by grondo** [comment]
Maybe the problem is that `online` and `offline` shouldn't be a "state" in `flux resource status` and `flux resource drain`, but should be its own field. Then the output might be

```
$ flux resource drain
TIME         STATUS   OFFLINE   REASON                         NODELIST
Feb02 18:19  drained  yes                                      picl4
```

This would be a bit of a refactor in `flux resource list`, but might be better in the long run.

It is however, trivial to flag drained targets with a `*` as is done in Slurm:

```
TIME         STATUS   REASON                         NODELIST
Dec12 13:21  drained  broker was unresponsive        fluke3
Sep11 09:06  drained* broker was unresponsive        fluke18
Aug15 15:57  drained* broker was unresponsive        fluke66
```

**Comment by garlick** [comment]
Hmm, I kind of like the asterisk in `flux resource drain` output, but either of your proposals sounds good actually.  Why don't we say this bug is closed by adding some offline indication to `flux resource drain` whichever presentation we decide on?

I can open another bug on the fact that `flux resource status` shows a node that is offline and drained repeated in two STATUS rows and we can decide if that needs fixing or not.

**Comment by grondo** [comment]
Ok, the asterisk was pretty trivial to add so I can propose a PR today. Since `drained*` would be a new state, it will also show up in `flux resource status` output (unless disabled for that subcommand somehow), so we'd have nodes duplicated in `drained*` and `offline`. This is IMO correct behavior for the current output format since the two "states" intersect.

Keep in mind that `flux resource drain` output is just a special case of `flux resource status` in the implementation, so these two commands can't really be separated. We could make things work the way you want, though, by adding an option to `flux resource status` to suppress the `*` marking of the drained+offline state though..

**Comment by garlick** [comment]
Sounds good!  I don't have a strong opinion on the duplication in `flux resource status`, just wanted to open the discussion, so if you feel it's OK we can close #4910 and do whichever you think is best on the `*` that would appear in its output as a result of changing `flux resource drain`.
