### ISSUE TITLE
flux resource status shows offline+drained nodes in two rows

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#4910]
Problem: as noted in #4909, when a node is both drained and offline, `flux resource status` lists the node in two rows, e.g. here picl4 is drained+offline and picl5 is just drained:
```
$ flux resource status
    STATUS NNODES NODELIST
     avail      5 picl[1-3,6-7]
   offline      1 picl4
   exclude      1 picl0
   drained      2 picl[4-5]
```
Is there a better way to present this?

**Comment by grondo** [comment]
Note that there is a similar problem with exclude -- if an excluded node is offline it will appear in two rows. IMO, there is nothing erroneous about nodes appearing in two rows of output in this utility. Above `picl4` is actually both drained and offline, so the current presentation is correct.

However, as was proposed in #4909, it might be better to give online/offline its own column in the output instead of treating as a state. Then you could easily tell which nodes are drained+offline or excluded+offline. I'm not sure what to display in the STATUS column, however, for the set of nodes that are offline, but neither excluded or drained..

**Comment by grondo** [comment]
As also noted in #4909, `flux resource drain` is really just `flux resource status -s drained,draining -o FORMAT` so we should strive not to make the output handling of these two subcommands diverge too much.
