### ISSUE TITLE
flux mini run --requires 4g,4g works but --requires 4g,host:picl1 does not

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#4917]
Problems:  `--requires` takes a list of constraints, where each constraint has the form operator:operand, but if no operator is specified, the default is "properties".  This makes the interpretation of "," as a properties operand separator a bit confusing:

```
$ flux mini run --requires='4g,4g' hostname
picl2
```
```json
      "constraints": {
        "properties": [
          "4g",
          "4g"
        ]
      }
```
while
```
$ flux mini run --requires='4g,host:picl2' hostname
flux-mini: ERROR: [Errno 22] Internal match error
```
```json
      "constraints": {
        "4g,host": [
          "picl2"
        ]
      }
```
It's a valid separator for properties but not for constraints.  Well, knowing that, it's not confusing, but it might be a bit confusing to first timers.

**Comment by grondo** [comment]
> Problems: --requires takes a list of constraints, where each constraint has the form operator:operand

Ah, part of the problem is that `--help` output of `flux mini` needs to be updated.  `flux mini --requires` does not take a list of constraints, but as better described in [flux-mini(1)](https://flux-framework.readthedocs.io/projects/flux-core/en/latest/man1/flux-mini.html#constraints), takes a string in RFC 35 Constraint Query Syntax.

To fix this issue, the `--help` output should be updated, and `,` should be removed from the list of valid characters in operator.
