### ISSUE TITLE
Can the callback for resource-hwloc.reload handle an error more gracefully?

### ISSUE THREAD

**Issue by dongahn** [flux-framework/flux-core#492]
This is just a minor enhancement request. I am trying to use fake hwloc load support with the resource-hwloc module to set up `flux-sched` tests. I mistakenly gave a wrong path to my fake xml file path, which then caused the entire flux instance to exit. It seems a simple path check within the reload handler can handle this case a bit more gracefully? 

```
cab670{dahn}51: flux event pub resource-hwloc.reload
cab670{dahn}52: [1449863488.699770] resource-hwloc.info[0]: loading hwloc from /nfs/tmp2/dahn/FLUXDEV/flux-sched/t/hwloc.0.out.xml
[1449863488.701141] resource-hwloc.info[2]: loading hwloc from /nfs/tmp2/dahn/FLUXDEV/flux-sched/t/hwloc.2.out.xml
[1449863488.701559] resource-hwloc.info[1]: loading hwloc from /nfs/tmp2/dahn/FLUXDEV/flux-sched/t/hwloc.1.out.xml
[1449863488.702388] resource-hwloc.info[3]: loading hwloc from /nfs/tmp2/dahn/FLUXDEV/flux-sched/t/hwloc.3.out.xml
[1449863488.720788] resource-hwloc.err[0]: resource.c:54:negative integer from:hwloc_topology_set_xml (ctx->topology, path):: No such file or directory
[1449863488.720767] resource-hwloc.err[1]: resource.c:54:negative integer from:hwloc_topology_set_xml (ctx->topology, path):: No such file or directory
[1449863488.720767] resource-hwloc.err[2]: resource.c:54:negative integer from:hwloc_topology_set_xml (ctx->topology, path):: No such file or directory
[1449863488.720788] resource-hwloc.err[3]: resource.c:54:negative integer from:hwloc_topology_set_xml (ctx->topology, path):: No such file or directory
flux-start: 0 (pid 85991) exited with rc=9
flux-start: 1 (pid 85992) exited with rc=9
flux-start: 2 (pid 85993) exited with rc=9
flux-start: 3 (pid 85998) exited with rc=9
```

**Comment by grondo** [comment]
@dongahn, I agree this is an issue we should fix.
I think we had talked about not having modules ever call `err_exit`, instead they should either exit from reactor loop and thus `mod_main` for unrecoverable errors, or just print an error or return to user on recoverable failures.

I'm not sure which case we're dealing with for `resource-hwloc` -- preference would be for a recoverable error, but since the load request is based on an event I'm not sure how to communicate any error back to requester. So perhaps module should call `flux_reactor_stop_error` instead of `err_exit` for now?

**Comment by dongahn** [comment]
Because I manually used `flux event pub resource-hwloc.reload`, I can see the error message and manually recover from it. But you are right, from the programmability point of view, errors in an event callback will be difficult to recover. `flux_reactor_stop_error` seems reasonable for now.

**Comment by dongahn** [comment]
Actually, it find the pub-based hwloc reload a bit difficult to use in creating tests. Issuing `flux event pub resource-hwloc.reload` and schedsrv load back to back is subject to a race as the reload handler would not sometimes fully reload `resource.hwloc.xml.<rank>` before the loading of schedsrv. If possible, I don't want to use `sleep n` between the calls, but by definition this will still be racy. 

@trws or @grondo, is there a way to check the status of a reload programmatically to confirm "done?" 

Or can hwloc reload be implemented as multi RPC?

**Comment by trws** [comment]
I could make a reload RPC, but you would have to send the message individually to each rank that needs to reload for that to work.  Perhaps that's how it should work, as that would also give it a place to return an error to the entity making the request to reload rather than exiting unless the incorrect path was specified in the initial configuration?

**Comment by grondo** [comment]
@trws: There is also the mrpc interface.

Whether you use mrpc or one to many RPCs, I think for the reload functionality it does certainly seem like some kind of RPC is warranted.

Maybe you could take a look at current mrpc interface and if it doesn't work for your use case we could improve it. Unless @garlick has any objections (I'm not sure if he's deprecated use of the current mrpc or not)

**Comment by dongahn** [comment]
Actually for testing, I like bulk reloading and get a single return code for this bulk operation a bit better. @grondo, does mrpc interface support this?

**Comment by grondo** [comment]
I also forgot about `flux_rpc_multi(3)` which issues RPCs to all ranks in a nodeset then waits asynchronously for all replies.

Either `flux_rpc_multi(3)` or `flux_mrpc_*` would work for "bulk reloading" if I understand your statement @dongahn. `flux_rpc_multi(3)` is just a nice wrapper around `flux_rpc` so messages will be sent one-to-many, while `flux_mrpc_*` uses the KVS as a shunt for the RPC message with "delivery" via a multicast event, so it is (perhaps) arguably more scalable. In this case, since load of hwloc info is probably mostly used for testing `flux_rpc_multi` might be the right approach.

(I'd also be interested to hear from @garlick if he thinks mrpc should still be used -- I don't remember his plans for that one)

**Comment by garlick** [comment]
I think `flux_rpc_multi(3)` makes the most sense here.

I would probably avoid `flux_mrpc()` for now as both its interface and implementation are overdue for a rethink.

**Comment by trws** [comment]
Just to be sure I'm reading this right, on the resource-hwloc end, it would still be a regular rpc service, but on the usage end it would be a flux_rpc_multi, right @garlick, @grondo?

**Comment by garlick** [comment]
Yep.

**Comment by trws** [comment]
That seems reasonable.  I'll take a look at it shortly.

**Comment by grondo** [comment]
@dongahn, unfortunately `flux_rpc_multi(3)` will require that you process each response in turn with a separate `flux_rpc_get()` (or handle via callback with `flux_rpc_then`). Sorry I had thought `flux_rpc_multi` would only invoke callback after all responses have been received.

However, it does make `flux_rpc` slightly more usable for multiple targets, and if you look at the examples it shouldn't be much more difficult to implement that what I thought you meant by "bulk load"

**Comment by trws** [comment]
We could probably make a little wrapper for that, something like 
"flux_rpc_consume_until" that eats all responses matching a pattern, or 
all those not matching a pattern I suppose, to say process all responses 
until there are none left if they're all successful, but return 
failure/call a callback when there's a failure?

**Comment by dongahn** [comment]
I will take a look. It seems easily enough to write a simple wrapper command atop of this.
