### ISSUE TITLE
Error message when flux broker is not running

### ISSUE THREAD

**Issue by ryanday36** [flux-framework/flux-core#4933]
When one issues a `flux ...` command on a node with no flux broker running, the error message is:
```
flux-mini: ERROR: [Errno 2] Unable to connect to Flux: No such file or directory
```
Which doesn't make the underlying issue very clear to the end user. Something like 'Flux is not running on this system' might be more clear.

See also https://mattermost.energy.gov/lc-llnl/pl/w3geaffyubdy5xu7rmgfk78xih

**Comment by garlick** [comment]
Oh I was going to say this is comically hard due to the layers of python program -> python api -> C api -> connector plumbing -> local connector plugin, and that we would need to plumb the whole call path to return a string error message instead of an errno.  I was rolling up my sleves to do that, but found some of the work is already done by @grondo in #4450 which added a `flux_open_ex(3)` call that returns a `flux_error_t` on error!  Happy day.

So to at least call out the socket path that can't be opened, we'd need to a) fix the local connector's `connector_init()` to put a the path in its `flux_error_t` parameter on connect failure, and then make sure we're calling `flux_open_ex()` from the python api and propagating the textual error?

Would it be acceptable to have a message like
```
flux-mini: ERROR: [Error 2] Unable to connect to Flux: /var/run/flux/local: No such file or directory
```

Also in python,  I'm not sure why we're calling out `[Error 2]` AND decoding it to No such file or directory.  Maybe the numerical error could be dropped?

**Comment by lee218llnl** [comment]
Would it be possible to mention that a flux broker is not running? As an end user, I'd have not idea what that file is for and what its omission means.

**Comment by garlick** [comment]
Would this be better?
```
flux-mini: ERROR: [Error 2] Unable to connect to Flux: the broker socket /var/run/flux/local was not found
```

**Comment by grondo** [comment]
Or something like:
```
Got {{error message}} trying to connect to broker socket at {{path}}
```
This would also work if the socket is not readable by the client for instance
```
flux-mini: ERROR: Got Permission denied trying to connect to the broker socket at /tmp/bobs-flux-emporium/local-0
```

**Comment by grondo** [comment]
> Also in python, I'm not sure why we're calling out [Error 2] AND decoding it to No such file or directory. Maybe the numerical error could be dropped?

This is the default string representation of a Python `OSError` exception (which is mostly what we get when an underlying call to the Flux API fails).

I _think_ this change to the `CLIMain` class will remove the superfluous `[Error N]` from `OSError` exceptions handled by all Python based frontend utilities:

```diff
diff --git a/src/bindings/python/flux/util.py b/src/bindings/python/flux/util.py
index 729b94702..c7f6a0f6e 100644
--- a/src/bindings/python/flux/util.py
+++ b/src/bindings/python/flux/util.py
@@ -218,7 +218,8 @@ class CLIMain(object):
             exit_code = ex
         except Exception as ex:  # pylint: disable=broad-except
             exit_code = 1
-            self.logger.error(str(ex))
+            errmsg = getattr(ex, "strerror", None) or str(ex)
+            self.logger.error(errmsg)
             self.logger.debug(traceback.format_exc())
         finally:
             logging.shutdown()
```

**Comment by grondo** [comment]
Is something like this acceptable?

```console
$ for f in /tmp /tmp/local; do FLUX_URI=local://$f src/cmd/flux mini run hostname; done
flux-mini: ERROR: Unable to connect to Flux: Connection refused
flux-mini: ERROR: Unable to connect to Flux: broker socket /tmp/local was not found
```

Seems like "Unable to connect to Flux: <error>" is pretty clear in most cases except "No such file or directory". In that case we pivot to an explicit error.
