### ISSUE TITLE
flux-jobs: support output format to show exception notes

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#4946]
While trying to write up a simple tutorial on `flux job cancel`, I realized that we have no easy way for users to check for exception notes other than writing their own format in `flux jobs`.  This is fine, but exceptions are a bit long to write formats for.

A format for listing failure information in `flux jobs` would probably be useful when users run `flux job --filter=failed` or `flux job --filter=canceled`.  Perhaps something like:

`{id} {user} {name} {result} {exception.severity} {exception.type} {exception.note}`

Maybe could throw `{returncode}` in as well.

**Comment by grondo** [comment]
> Maybe could throw {returncode} in as well.

What about a new "contextual" field in JobInfo that returns the "exit reason" (we could actually call it `exit_reason` though that could be confusing because not all inactive jobs actually exited), i.e. if the job is inactive it returns some text describing  the exception if one occurred, otherwise a string with the return code, perhaps in shell-like form, e.g. `Exit 0`, `Exit 1`, `Killed`, `Terminated`, etc. Then we might have room for start and end times which might be nice.

**Comment by chu11** [comment]
> What about a new "contextual" field in JobInfo that returns the "exit reason" (we could actually call it exit_reason though that could be confusing because not all inactive jobs actually exited), i.e. if the job is inactive it returns some text describing the exception if one occurred, otherwise a string with the return code, perhaps in shell-like form, e.g. Exit 0, Exit 1, Killed, Terminated, etc. Then we might have room for start and end times which might be nice. 

Oh that's a good idea.
