### ISSUE TITLE
t2000-wreck.t: not ok 37 - wreckrun: error supported

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#498]
Looks like we have an intermittent failure of wreck test 37 in travis:

```
expecting success: 
	flux wreckrun --output=test2.out --error=test2.err \
	    sh -c "echo >&2 this is stderr; echo this is stdout" &&
        $WAITFILE 1 "this is stderr" test2.err &&
        $WAITFILE 1 "this is stdout" test2.out
this is stderr
this is stdout
waitfile: wakeup
waitfile: Timeout after 1s
not ok 37 - wreckrun: --error supported
```

**Comment by grondo** [comment]
Most likely a related error in a recent travis build
```
expecting success: 
	test_when_finished "flux kvs put lwj.output=" &&
	flux kvs put lwj.output.labelio=true &&
	flux kvs put lwj.output.files.stdout=test3.out &&
	flux wreckrun -n${SIZE} echo foo &&
	for i in $(seq 0 $((${SIZE}-1)))
		do echo "$i: foo"
	done >expected.kvsiocfg &&
	sort -n test3.out >output.kvsiocfg &&
        $WAITFILE 1 "" output.kvsiocfg &&
	test_cmp expected.kvsiocfg output.kvsiocfg
foo
foo
foo
foo
--- expected.kvsiocfg	2015-12-18 02:17:47.611040495 +0000
+++ output.kvsiocfg	2015-12-18 02:17:47.611040495 +0000
@@ -1,4 +0,0 @@
-0: foo
-1: foo
-2: foo
-3: foo
not ok 38 - wreckrun: kvs config output for all jobs
```

**Comment by dongahn** [comment]
I noticed that sync_flux_jstat now uses Lua waitfile support. Perhaps there is a subtle bug in it?

**Comment by grondo** [comment]
@dongahn, yes that is a good observation. I'll check that out.

**Comment by grondo** [comment]
Also, more specifically in the kvsiocfg test, the waitfile should be *before* the sort, not after.

**Comment by dongahn** [comment]
I think you nailed it!

For jsc's `sync_flux_jstat`, I previously had `while [ ! -f $fn -a $tout -ge 0 ]` so I probably was expecting a case where the file doesn't exit for a while.

**Comment by grondo** [comment]
Ok, I will propose a fix for some of these cases early tomorrow. I went through the test suite and tried to remove use of `sleep N` to get the testsuite to run faster (this was the impetus for creation of `waitfile`). However, that's no good if the testsuite is unreliable. But perhaps `waitfile` usage can be fixed up.

**Comment by dongahn** [comment]
Sounds good. Yeah removing sleep N is a good idea.

**Comment by grondo** [comment]
@dongahn: Just so I understand `sync_flux_jstat` is there to ensure `flux-jstat` is executing and ready to receive events? If `flux-jstat` opens it output file *after* subscribing to events, would this help remove the race seen in the `t2001-jsc.t` tests without an arbitrary `sleep`? 

We can't wait for data to appear in the output file via `waitfile.lua` because the `sync_flux_jstat` needs to complete before the jobs are actually run.

**Comment by dongahn** [comment]
@grondo: 

Thanks. Yes, the purpose of `sync_flux_jstat` is that. And also it should return the pid of `flux-jstat` so that the calling test can send SIGINT to `flux-jstat` process to make it exit at the end of each subtest. 

Now, there is indeed a slight race within `flux-jstat` between the creation of the output file and subscription of job events. I guess I did it this way because I didn't want to introduce another callback handler that depends on an external mechanism back then.  

Because `flux-jstat` isn't a module, for this to work properly, I need to start the reactor first and then rely on an external mechanism like the heartbeat event to invoke an epoch handler within which  I subscribe to job events (i.e., through `jsc_notify_status()`). And then create the output file. 

I know this works because I used it to implement `waitjob` within `flux-sched`: [waitjob.c](https://github.com/flux-framework/flux-sched/blob/master/sched/flux-waitjob.c). But this would make the code a bit complex of course. 

With this particular failure though, I want to understand if this slight race is actually causing the observed test failure. 

From @garlick's output: 

```
expecting success: 
run_flux_jstat 1 &&
p=$( sync_flux_jstat 1) &&
run_timeout 4 flux wreckrun -n4 -N4 hostname &&
cat >expected1 <<-EOF &&
$trans
EOF
cp output.1 output.1.cp &&
kill -INT $p &&
test_cmp expected1 output.1.cp 
testing-worker-linux-docker-8ea8c977-3196-linux-7
testing-worker-linux-docker-8ea8c977-3196-linux-7
testing-worker-linux-docker-8ea8c977-3196-linux-7
testing-worker-linux-docker-8ea8c977-3196-linux-7
./t2001-jsc.t: 9: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
not ok 1 - jstat 1: notification works for 1 wreckrun
```

It seemed to me what's not there is the pid returned from `sync_flux_jstat`, which is used by `kill`. But the code used in this shell subroutine, `waitfile.lua 2 "" output.$1 && cat jstat$1.pid` tells me that, by the time waitfile returns, `jstat$1.pid` should exit but it seems not??

So my suspicion is, this could be yet another race between `flux-jstat` output file creation and `jstat$sess.pid` file creation. Perhaps

```
waitfile.lua 2 "" jstat$1.pid && waitfile.lua 2 "" output.$1 && cat jstat$1.pid`
```

will work a bit better?

**Comment by grondo** [comment]
Ah, yes, I indeed forgot that what is missing is the PID in the failure quoted. I think your fix would certainly help.

Why doesn't `run_flux_jstat` just return the pid on stdout? This might allow us to get rid of an extra file, the subshell, and consequently one place where we are waiting for a file to appear?

**Comment by grondo** [comment]
> Because `flux-jstat` isn't a module, for this to work properly, I need to start the reactor first and then rely on an external mechanism like the heartbeat event to invoke an epoch handler within which I subscribe to job events (i.e., through jsc_notify_status()). And then create the output file.

I'm most likely not understanding the way it works, but can you subscribe to events (assuming event subscribe is synchronous), then open output file within the serial part of the code, then start the reactor?
(I realize now, however, that this is off topic for this issue though)

**Comment by dongahn** [comment]
> Why doesn't run_flux_jstat just return the pid on stdout? This might allow us to get rid of an extra file, the subshell, and consequently one place where we are waiting for a file to appear?

Sure, this can certainly be done. Just to understand:

```
run_flux_jstat () {
    sess=$1
    flux jstat -o output.$sess notify &
    echo $?
}
```

?

The current script probably is a result of various various synchronization tries back then anyway.

**Comment by grondo** [comment]
Ok, let me try it out and see if you like it

**Comment by dongahn** [comment]
> I'm most likely not understanding the way it works, but can you subscribe to events (assuming event subscribe is synchronous), then open output file within the serial part of the code, then start the reactor?
(I realize now, however, that this is off topic for this issue though)

Because the subscribed events will not be delivered to `flux-jstat` until its reactor starts, I think there will still be a slight race. 

Say, `flux-jstat` somehow got context-switched out right after the output file is opened but before its reactor started. In the meantime, the testing script will go ahead and submit jobs, but I think the job events that were emitted before `flux-jstat` resumes and starts the reactor will not be delivered to jstat.

If we want to make this completely airtight, I think the reactor should start first before `jstat` subscribes to the events unless I misunderstand how pub/sub works with reactor. 

@garlick: is my understanding right?

**Comment by dongahn** [comment]
@grondo: sounds good.

**Comment by grondo** [comment]
> Because the subscribed events will not be delivered to flux-jstat until its reactor starts, I think there will still be a slight race.

I think messages will be queued until you process them via a reactor callback or `flux_recv`. I could be mistaken though and you are right to get @garlick to verify it, but otherwise how could anything work?

**Comment by grondo** [comment]
I noticed `sync_flux_jstat` is always called right after `run_flux_jstat`, so why don't we do away with `sync_flux_jstat` for now and use `run_flux_jstat` something like this?

(run_flux_jstat prints PID of jstat then waits for output file to appear before returning to caller)

```diff
diff --git a/t/t2001-jsc.t b/t/t2001-jsc.t
index f6ced61..09a52f6 100755
--- a/t/t2001-jsc.t
+++ b/t/t2001-jsc.t
@@ -23,23 +23,11 @@ $tr4
 $tr5"
 
 run_flux_jstat () {
-    sess=$1
-    rm -f jstat$sess.pid
-    (
-        # run this in a subshell
-        flux jstat -o output.$sess notify & 
-        p=$!
-        cat <<HEREDOC > jstat$sess.pid
-$p
-HEREDOC
-        wait $p
-        #rm -f output.$sess
-    )&
-    return 0
-}
-
-sync_flux_jstat () {
-    $SHARNESS_TEST_SRCDIR/scripts/waitfile.lua 2 "" output.$1 && cat jstat$1.pid
+    ofile="output.$1"
+    rm -f ${ofile}
+    flux jstat -o ${ofile} notify >/dev/null &
+    echo $! &&
+    $SHARNESS_TEST_SRCDIR/scripts/waitfile.lua -v 2 "" ${ofile} >&2
 }
 
 overlap_flux_wreckruns () {
@@ -57,8 +45,7 @@ overlap_flux_wreckruns () {
 }
 
 test_expect_success 'jstat 1: notification works for 1 wreckrun' '
-    run_flux_jstat 1 &&
-    p=$( sync_flux_jstat 1) &&
+    p=$(run_flux_jstat 1) &&
     run_timeout 4 flux wreckrun -n4 -N4 hostname &&
     cat >expected1 <<-EOF &&
 $trans
```

**Comment by dongahn** [comment]
Looks like a great improvement: I see no flaw in your code. Once Travis likes it, I will also copy this code to `flux-sched.` Thanks.

**Comment by grondo** [comment]
NP! This is coming with some other changes to `waitfile.lua` which should allow more robust other tests that use that script so look for a PR toward the end of today.

Thanks for your help @dongahn!

**Comment by grondo** [comment]
This issue should be fixed or worked-around in #504. Closing.

**Comment by dongahn** [comment]
@garlick:

Sorry, this is a closed case, but can you please comment on one question @grondo and I posted above as to when our communication system starts to queue up the subscribed events for an API user like `flux-jstat`? Would it be at the end of `flux_event_subscribe` or after the starting of reactor? 

I somehow thought the case was the later -- i vaguely remember I had a little testing for this before, and I used some tricks to accommodate this synchronization assumption. 

If the case is indeed the former and my assumption was wrong, this will simplify things for me. 

Thanks.

**Comment by garlick** [comment]
Sorry I missed that @dongahn!  @grondo's statement above is correct.  Messages queue after the subscribe.  It's not even necessary to have a reactor to receive events with `flux_recv()`.
