### ISSUE TITLE
Plans for disconnect/reconnect of brokers?

### ISSUE THREAD

**Issue by trws** [flux-framework/flux-core#499]
As of now, any broker dying kills an entire flux instance.  I'm labeling this as an issue for 1.0, but the sooner we start thinking about how to handle death/disconnection of brokers and connection of new brokers the better off we're likely to be.

**Comment by garlick** [comment]
Brokers should detect when one of their children becomes unresponsive and then send out an event notifying their grandchildren to reconnect the TBON to the grandparent.  I called this "self healing" since the TBON at least can become whole again even if other aspects of the session are not.

However, the design expects that EPGM is used for event distribution so events get delivered even with breaks in the TBON.  Not the case currently unless --enable-epgm is used.

Then there's the problem of what to do with requests in flight...

**Comment by trws** [comment]
The other thing that occurs to me is that we have an implicit assumption in a few places that:

1) There is a defined number of brokers we can reason about (n_ranks)
2) The number of brokers doesn't change dynamically
3) There is a balanced tree topology with a single root (leader death being the main issue here)

What's hitting me is that I think, hopefully incorrectly, that even if the TBON is self-healing and we lose a non-root broker, we may have other components that fritz out because of invalidation of the constraint that size is constant or that all ranks live forever.  It's the "MPI trap" in a sense.

**Comment by garlick** [comment]
I can't find the issue, but an idea was to have collective operations like barriers, fences, even rpc_multi, accept a group handle that could cause those operations to abort if a group member dropped out.  That would go some way towards addressing, for example, services that perform a fence over the whole session and hope for the best like resource-hwloc.  I felt that groups of this nature should be first instance abstractions.

All we have at present is the data in the kvs that flux-up reports.

**Comment by grondo** [comment]
You mentioned the idea in #447 I think.

**Comment by garlick** [comment]
Note the live module is no longer loaded by default, so my comments above about "self healing" are not relevant anymore.  This has turned into a major design topic for the "bootstrap instance", tracked in #755.  In fact let's close this one and update the 1.0 tracking to point to #755.
