### ISSUE TITLE
prepending /usr/bin to PATH may be inconvenient

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#5016]
Problem: When invoked as `/usr/bin/flux`, the `flux(1)` command driver prepends `/usr/bin` to PATH. This can be inconvenient for users that are using the system-installed flux with some side installed versions of other software. By re-inserting `/usr/bin` at the front of `PATH`, flux is causing these users to, perhaps unknowingly, use the system versions of other software in `/usr/bin`.

One workaround is to invoke flux without the absolute path. In this case, `flux(1)` assumes that `PATH` needs to modification. However, this may not always be possible, so perhaps we should have a set of paths that are not prepended, e.g. `/usr/bin`? This needs more thought, since this would cause the wrong `flux` to be invoked if, for example, a user running a side install flux wanted to invoke the system installed `flux` in `/usr/bin`. :thinking: 

Another option might be to walk the current `PATH` and only insert the `flux` executable path as far up in `PATH` as is necessary to make the current executable the new default. In some cases this may mean the path does not need to be moved at all.

**Comment by trws** [comment]
I just got back to this email from CEA, we run into this issue with RPATHs as well, and usually resolve it by having a list of "system paths" that never get added to the DT_NEEDED section even if it can cause ordering problems.  It's not necessarily ideal as you point out, but it means the user asked to slice their own invocations of flux by the way they set their paths and invoked us, rather than us reordering things for them at least.

The other thing we could do is check which flux is found in path and see if it's the same as `/proc/self/exe` or not.  I was considering using that as a way to get us away from the compiled-in path issue as well at some point too FWIW.
