### ISSUE TITLE
inconsistent time zones used in error message timestamps

### ISSUE THREAD

**Issue by ryanday36** [flux-framework/flux-core#5081]
minor issue: a user was asking about the following errors from the `flux broker` in one of his job logs:

```
639 2023-03-30T11:09:03.246032Z broker.err[0]: rc2.0: /tmp/flux-script-356672498529469440-rjRz2F Hangup (rc=129) 43189.5s
640 2023-03-30T11:09:03.245610Z broker.err[5]: runat_abort cleanup (signal 14): No such file or directory
641 2023-03-30T11:09:03.276023Z broker.err[13]: rc3.0: /etc/flux/rc3 Hangup (rc=129) 0.0s
642 2023-03-30T11:09:03.275590Z broker.err[10]: rc3.0: /etc/flux/rc3 Hangup (rc=129) 0.0s
643 2023-03-30T11:09:03.275687Z broker.err[8]: rc3.0: /etc/flux/rc3 Hangup (rc=129) 0.0s
644 2023-03-30T11:09:03.276284Z broker.err[12]: rc3.0: /etc/flux/rc3 Hangup (rc=129) 0.0s
645 2023-03-30T11:09:03.276515Z broker.err[11]: rc3.0: /etc/flux/rc3 Hangup (rc=129) 0.0s
646 2023-03-30T11:09:03.276134Z broker.err[9]: rc3.0: /etc/flux/rc3 Hangup (rc=129) 0.0s
647 2023-03-30T11:09:03.277069Z broker.err[14]: rc3.0: /etc/flux/rc3 Hangup (rc=129) 0.0s
648 2023-03-30T11:09:03.277616Z broker.err[15]: rc3.0: /etc/flux/rc3 Hangup (rc=129) 0.0s
649 E: (flux-broker) 23-03-30 04:09:03 [497787]dangling 'PAIR' socket created at shmem.c:148
650 E: (flux-broker) 23-03-30 04:09:03 [244723]dangling 'PAIR' socket created at shmem.c:148
651 E: (flux-broker) 23-03-30 04:09:03 [445731]dangling 'PAIR' socket created at shmem.c:148
652 E: (flux-broker) 23-03-30 04:09:03 [325344]dangling 'PAIR' socket created at shmem.c:148
653 E: (flux-broker) 23-03-30 04:09:03 [328434]dangling 'PAIR' socket created at shmem.c:148
```

It looks like the job timed out and entered cleanup at 23-03-30 04:09:03, so I assume all of those messages are from the job teardown. It was somewhat confusing the have some of the messages displaying the time in UTC and others in the local time of the cluster though. Since `flux jobs` displays timestamps in local time, it seems like the error messages should all use that as well.

**Comment by chu11** [comment]
seems reasonable to me, all that would have to be adjusted is `wallclock_get_zulu()`'s use of `gmtime` and use `localtime` instead (and we should probably rename the function too, since "zulu time" wouldn't make any sense anymore).

as a side note, the latter 5 log messages are coming from `czmq`.  AFAICT we cannot adjust czmq's log messaging, so we're stuck with localtime for them.  So if we want to have them be equivalent we only adjust on the flux side.

**Comment by grondo** [comment]
> seems reasonable to me, all that would have to be adjusted is wallclock_get_zulu()'s use of gmtime and use localtime instead 

I don't think it is as simple as that. I believe storing log timestamps in UTC is purposeful (the logging code is using the RFC standard syslog wire protocol). Syslog and the broker keep timestamps in UTC so that when you _display_ them you can reliably convert to local time if desired. For example, if you made this change, you'd break `flux dmesg`.

The correct fix here would be some way to convert log messages to localtime as they are displayed to stderr by the broker. Note there is already a parsing function for syslog timestamps in `flux dmesg`.

**Comment by grondo** [comment]
And actually, I'd want @garlick to comment here before any changes were made since he probably best understands the nuances of the broker logging.
