### ISSUE TITLE
SLURM environment confuses flux-launched intel MPI > 2019.0.5

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#5206]
Problem: as noted in #5203, newer intel MPI apparently uses hints from the SLURM environment to determine process mapping for shared memory use, and when slurm launches flux, and flux launches intel MPI, things can go badly with multiple tasks per node, e.g.
```
$ flux run -n4 -N2 ./test.exe
9.911s: job.exception type=exec severity=0 MPI_Abort: Fatal error in PMPI_Init: Other MPI error, error stack: MPIR_Init_thread(176)...:  MPID_Init(1516).........:  MPIDU_Init_shm_init(180): unable to allocate shared memory
Abort(1090831) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init: Other MPI error, error stack:
Abort(1090831) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init: Other MPI error, error stack:
MPIR_Init_thread(176)...: 
MPIR_Init_thread(176)...: 
MPID_Init(1516).........: 
MPID_Init(1516).........: 
MPIDU_Init_shm_init(180): unable to allocate shared memory
MPIDU_Init_shm_init(180): unable to allocate shared memory
forrtl: error (78): process killed (SIGTERM)
Image              PC                Routine            Line        Source             
forrtl: error (78): process killed (SIGTERM)
test.exe           0000000000404CC4  Unknown               Unknown  Unknown
libpthread-2.17.s  00007F589E1C3630  Unknown               Unknown  Unknown
Image              PC                Routine            Line        Source             
libmpi.so.12.0.0   00007F589ECF93F3  Unknown               Unknown  Unknown
test.exe           0000000000404CC4  Unknown               Unknown  Unknown
libmpi.so.12.0.0   00007F589E9D44B2  Unknown               Unknown  Unknown
libpthread-2.17.s  00007FA18298B630  Unknown               Unknown  Unknown
libmpi.so.12.0.0   00007F589EC6D3A0  Unknown               Unknown  Unknown
libmpi.so.12.0.0   00007FA1834C13F3  Unknown               Unknown  Unknown
libmpi.so.12.0.0   00007F589EC6CC5B  MPI_Init              Unknown  Unknown
libmpi.so.12.0.0   00007FA18319C4B2  Unknown               Unknown  Unknown
libmpifort.so.12.  00007F58A00FD85B  PMPI_INIT             Unknown  Unknown
libmpi.so.12.0.0   00007FA1834353A0  Unknown               Unknown  Unknown
test.exe           0000000000403B71  Unknown               Unknown  Unknown
libmpi.so.12.0.0   00007FA183434C5B  MPI_Init              Unknown  Unknown
test.exe           0000000000403B12  Unknown               Unknown  Unknown
libmpifort.so.12.  00007FA1848C585B  PMPI_INIT             Unknown  Unknown
libc-2.17.so       00007F589DB06555  __libc_start_main     Unknown  Unknown
test.exe           0000000000403B71  Unknown               Unknown  Unknown
test.exe           0000000000403A29  Unknown               Unknown  Unknown
test.exe           0000000000403B12  Unknown               Unknown  Unknown
libc-2.17.so       00007FA1822CE555  __libc_start_main     Unknown  Unknown
test.exe           0000000000403A29  Unknown               Unknown  Unknown
flux-job: task(s) exited with exit code 1
```
So perhaps we should (re-?)consider unsetting some or all slurm environment variables (shell plugin?  broker environment blocklist?)   There are some old issues that discuss this (#864, #223) but at some point I think we decided against blocking SLURM_*.  Maybe this requires a bit of thought/discussion/research.

**Comment by grondo** [comment]
I'm trying to think of a use case where a user would want to access some Slurm environment variables from the initial program of a Slurm-launched Flux instance, and it feels like that would be a use case we would want to discourage since it would hurt the portability argument for using Flux. Not to mention that I can't think of a valid use case at the moment.

If we then admit that we should be sanitizing foreign RM environment for Flux jobs, it does seem reasonable to conclude that we should be doing that in the broker env blocklist, since otherwise every submitted jobspec would contain useless environment variables removed by a job shell plugin. (Though I guess another approach would be a default remove glob for the python cli submission commands, but there doesn't currently exist a way to enable that).

Since the number of Slurm environment variables is as countless as grains of sand on the seashore, we might need to support a glob in the broker env blocklist, and since Slurm isn't the only RM for which this may pose a problem, I wonder if there's some way to make it runtime configurable...

**Comment by garlick** [comment]
I did write an [unsetenv_glob()](https://github.com/flux-framework/flux-pmix/blob/main/src/common/libutil/unsetenv_glob.c) for use in flux-pmix (with tests) that could be pulled in.

**Comment by grondo** [comment]
Sounds great! The one use case that comes to mind where we might want a Flux instance to know it is running as a Slurm job is to discover the time limit of a Flux instance run via Slurm. However, I think we have proposed other mechanisms to support this, so I think I'm all for santizing other RM variables from the initial program environment.
