### ISSUE TITLE
job-exec: shell service name reconstruction may be fragile to mismatched locale configuration

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#5257]
Problem: as noted in #5256, the job-exec module reconstructs the shell's service name to send the rank 0 shell an exception message when one of the other job shells goes offline, but when f58 encoding is used, this becomes somewhat fragile to mismatched locale configuration, especially as the job-exec module is further developed into a distributed service.

There may be other ways to notify rank 0 or to obtain the service name without reconstructing it.  This issue is for considering alternatives.

**Comment by grondo** [comment]
A few alternatives mentioned in #5256:

 - Make it unnecessary for job-exec to send an RPC directly to the job shell by having the job shell watch for lost shell exception in the job eventlog. The shell would have to parse the affected shell rank from the exception note.
 - The job shell could respond with its service name in the barrier protocol instead of just writing `enter`.
 - The job-exec module could fetch the service name from the exec eventlog only when necessary.

**Comment by garlick** [comment]
Hmm, maybe for non UX sitautions such as this one, we ought to have an "f58 plain" encoding that always uses f instead of ƒ?

I'd also kind of like that so I can use f58 encoded job IDs in system unit names.  (systemd balks at ƒ).

**Comment by grondo** [comment]
That's a great idea!

**Comment by garlick** [comment]
Fixed by #5297
