### ISSUE TITLE
consider flux-python-binding project

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#527]
I wanted to float the idea of splitting the python bindings out of core.

There are two pain points resulting from having it in:
* python bindings have to track iterative flux-core api evolution
* when make check runs, python tests are the first ones that launch a comms session, so any disruption during development is first detected as a python binding failure, a little harder to run down than if we hit that in the early sharness tests.

Now that flux-core releases are being tagged, if we pulled the python bindings out, we could update them on the flux-core release cycle rather than as we go.

I think the bindings can be generated from the installed header files, i.e. access to flux-core source would not be a requirement?

A downside is that `flux-list-instances` and `flux-lstopo` would also need to be relocated.

I know we discussed this at length when these went in and arrived at the current situation.  I may not remember all the reasons, but have we moved into a different phase of the project where the argument may have shifted somewhat?

**Comment by trws** [comment]
Could those two pain points be alleviated by building and testing the bindings after the sharness tests are run?  I suppose not since the lua bindings are actually in the sharness tests, but I suppose that brings up the subsequent question, could it be solved by using sharness for the python tests with numbering such that they're run last?  Either of these would seem less disruptive, at least to me, than actually moving the bindings out of core.

The worry on my end is that if they move out of core they'll go out of sync more easily and wont be usable in tools in core.  As of now, the list of such tools is short, so maybe that's insufficient, but that was a big part of the reasoning before.

**Comment by garlick** [comment]
I'm not sure how much work it would be @trws, but if we could move the python tests that require a running instance to sharness, numbered to run late, that would help a lot.  The lua tests already work this way.

**Comment by trws** [comment]
It would take some refactoring, but probably just a couple of hours of concentrated work.  I'll check into it and see if I can make that change.

**Comment by trws** [comment]
Well, my estimate was wrong.

For once, in a pleasant direction. =)

PR coming in a couple of minutes with a *minimal* patch to run python tests after all other tests.  It may need extra poking with, because my environment is a little wonky right now, but it does run the python tests, and runs them dead last.
