### ISSUE TITLE
crashed nodes are drained with generic epilog failure messages

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#5391]
Problem: node crashes tend to result in drained nodes with "reasons" like `epilog failed for jobid f28XEx4Rf73d`, which is not as helpful as it could be.

Request from the sys admins is to somehow indicate that "no route to host" is the reason.  Otherwise they have to go digging in the logs to see what part of the epilog script might have failed.

**Comment by grondo** [comment]
The epilog is currently run via the `flux-perilog-run.py` helper command.

One solution would be to skip attempting to run `flux exec -r{rank}` on nodes that are currently offline at the time the script is started, since `flux exec` will definitely fail, and instead preemptively drain the node with a specific error `node was offline for job ID epilog` or similar.

I assume in our environment the flux broker is not started on nodes until there is manual intervention, so there wouldn't necessarily be a race here where the node would come back in time to run the epilog successfully even though it had crashed.

**Comment by watson6282** [comment]
Correct.  We still require a manual `nodeup` to start the flux broker (and other stuff) after a node reboot.  It takes over ten minutes for a node to reboot back to a point where `nodeup` can be run.  I'm assuming that is long enough for the epilog-running process to complete and drain these down nodes.  We are also very unlikely to `nodeup` nodes that don't have a drain message.
