### ISSUE TITLE
Clean up use of exit() from modules

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#540]
The following modules apparently use `msg`||`err_exit` and thus will cause broker to hard exit on failure. These should be replaced with `flux_log` based error messages and either exit `mod_main` or send failure RPC message:
```
$ git grep -E --line-number '(msg|err)_exit' .                                                                                              
barrier/barrier.c:78:            err_exit ("flux_get_rank");
connector-local/local.c:115:            err_exit ("flux_get_reactor");
kvs/kvs.c:816:            msg_exit ("%s: unexpected DIRVAL: path=%s name=%s: dirent=%s ",
kvs/kvs.c:823:            msg_exit ("%s: unknown dirent type: path=%s name=%s: dirent=%s ",
kvs/kvs.c:922:            msg_exit ("%s: corrupt internal storage", __FUNCTION__);
live/live.c:178:            err_exit ("flux_get_rank");
live/live.c:189:            err_exit ("flux_reduce_create");
pymod/py_mod.c:94:        msg_exit ("optparse_add_option_table");
pymod/py_mod.c:96:        msg_exit ("optparse_set usage");
wreck/job.c:146:        err_exit ("kvs_get_dir (id=%lu)", id);
wreck/wrexec.c:86:            err_exit ("flux_get_rank");
wreck/wrexec.c:88:            err_exit ("flux_attr_get local-uri");
wreck/wrexec.c:160:        err_exit ("fork");
wreck/wrexec.c:172:        err_exit ("setenv");
wreck/wrexec.c:175:        err_exit ("execvp");
wreck/wrexec.c:192:        err_exit ("fork");
```

**Comment by grondo** [comment]
FYI I'm working on the major violators here: `wrexec` and `job`

**Comment by garlick** [comment]
Partially fixed by PR #541 (wreck) and PR #539 (live, barrier)

**Comment by trws** [comment]
I think the resource-hwloc module has this issue also.  Is there a way, from a reactor callback, to register a failure with the reactor and cause it to kill the module rather than the full system?  Perhaps that's what an error RPC does?

**Comment by garlick** [comment]
Sorry I missed this question @trws!   See flux_reactor_create(3) which describes
```
void flux_reactor_stop (flux_reactor_t *r);
void flux_reactor_stop_error (flux_reactor_t *r);
```
The latter causes `flux_reactor_run()` to return -1 (otherwise it returns 0).  Typically when the reactor returns, `mod_main()` exits, which effectively kills the module without killing the broker.

#559 asks the question whether returning -1 from `mod_main()` should kill the broker.  I think so, that way modules can decide if a fatal error to the module should be fatal to the session.  For most of the built-in modules that would be the case.  Currently a -1 return just results in a LOG_CRIT message.

**Comment by trws** [comment]
Thanks @garlick.  I was thinking I could update the flux_check methods to use that, or something similar, as a module fatal rather than session fatal error mechanism for in-recoverable errors.  Looks like it should work for that purpose, would that be useful for this to make an easy replacement for err_exit and similar?


________________________________

**Comment by garlick** [comment]
The flux_check macros were dropped in pr #539 when we weaned resource-hwloc off it (to avoid killing the broker) and it no longer had any users.  That "assertion style" of error handling is a bit heavy handed for non-fatal errors as then you may need to free resources on your way out from the reactor callback and/or return error responses to RPC's.

So I guess I vote for not bringing back that sort of thing, particularly for use within comms modules.

**Comment by garlick** [comment]
I think this is in large part addressed.
