### ISSUE TITLE
"is not a tty" when starting flux programmatically

### ISSUE THREAD

**Issue by andre-merzky** [flux-framework/flux-core#5427]
Hi Fluxies, 

we start a flux instance via a command line which is executed from Python via popen.  At that point though we do not have a tty nor a pty, and the flux startup fails because of that.  Is there a recommended way to start a flux instance w/o a tty, but via command line?  FWIW, we gab the flux URI from the command output, so some means to derive the flux URI after start would still be needed.

The somewhat convoluted way we run flux is this:

```py
check = 'flux env; echo "OK"; while true; do echo "ok"; sleep 1; done'
start = 'flux start -o,-v,-S,log-filename=%s.log' % self._uid
cmd   = '/bin/bash -c "echo \\\"%s\\\" | %s"' % (check, start)
```

so we run an interactive flux shell and feed it `flux env` commands in order to grab the URI in the output, and then send `echo` commands to confirm shell health by watching the output.  There likely is a better way to do this? :-)

**Comment by grondo** [comment]
The warning: `"stdin is not a tty - can't run interactive shell"` should only occur if there is no argument to `flux start` (in which case the default argument is `$SHELL`), or if the number of arguments to `flux start` is 1 and it is a shell (i.e. present in `/etc/shells`). This prevents users from accidentally running `flux start` non-interactively and thinking that `flux start` is hung because the shell will not display a prompt.

It doesn't seem like your case above should trigger this error though, since there is more than one argument `/bin/bash -c "echo ..."`, so I admit to be being a bit confused :slightly_smiling_face: 

BTW, how I'd run a non-interactive `flux start` locally is just to run `echo $FLUX_URI && sleep inf` as the shell command line. I may not be understanding why you need the shell `"ok"` loop, but that should work I'd think in place of the `sleep inf`...

Here's my proof of concept if this helps -- I don't seem to get a 'not a tty' error from this even when `stdin` is `/dev/null`, but I may still be doing something wrong, so please correct me if so:
```sh
#!/usr/bin/python3

import sys
import subprocess
import time

import flux

cmd = ["flux", "start", "bash", "-c", "echo $FLUX_URI && sleep inf"]

sp = subprocess.Popen(
    cmd,
    stdin=subprocess.DEVNULL,
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE,
    encoding="utf-8",
)

local_uri = sp.stdout.readline().rstrip()
print(f"connecting to pid={sp.pid} listening on uri {local_uri}")

h = flux.Flux(local_uri)

# Run jobs in subinstance with h, etc.

# Tell Flux to shut down and wait for shutdown to complete:
h.rpc("shutdown.start").get()

# Copy any stdout/err from subprocess
stdout, stderr = sp.communicate()
print(stdout)
print(stderr, file=sys.stderr)

sp.wait()
```

```console
$ flux python test.py
connecting to pid=2742843 listening on uri local:///tmp/flux-JvkvJ7/local-0

Sep 06 07:42:53.164275 broker.err[0]: rc2.0: bash -c echo $FLUX_URI && sleep inf Hangup (rc=129) 0.0s

```

**Comment by grondo** [comment]
BTW a couple other bits of info that may be helpful

 - The flux broker will exit once the command you've instructed it to run exits, so e.g. `flux start sleep 10` will cause the broker (the thing launched by `flux start`) to exit after 10s. (Not sure if that is why you're using the `sleep 1; echo "ok"` loop?
 - There is a [flux-uri(1)](https://flux-framework.readthedocs.io/projects/flux-core/en/latest/man1/flux-uri.html) command and also a Python [FluxURIResolver](https://flux-framework.readthedocs.io/projects/flux-core/en/latest/python/autogenerated/flux.uri.uri.html#flux.uri.uri.FluxURIResolver) class that can resolve a Flux or Slurm jobid to a URI, or even a PID to a URI in case this is useful, e.g. `flux uri pid:1234` will attempt to get the URI for process id `1234`.

**Comment by andre-merzky** [comment]
Sorry for the late response - too many things going on...  But mostly thanks for the response, that is right on target and I consider the issue resolved at this point!
