### ISSUE TITLE
default begin-time dependency format in `flux jobs`

### ISSUE THREAD

**Issue by ryanday36** [flux-framework/flux-core#5465]
from the department of minor fixes, currently, `flux jobs` displays the begin-time dependency timestamp in seconds from the epoch. Could this be changed to display a human readable date time instead?

```
[day36@rzvernal10:~]$ flux jobs -A
       JOBID QUEUE    USER     NAME       ST NTASKS NNODES     TIME INFO
 fUf7ibZRKFD pdebug   jdkotul  gemma       D    256     32       3h depends:begin-time=1695430800.000
...
[day36@rzvernal10:~]$ date -d @1695430800
Fri Sep 22 18:00:00 PDT 2023
[day36@rzvernal10:~]$
```

**Comment by grondo** [comment]
Valid request! However, this is going to be slightly tricky because of the way dependencies work and how outstanding dependencies are transmitted back to `flux jobs` from the `job-list` service.

Dependencies are represented as a set of strings, added by a `dependency-add` event, then removed by a `dependency-remove` event. Internally, the outstanding dependencies (holding a job in the DEPEND state) are thus represented as a set of strings. For the `begin-time` dependency, the string is just `begin-time=T`,  where `T` is floating-point seconds since the epoch, i.e. the UNIX time. When `flux jobs` gets the list of current dependencies, it just gets the current set of dependency strings and prints them as is. This is partially done because these dependency strings or descriptions are considered somewhat opaque and extensible.

Given these limitations, there are a couple approaches we could take:

 - Have the `begin-time` dependency plugin represent the time as something more human readable. This would be simplest but has the drawback that any such representation would have to pick a timezone (likely the timezone of the broker process) and use that for the representation. This may not match the user's actual timezone, so this could be confusing (but could be mitigated by appending the timezone to the description)
 - Add some special handling for `begin-time` dependencies in `flux jobs` or the underlying `JobInfo` class. The code would need to walk the set of dependencies looking for `begin-time=`. Since it is known that the remainder of the string is a timestamp, it could parse this and replace with a datetime rendered in the current timezone. This method could be extended to handle other known dependencies in the future if needed.

**Comment by grondo** [comment]
Well patching something into `JobInfo` was pretty easy as a prototype.

For instance, we could show the simple begin time if the job is scheduled to run today, the date otherwise:
```
flux jobs
       JOBID USER     NAME       ST NTASKS NNODES     TIME INFO
   ƒ6DBbeYzK grondo   hostname    D      1      -        - depends:begin=17:11:55
   ƒ6FuQt6sH grondo   hostname    D      1      -        - depends:begin=Sep23-17:01:55
```
