### ISSUE TITLE
jobtap history plugin throws errors

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#5475]
In one of @vsoch's cloudy experiments, in  the output of a failing intel MPI job, we noticed two jobtap errors:

```
jobtap: job.new: callback returned error
jobtap: job.inactive.add: callback returned error
```

The only jobtap in-tree that registers `job.inactive-add` is `history`.  Maybe there is something to run down here or at least a couple places where log messages could be added to give us something to go on next time.

**Comment by grondo** [comment]
Just reporting that another user hit this same issue when trying to set up a small system instance. (using flux RPMs on TOSS)

Looking at the code, the only way the history plugin returns an error from these callbacks is if `hola_list_insert()` fails:
```c
        if (!hola_list_insert (hist->users, int2ptr (userid), entry, false)) {
            job_entry_destroy (entry);
            return -1;
        }
```

Maybe adding a `flux_log_error()` at these spots would help run down the issue.

**Comment by grondo** [comment]
Ah, this user reports they are running jobs (and the flux-broker) as uid 0, which will cause `hola_list_insert()` to fail since `int2ptr(0) == NULL`. Perhaps we should actively discourage running the flux-broker as root by checking for that in the broker. However, for now maybe the `history` plugin should just ignore root jobs, or should add a check specific to uid 0 and give a meaningful error message.

**Comment by vsoch** [comment]
I see this all the time in containers (with root) and I just ignore it.

**Comment by grondo** [comment]
Well now we know you can suppress the errors with `flux jobtap unload .history`

**Comment by vsoch** [comment]
Nice! I'll add that to my containers.

**Comment by garlick** [comment]
`(uid_t)-1` is apparently [reserved](https://pubs.opengroup.org/onlinepubs/009695399/functions/chown.html) per POSIX so maybe we can just map root to that within the cache?
