### ISSUE TITLE
t/ executables are dyanmically linked

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#5519]
I can't remember the rationale for a5806b68763062a14e2c68f4d1ae5dff7aea2cca where we added a test to ensure unit tests were statically linked to project libraries.  I noted that test executables under `t` are dynamically linked just wondered if whatever the reason was should apply there too.

**Comment by grondo** [comment]
The description of why is in the previous commit f718a8650e07c833403d6c88ab49d775576fd1ee. I'm not sure if the same problem linking dynamically with a system libflux-core.so was ever seen with the test programs under `t` since they are being run in the context of system testing and not standalone like unit tests.

I think we didn't apply `-no-install` to tests in `t` because those are supposed to be linked more like an externally built program would be for more authentic testing, however it would indeed be bad if they are linking with the wrong libflux-core.so at runtime.

**Comment by garlick** [comment]
Ah sorry I think I was filtering the commit log when looking back in history.  My bad!  Great explanation in that commit message.
