### ISSUE TITLE
jansson version requirement on SLES

### ISSUE THREAD

**Issue by mattaezell** [flux-framework/flux-core#5544]
`flux-core` requires `jansson` 2.10 (#3240), but SLES provides `jansson` version 2.9 (even sles15-sp5). It looks like you really just needed a feature from 2.8 but selected 2.10 because it is what was in EL7. Would you be willing to relax the version requirement to make SLES packaging easier? It compiles fine against 2.9, and I haven't found any issues in my testing to date. `make check` fails with:
```
not ok 2 - flux_open on loop works
FAIL: test_subprocess.t 2 - flux_open on loop works
#   Failed test 'flux_open on loop works'
#   at test/subprocess.c line 86.
```
but it's not clear this is related, as I don't have a "clean" build with newer `jansson` on this platform.

**Comment by garlick** [comment]
I don't _think_ that will cause any problems for us.  We do have to be a bit careful because the Flux C API has some calls with pack/unpack style arguments that are fed directly to jansson internally, but I don't see anything in the [release notes for 2.10](https://jansson.readthedocs.io/en/latest/changes.html#version-2-10) that would cause trouble.

Aside: if that test is failing in 'make check' then I would presume many other tests would be failing too?  Also, I believe the system tests in `t` won't run if any of the unit tests are failing.  We should get all that resolved.  Feel free to open issue(s).

**Comment by grondo** [comment]
When the minimum required version for Jansson was bumped to 2.10, two updates were made in commits 1df44be97c8d10cf4f695dac07d389683c5320ac and 28261f0f5bf23ba4ce325a77489a9622d9aab13f: Use of `O?` and `json_string_length()`. These features were added in 2.8 and 2.7 respectively, so it also seems to me that 2.9 would work without issue.
