### ISSUE TITLE
flux in the last year

### ISSUE THREAD

**Issue by zhuwqvip** [flux-framework/flux-core#5640]
hello.
Last year we tested the functionality of flux on 10 compute nodes and it seems to be working very well, but flux is still a work in progress. I would like to ask when flux will be released in the future. It's been a year since we tested it, and we want to know what major improvements flux has made in the past year? I look forward to hearing from you

**Comment by garlick** [comment]
Hi - releases are usually monthly and [here](https://github.com/flux-framework/flux-core/blob/master/NEWS.md) are the release notes for all flux-core releases of the last year.  If I had to summarize some major items
- the addition of batch directives
- abiltiy to update duration of a job (even while running)
- memory cgroups (v2) confinement
- better PMI configurability
- many user interface improvements

Flux has been running as the primary resource manager on several  smaller clusters at LLNL and many of the changes came about due to feedback from users accustomed to Slurm.

There are some improved flux-core docs here too:
https://flux-framework.readthedocs.io/projects/flux-core/en/latest/

Were there specific features you were waiting hoping to see in Flux?

**Comment by grondo** [comment]
This has been answered, so I'm closing for now. Feel free to reopen if there wasn't enough detail in the answer, or open other issues for specific questions, Thanks!
