### ISSUE TITLE
flux-core.pc should provide configured path settings

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#572]
As briefly discussed in flux-framework/flux-sched#115, it is possible to export autoconf-generated paths via flux-core's pkg-config file, and thus eliminate some duplication/guesswork in framework projects.

Examples of things we might set in `flux-core.pc`:
- bindir=@fluxbindir@ for locating flux(1)
- libexecdir=@fluxlibexecdir@ for aux executable install location
- cmddir=@fluxcmddir@ for flux(1) subcommand install location
- libdir=@fluxlibdir@ for flux libraries that are added to LD_LIBRARY_PATH only for child programs
- moddir=@fluxmoddir@ for comms module install location
- connectordir=@fluxconnectordir@ for connector install location
- includedir=@fluxincludedir@ for header file install location
- luadir=@fluxluadir@ for lua lib install location

**Comment by grondo** [comment]
This is a good idea and I guess I can't see a good reason *not* to do it. It might help framework projects determine where they should install their products.

**Comment by garlick** [comment]
Maybe there should be a flux-framework.pc just for this sort of stuff?

**Comment by morrone** [comment]
Maybe this should be removed from the 0.7.0 milestone.  It is not clear that making a new .pc file for a non-existent library is really kosher.  And it sounds like the information flux-sched needed was resolved satisfactory.

If we want to work on the .pc files in the future, we probably need to first decided what type of library interface we want to present to the outside world.  Right now we have one giant .pc file that links in many little libraries.  That isn't really kosher for a .pc file either.  There is supposed to be a .pc file per library, with library interdependencies expressed in the "Libs.private" rather than in "Libs".

To avoid users needing to add a dozen pkg-config commands to use flux-core, we might combine some of the libraries into a single externally visible library.  Some (liboptparse?) might remain stand-alone, and then certatinly would get their own .pc file.

But I suspect decisions about library organization need more time than will be addressed in 0.7.0.

**Comment by garlick** [comment]
Yes, more discussion required and that works for me.  I"ll drop this from 0.7.0
