### ISSUE TITLE
make preferred TBON network configurable by address

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#5754]
Problem: although the network addresses used in the system instance are configurable, the only way to force a subinstance to use a specific network is to set the FLUX_IPADDR_INTERFACE environment variable.

Sys admins may need a way to tell all Flux instances to use a particular network.  Ideally this would be by setting an attribute in the system instance config.  If configured, this setting would be inherited by progeny at any depth (e.g. via the batch/alloc config).

@grondo pointed out that CIDR notation to identify a network would be better ergonomics than interface names which are pretty strange and not even deterministic on some system configurations.

**Comment by grondo** [comment]
This came up again. Currently there is no way to force subinstances to use the management network on systems where the hostname is associated with the interconnect IP address. `FLUX_IPADDR_INTERFACE` won't work because the interface names are not consistent across the cluster. Sysadmins would really like Flux to use the management network (at least for now), but we currently have no way to let them configure that.

**Comment by grondo** [comment]
Another idea would be to allow a "default" config location, e.g. `$sysconfdir/flux/default/conf.d`, which is read first by all brokers if it exists. This would then be merged/overwritten by the config specified on the command line (e.g. from the `flux batch --conf=` or `flux alloc --conf=`.

This might be slightly easier to reason about than the inherited subinstance config, though I admit the inherited config is more interesting.

**Comment by garlick** [comment]
Perhaps we could close this issue once a `tbon.tcp_network` config key is added that works with a network address or interface, and then we could open another issue to discuss "global/sub-instance configuration"?

(On the latter, I thought we already had one but I'm not finding it)
