### ISSUE TITLE
Using local machine and restrict the maximum CPU can be used

### ISSUE THREAD

**Issue by unkcpz** [flux-framework/flux-core#5788]
Dear developers, I have a use case that I want to use my local machine as a cluster and use partial of its CPUs to run jobs. 
Let's say I have 32 CPUs in my machine, I want to use 16 CPUs for running calculations. It means the flux will handle the queue and put the jobs in waiting status when 16 CPUs are already used in the flux. How to tell the flux the maximum number of CPUs that it can use (and RAM if possible)?

**Comment by grondo** [comment]
Flux will detect the resources available to it at startup (using [hwloc](https://www.open-mpi.org/projects/hwloc/)), so an easy way to run flux on a subset of resources is to launch `flux start` under [taskset(1)](https://man7.org/linux/man-pages/man1/taskset.1.html) or [hwloc-bind(1)](https://linux.die.net/man/1/hwloc-bind).

```console
grondo@pi3:~$ flux start flux resource list -s free -o rlist
     STATE NNODES   NCORES    NGPUS LIST
      free      1        8        0 rank0/core[0-7]
grondo@pi3:~$ hwloc-bind core:0-3 flux start flux resource list -s free -o rlist
     STATE NNODES   NCORES    NGPUS LIST
      free      1        4        0 rank0/core[0-3]
```

Even if you specified cores `4-7` here, Flux will renumber the cores to `0-3`, however when launching job tasks they should still be constrained to real cores `4-7` since Flux will index the cores relative to those core it has access.

If you want to run a multi-user instance of Flux, then that would be a slightly different setup.

**Comment by garlick** [comment]
For multi-user, you may be able to edit the systemd unit file to set up [resource control](https://www.freedesktop.org/software/systemd/man/latest/systemd.resource-control.html) e.g. `AllowedCPUs` and `MemoryMax`, thus restricting flux to a given set of cores and memory using cgroups.

The [admin guide](https://flux-framework.readthedocs.io/projects/flux-core/en/latest/guide/admin.html) describes how to set up multi-user Flux which is a little more involved than what @grondo is describing, so his suggestion may be a better starting point.

**Comment by unkcpz** [comment]
Cool, thanks a lot for the help! I think that what I need, the single user solution is fit for my use case for the moment.

I notice with `--test-size <num>` can create more brokers than CPUs, is that possible let's say using 2 CPUs in total but can further separate it to run 4 jobs with each one using 0.5 CPUs? (Sorry if I confused with the terminology)

**Comment by unkcpz** [comment]
So I need to use `--test-size=2` I assume, it says "a test instance" is there any downside of using it, for my case to use local machine as a cluster I think it cover the use case?

**Comment by grondo** [comment]
There is no real downside except that you will be oversubscribing resources.

**Comment by unkcpz** [comment]
I gave a test for my use case, seems all works fine! Thanks a lot for the help, I close the issue as resolved.
