### ISSUE TITLE
hostlist: perf issue in `hostlist_find_host()` due to `hostname_create()`

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#5987]
@trws noted in some perf benchmarking of Fluxion that `hostlist_find_host()` and specifically `hostname_create()` was taking a large percentage of time due mainly to the `calloc(3)` used in creating the `struct hostname` used for matching purposes.

Consider a strategy that doesn't require memory allocation to speed up repeated use of `hostlist_find_host()`

**Comment by trws** [comment]
Thanks for filing this @grondo! To add a bit of context, here's a slice of the perf output from the updated version of sched:

<img width="690" alt="image" src="https://github.com/flux-framework/flux-core/assets/660149/57d81376-7d04-4e63-8c82-204adcf775b6">

Overall it looks like hostlist ends up spending a good amount of time on allocations, and on repeatedly calculating lengths.  Did we ever end up with a lib for string-with-length-and-capacity? It occurs to me because I'm working with the one git is using to fix the archive bug over there, and something like that would squash a lot of this and probably other similar things if we could easily pass those around.

**Comment by grondo** [comment]
I think this was addressed by #6259
