### ISSUE TITLE
parallel make check failures

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#601]
When using automake versions that support parallel test harness, it should be possible to run `make -j2 check` and perhaps get through the entire testsuite a bit more quickly.

However, when I tried this, a small number of tests failed with errors like this:

```
flux-start: setrlimit: could not remove core file size limit: Operation not permitted 
[1457758996.363964] kvs.err[2]: getroot: Function not implemented 
[1457758996.363998] kvs.crit[2]: fatal error: Function not implemented   
[1457758996.363998] kvs.crit[2]: fatal error: Function not implemented     
[1457758996.365206] broker.err[0]: rc1: flux-module: cmb.insmod[2]: Function not implemented 
[1457758996.366900] broker.err[0]: Run level 1 Exited with non-zero status (rc=1)
flux-start: 0 (pid 59230) exited with rc=1
ERROR: t1003-mecho.t - missing test plan 
ERROR: t1003-mecho.t - exited with status 1 
```

This could possibly be a resource exhaustion problem on c9.io host, but I thought I'd post it here for later investigation. The errors at least could use some improvement possibly.

**Comment by garlick** [comment]
I'm getting some decent speedup on my desktop (Ubuntu 16.04.1 LTS) with this, and no failures observed, e.g.
```
$ time make -j1 check
...
real	2m32.335s
user	1m11.952s
sys	0m27.324s

$ time make -j2 check
...
real	1m19.421s
user	1m11.432s
sys	0m25.220s

$ time make -j4 check
....
real	0m42.674s
user	1m6.944s
sys	0m23.984s

$ time make -j8 check
...
real	0m27.807s
user	1m7.220s
sys	0m22.740s
$ make -j16 check
...
real	0m25.205s
user	1m6.844s
sys	0m22.528s

```

Wow, to think of all the time I've wasted when there was a "go fast" button all along!

**Comment by garlick** [comment]
The errors in the description _look_ like kvs on rank 2 was loaded before kvs on rank 0.

There was a chain of prs starting with #586 which added tracking of module state transitions, and ending with #597 (merged march 12) which moved module loading to rc shell scripts.  Some of those changes addressed module loading synchronization, i.e. ultimately it became safe for rc1 to synchronously load kvs on rank 0, then load it on all other ranks, and prevent errors like the above from happening.

Since that sequence completed on mar 12 and this issue was created on mar 11, it's somewhat up in the air wether the error popped occurred on code with all those changes or not.  Likely not.

Given that ambiguity and the success reported above, let's close this and reopen if we see it again.
