### ISSUE TITLE
flux-queue: consider combining "status" and "list"

### ISSUE THREAD

**Issue by ofaaland** [flux-framework/flux-core#6145]
As a user, it seems like these two commands could be combined, and like that would be a more obvious user interface.  For example:

```
$flux queue list
QUEUE    DEFAULTTIME  TIMELIMIT     NNODES     NCORES      NGPUS   ENABLED   SCHEDULING
gateway          30m         1d      0-inf      0-inf      0-inf     yes        no
rabbit           30m         1d      0-inf      0-inf      0-inf     yes       yes
compute*         30m         5d      0-inf      0-inf      0-inf      no        no
```

In case it helps, some anecdotes:
I personally didn't notice there was a `flux queue status` command until today.  Part of the reason for that was that I did find `flux queue list`, and it didn't occur to me there would be a separate status command.

More generally, I think it would help to make it more visible, whether a queue is enabled and scheduling is started or not.

**Comment by grondo** [comment]
This is a pretty good idea. The reason `flux queue list` and `flux queue status` are different commands is because they query different subsystems (`flux queue list` queries configuration and `flux queue status` queries the job manager).

However, similar to `flux resource status` and `flux resource list`, information from the two subsystems can easily be combined here...
