### ISSUE TITLE
flux resource list doesn't display queue name when there are 0 resources in a state

### ISSUE THREAD

**Issue by ryanday36** [flux-framework/flux-core#6166]
`flux resource list` appears to list all possible states, but if there are no nodes in a given state, it doesn't list a queue name (or node list) for that state. At least, I think that's the issue. This can be a bit confusing. I would argue that it would be better to just not list the state if there are no nodes in that state, or to list all of the queues to show that there are 0 nodes in that state in any queues.

We've seen this in a couple of places. On corona, when there happened to be no jobs running:
```
corona212{gpt}40: flux resource list -o '{queue} {nnodes} {state} {nodelist}'
QUEUE NNODES STATE NODELIST
pdebug 15 free corona[171,173-186]
pbatch 84 free corona[188-194,196-207,213-214,219,221-250,252-253,255-259,261-269,272-275,277-280,282-285,287-290]
pnvmeof 5 free corona[292-296]
 0 allocated 
pdebug 1 down corona172
pbatch 15 down corona[187,195,215-218,220,251,254,270-271,276,281,286,291]
```

and on rzvernal when there happened to be no nodes down:
```
[day36@rzvernal10:src]$ flux resource list -o '{queue} {nnodes} {state} {nodelist}'
QUEUE NNODES STATE NODELIST
pdebug 23 free rzvernal[15,19,22,25-30,32-45]
mi300a 4 free rzvernal[48-51]
pdebug 11 allocated rzvernal[12-14,16-18,20-21,23-24,31]
 0 down 
[day36@rzvernal10:src]$
```

**Comment by grondo** [comment]
Yeah, unfortunately I think I have an idea of the issue here and it is probably a slight design flaw in the way `flux resource list` works. An empty resource set is used as a placeholder when there are no nodes in a given state. An empty resource set obviously has no associated queue. This goes back to when Flux didn't even yet support queues.

I think we can generate an empty resource set for every queue instead and it will just work, but I will try it.

**Comment by grondo** [comment]
Well, this is actually a bit awkward. Each line of `flux resource list` output represents a resource set (that would display unique information given the current format). When there are no resources in a state, an empty resource set is substituted. Of course, an empty resource set can't have any properties, and therefore do not belong to a queue, since a queue is assigned a set of resources by property.

The output does make a bit more sense with the default format:
```
     STATE QUEUE      NNODES   NCORES    NGPUS NODELIST
      free pdebug         16      768      128 corona[171-186]
      free pbatch         19      912      152 corona[187,195,215-218,220,251,254,270-271,276,281,285-286,288-291]
      free pnvmeof         5      240       40 corona[292-296]
 allocated pbatch         80     3840      640 corona[188-194,196-207,213-214,219,221-250,252-253,255-259,261-269,272-275,277-280,282-284,287]
      down                 0        0        0 
```

Since it is somewhat obvious that there are no down nodes overall, so none in any queue.

One solution might be to use allow a queue to be manually set on the `ResourceSetExtra` class specific to `flux-resource.py`, and when the resource set for a state is empty, add an empty set for each configured queue, instead of just a plain empty set.

This would probably fix this specific problem, but it wouldn't do anything for non-queue properties, and I kind of wonder if there is some inherent design flaw being exposed here.

Anyway, for now we could fix this specific issue (with the caveat that empty resource set lines won't ever have any properties), and then asses later when the next issue surfaces.
