### ISSUE TITLE
Suggestion: ability to specify a node range in flux jobs

### ISSUE THREAD

**Issue by kkier** [flux-framework/flux-core#6202]
Scenario:
As a sysadmin, I'm planning to do maintenance on an arbitrary set of nodes.  After draining those nodes, I'd like an easy way to return a list of jobs running on them so I can contact the job owners/see when they'll expire/kill them outright/whatever.  Something like `flux jobs -i <hostlist>` would make sense.

Design-wise, it arguably makes sense assume `-A` but that breaks the current paradigm.

**Comment by grondo** [comment]
Note there is _sort of_ a solution to this proposed in #5711. It adds a query syntax to the `-f, --filter` option that would allow you to get this result with `flux jobs -f host:<hostlist> -f running`. That PR has never been merged because there isn't good consensus on the interface.

Perhaps filtering `flux jobs` by hostlist would be common enough that it should get its own option. I like your idea of using the `-i, --include=hosts|ranks` from the `flux resource` utilities, though I also wonder if that could be confusing in `flux jobs` which isn't listing resources (and not all jobs even have had resources assigned).

Anyway, we could support this option and `and` it with other filter options including any result of an advanced filter from `-f, --filter=` in the future.
