### ISSUE TITLE
Flux not correctly binding a single GPU per task with `--gpus-per-task=1`

### ISSUE THREAD

**Issue by hagertnl** [flux-framework/flux-core#6239]
We are trying to enable using Flux within Slurm on Frontier, and the following job script:
```
#!/bin/bash

...

module load rocm/5.7.1
module load hwloc/2.9.1-gpu # a ROCm-enabled hwloc
module load flux # Flux version 0.60.0

...

# Flux flags:
#   -N 1 -- 1 node
#   -n 8 -- 8 tasks
#   -c 7 -- 7 cores per task
#   --gpus-per-task=1 -- 1 GPU per task (doesn't work)
srun -N $SLURM_NNODES -n $SLURM_NNODES -c 56 --gpus-per-node=8 flux start \
    "flux resource list;
     echo Starting launch at \$(date);
     for i in \$(seq 1 $SLURM_NNODES); do
        flux submit -N 1 -n 8 -c 7 -x --gpus-per-task=1 --output=output.\$i.txt bash -c 'hostname; env | grep VISIBLE; /usr/bin/time ./vadd';
     done;
     echo Finished launching at \$(date);
     sleep 10;
     flux jobs -a;
     flux queue drain;"
```
Results in each node getting a binding like this:
```
Rank 0 (of 8) sees 8 devices, ROCR_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
```
This message is printed inside the code via calls like `hipGetDeviceCount()`. We checked `CUDA_VISIBLE_DEVICES` and it is getting set to `0,1,2,3,4,5,6,7` as well.

We are using the default configuration options that come with Flux. Any thoughts on what is going wrong here?

**Comment by grondo** [comment]
I think what may be going on is that Flux only binds the _job_ to assigned resources by default, not each task.

Can you try adding the option `-o gpu-affinity=per-task` to your `flux submit` line and see if you get a different outcome?

**Comment by hagertnl** [comment]
That appears to work for setting the `CUDA_VISIBLE_DEVICES` environment variable, which HIP does appear to listen to. Each rank is now only seeing 1 device, as expected

**Comment by grondo** [comment]
Note that the same goes for cores, to get per-task binding you would need to specify `-o cpu-affinity=per-task` with default Flux. Be aware, however, that Flux may not pick cores that are topologically closest to the chosen GPUs in this scenario (an open issue see e.g. https://github.com/flux-framework/flux-sched/issues/1033).

The [mpibind](https://github.com/LLNL/mpibind/blob/master/tutorials/flux/README.md) Flux plugin can help mitigate this effect for now, since it is good at choosing the correct GPUs given a set of cores. If you did decide to use `mpibind`, then best practice for now is to leave off `-o gpu-affinity=per-task` and `--gpus-per-task` and let mpbind set `CUDA_VISIBLE_DEVICES` based on the allocated cores.

Hope that wasn't too confusing :disappointed:

**Comment by hagertnl** [comment]
Thanks! That answered my next 2 questions -- why doesn't my CPU affinity work and how do I get optimal bindings :) Thanks for the help!

**Comment by grondo** [comment]
I think this one's been answered, so closing. Please feel free to reopen or open a new issue if not!
