### ISSUE TITLE
flux-sharness.sh

### ISSUE THREAD

**Issue by lipari** [flux-framework/flux-core#654]
In an effort to leverage the features and functionality of flux-core's test facility, flux-sched has setup its own test directory closely modeled after flux-core.  To facilitate this, we have done periodic copies of the latest t/sharness.d/flux-sharness.sh into the flux-sched's equivalent directory.
Today's effort to update this script ran into a snag with the $FLUX_SOURCE_DIR variable.  FLUX_SOURCE_DIR is not defined in the flux-sched project.

We are faced with having to maintain flux-sched's local version of flux-sharness.sh and doing periodic hand merges from flux-core of changes as they appear in flux-core.  Alternatively, flux-core's version could be designed to be generic and apply to flux-sched and all future flux projects.  flux-core-specific definitions and logic could be moved to an external file and be referenced by the generic flux-sharness.sh.

@dongahn and I are not quite sure what the best solution is, but we wanted to capture the need in an issue.

**Comment by grondo** [comment]
Original intent was to allow `flux-sharness.sh` to be copied verbatim to other framework projects, which then extend their own version of sharness with `flux-<name>.sh` in the `sharness.d` directory.

Unfortunately, it appears the `test_under_flux` "personality" support broke this, but it could be easily fixed by only allowing that functionality if `FLUX_SOURCE_DIR` is set and not empty.

Ideally, flux-core`s `sharness.sh` and `flux-sharness.sh` would be installed as part of flux-core or flux-core-devel package and could be somehow sourced from framework projects without being copied around. However, that is somewhat anathema to the original design of sharness so I don't know how much work it would be.

I can propose a fixup for the current breakage I think.

**Comment by grondo** [comment]
Actually looking at the `flux-sharness.sh` code FLUX_SOURCE_DIR is only used when `$personality != "full"`.. The personality rc scripts are all in flux-core source dir, and flux-sched tests probably mostly need "full" personality anyway so could you just use default rc scripts from the distribution?

Is there something else breaking?

**Comment by dongahn** [comment]
@grondo: thank you for the quick reply.

This doesn't break anything because sched uses the full personality for now. 

What @liparti and I werent sure was how future proof this would be. 

To reduce potential side effects my preference woukd to control the logic only specific to flux core more tightly. 

The rc personality loguc would be one example because other projects wont have access to flux core's source directory. 

Perhaps flux core test can define project specific variable and contain such a logic underneath it. Or one can have base flux sharness other project should copy and flux core specific sharness as well
