### ISSUE TITLE
avoid broker deadlock during module teardown

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#666]
As noted in pr #659, if a comms module registers a destructor for handle aux state that makes an RPC, the broker can be blocked in `pthread_join()` while the module is blocked in the RPC.

Possibly some assurances need to be made that the FLUX_MODSTATE_EXITED message doesn't go out on the module socket, triggering the `pthread_join()` until the aux state is destroyed.

**Comment by grondo** [comment]
Also, I would argue for removing blocking calls in the reactor main loop wherever possible. The blocking `pthread_join()` could be replaced with `pthread_tryjoin_np()` (not portable). If the `pthread_join()` is guaranteed to return due to design change above, then `tryjoin()` is still preferred as it could assert the expected result, and `pthread_kill()` the misbehaving module if need be.

**Comment by garlick** [comment]
That sounds like a good defensive strategy.

**Comment by grondo** [comment]
Closed by #2713
