### ISSUE TITLE
capture IB topology aware scheduling use case details

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#750]
Tim Meier @meier asked about Flux's support for network topology aware scheduling.  He recently met with one of Abhinov's students (Jens?) who is attempting to alter IB routes on the fly to track running jobs scheduled by SLURM as part of his research.  Tim felt that a better approach would be to have the RM be smarter about placement up front, and keep the routes (relatively) static, which is I think in agreement with what we were considering.

I know our [resource description language](https://github.com/flux-framework/rfc/blob/master/spec_4.adoc) (RDL) was designed from the outselt to represent a tree-topology network, although support for scheduling network as a resource remains a research topic at this point for us.

Tim pointed out that while routing tables are mostly static, at times they have to route around a bad link and so have to be monitored.  The subnet manager (SM) knows the routing topology at any given moment, and Tim maintains software that acts as intermediary between the SM and other entities that may need to track the routes.

Tim was interested in how Flux would interface with his software, and in general wanted to explore this use case in more detail to be sure we get this done, hence I wanted to create this issue and solicit comments from other project members and Tim to capture any details that might move this forward a bit.  Possibly we could follow this up with a meeting if that would be beneficial.

For starters, @meier would you mind providing a link to your software and if you have it, a link to Jens' work?  Also if you'd like to add to or correct anything above, please add your comments.  Perhaps others can explain in more detail how this would work in Flux as I know others have a deeper understanding of the plans in this space.

**Comment by meier** [comment]
You captured my interest and my general feeling that it may be more appropriate for the scheduler/resource manager be aware of the static and dynamic (routing, bw, traffic, and errors) conditions in the fabric, so it could place jobs to avoid congestion and latency issues.  The difference between the two approaches boils down to pro-active vs re-active.

Jens Domke is the summer student doing research on his "scheduling-aware routing" algorithm.  It basically polls information from the batch system, and tries to dynamically optimize routes for jobs.
[Job Aware Routing](http://sc15.supercomputing.org/sites/all/themes/SC15images/tech_poster/poster_files/post179s2-file3.pdf)
He has been testing his algorithms on systems in Germany, Japan, and his home University.  I will be incorporating his code into our Subnet Manager for a DAT on cab in the next few weeks.

I will be interested to see the results of the DAT.  Perhaps a combination of both approaches would work best.  But at a minimum, Flux probably shouldn't assume that the routes are ideal and static.

**Comment by lipari** [comment]
The scheduler’s role is essentially to take a job’s resource request and schedule those resources at the soonest appropriate time.  The scheduler has to not only look for resources over a time frame that extends into the future; it has to filter its selection based on a number of factors.  For example, does the user have permission to access those requested resources?  Are there limits imposed on the use of those resources?  Etc.  There is a second order concern when resource requests involve relationships to other resources.

In all these cases, the scheduler works with an internalized model of all the resources under its control.  The simplest model is a 1:1 mapping of an array to a resource.  Nodes are typically modeled this way.  A more complex model which the Flux scheduler uses is a tree to represent composite relationships.  One can schedule thing A along with thing B which thing A has.

The solution to scheduling network topology lies in the model the scheduler can use to represent the resource and gauge whether and how much of it can be allocated to a job.  In addition, this model must be dynamically changing as real-world conditions vary.  One idea that I have planned is to model this relationship as a tree that mirrors physical connections between switches and interfaces.  One could model the connection between each “node” in the tree as a flow with a bandwidth capacity as well as individual quantities allocated to each job scheduled to utilize that connection.

But this model might only be applicable to the most basic of bandwidth scenarios.  An alternate idea would be to create a “resource manager” specifically to model all the complexities @meier described.  This could be just another service (or distributed services) loaded by a flux broker(s) somewhere and specifically tasked with monitoring and controlling the network.  Under this plan, the scheduler would relegate the model to a specialized service and query that service with the most basic requests:  i.e, can I get X bandwidth between these two resources and use it for one hour at some time in the future?

This second approach might work best with Jens Domke’s research, particularly if the work is self-contained.  All that would be needed would be crafting the appropriate API’s a scheduler could use to interrogate and direct the network manager service.

**Comment by garlick** [comment]
One loose thought:  I recall hearing that message injection rate was more critical to the performance of our apps than bandwidth.  Is that what network-aware scheduling should be focused on?  (I have no idea how message injection rate relates to topology/routing).

**Comment by dongahn** [comment]
For the upcoming DAT, I think Slurm already has topology aware scheduling so one can explore topo+static, vanilla+dynamic and topo+dynamic to see the impacts more systematically?

What I was told about slurm's topo aware scheduling is that this additional network constraint quickly leads to resource underutilization and as part of best effort polict, it quickly becomes ineffective (can't satisfy topo constraint so it just ends up not considering network topi after the machine state becomes complex enough). 

Maybe adaptive routing is more dynamic and complement what a job scheduler can do. I have to believe a hybrid will probably be the best but unless this space is explored we don't know.

One thing about slurm's topo aware scheudling is that I couldn't find a paper describing its effectiveness. So don't quote me on that. I just hears about this from various ppl.

**Comment by garlick** [comment]
Ah right, see Hierarchical Networks section of SLURM  [Topology Guide](http://slurm.schedmd.com/topology.html).

I wonder if it would be useful or interesting to pull in the IB topology at job bootstrap like we do with hwloc?  If that's useful maybe that could be a "help wanted" issue that @meier could contribute to?
Then the path to converting to RDL or internal sched representation might be clearer.

**Comment by grondo** [comment]
That is a great idea!

**Comment by meier** [comment]
The routing algorithm we (llnl) primarily use is "fat tree", which is static until some sort of exceptional condition happens (bad links), at which point the entire fabric will be re-routed.  Attempts have been made to employ dynamic routing, but I believe substantial hardware support in the switches is necessary to do that well.

So even though the topology/routing is expected to be static, it is not uncommon for a well-behaved fabric to be re-routed a few times per month as issues occur and are addressed.

BW utilization is a more dynamic attribute of the fabric.  More than half of the links in a fabric can be shared.  Managing that sharing is what Jens is attempting to do for the purpose of optimizing performance.  His algorithm will watch traffic on links, looking for signs of congestion, and conditionally re-route the fabric so that links aren't "over subscribed".  How effective this can be, I think, would depend on the nature of the jobs that are running, and how fast routing changes can be made.

I suppose some jobs are very IO intensive, and would rather not share BW, while others could probably peacefully share links with several jobs.  It might be nice if the scheduler had a "hint" of the type of IO pattern a job is expected to use.  The scheduler could take that information into account when assigning/allocating resources for a job.  Ideally, it could avoid the need to dynamically re-route.

Side Note:  I have monitored several clusters for a few years, and our fabrics (on average) utilize far below 15% of their BW.  Peak utilization is difficult to measure, but I suspect its under 30%.  Jens/Abhinav have a suite of jobs for their DAT that can exercise the fabric, stress the BW limits of links, and cause the type of congestion that would trigger his system to re-route the fabric.  It will be interesting to see.

**Comment by garlick** [comment]
Closing old issue
