### ISSUE TITLE
Issues running autogen.sh under spack

### ISSUE THREAD

**Issue by SteVwonder** [flux-framework/flux-core#770]
When compiling flux under spack, autogen.sh fails.  @trws and I were able to fix it by adding an additional execution of aclocal after libtoolize.  @grondo suggested moving the discussion to an issue under flux-core.  He also suggested trying `autoreconf -i`.

Related spack issue: https://github.com/LLNL/spack/issues/1213
Related build log: https://gist.github.com/SteVwonder/9a5f2d7b839cb0ecafc9ed08abe7f1a7

**Comment by grondo** [comment]
Thanks @SteVwonder! If `autoreconf -i` works I propose we just copy flux-sched `autogen.sh` to flux-core. Feel free to submit a PR or I can if you are busy with other work.

Thanks!!

**Comment by SteVwonder** [comment]
When running `autoreconf -i`, I get the exact same error.

**Comment by SteVwonder** [comment]
When I swap the ordering of commands so that libtoolize is first, followed by aclocal, it works:

```
spack env flux ./autogen.sh
Running libtoolize ...
Running aclocal ...
Running autoheader ...
Running automake ...
configure.ac:31: installing config/compile
configure.ac:9: installing config/config.guess
configure.ac:9: installing config/config.sub
configure.ac:15: installing config/install-sh
configure.ac:15: installing config/missing
doc/man3/Makefile.am: installing config/depcomp
parallel-tests: installing config/test-driver
src/bindings/python/flux/Makefile.am:92: installing config/py-compile
Running autoconf ...
Cleaning up ...
Now run ./configure.
```

**Comment by grondo** [comment]
Is Spack installing its own autotools, or using the system autotools?

**Comment by SteVwonder** [comment]
It can definitely install it's own autotools, but the Flux spack package
doesn't explicitly depend on the autotools spack package, so I think it
defaults to the system version.

My advisor is in town and wanted to get dinner, so I cannot verify right
now. I'll will look either tonight or first thing tomorrow morning.

**Comment by grondo** [comment]
oh, no prob! Will look at this more tomorrow. I do find it strange that flux `autogen.sh` works fine outside of spack with system autotools, but not under Spack. I'd like to understand that out before adding the aclocal changes described here.

**Comment by grondo** [comment]
I installed spack and attempted to build flux with `spack install flux`. It did fail (actually had to update libsodium to version 1.0.5 since 1.0.3 isn't on downloads page anymore) as you say.

However, it does look like custom autotools are installed (possibly dependency of some other package?)

```
$ ./spack find
==> 33 installed packages.
-- linux-redhat6-x86_64 / gcc@4.4.7 -----------------------------
asciidoc@8.6.9   libgpg-error@1.21    lua@5.1.5             python@2.7.12
autoconf@2.69    libjson-c@0.11       m4@1.4.17             readline@6.3
automake@1.15    libpciaccess@0.13.4  munge@0.5.11          sqlite@3.8.5
bzip2@1.0.6      libsigsegv@2.10      ncurses@6.0           xz@5.2.2
czmq@3.0.2       libsodium@1.0.5      openssl@1.0.2h        zeromq@4.1.2
docbook-xml@4.5  libsodium@1.0.10     pkg-config@0.29.1     zlib@1.2.8
hwloc@1.11.3     libtool@2.4.6        py-cffi@1.1.2
libffi@3.2.1     libxml2@2.9.2        py-pycparser@2.13
libgcrypt@1.6.2  libxslt@1.1.28       py-setuptools@20.7.0
```

In this case, how will the custom `aclocal` find m4 macros installed by other packages (like libtool)? Does spack modify the [ACLOCAL_PATH](https://www.gnu.org/software/automake/manual/automake.html#Macro-Search-Path)?

**Comment by trws** [comment]
I'm not sure, that's worth checking though.  I think if it does a clean autogen it has libtool pull in the macros to the local configuration, but I haven't tested it.





On August 16, 2016 at 9:18:22 AM PDT, Mark Grondona <notifications@github.com> wrote:

I installed spack and attempted to build flux with spack install flux. It did fail (actually had to update libsodium to version 1.0.5 since 1.0.3 isn't on downloads page anymore) as you say.

However, it does look like custom autotools are installed (possibly dependency of some other package?)

$ ./spack find
==> 33 installed packages.
-- linux-redhat6-x86_64 / gcc@4.4.7 -----------------------------
asciidoc@8.6.9   libgpg-error@1.21    lua@5.1.5             python@2.7.12
autoconf@2.69    libjson-c@0.11       m4@1.4.17             readline@6.3
automake@1.15    libpciaccess@0.13.4  munge@0.5.11          sqlite@3.8.5
bzip2@1.0.6      libsigsegv@2.10      ncurses@6.0           xz@5.2.2
czmq@3.0.2       libsodium@1.0.5      openssl@1.0.2h        zeromq@4.1.2
docbook-xml@4.5  libsodium@1.0.10     pkg-config@0.29.1     zlib@1.2.8
hwloc@1.11.3     libtool@2.4.6        py-cffi@1.1.2
libffi@3.2.1     libxml2@2.9.2        py-pycparser@2.13
libgcrypt@1.6.2  libxslt@1.1.28       py-setuptools@20.7.0


In this case, how will the custom aclocal find m4 macros installed by other packages (like libtool)? Does spack modify the ACLOCAL_PATH<https://www.gnu.org/software/automake/manual/automake.html#Macro-Search-Path>?

-

**Comment by grondo** [comment]
> I'm not sure, that's worth checking though.  I think if it does a clean autogen it has libtool pull in the macros to the local configuration, but I haven't tested it.

@trws, I think that may be the problem here. In a system install, libtool macros are in a common system path that is in default `aclocal` macro search path. In the case of spack or other systems that install packages in their own roots, `aclocal` has no way to find the libtool (or any other macro-providing package) macros, and thus `libtoolize` must first be run to copy or link the macros into the current project config path.

If spack packages could prepend to `ACLOCAL_PATH` then this could be solved generically. `libtoolize` first perhaps works in this case, but if there were other packages providing macros it wouldn't work.

Of course, I'm speculating here, but here's a very old similar problem from mpich:
 http://trac.mpich.org/projects/mpich/ticket/1053

I actually don't see a problem with running aclocal before and after libtoolize, or perhaps we should change autogen.sh to run `libtoolize && autoreconf -i` -- however, like I said if we ever depend on some macros from another package that isn't libtool this won't work I don't think

(probably we should update `flux-sched` too?)

**Comment by grondo** [comment]
Hmm, I still can't get flux-core to build under spack, looks like `libffi.so.6` is not in LD_LIBRARY_PATH?
```
Traceback (most recent call last):
  File "_core_build.py", line 3, in <module>
    ffi = FFI()
  File "/g/g0/grondo/git/spack/opt/spack/linux-redhat6-x86_64/gcc-4.4.7/py-cffi-1.1.2-3elvpt5xlzvhwdgizfd4s6d4t5dcg2nj/lib/python2.7/site-packages/cffi-1.1.2-py2.7-linux-x86_64.egg/cffi/api.py", line 56, in __init__
    import _cffi_backend as backend
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
make[5]: *** [_core.c] Error 1

$ find ~/git/spack -name libffi.so.6 
/g/g0/grondo/git/spack/opt/spack/linux-redhat6-x86_64/gcc-4.4.7/libffi-3.2.1-zcwtp45bs4zbd22clwxgmuoypwu7kehs/lib64/libffi.so.6
```

Know what I'm doing wrong?

**Comment by SteVwonder** [comment]
That is a separate bug with py-cffi, I have a fix for that in this branch: https://github.com/Stevwonder/spack/tree/py-cffi-rpath-fix

**Comment by SteVwonder** [comment]
It looks like spack is pulling in the custom libtool even though the flux package does not depend on it:
```
# herbein1 at hype356 in /tmp/herbein1/spack-stage/spack-stage-c3Hnkd/flux-core on git:master ✖︎ [11:07:22]
→ spack env flux which libtool
/g/g17/herbein1/Repositories/spack/opt/spack/linux-redhat6-x86_64/gcc-4.4.7/libtool-2.4.6-icw6h4fakzo6kcf2m4zwqn73nqw362us/bin/libtool
```

It also appears that spack does not edit the ACLOCAL_PATH, but we can edit the spack package to modify the ACLOCAL_PATH if necessary.
```
# herbein1 at hype356 in /tmp/herbein1/spack-stage/spack-stage-c3Hnkd/flux-core on git:master ✖︎ [11:07:37]
→ spack env flux printenv ACLOCAL_PATH

```

**Comment by grondo** [comment]
Even though this is likely an issue with spack autotools environment, I didn't see any harm in running libtoolize before autoreconf, so I threw up PR #771
