### ISSUE TITLE
implement kvs_link()

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#778]
As described in pr #777, it may be useful to have a KVS operation that allows a KVS key to be mapped directly to a blobref.  This could facilitate testing where a (potentially large) KVS hierarchy could be mapped into the namespace in one go.  It could also be used in cases when a reduction is needed to scalably build up KVS information.

**Comment by garlick** [comment]
Just realized: If we also add the converse of this function, e.g. `kvs_getref()`, the `kvs_move()` and `kvs_copy()` operations would no longer need to be recursive, and would consist of two synchronous RPCs instead of as many as there are keys in the namespace being moved/copied (plus one).

copy:
```
kvs_getref (h, src, &ref)
kvs_link (h, dest, ref)
kvs_commit (h);
```

move: 
```
kvs_getref (h, src, &ref)
kvs_link (h, dest, ref)
kvs_unlink (h, src);
kvs_commit (h);
```

Since `kvs_move()` is on the critical path for job completion, this may be something we want sooner rather than later.

**Comment by grondo** [comment]
> Since kvs_move() is on the critical path for job completion, this may be something we want sooner rather than later.

The above seems like a huge improvement to moving and linking things into the kvs! However, I'm not sure the `kvs_move()` is currently critical path for job completion. The `kvs_move()` is called after the job is marked completed (assuming that the move is transactional, observers should be unaware). 

However, don't let that stop you from implementing the above sooner rather than later!

**Comment by garlick** [comment]
Ah, that's kind of cool that it's _not_ on the critical path actually.
