### ISSUE TITLE
throughput slowdown on recent master

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#784]
As noted by @dongahn flux-framework/distribution#14, a generic "slowdown" in job throughput was noted between current master (181d3ca827be91cbe7f80f5991607987e08ba316) and a previous state (fd8723b2539b116e24aceae9c024ac82a8da1a0c).

Currently bisecting using the following "script"
```sh
./autogen.sh &&
  ./configure && 
  make clean &&
  make -j 32 &&
  time src/cmd/flux start -s 4 'for i in $(seq 1 100); do flux wreckrun -n 4 sleep 0; done'
```

In the "good" case the sequence of 100 wreckruns takes on the order of 10s, on current master it is consistently 25s.

**Comment by grondo** [comment]
`git bisect` resulted in:

```
483bad856f0638c3ac9a09de6291042affbe94b2 is the first bad commit
commit 483bad856f0638c3ac9a09de6291042affbe94b2
Author: Jim Garlick <garlick.jim@gmail.com>
Date:   Mon Aug 22 12:53:06 2016 -0700

    modules/kvs: increase commit aggregation window + cleanup

```

I guess it makes sense since the latency of kvs commits was increased by a factor of 50. Perhaps it would make sense to allow this to be tunable for high throughput scenarios? (If I've indeed understood the situation correctly)

**Comment by dongahn** [comment]
Ah. Yes, this makes sense. 

I think we probably want to make it tunable, perhaps even at runtime? In fact, when all is said and done, I want to provide "named" scheduling choices to the users such that they can specialize their flux instance according to the characteristics of their workload. Some discussions are [here in this comment](https://github.com/flux-framework/flux-sched/issues/183#issuecomment-241594056). flux-core dials like this can be adjusted for each named choice along with other scheduling dials (e.g., queue depth, reservation depth, scheduling policy...)

**Comment by dongahn** [comment]
BTW, I had a dinner with one of my former interns some time back. And what his team is currently working on is to provide "experiments as services" so that users can choose provide representative inputs and their service give the best scheduling choices... I can see us headed in that kind of directions in the distance future and having a good set of tunables will give good choices for us.

**Comment by dongahn** [comment]
It is also not clear if the previous small window setting will work well as I will increase the job sizes. 

I will probably get some interesting data points tomorrow but my preliminary result seems to indicate, as I increase job sizes (e.g., "half" sizing policy at increasing numbers of CNs), job throughput becomes job-size-bound. If this is indeed the case, I will again have to tease apart whether this scheduling performance limiting factor is due to flux-core performance and/or scheduler's own performance (my guess is again both). But it may be a case where there is no one-size-fit-all solution. Stay tuned.

**Comment by garlick** [comment]
Can this be closed now that #788 is merged?

**Comment by grondo** [comment]
I think so since I verified the testcase above now "passes" at least. If @dongahn sees more throughput issues with his testing it should probably go into a new issue.

**Comment by dongahn** [comment]
Sounds good. I will update my flux-core to the latest then.
