### ISSUE TITLE
Allow string error in addition to errno in rpc/msg error responses?

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#796]
While errno error responses are easy, in more complex cases they are possibly unhelpful. I can't think of a technical reason why a full string description of errors could not be sent back to callers in addition to an error number.

This might also help avoid the inevitable boundless-increase-in-custom-error-numbers, as seen in other projects...

**Comment by garlick** [comment]
Yeah, that would be nice.  Thinking out loud about implementation and minimizing changes to the code base:

Trivial to change RFC 3 (message format) and RFC 6 (RPC).

Not too hard to change the raw RPC interfaces in a backwards compatible manner, e.g. `flux_rpc_get()` could return -1 with errno set as usual on error, and a new function `flux_rpc_get_errorstr()` or similar could return the helpful context, if any was set on the other end.  On the other end possibly a specialized version of `flux_respond()` could be added that takes a reason string.

It's a bit trickier to think how to change functions that encapsulate the whole rpc life cycle like `kvs_get()` so that a string could be plucked out.  I suppose one could capture it in the handle and have something like `const char *flux_get_last_errorstr(h)` to pull it out.

Maybe functions that encapsulate a synchronous RPC will be replaced with async versions that preserve the rpc state anyway until explicitly destroyed anyway?

**Comment by grondo** [comment]
Good points, thanks!

I like your suggestions above as it was almost precisely what I was thinking. I think the async functions lend themselves very nicely to holding any error message as you say, and that for now a `flux_get_last_errormsg (h)` is a good stopgap.

**Comment by garlick** [comment]
Just to be sure we're on the same page, the string response would not be a replacement for `errnum` (or rather `flux_strerror (errnum)`) but an additional explanatory context that would be optional.  Right?

In other words, errors might be logged like this:
```C
const char *s = flux_get_last_error_reasno (h);
flux_log (h, LOG_ERR, "kvs_get: %s (%s)",
          flux_strerror (errno), s ? s: "unknown");
```
not like this
```C
const char *s = flux_get_last_error_reason (h);
flux_log (h, LOG_ERR "kvs_get: %s", s ? s : flux_strerror (errno));
```

(And of course helpers like `flux_log_error()` could hide all this)

**Comment by grondo** [comment]
Yes, I was thinking it would be optional just as youve proposed.

**Comment by garlick** [comment]
I have a use case that really calls out for this feature.  I was hoping to implement an API call for job submission that could fail immediately without creating a jobid, returning a more detailed error response than just a numerical POSIX errno, for example "more cores requested than could exist in the universe".   While a submit RPC could return a success response with an error message in the payload, it just feels like bad API design.  It would be much better to be able to have the RPC fail in the usual way _and_ be able to get the detailed error message.

I propose to add a function that allows an optional error string to be returned in the response payload as described above.  It would be used by request handlers:
```c
// errstr can be NULL; if non-NULL it becomes response message payload
int flux_respond_error (flux_t *h, const flux_msg_t *request,
                        int errnum, const char *errstr);
```
then add a function that returns the best textual error message available after an RPC failure:
```c
// always valid: on success, flux_strerror (0); 
// on failure, detailed message if available, else flux_strerror (errnum)
const char *flux_rpc_get_error (flux_future_t *f);
```

A user of an API call that wraps `flux_rpc()` would be able to retrieve the error string with `flux_rpc_get_error()`.  For example, my job submission function might look like:
```c
// submit job described by 'jobspec'.
flux_future_t *flux_job_submit (flux_t *h, const char *jobspec, int flags);

// get jobid if job was successfully submitted
int flux_job_submit_get_id (flux_future_t *f, flux_jobid_t *jobid);
```
and a command line utitility that uses it might look like this:
```c
flux_future_t *f;
flux_jobid_t jobid;

if (!(f = flux_job_submit (h, jobspec, 0)))
    fatal ("submit: %s", flux_strerror (errno));
if (flux_job_submit_get_id (f, &id) < 0)
    fatal ("submit: %s", flux_rpc_get_error (f));
flux_future_destroy (f);
```
