### ISSUE TITLE
t1008-proxy.t: not ok 20 - flux proxy with ssh:// and bad jobid fails, when run under existing instance

### ISSUE THREAD

**Issue by grondo** [flux-framework/flux-core#817]
Just wanted to add this issue before I forget. On current master b532e12c6abf509f97045dc052e615904a38fa03, one of the `flux proxy` tests is failing when run under an existing instance. 

The failing test is:
```
not ok 20 - flux proxy with ssh:// and bad jobid fails
#	
#		! FLUX_SSH=$TEST_SSH FLUX_SSH_RCMD=$TEST_FLUX \
#		  flux proxy ssh://localhost/0 flux getattr size
#	
```

It appears, in my current environment, that jobid `0` on localhost is actually valid:
```
$ src/cmd/flux start
$ flux getattr local-uri
local:///var/tmp/grondo/flux-0-a2LrYR/0
```

From another window
```
$ src/cmd/flux proxy 0 flux getattr local-uri
local:///var/tmp/grondo/flux-0-a2LrYR/0
```

**Comment by garlick** [comment]
I think before I had said I was seing this too, but actually I was seeing a hang in this test when run under an instance, and I can no longer reproduce that.  I cannot reproduce this failure either, on current master or the commit you referenced, presumably because my `/tmp` doesn't have such an interesting artifact in it.

Is the problem here simply that we just need to pick a more unlikely "impossible" job id for the test?  e.g.
```diff
diff --git a/t/t1008-proxy.t b/t/t1008-proxy.t
index 78fdb94..7903efa 100755
--- a/t/t1008-proxy.t
+++ b/t/t1008-proxy.t
@@ -122,7 +122,7 @@ test_expect_success 'flux proxy works with ssh:// and local sockdir' '
 
 test_expect_success 'flux proxy with ssh:// and bad jobid fails' '
        ! FLUX_SSH=$TEST_SSH FLUX_SSH_RCMD=$TEST_FLUX \
-         flux proxy ssh://localhost/0 flux getattr size
+         flux proxy ssh://localhost/noexist flux getattr size
 '
 
 test_expect_success 'flux proxy with ssh:// and bad query option fails' '
```
Easy to change, just checking if we are on the same page.

**Comment by grondo** [comment]
Yes, probably. But I never looked into why exactly the test was failing. I
just didn't want to lose track.
