### ISSUE TITLE
typedefs violating coding style guide

### ISSUE THREAD

**Issue by morrone** [flux-framework/flux-core#829]
It seems like a number of high-level typedefs violate this rule in the coding style guide:

> Abstract types SHOULD be publicly defined as incomplete types, for example:
> ...
> Abstract types SHOULD NOT be defined as pointers to incomplete types,

Here are a couple of examples that I have hit thus far:

`typedef struct flux_sec_struct *flux_sec_t;`

`typedef struct flux_handle_struct *flux_t;`

So what is the word there?  I personally think the rule is a great one.  I hate having pointers hidden behind typedefs.

**Comment by grondo** [comment]
@morrone, our only defense is there is a lot of types from *before* we decided on that rule :smile:. All new code should definitely follow the style guide.

**Comment by garlick** [comment]
While `flux_t` would be a bit of work, `flux_sec_t` is actually an easy one that we should fix.

**Comment by morrone** [comment]
Ah, because flux_sec_t is only used internally to flux-core right now, but flux_t is used exernally, for instance by flux-sched.

**Comment by garlick** [comment]
Right.

**Comment by garlick** [comment]
Anticipating the next one, in case you find yourself game:  `shortjson.h` is a header that contains the `JSON` type, an alias for `json_object *`, plus some inline functions.  Rather than make that one `JSON *`, we should just be using `json_object *`, since the alias effectively serves no purpose except to obfuscate.

That's a fairly big change, though it's not part of the public api.

**Comment by grondo** [comment]
Have we finished tackling all these?

**Comment by garlick** [comment]
I think so!
