### ISSUE TITLE
ensure flux-sched builds against rpm of latest flux-core

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#881]
Build an RPM of flux-core and ensure flux-sched builds properly against the installed RPM prior to release of 0.5.0.

**Comment by grondo** [comment]
I built a test rpm for TOSS 2 and temporarily installed into `/opt` on hype.

I was then able to `module load` that test version of flux-core, and configure and build flux-sched with all tests passing. I think we're ok on TOSS 2.x

BTW, is there some reason I'm forgetting that we installed in `/opt/flux-core/` directly on TOSS2 instead of `/opt/flux-core-${version}`? I can't remember why we chose to that, but it makes it difficult to side install versions (but not impossible, just have to modify the specfile...)

**Comment by garlick** [comment]
I seem to remember a discussion, but I can't think of any reason not to append the version now...
