### ISSUE TITLE
optparse: add "flag" field for future use such as legacy/hidden options

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#907]
After using the GNU ```argp``` library for a long time in ```freeipmi```, I found ```argp```'s option flags very useful (https://www.gnu.org/software/libc/manual/html_node/Argp-Option-Flags.html).   Most notably, you could legacy options by simply setting an option of ```OPTION_HIDDEN```, so it still worked but wasn't advertised in ```--help```.

Don't know ```optparse``` perfectly, but now might be the time to stick a ```flag``` or ```options``` kinda thing into it for the future, b/c it doesn't appear to have that.  Perhaps ```has_arg``` could be used if it instead used bitmasks.  Probably need to add a field for subcommands?  I could add ```OPTION_HIDDEN``` as the first implementation as a trial.  But I imagine there will be other odd-ball things that will come up that we'll eventually need the field for.

**Comment by grondo** [comment]
I like this idea, though hopefully we don't *already* have a case where we need `OPTION_HIDDEN`!  I also like the argp option for making an option an alias for a preceding option, that could be useful.

Adding a flags field should not be too bad since most usage of `struct optparse_option` is using designated initializers. Another approach would be to use to upper 16 or 24 bits of `has_arg` for flags. I wonder if the `list_argument` value for `has_arg` should turn into a flag, e.g. `required_argument | OPT_LIST_ARG`.

And yeah, it does seem like `struct optparse_subcommand` should also have `flags` added. Since subcommands are themselves `optparse_t` parsers, this could also be implemented via the `optparse_set` interface, though it would not be as convenient when creating a set of subcommands with `optparse_reg_subcommands`

**Comment by chu11** [comment]
We definitely don't need it now.  My thought was mostly about sticking it in now so we don't have to do it later and potentially break ABI, either in structs or in calls like ```optparse_reg_subcommands```.

Yeah, I was actually thinking we should tweak ```has_arg``` as a result too.  ```has_args``` sounds like a "flag" variable, but with ```list_argument``` it's gone a bit beyond that.

**Comment by grondo** [comment]
Well, intially this was just a wrapper around `getopt_long` so we were using their semantics directly -- GNU getopt already supports `optional_argument` over just has/doesn't have arg.

Since I'm already working on optparse I could take a look at adding flags as you suggest... or if you're already in there let me know

**Comment by chu11** [comment]
I haven't started working on any flag fields.  So feel free to take a crack if you have time and are in that area.  I am adding some more convenience functions (e.g. ```optparse_get_double```), so there could be some changes in that area.  But that's it.

**Comment by chu11** [comment]
I just noticed that ```optparse_get_int()``` assumes the integer cannot be negative.  Was about to add a ```optparse_get_positive_int()```, but I think if the option has the flag variable it could be useful here, such as an OPTION_NOT_NEGATIVE or OPTION_POSITIVE.

**Comment by grondo** [comment]
I would think the right approach here would be to let get_int accept any
integers. I'm not sure pushing anything but the most basic option argument
validations into optparse makes sense, though I could perhaps be persuaded
otherwise.

>
> I just noticed that optparse_get_int() assumes the integer cannot be
negative. Was about to add a optparse_get_positive_int(), but I think if
the option has the flag variable it could be useful here, such as an
OPTION_NOT_NEGATIVE or OPTION_POSITIVE.

**Comment by chu11** [comment]
I think it's just for convenience and to me the flags make the code a bit more clear.  If we push checks to the tools, you'll have:

```
if ((a = optparse_get_int (p, "a", 0)) < 0)
   log_msg_exit ("a should be >= 0");
if ((b = optparse_get_int (p, "b", 0)) <= 0)
   log_msg_exit ("b should be > 0");
```

all over the place.  If hypothetically a flag to optparse_get_int() were there:

```
a = optparse_get_int (p, "a", NON_NEGATIVE, 0);
b = optparse_get_int (p, "b", POSITIVE, 0);
```

**Comment by grondo** [comment]
Here's some of my arguments against:

 - Most integer arguments will actually have a range of valid values. We can't possibly *also* add flags for minimum and maximum values.
 - Pushing validation into an accessor seems a bit off to me
 - Forcing the caller to validate values is not only more flexible, it allows the caller to issue their own error message, which most of the time is going to be more useful for the end user than a generic "--foo argument must be non-negative"

Also, this is just my opinion, but the first example above is almost more clear to me...

**Comment by chu11** [comment]
> Most integer arguments will actually have a range of valid values. We can't possibly also add flags for minimum and maximum values.
Ahh, I had not thought of this bullet and you're right, that's probably the most important reason.
