### ISSUE TITLE
flux-start --size option rename

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#952]
Per Issue #834 and PR #951 , the ```--size``` option now only starts up a local flux instance, predominantly for devel/testing purposes.  The ```--size``` option name is carried over from the very beginning of ```flux start```'s existence and it probably should be renamed to something more clear to indicate its purpose.

There would be huge fallout from this change all over the place, minimally all documentation (including on the flux website), the flux-core testsuite, the flux-sched testsuite, and maybe other things too.

It could be made legacy via liboptparse OPT_HIDDEN to avoid too much churn.

**Comment by garlick** [comment]
And @morrone suggested `flux pmiserver [--size N]` in #834

If the issue is that using `--size` when running under slurm/flux produces unexpected results, would it make sense to add an option to select the mode, and then warn if in ambiguous territory, e.g.
```
$ flux start --size=64
warning: assuming --launch-mode=local due to --size option
$ flux start --launch-mode=external --size=64
error: --size can only be used with --launch-mode=local
```
I think the idea of an option to force the mode came up in #643
