### ISSUE TITLE
Create common lib/functions for module option parsing

### ISSUE THREAD

**Issue by chu11** [flux-framework/flux-core#973]
Noticed in several files that module option parsing looks a bit like this (coming from the kvs module):

```
static void process_args (ctx_t *ctx, int ac, char **av)
{
    int i;

    for (i = 0; i < ac; i++) {
        if (strncmp (av[i], "commit-merge=", 13) == 0)
            ctx->commit_merge = strtoul (av[i]+13, NULL, 10);
        else
            flux_log (ctx->h, LOG_ERR, "Unknown option `%s'", av[i]);
    }
}
```

The manual key=val parsing isn't done in a large amount of modules at the moment, so it's perhaps sufferable.  But it should be refactored later on, with appropriately included error checks for valid inputs and such.

**Comment by grondo** [comment]
I go back and forth on this one. If we do add convenience functions for module parameters, these functions must be added to the libflux-core API. Also, I'm not sure if it is wise to force all modules to only take key=value pairs, some modules may take a single character parameter, or list of free-format strings, etc. There are also certain advantages to treating modules like a standard process, because this will map well to one day executing modules as processes (which again, may want to use their own option parsing library). Finally, manual parsing as above is common in existing software like PAM modules, etc.

That being said, I'm not opposed to using a common option parsing interface for modules. Currently, if a module wants to use getopt_long style options, I think liboptparse would work. If interested we could go even further and force liboptparse by having modules optionally export an `option_table`, and the module loader could pre-parse options on behalf of the module... (this is only possible since liboptparse is now MT-safe)

**Comment by garlick** [comment]
Were you thinking that a `flux modinfo` style command could dump the argument usage for a module then?  That would be pretty neat.

**Comment by grondo** [comment]
Yes, that would be a nice side effect of "exporting" the module option list for DSOs (for module-as-executable, a modinfo hook in the module loader could instead run the executable with `--help`, other module types could export options in their own way...)

**Comment by chu11** [comment]
@grondo I actually wasn't thinking as far as something in libflux-core.  I was thinking something more simple, such as adding an internal convenience library for "core" flux modules.  Seeing a nice chunk of "hand" parsing and error checking (or lack thereof) seemed prime for some refactoring.  

But I do like @garlick's suggestion.  I was grepping around trying to see "do we document module options anywhere?"  And couldn't find anything.  Some type of ```modinfo``` would be nice.

**Comment by grondo** [comment]
@chu11, good point though possibly there is some benefit in "normalizing" module options (e.g. perhaps an update for the rfc) because then external projects like flux-sched would see a benefit, users would have a common interface to module options, etc...

**Comment by garlick** [comment]
Argh, just ran into one lame problem.  The argc, argv passed to modules start with options at `argv[0]`, but of course optparse skips that one.   This is my fault - options should have started `argv[1]`.  We should probably try to fix that.

**Comment by garlick** [comment]
Clearly not urgent, closing.
