### ISSUE TITLE
[idea] test hooks for services

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#977]
In #813 some ideas for generalized test interfaces were discussed

@dongahn:
> Maybe this should be the way. A tester sends n consecutive commits rapidly and check at least one a commit merge happens. If n is big enough to overcome network delays etc, this should happen with a high probability. Converse, if the tester send m commits each with k interval in between where k >> the merge window, statistically speaking you shouldn't see a merge... Well, PASS/FAIL can still be non-deterministic. Maybe the testing results are the numbers, not PASS/FAIL..

@grondo:
> Thinking about a way to test these difficult to reproduce timing conditions or corner-cases in general is a good idea. Lots of systems have separate interfaces for testing (e.g. something like the test-only commit flag described here, or better yet a separate kvs.test.* set of interfaces), or perhaps there is some kind of general interface or debug mode we could design that could be useful in more than just a single service? (e.g. would it be helpful if there was a way to "pause" a service, queue up messages, then "restart" -- or do something similar with perceived advancement of time?) Similarly, a "trace" interface might be useful during testing.

**Comment by garlick** [comment]
@morrone might have some good ideas from the Lustre world on how to do this.

I wonder if maybe we could add two new automatically registered methods for services (like ping):
1) get/set/clear test bit
2) generate test event (based on a request, not event message)

Provide an efficient and unobtrusive way to check if a test bit is set to activate test behavior, and a way to register callbacks for test events.

**Comment by morrone** [comment]
Not really, Lustre doesn't has pretty weak code coverage in the testing arena.  One thing Lustre has are test hooks that can insert bad data, or a pause, or whatnot.

In theory better still (but requiring a higher level of development effort), is to lay out the code so that it lends itself to unit testing.  That requires higher degrees of abstraction and encapsulation to make it possible to compile smaller bits of the code into other test programs.  I've never actually been on a project that went that far into test-driven development.  Flux is probably already better in the testing are than most I have been involved with.

**Comment by garlick** [comment]
Old issue.
