### ISSUE TITLE
drop broker pid check from local connector

### ISSUE THREAD

**Issue by garlick** [flux-framework/flux-core#987]
Over in #980 I've been playing with multi-user and ran across the following behavior:  the local connector (client side) opens the broker pid file in the same directory as the local connector socket and sends the pid therein a kill -0 to ensure the broker associated with the socket is running.  This of course only works for the instance owner and one aspect of #980 is to allow other users to connect.

I was thinking of removing this check and just doing timed-wait connect retries in the local connector (client side).  The broker pid file is still useful for the broker to know whether its socket path conflicts with a running broker (e.g. if broker dies without cleaning up socket), but I can't see a good reason for the client to need to check it.

Am I forgetting some consideration?

**Comment by grondo** [comment]
I can't remember why that kill -0 was added in the first place, either. I would also argue for removing it, since if a broker exits it is only a matter of time before some other process with the same PID takes its place anyway, making the signal 0 check a bit frivolous. (In addition to the reason you give). (In fact I think there is some workaround in there now so that the connector doesn't hang forever when this happens)
